build.rs
examples/repl/cmdline.rs
examples/repl/main.rs
misc.c
misc.h
src/types.rs

Fix linking

---

.circleci/config.yml
README.md

Closes https://github.com/deltachat/deltachat-core-rust/issues/11

Add basic setup for circleci

---

.circleci/config.yml
examples/repl/main.rs
src/dc_strencode.rs
tests/stress.rs

Closes https://github.com/deltachat/deltachat-core-rust/issues/13

Stress tests

---

.circleci/config.yml

Lets try using `libsasl2-dev` from `apt` instead of compiling each time. Also, this is rather quick so maybe we should just skip using a custom docker container for now.

Try libsasl2-dev

---

.circleci/config.yml

Closes https://github.com/deltachat/deltachat-core-rust/issues/29

Build deltachat_ffi on ci

---

src/dc_saxparser.rs
src/dc_strencode.rs
src/dc_tools.rs
src/types.rs
tests/stress.rs

Closes https://github.com/deltachat/deltachat-core-rust/issues/27

Fix FIXMEs in stress.rs

---

examples/repl/main.rs
src/lib.rs

Closes https://github.com/deltachat/deltachat-core-rust/issues/34

chore: stop allowing unused_attributes

---

deltachat-ffi/src/lib.rs
examples/repl/cmdline.rs
src/dc_aheader.rs
src/dc_array.rs
src/dc_chat.rs
src/dc_chatlist.rs
src/dc_contact.rs
src/dc_job.rs
src/dc_mimefactory.rs
src/dc_msg.rs
src/dc_oauth2.rs
src/dc_qr.rs
src/dc_receive_imf.rs
src/dc_securejoin.rs
src/dc_simplify.rs
src/dc_strencode.rs
tests/stress.rs

Replace types that use only 0 and 1 with bool (#18)

---

deltachat-ffi/Cargo.toml

fix(ffi): rename generated lib to libdeltachat

---

src/dc_securejoin.rs

Closes https://github.com/deltachat/deltachat-desktop/issues/820

fix: peerstate.addr to c string in dc_handle_degrade_event()

---

deltachat-ffi/Cargo.toml
deltachat-ffi/src/lib.rs

feat(ffi): install global panic handler

---

src/imap.rs

fix(imap): ignore uid 0 when setting flags

---

src/dc_mimefactory.rs

fixes the voice-message error of #107

make sending voice messages work

---

Cargo.toml
deltachat-ffi/Cargo.toml
deltachat-ffi/deltachat.h
deltachat-ffi/src/lib.rs
src/constants.rs
src/context.rs
src/dc_mimefactory.rs

Closes https://github.com/deltachat/deltachat-core-rust/issues/127

chore: update version to 1.0.0-alpha.0

---

Cargo.toml
LICENSE

chore: add missing license

---

Cargo.toml

fixes deltachat/deltachat-node#359
This is the better way then #166 see https://github.com/deltachat/deltachat-node/issues/359#issuecomment-507568895

Update Cargo.toml - add path for simple example

---

python/CHANGELOG
python/setup.py
python/src/deltachat/__init__.py

see changelog in diff for what is in.

prepare 0.600.0 release

---

src/constants.rs
src/dc_mimeparser.rs
src/dc_receive_imf.rs
src/dc_securejoin.rs

- remove some indentation 
- introduce save dc_mimeparser_lookup_field_r version. 
- convert created_db_entries carray into Vec
- converted rr_event_to_send carray into Vec
- converted some logging 
- converted two lookup functions to use &str instead of `char*`

improve dc_receive_imf and friends a little (part 1)

---

src/top_evil_rs.py

the output of "python top_evil_rs.py" in the src/ dir currently is: 
```
dc_tools.rs                    unsafe:  90 free:  61 goto-blocks:   7
dc_chat.rs                     unsafe:  65 free:  41 goto-blocks:  26
dc_msg.rs                      unsafe:  63 free:  41 goto-blocks:   3
dc_imex.rs                     unsafe:  15 free:  37 goto-blocks:  51
dc_configure.rs                unsafe:  18 free:  32 goto-blocks:  34
dc_contact.rs                  unsafe:  41 free:  32 goto-blocks:  10
dc_job.rs                      unsafe:  32 free:  12 goto-blocks:  29
dc_receive_imf.rs              unsafe:  19 free:  28 goto-blocks:  25
dc_mimeparser.rs               unsafe:  29 free:  28 goto-blocks:  15
dc_securejoin.rs               unsafe:  14 free:  17 goto-blocks:  32
dc_sqlite3.rs …
```

add a little script to compute rust-evilness

---

src/constants.rs
src/dc_receive_imf.rs

Show AutocryptSetupMessage independently of show-emails settings

---

examples/repl/cmdline.rs
examples/repl/main.rs
src/dc_chat.rs
src/dc_tools.rs

This is about #190. I tried to reproduce bug by trying to send garbage and crash receiver, but discovered that sender crashes on garbage first.

Send garbage

---

src/dc_tools.rs

Remove goto/current_block logic in dc_tools

---

src/context.rs
src/dc_securejoin.rs
src/dc_tools.rs

I swear I already did this, see #273.

Kill to_cstring with fire

---

src/dc_lot.rs

probably not the best way to go about it, but hey it works now again!

fix tofu in chat list

---

src/dc_tools.rs

This change removes one more use of unstable `wrapping_offset_of'.

Reimplement dc_str_replace() with standard Rust functions

---

src/dc_msg.rs

fix msg info: message-id

---

src/constants.rs
src/dc_chat.rs

also use DC_CHAT_TYPE_SINGLE const instead of it's number representation

chat magic to const

---

src/dc_configure.rs

and add a progress macro for convenience and code readability.

rm GOTO: dc configure

---

deltachat-ffi/src/lib.rs
src/contact.rs

And never return nullptr from dc_get_blocked_contacts.

Return Vec from get_all_blocked

---

ci_scripts/run_all.sh
src/dc_job.rs
src/imap.rs

Hopefully closes #331 and #361

fix(imap): reduce lock contention around session and config locks

---

src/context.rs
src/dc_imex.rs

This change makes code more type-correct, but introduces copying: compiler
refuses to return reference to object behind Arc<RwLock>.
When #335 is merged, this code could be simplified and optimized, since there
will no longer need in RwLock's.

Change type of Context.dbfile to std::path::PathBuf

---

python/doc/api.rst
python/doc/examples.rst

fix documentation

---

src/imap.rs

fix(imap): call create, not subscribe

---

src/config.rs

Fixes https://github.com/deltachat/deltachat-core-rust/issues/377

Add missing config keys which caused a panic in desktop

---

src/constants.rs
src/contact.rs
src/dc_array.rs
src/dc_chat.rs
src/dc_configure.rs
src/dc_job.rs
src/dc_mimefactory.rs
src/dc_mimeparser.rs
src/dc_msg.rs
src/dc_saxparser.rs
src/dc_strencode.rs
src/dc_token.rs
src/dc_tools.rs
src/imap.rs
src/key.rs
src/lib.rs
src/oauth2.rs
src/peerstate.rs
src/types.rs

Changes:
8dc55f1 (Dmitry Bogatov, 3 минуты назад)
Remove dead code
123f5c6 (Dmitry Bogatov, 3 часа назад)
Do not export unused functions
f31884f (Dmitry Bogatov, 3 часа назад)
Remove unused `dc_str_contains' function
2b1ffb5 (Dmitry Bogatov, 3 часа назад)
Do not export `dc_strlower' function

Remove dead code

---

deltachat-ffi/src/lib.rs
src/dc_lot.rs
src/dc_mimefactory.rs
src/dc_msg.rs
src/dc_tools.rs

Make dc_msg_get_summarytext_by_raw safe

---

src/dc_qr.rs

a "just one thing before going to bed" PR.  review only the first commit -- the second is cargo fmt.

Ungoto/deindent dc_qr.rs

---

src/dc_mimeparser.rs

another two-commit little cleanup.  now really going to sleep ...

Ungoto mimeparser

---

python/src/deltachat/__init__.py
python/src/deltachat/cutil.py
python/src/deltachat/message.py

Solution based on https://stackoverflow.com/questions/44439683/canonical-way-to-free-string-passed-back-from-a-c-function-in-cffi

fix(python): free allocated string pointers

---

src/message.rs

fix(message): avoid nested sql statement in dc_get_msg_info

---

src/dc_mimeparser.rs
src/dc_receive_imf.rs
tests/stress.rs

dc_mimeparser_parse: accept input as slice, not as pointer + length

Refactor dc_mimeparser

---

src/dc_mimeparser.rs

Should result in panic instead of crash for issue #420
Edit from @simon-laux:
fixes #420

mailmime_get_mime_type: do not dereference null pointer

---

src/dc_securejoin.rs

transform `current_block` to `ok_to_continue`

Remove goto: securejoin

---

src/dc_imex.rs

transform `current_block` to `ok_to_continue`

Remove goto: imex

---

Cargo.lock
Cargo.toml
src/imap.rs

It uses imap-proto 0.8.1 instead of outdated 0.7.0.

Update to the latest rust-imap

---

src/configure/mod.rs

Still needs to be tested, desktop currently has a few problems with the configuration, but they could have been there before so I need to test that.
Todo:

Reorganize dc configure functions

---

src/top_evil_rs.py

counting ok_to_continue reflects structural or missing-rustification problems

switch to counting ok_to_continue instead of current_blocks

---

src/dc_tools.rs

just some tiny things that crossed my way :)

cleanup tools

---

deltachat_derive/src/lib.rs
src/constants.rs
src/contact.rs
src/job.rs
src/message.rs

closes #448, see https://github.com/deltachat/deltachat-core-rust/issues/448#issuecomment-529117884 for some additional info
closes #443, see comment below
@dignifiedquire not sure, if this is really rust-style :)

fix reading unknown origin

---

src/job.rs

this should check for equality:
https://github.com/deltachat/deltachat-core-rust/blob/master/src/job.rs#L1083
this pr fixes it.

fix(job): "invalid job action" check

---

src/chat.rs

Fix leaving group

---

tests/stress.rs

It is broken since 28cae607a481185423561f1ba365f7d91c3b9391

Fix test_encryption_decryption

---

src/dc_receive_imf.rs

fix crash when msg_raw is None

---

src/chat.rs
src/constants.rs
src/dc_imex.rs
src/dc_mimefactory.rs
src/dc_mimeparser.rs
src/dc_receive_imf.rs
src/e2ee.rs
src/message.rs
src/param.rs
src/securejoin.rs

the first step of many to make mimeparsing a little saner

refactor(mimeparser): some more sanity

---

spec.md

this pr moves the spec from the more or less forgotten [spec-repo](https://github.com/deltachat/spec) here into this repo to get spec-related-things more into view.
once merged, the old spec-repo can be deleted.

move spec.md from separate repo here

---

src/context.rs
src/dc_dehtml.rs
src/dc_simplify.rs

Changes:
* Add property test for simplify_plain_text
* Add tests for dc_dehtml
* Add smoke test for Context.get_fresh_msgs

Improve test coverage

---

src/dc_receive_imf.rs

fix(receive_imf): do not attempt to convert raw body to utf8

---

Cargo.lock
deltachat-ffi/Cargo.toml
deltachat-ffi/deltachat.h
deltachat-ffi/src/lib.rs
deltachat-ffi/src/providers.rs
python/src/deltachat/const.py
python/src/deltachat/provider.py
python/tests/test_lowlevel.py
python/tests/test_provider_info.py

add Provider overview/info

---

deltachat-ffi/deltachat.h

this pr does not change any logic or function-footprint.
it only fixes some minor things to make doxygen work and to follow the implicit conventions previously used in the file.

fix ffi docs

---

src/configure/mod.rs

i do not know much about testing, so feel free to close or so ;)
i think this test would have catched the problem in https://github.com/deltachat/deltachat-core-rust/pull/545

test that bad credentials do not panic

---

src/dc_mimeparser.rs
src/dc_tools.rs

You only need to review the first commit.
the other commit is deindentation/cargo fmt.

Cleanup/mimeparser indent1 (one-commit + cargo-fmt commit style)

---

src/dc_mimefactory.rs

* src/dc_mimefactory.rs(new): add factory method to have verbose
initialization of all (more than 10) MimeFactory fields only in one place.
* src/dc_mimefactory.rc(dc_mimefactory_load_msg, dc_mimefactory_load_mdn):
simplify code (and reduce linecount) using Mimefactory::new

Add factory method MimeFactory::new

---

deltachat-ffi/src/lib.rs
examples/repl/cmdline.rs
src/chat.rs
src/dc_receive_imf.rs
src/dc_tools.rs
src/message.rs
src/securejoin.rs

refactor(chat): remove c types and unsafe

---

Cargo.lock
Cargo.toml
appveyor.yml
ci_scripts/run-rust-test.sh
mmime/.circleci/config.yml
mmime/Cargo.toml
mmime/LICENSE-APACHE
mmime/LICENSE-MIT
mmime/LICENSE.md
mmime/README.md
mmime/src/charconv.rs
mmime/src/chash.rs
mmime/src/clist.rs
mmime/src/lib.rs
mmime/src/mailimf.rs
mmime/src/mailimf_types.rs
mmime/src/mailimf_types_helper.rs
mmime/src/mailimf_write_generic.rs
mmime/src/mailmime.rs
mmime/src/mailmime_content.rs
mmime/src/mailmime_decode.rs
mmime/src/mailmime_disposition.rs
mmime/src/mailmime_types.rs
mmime/src/mailmime_types_helper.rs
mmime/src/mailmime_write_generic.rs
mmime/src/mailmime_write_mem.rs
mmime/src/mmapstring.rs
mmime/src/other.rs

This moves the mime parsing crate into here, to make development easier.

feat: import mmime crate

---

src/chat.rs
src/securejoin.rs

first commit contains the actual changes
second commit cargo fmt

Cleanup chat.rs -- remove ok_to_continue, better error handling

---

src/job.rs

this is on top of #588 so please merge that first
first commit cleanup, second commit cargo fmt -- but look only at the two last job-related commits.

Cleanup job, remove ok_to_continue etc

---

python/src/deltachat/message.py
python/tests/test_account.py
src/message.rs

fix boolean error that makes get_setupcodebegin() failing

---

python/install_python_bindings.py

Trying to open a pull request from emacs, let's see...

Use sys.executable in install_python_bindings.py

---

src/e2ee.rs

review the first commit, second is cargo fmt only.

remove ok_to_continue, resultify decrypt in e2ee. 

---

examples/repl/cmdline.rs
src/dc_receive_imf.rs
src/imap.rs

Pass slice to dc_receive_imf

---

src/dc_imex.rs

please review first commit, second is cargo fmt

little cleanup imex

---

src/e2ee.rs
src/securejoin.rs
src/wrapmime.rs

from https://github.com/deltachat/deltachat-core-rust/pull/622
make a few more function return Results , and save_to_db() now just bubbles up.

address review comments incoming-decrypt PR 

---

src/sql.rs

for whatever reasons, _some_ database-migration actions were logged, others not.
this pr switches to log all database-migration actions.

log all database-migration actions

---

src/sql.rs

- increase the number of simultan database-connections handled by the r2d2 pool.
currently we have already at least 5 threads threads,
but also the ui may call from any thread.
- the busy-timeout for all connections is set to 10 seconds.
this means, if a connection-A wants to write,
but connection B-is already writing,
connection-A waits multiple times a few ms and tries over.
this is repeated until the 10 seconds are accumulated.
if busy_timeout() fails for some reason, we bubble up the error. not sure about that. we have a handle that can be used theoretically, so we could also ignore the error. otoh, this should not happen normally, and if it does, probably more things are wrong and it might be better to not use the connection.
fixes #656

more resilient database writes

---

src/chat.rs

if it breaks some existing prs, ping me and i'll add it to another branch :)

redo some c-comments

---

src/dc_mimeparser.rs

review only first commit,
second is cargo fmt, deindents.

remove ok_to_continue from mimeparser

---

src/imex.rs

review first commit, second ist cargo-fmt only.

remove ok_to_continue from imex, simplify/resultify

---

.circleci/config.yml
ci_scripts/ci_upload.sh
ci_scripts/run-doxygen.sh
python/doc/_templates/globaltoc.html
python/doc/lapi.rst

try generating doxygen docs

---

mmime/src/other.rs

fix(mmime): correct implementation of strncasecmp

---

Cargo.lock
Cargo.toml
ci_scripts/ci_upload.sh
src/dc_tools.rs
src/e2ee.rs
src/error.rs
src/imex.rs
src/key.rs
src/message.rs
src/pgp.rs
tests/stress.rs

refactor: safe pgp module

---

src/dc_receive_imf.rs
src/dc_tools.rs

this makes cleanup closure unneccessary in one function in dc_receive_imf. 
second commit is cargo-fmt purely.  not sure why that caused so many changes (was there an update on cargo-fmt maybe?).

dc_str_from_clist safe and returning string

---

src/chatlist.rs
src/dc_simplify.rs
src/imap.rs
src/job.rs
src/top_evil_rs.py

Eventually all libc usage should be moved to FFI.

Start removing libc references

---

Cargo.lock
Cargo.toml
src/imap.rs
src/smtp.rs

Needed some fixes in other places
- https://github.com/jonhoo/rust-imap/pull/145
- https://github.com/jonhoo/rust-imap/pull/144
- https://github.com/deltachat/lettre/commit/119ef8e5a003e0afb3abcbe706951cf827bdac2c

The final oauth2 fixes are here

---

Cargo.lock
Xargo.toml

or is "Xargo.lock" used for anything? 
in any case this fixes master to build again.

fix rust-imap dep and remove Xargo.lock

---

Cargo.lock
Cargo.toml

chore(deps): switch back to rust-imap master

---

Cargo.lock
src/smtp.rs

this aims to fix https://github.com/deltachat/deltachat-android/issues/1061
the actual smtp-connect was not performed and so configuration wrongly indicated success on ports where the server would not respond.

actually try smtp-connecting, instead of just preparing the connect

---

src/imap.rs

might fix #717
seems as if the same problem was already fixed at https://github.com/open-xchange/deltachat-core-rust/pull/7

reconnect on io errors and broken pipes

---

src/location.rs

Use constants where possible, move "let" closer to assignments.

location.rs cleanup

---

src/imap.rs
src/stock.rs

closes #700 (see there for some more explanations)
targets https://github.com/deltachat/deltachat-ios/issues/328 but also android and desktop will get improved by that.
related to https://github.com/deltachat/deltachat-core-rust/pull/698

better error messages

---

src/qr.rs

the qr-code paramteters are encoded as url-parameters as `?key=value`. non-ascii-characters are typically encoded with percent-encoding as `?key=a%20value` for `a value`.
this pr also allows using a simple `+` as a space, not sure where this standard comes from but it is widely seen - and was also used in core-c for encoding group and contact names.
closes #758

fix plus-space-decoding in qr-code

---

src/qr.rs

fixes https://github.com/deltachat/deltachat-core-rust/issues/759

fix recognition of mailto-address-qr-codes, add tests

---

src/blob.rs

This is an additional fix for #768 aka
commit eac8ad8

Be more accepting in creating blobs from existing names 

---

ci_scripts/run-python.sh
src/dc_tools.rs
src/imex.rs

more error logging with file operations in general

---

python/src/deltachat/account.py
python/src/deltachat/chatting.py
python/tests/test_account.py
src/dc_mimeparser.rs
src/dc_receive_imf.rs
src/location.rs
src/mimefactory.rs

hopefully fixes #757 (in fact three and a half separate bugs). 
also adds a python api for locations and an end-to-end functional test that now passes.

test and add location streaming python api, fix various Rust-core bugs 

---

src/dc_tools.rs

thanks @csb0730 for the analysis of the issue in https://github.com/deltachat/deltachat-core/issues/534
this fixes #786

fix #786 by always succeeding to create a canonical deterministic message-id

---

python/doc/api.rst
python/src/deltachat/account.py
python/src/deltachat/chat.py
python/src/deltachat/contact.py
python/src/deltachat/message.py
python/tests/test_account.py

- split chatting.py into chat.py and contact.py to better mirror core structure 
- fix some docstrings
- add account.get_chat_by_id() and some doc strings.

refinements to python api

---

src/blob.rs

Before we created an empty file and asked the OS to copy the file.
The OS is very good at this so this is a good idea generally.  However
it seems that in some cases, e.g. an Android Dowload folder, we might
be able to create a file but not overwrite it.  Thus refactor this a
bit so we are copying the file ourselves.  For this we must read the
entire file into memory which we do this in 4Mb chunks, this is a
tradeoff between memory usage and the speed of copying.  The OS is
much better at making these tradeoffs, hence the original approach.
There are no new tests here since the behaviour remains identical.
The good news is that the existing tests were good enough to catch
some bugs already.

Copy the file contents manually

---

src/configure/mod.rs
src/job.rs
src/smtp.rs

try to fix some smtp todos and do better error logging

---

src/chat.rs
src/chatlist.rs
src/contact.rs
src/dc_receive_imf.rs
src/location.rs
src/message.rs

the point of this pr is to get an overview how and where DC_CONTACT_ID_DEVICE is used, to prepare introducing a device-"chat".
i did not change the sql statements for now as this would require some more refactoring and has the potential to introduce bugs.

name special contact-ids where easily possible

---

src/chatlist.rs

resorting the chatlist on changing drafts has some ux issues. eg. when the chatlist is visible together with the input field, if may come to flickering resorting during input or to a resorting just when the user leave the chat as this might trigger set_draft().
but also on mobiles, the resorting is visible and a bit unexpected. also it is unclear what happens when a chat with a draft is entered and left without modifications.
the solution proposed here is to ignore draft on sorting while still showing them in the chatlist if they're newer as the last message.
a possible disadvantage is that the date for the chat with a draft does not follow the ordering (the ordering is by the last message), however, the date is not shown as a "primary sort" criterion or so, so it might be that this is …

do not resort chatlist on draft changes

---

src/key.rs

TryInto is derived automatically and its documentation recommends implementing TryFrom.

Implement TryFrom instead of TryInto

---

python/tests/test_account.py
src/imap.rs

also fixes https://github.com/deltachat/deltachat-ios/issues/204 probably and potentially a few other things depending on interrupt_idle to work

cleanup select_folder and fix idle/termination issues

---

src/message.rs

resolves #843
Since I don't know what happens with messages in trash (is there a restore method?) I didn't delete the location but moved it to trash chat ID

Delete msg related POI when message is deleted

---

src/location.rs

Use coalesce for optional columns

---

src/job.rs

messages sent to groups with only SELF and bcc_self disabled (which is default now) are forever pending as there are no recipients and the smtp-job is never started.
this situation happens easily when "playing around" after a fresh installation - the "forever pending" messages look like if sth.  is not working and is probably not what the user expect.
this pr marks these messages as being "done", which is what the user will expect. 
fixes #860

mark messages as sent

---

src/blob.rs

Double extensions are sometimes used to identify files correctly,
e.g. .tar.gz or .html.zip.  Breaking those extensions is not very
nice.
This fixes #865.

Do not break double file extensions

---

Cargo.lock
Cargo.toml

as recent fixes are merged to async-imap, let's use that

---

src/config.rs

This code it simple enough.  But I'll write some tests before considering this ready for merging.

Copy Selfavatar to blobdir and store as proper blob

---

src/job.rs

Introduce TryAgain type with C core constants
Make try_again field and method private.
Remove try_again == 2 processing, it was never used.

job: try_again refactoring

---

src/dc_receive_imf.rs
src/securejoin.rs

The ongoing process of dc_join_securejoin() was stopped before the
corresponding chat was created.  This resulted in a race-condition
between the sqlite threads executing the creation and query
statements, thus sometimes the query would not find the group and
mysteriously fail.
Tripple-programming with hpk & r10s.

Attempt to fix race in securejoin handling

---

src/job.rs
src/smtp.rs

Same as with IMAP, some errors can be retried and some should result in job removal.

Resultify Smtp::send

---

src/chatlist.rs

this reverts the logical changes done in #811
but keeps the improvements done later eg. in #911.
the reason for the revert is that it is too hard to
find a started draft in a larget chatlist.
also the shown date would not be just descending.

sort drafts again to the top of the chatlist

---

src/imap.rs
src/job_thread.rs

this addresses (but does not nicely/fully fix) https://github.com/deltachat/deltachat-core-rust/issues/925

address last(?) idle race condition heuristically

---

src/oauth2.rs
tests/stress.rs

Move another OAuth2 test from stress.rs to oauth2.rs

---

examples/repl/cmdline.rs
src/chat.rs

this pr makes sure, no messages can be sent or forwarded to the device chat.

fix forward

---

src/chat.rs
src/chatlist.rs
src/contact.rs
src/context.rs
src/error.rs
src/events.rs
src/imex.rs
src/job.rs
src/login_param.rs
src/lot.rs
src/message.rs
src/param.rs

An attempt to improve documentation to make crate docs usable

Improve documentation and hide some public structures

---

python/src/deltachat/message.py
python/tests/test_account.py

fix message creation in python

---

deltachat-ffi/deltachat.h
deltachat-ffi/src/lib.rs
python/src/deltachat/chat.py
python/tests/test_account.py
src/chat.rs

New json summary

---

python/tox.ini

we've fixed the flakyness of qr tests last week.

don't split qr tests out anymore now

---

src/aheader.rs

Specification
https://autocrypt.org/level1.html#the-autocrypt-header
says that prefer-encrypt attribute can only occur with the value `mutual`.

Do not include "prefer-encrypt=nopreference;" in Autocrypt header

---

src/dc_receive_imf.rs
src/mimeparser.rs
src/securejoin.rs

less state/caching is better and we have a fast enough HashMap

Mimeparser remove three attributes, not worth caching

---

src/imap/idle.rs

Return proper cause and avoid matching on nested Result

Improve IMAP idle timeout error handling

---

deltachat-ffi/deltachat.h

instead of dc_contact_is_verified_ex documentation.

Copy correct dc_contact_is_verified documentation from C core

---

python/tests/test_account.py
src/chat.rs
src/dc_receive_imf.rs
src/job.rs
src/mimefactory.rs
src/peerstate.rs

Only add gossip headers if chat has more than one peer

---

src/contact.rs

fix displayname to use authname when availible

---

src/configure/mod.rs

use provider-database only if the user did not enter a server/port/whatever manually; this allows the user to override erroneous choices
this pr is meant to be merged into https://github.com/deltachat/deltachat-core-rust/pull/1017

let user override provider-database

---

Cargo.lock
src/chat.rs

Do not format! SQL queries

---

python/tests/test_account.py
src/contact.rs
src/dc_receive_imf.rs
src/mimeparser.rs

fix #1037 and simplify mdn-report related code and state

avoid read-receipt garbling when mdns are disabled / simplifications

---

python/src/deltachat/account.py
python/tests/test_account.py

allow to set os_name in python bindings

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

prepare to tag 1.0.0-beta.18

---

Cargo.lock
Cargo.toml
src/smtp/mod.rs
src/smtp/send.rs

- no more auto connection when sending
- all commands that are issued, including connecting and sending are now using a timeout (of 15min)
- depends on https://github.com/async-email/async-smtp/pull/6

feat(smtp): update to use async-smtp based timeouts

---

src/mimefactory.rs

RFC5322 requires emails to be wrapped to 78 columns excluding CRLF.
Fixes #1009

fix(mimefactory): wrap base64-encoded attachments to 78 columns

---

src/constants.rs
src/contact.rs
src/error.rs
src/imex.rs
src/lot.rs
src/param.rs
src/peerstate.rs
src/smtp/mod.rs
src/smtp/send.rs

add some empty lines to enums & co to make things more readable and to avoid errors this way.
this was exactly the kind of stuff i could achieve yesterday after being at the greek bar :)

add some empty lines

---

examples/repl/cmdline.rs

in the very beginning, we allowed using the cmdline partly from the ui via a special function; this made info!() handy.
however, this is long gone and no longer needed. moreover, by the additional information added to info!(), this also results in more confusing output.

use println!() for all repl outputs

---

src/job.rs

This should help with #1063 and similar network bugs debugging

Improve job_perform() logging

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

after merge make sure to pull and `git tag 1.0.0-beta.22` and push tags :)
once merged, i do an android 1.0.3

prep beta22 and see if all tests pass

---

README.md

list language bindings in README

---

deltachat-ffi/src/dc_array.rs
deltachat-ffi/src/lib.rs
src/chat.rs
src/constants.rs
src/dc_receive_imf.rs
src/dc_tools.rs
src/job.rs

this pr removes some `#[allow()]` statements that seems to be no longer needed as the code was rustified in between :)

remove some meanwhile unneeded allow-statements

---

src/mimefactory.rs
src/mimeparser.rs

PR fixes #1116 and adds a test for `message.kml` parsing.

Location streaming fixes

---

python/README.rst

It is used in tests/conftest.py

Add requests dependency to python/README.rst

---

python/tests/test_account.py
src/chat.rs
src/dc_receive_imf.rs
src/mimefactory.rs
src/peerstate.rs

Gossip bugfixes

---

src/chat.rs
src/dc_receive_imf.rs
src/mimefactory.rs
src/mimeparser.rs
src/oauth2.rs

Mostly random refactorings, removing `unwrap`s and simplifying the code

Refactoring

---

python/tests/test_account.py
src/chat.rs

Correctly determine whether reply is to encrypted message or not

---

src/dc_receive_imf.rs
src/securejoin.rs

This return value was very complicated to understand.  Some failure
returns were returned as Err and some as Ok with no consistency, but
resulting in the same behaviour.
This refactor makes the handle_securejoin_handshake the sole place
responsible for maintaining the state of the secure join
process (context.bob) and also in charge of terminating the ongoing
process.  This is none of receive_imf's business.
The remaining returns are now cleanly classified in application-errors
and protocol errors:
Applications errors result in an Err and mean there is a bug or
something else serious went wrong, like database access suddenly
failed or so.  In this case receive_imf is still responsible for
clearing the state and resetting ongoing-process.  It may be possible
this should still be moved back …

Refactor return values from secure-join message handling

---

src/mimefactory.rs

This header is specified in RFC 3834.
Fixes #1175

Add "Auto-Submitted: auto-replied" header to MDNs

---

src/configure/mod.rs
src/dc_receive_imf.rs
src/lib.rs
src/mimefactory.rs
src/mimeparser.rs
src/sql.rs

This prevents creation of new overly complex functions.

Reduce the scope of clippy exceptions

---

src/securejoin.rs

The HandshaeMessage::Propagate return should only occur for
vg-member-added messages since it is for those that we still need to
handle the group add.
Fixes https://github.com/deltachat/deltachat-core-rust/issues/1208
Yes, I also wonder where the tests are.

When handling vc-contact-confirm the message is Done

---

src/chat.rs
src/sql.rs

This PR should prevent accidental sending of unencrypted message when `parent_is_encrypted` returns `false` due to SQL error, such as database being busy because of the other thread activity.

Resultify parent_is_encrypted

---

ci_scripts/run-python-test.sh
src/job.rs
src/mimefactory.rs

This should speed up compilation and enable additional integer overflow checks.

Run python tests on CI in debug mode

---

src/job.rs

Minor changes in comments

---

src/aheader.rs
src/e2ee.rs
src/headerdef.rs
src/imap/mod.rs
src/mimeparser.rs

Implement get_headerdef method for MailHeader slices

---

src/imap/mod.rs

log the positive, negative or part-negative outcome of moving messages.

better event information for moved messages

---

deltachat-ffi/deltachat.h
deltachat-ffi/src/lib.rs
examples/repl/cmdline.rs
src/lot.rs
src/qr.rs

this pr is about the core around the new burner-account features.
counterpart of https://github.com/deltachat/deltachat-android/pull/1231

burner accounts

---

src/imap/mod.rs

Check for MOVE capability before using it and fix COPY/STORE/EXPUNGE fallback deadlock

---

Cargo.lock
src/chat.rs
src/chatlist.rs
src/constants.rs
src/message.rs
src/param.rs

more derives

---

examples/repl/cmdline.rs
src/constants.rs
src/dc_receive_imf.rs
src/imap/mod.rs

Replace `flags` integer with a `seen` boolean.

Remove DC_IMAP_SEEN constant

---

src/chat.rs
src/sql.rs

Do not set grpid to contact address for 1-to-1 chats

---

src/peerstate.rs

Include prefer-encrypt attribute in Autocrypt-Gossip headers

---

src/provider/data.rs

command:
./src/provider/update.py ../provider-db/_providers/ > src/provider/data.rs
prs on https://github.com/deltachat/provider-db are _zero_, so i think, this makes some sense. added providers are aol, t-online, fastmail, protonmail.

update providers from provider-db

---

spec.md

just some word, this was just missing.

add location handling to spec

---

src/provider/data.rs

together with the ecc keys, this will result in some speed improvements for the burner accounts :)

add testrun to provider-db

---

src/provider/data.rs

aol is not broken, it just needs some prepararions :)
command for updating:
./src/provider/update.py ../provider-db/_providers/ > src/provider/data.rs
closes #1294

get fix wrt aol from provider-database

---

src/contact.rs

Make add_or_lookup errors non-fatal in add_address_book()

---

Cargo.lock
Cargo.toml
README.md
deltachat-ffi/Cargo.toml

fix: update to pgp@0.5

---

python/tests/test_account.py
src/dc_receive_imf.rs

Rebuild group member list on group rejoin

---

src/contact.rs

Found this while investigating #1350

Fix potential normalize_name() crashes

---

src/chatlist.rs

this pr hides the device chat from the chatlist that is used for forwarding. we hide it from the normal-list and from the filtered-normal-list - but keep it in the archived-list because otherwise the numbers in "Archived chats (1)" would not match which is even more irritating - and adapting that would mean some effort that is not worth the tiny result - also as, depending on the ui, forwarding-to-archived is not even possible - or at least pretty hidden.

hide the device-chat from default forward-to-lists

---

Cargo.lock

Update rPGP to 0.5.2

---

src/dc_receive_imf.rs

@adbenitez reported that in the testing group:
```
1. create 1:1 chat with A
2. create group with A
3. archive 1:1 with A
4. send message to group with A
5. wait read receipt from A
```
=> this should unarchive the 1:1 with A
i did not test this with android yet, but i created a function test - which, unfortunately does not contain the issue. but might be around in parts not tested by the test. and having some tests wrt read-receipts and stuff is nice anyway :)

check that incoming read-receipts do not unarchive chats

---

src/mimeparser.rs

Parse inline attachments from non-DC clients

---

src/mimeparser.rs

mimeparser: display inline images received from Thunderbird

---

deltachat-ffi/deltachat.h

this pr changes the docs wrt the fact that events do no longer use return values.

adapt ffi doc, section events

---

deltachat-ffi/deltachat.h

fix doc for return value of dc_lookup_contact_id_by_addr()

fix doc for dc_lookup_contact_id_by_addr()

---

src/job.rs

Fixes #1414 
Not tested.
See commit messages for description.

Dynamic imap delete job generation

---

src/job.rs

Let the thread load new messages. This may happen when user switches
the setting to delete messages on the server on and there are a lot of
messages to delete.

job: perform no more than 20 IMAP jobs in a row

---

src/provider/data.rs

called `./src/provider/update.py ../provider-db/_providers/ > src/provider/data.rs`

update provider database

---

src/imap/mod.rs

Log precheck_imf errors

---

src/chat.rs

and rewrite the error message so that it makes more sense

fix muting dm chats

---

deltachat-ffi/deltachat.h

the `@memberof` thingie was just forgotten.

add dc_estimate_deletion_cnt() to docs, add some references

---

src/chatlist.rs

Extract flags in try_load() to variables

---

python/src/deltachat/account.py
python/src/deltachat/testplugin.py

switching logging on/off globally

make sure we don't garble output during test runs by more carefully

---

src/imap/mod.rs

@r10s for #1488
Still unsure what's the best way for small suggestions on PRs, anyway...

Code style (#1488)

---

src/sql.rs

journal_mode is persisted, it is sufficient to change it only for one handle.
with_init() is called for a bunch of handles directly on pool-creation,
so changing to WAL here easily results in busy-errors.

change to WAL only on one handle.

---

examples/repl/main.rs

Remove help for nonexisting open and close commands.

---

ci_scripts/docker-coredeps/Dockerfile
ci_scripts/docker-coredeps/deps/build_rust.sh
ci_scripts/remote_python_packaging.sh
ci_scripts/run_all.sh
python/README.rst
python/examples/echo_and_quit.py
python/src/deltachat/message.py
python/tests/auditwheels.py
python/tests/test_account.py

also add a test (somewhat unrelated, but can never hurt to add tests)

make wheel building work again -- switch manylinux2014

---

deltachat-ffi/deltachat.h

just some tiny things i noticed while implementing the android part ...

tweak async ffi-docs

---

src/configure/mod.rs

Not quite as nice as the C code yet, but at least there is no step counter anymore.

refactor(configure): simplify logic and code

---

src/contact.rs

Sanitize address book

---

python/src/deltachat/direct_imap.py
python/src/deltachat/testplugin.py
python/tests/test_account.py

several cleanups and fixes, also refined some tests that were sometimes failing.
This is a follow up PR to @Hocuri 's imap-python pr which i was too late to review.

Refactor python imap support

---

spec.md

Adapt spec.md to new subject (#1395)

---

src/chat.rs

get_rowid should not return 0, as we have inserted a row right above.
And using is_error() instead of comparing row_id to 0 is a strange way
to check this condition.
As all functions that actually returned 0 chat ID to indicate error have
been removed, the function is gone too.

chat: get rid of ChatId.is_error()

---

deltachat-ffi/deltachat.h

add new string to deltachat.h

---

.circleci/config.yml
.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/job.rs
src/scheduler.rs

- avoids blocking on start_io
- attempts to connect to the imap on all tasks when needed

fix: improve imap connection establishment

---

src/imap/client.rs
src/imap/mod.rs
src/login_param.rs
src/provider/data.rs
src/provider/mod.rs
src/provider/update.py
src/smtp/mod.rs

Add strict_tls support

---

src/smtp/mod.rs

More verbose SMTP connect error to see what is going on at  #1556

More verbose SMTP connect error to see what is going on at  #1556

---

src/dc_receive_imf.rs

refactor: replace calc_timestamps with calc_sort_timestamp

---

python/src/deltachat/testplugin.py

Fix #1608 
The log is also much cleaner now without `ac1` messages:
```
========== waiting for the reply message from the bot to arrive ==========
3.35 [events-ac2] calling hook name=ac_outgoing_message kwargs={'message': <Message outgoing sys=False 'hello' id=10 sender=1/tmp.mrgeg@testrun.org chat=10/tmp.tqz4r@testrun.org>}
3.35 [events-ac2] DC_EVENT_INFO data1=0 data2=src/scheduler.rs:222: smtp fake idle - interrupted
3.35 [events-ac2] DC_EVENT_INFO data1=0 data2=src/job.rs:1068: loading job for Smtp-thread
3.35 [events-ac2] DC_EVENT_INFO data1=0 data2=src/scheduler.rs:214: executing smtp job
3.35 [events-ac2] DC_EVENT_INFO data1=0 data2=src/job.rs:891: Smtp-job #1, action SendMsgToSmtp started...
3.35 [events-ac2] DC_EVENT_INFO data1=0 data2=src/job.rs:960: Smtp begin immediate try 0 …
```

run_bot_process: shutdown before starting the bot

---

Cargo.lock

See https://github.com/Geal/nom/issues/1162 for details

fix: update deps to fix nightly builds

---

src/pgp.rs

Avoid unnecessary indexing, decompress only once and check if the message
is Signed before trying to verify it.

pgp: refactor and document pk_decrypt()

---

python/src/deltachat/direct_imap.py
python/tests/test_account.py
src/dc_receive_imf.rs

Mark read receipts as read

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

already preparing this, not sure what from https://github.com/orgs/deltachat/projects/23 should go in before. an android-apk is close, but i want to get two smaller things done before, so merging this is not needed immediately :)
on merging, do not forget `git tag 1.36.0; git push --tags`
EDIT: updated the changelog to the last commits - and i assume, we also merge #1631 before a 1.36 release :)

prepare 1.36

---

deltachat-ffi/src/lib.rs
src/imap/mod.rs
src/location.rs
src/mimeparser.rs

fix warnings and bugs, noticed on nightly

---

src/scheduler.rs

this pr creates the inbox_loop inpendendingly of inbox_watch config-setting as the loop is also required to perform jobs. the config-setting is checked inside the loop then.

perform jobs also if inbox_watch disabled

---

Cargo.lock

includes async-std@1.6.2 and smol@0.1.18 which fix various  hangs and possible deadlocks

feat: update deps

---

src/scheduler.rs

fix(scheduler): only start watch loops if the appropriate config is set

---

src/blob.rs

tests are taken from closed #1666

add more tests for BlobObject::sanitise_name()

---

deltachat-ffi/deltachat.h
deltachat-ffi/src/lib.rs
python/src/deltachat/chat.py
python/tests/test_account.py
src/chat.rs
src/chatlist.rs
src/context.rs
src/dc_receive_imf.rs
src/ephemeral.rs
src/events.rs
src/headerdef.rs
src/job.rs
src/lib.rs
src/message.rs
src/mimefactory.rs
src/mimeparser.rs
src/sql.rs
src/stock.rs

#1442 rebased on top of master

Async ephemeral messages

---

src/ephemeral.rs

Ephemeral task fix

---

src/imap/mod.rs

Parallel processing of messages results in bugs such as messages sent by
a new member being processed before the message that adds this member to
the chat, even when it has lower UID. In this case, messages are shown as
"[Unknown sender for this chat. See 'info' for more details.]", while
there is a message "Member ... added" right before, because writing the
information about new member to the database takes longer then reading
old index from the database.

imap: call dc_receive_imf sequentially

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

needed for a  1.10.1 ios bugfix release

prepare 1.40

---

deltachat-ffi/deltachat.h
deltachat-ffi/src/lib.rs
python/src/deltachat/message.py
python/tests/test_account.py
src/message.rs

Add dc_msg_get_ephemeral_{timer, timestamp}()

---

src/dc_receive_imf.rs

Start ephemeral timer immediately for already seen messages

---

examples/repl/cmdline.rs

repl does not compile on current master; this is fixed by this pr.

adapt repl to new marker

---

python/tests/test_account.py
src/context.rs
src/dc_receive_imf.rs
src/imap/mod.rs
src/job.rs
src/message.rs

Read the commit message.
Fixes #1672 
Fixes #1711

Send MDNs for messages deleted on the server

---

set_core_version.py

idea is that a tagged core version can not accidentally have lto=false.

set_version now ensures lto = true, more logging

---

src/mimefactory.rs

Mark location-only messages as auto-generated

---

src/imex.rs

import_backup: do not load all blobs into memory at once

---

python/CHANGELOG
python/src/deltachat/account.py
python/tests/test_account.py

reported by @adbenitez this morning from his life running bot

fix python's create_contact(self_addr) 

---

src/dc_receive_imf.rs
src/mimefactory.rs

Good thing you noticed this, Björn!

Fix #1739 LastSubject should not be updated for read receipt

---

src/dc_receive_imf.rs

Adhoc groups for group messages that don't have Chat-Group-ID are already
created above in another `create_or_lookup_adhoc_group`.
At this point it could be that there is a valid Chat-Group-ID header,
but no group was created because `removed_id` was non-zero i.e. received
message removes some group member.
If group was not explicitly left, current code creates an adhoc group
instead of trashing late or reordered messages that remove group
members. Such groups have adhoc group IDs locally, but proper group
message-IDs.  Attempts to reply to such groups or leave them creates
"split groups" for all other members of original group. The solution is
not to create adhoc groups in this case.

dc_receive_imf: do not create adhoc groups when group ID is known

---

src/job.rs
src/message.rs
src/mimefactory.rs

Do not send read receipts for system messages

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

~~we should merge https://github.com/deltachat/deltachat-core-rust/pull/1766 in first and rebase on master before merging.~~
~~do not for get to create and push the tag `1.41.0` after merging.~~

prepare 1.41

---

Cargo.lock

as CI seems to have cache problems and fail our tests let's see if a cargo update fixes it.

try unblocking CI by "cargo update"

---

Cargo.lock

This change fixes timeout issues with large files.
Fixes #1383

Update async-smtp and async-imap

---

src/dehtml.rs

dehtml: handle empty tags

---

deltachat-ffi/src/lib.rs
python/src/deltachat/chat.py
python/tests/test_account.py

Includes regression test for #1803

Fixes and tests for dc_chat_get_remaining_mute_duration

---

src/dc_receive_imf.rs

An `EphemeralTimerChanged` message with the same timer as already set can
be received when there are large delays or lost messages.  Even though
`inner_set_ephemeral_timer` should not be called in this case, because it
emits an event indicating timer change, system message will be added to
the chat, so it should be translated with `set_better_msg` in any case.

Always translate EphemeralTimerChanged message

---

src/dc_receive_imf.rs
src/mimeparser.rs
src/simplify.rs

Fixes #1364
cc @agutierrez25249
Reopened  #1811 with ascii branch name

Hide SIJÚ messenger footer

---

src/message.rs

Add more extensions to guess_msgtype_from_suffix()

---

src/configure/mod.rs

configure: add "mail." to smtp_server when configuring SMTP

---

src/mimeparser.rs

threading was broken in core43 as this flags unencrypted messages as errors
and errors are not replied-to.
the fix is not to mark missing signatures for unencrypted messages as errors.
for review: this is only a three-line change, rustfmt does a bit of noise and i've missed putting that into a separate commit, but comparing with whitespace ignored should do the job as well :)
fixes #1836 
i think, we should have some high-level tests with real non-delta-accounts for expected headers etc. things easily break otherwise, things are complex :)

fix threading in interation with non-delta-clients

---

Cargo.lock
Cargo.toml
src/imap/client.rs
src/imap/mod.rs

Lockfile should be updated once https://github.com/async-email/async-imap/pull/36 is merged

Update async-imap to fix Oauth2

---

src/chat.rs
src/config.rs
src/contact.rs
src/dc_tools.rs

Fix https://github.com/deltachat/deltachat-android/issues/1564

Remove newlines from group names, chat names and the displayname

---

.github/workflows/ci.yml
src/blob.rs
src/configure/auto_mozilla.rs
src/configure/auto_outlook.rs
src/configure/mod.rs
src/context.rs
src/dc_receive_imf.rs
src/dc_tools.rs
src/key.rs
src/location.rs
src/message.rs
src/mimeparser.rs
src/param.rs
src/pgp.rs
src/provider/mod.rs

Run clippy on tests and examples

---

src/peerstate.rs

Create and return immutable Peerstate instead.

Remove Peerstate::new()

---

src/configure/mod.rs

SMTP configurations are tested in a separate async task.
Closes #1867

Attempt IMAP and SMTP configuration in parallel

---

src/peerstate.rs

This commit fixes condition which ignores reordered autocrypt messages.
If a plaintext message resetting peerstate has been received, autocrypt
header should only be applied if it has higher timestamp.
Previously, timestamp of the last received autocrypt header was used,
which may be lower than last_seen timestamp.

Ignore reordered autocrypt headers

---

src/chat.rs
src/securejoin.rs
src/test_utils.rs

pretty verbose to read, but no magic.

Add happy path test for secure-join

---

src/configure/mod.rs

configure: add progress! calls during IMAP configuration

---

src/accounts.rs

HashMap may rearrange all accounts after each insertion and deletion,
making it unpredictable where the new account appears.

Make dc_accounts_get_all return accounts sorted

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

wow - an impressive list of changes!

prepare 1.46

---

ci_scripts/run-python-test.sh
ci_scripts/run-rust-test.sh

Followup for aae816369637021888eaf0fa22254e5f364eea7d

ci: set huponexit for inner bash processes

---

python/tests/test_account.py
src/contact.rs

Set contact ID in ContactsChanged on modification

---

python/tests/test_account.py
src/contact.rs

Emit chat modification event on contact rename

---

Cargo.lock
Cargo.toml
src/oauth2.rs
src/pgp.rs

updates
- pgp
- async-std
- surf
- mailparse

feat: update dependencies

---

deltachat-ffi/Doxyfile
deltachat-ffi/deltachat.h

fix doxygen warnings

---

src/param.rs

Newlines are escaped by repeating them.
This encoding is compatible to existing values, because they do not
contain newlines.

param: escape newlines in values

---

Cargo.lock

making sure latest bug fixes are in

update async-std to 1.6.5

---

deltachat-ffi/deltachat.h

Fixes https://github.com/deltachat/deltachat-core-rust/issues/1949

Mention in dc_event_get_data2_str method that it can also return 0

---

src/dc_tools.rs
src/imex.rs

Reverts deltachat/deltachat-core-rust#1952 because Desktop never had a release with tar-import

Revert "Export to the new backup format"

---

deltachat-ffi/deltachat.h
deltachat-ffi/src/lib.rs
src/dc_receive_imf.rs
src/message.rs
src/mimeparser.rs

https://github.com/deltachat/deltachat-core-rust/pull/1924

Accessible msg error and type changes

---

Cargo.lock

use new imap-proto/async-imap 0.4.1

---

deltachat-ffi/deltachat.h
src/config.rs
src/configure/mod.rs
src/job.rs

closes #2002 
to use that in provider-db, just add a `fetch_existing: 0` line to the `config_defaults` section.

add fetch_existing config value

---

src/provider/data.rs

ran `./src/provider/update.py ../provider-db/_providers/ > src/provider/data.rs` again

update provider-db, second time today

---

src/dc_receive_imf.rs

check protection properties for all chats, allow missing Chat-Verified header

---

spec.md

fix link to Protected Headers draft

---

src/chat.rs
src/dc_receive_imf.rs

see commit-messages for details.

drop protection message where not needed

---

src/dc_receive_imf.rs

by #2001, processing of protection-enabled and protection-disabled
messages is only done if verification-checks pass.
unfortunately, these verification checks
were only applied on already protected chats,
so that enabling via a protection-enabled message was not possible.
this is fixed by this pr.
moreover, when inner_set_protection() fails,
the error is shown in the chat.
i came over that when testing https://github.com/deltachat/deltachat-android/issues/1671 - and yes, we should have an automated python-test for that one day.

fix processing of protection-changed messages

---

python/src/deltachat/chat.py
python/tests/test_account.py
src/chat.rs

Do not allow to save drafts in non-writeable chats, fix #1986

---

src/job.rs

@adbenitez complained about this IIRC.

Don't peek-receipients/fetch-existing if this is a bot

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

did not add a tag yet, this should be done once this pr is merged, or just before.

prepare 1.47

---

src/configure/mod.rs

Previously empty autoconfig resulted in no servers being tried and no
error displayed.
Fixes #2024

configure: always try at least one IMAP and SMTP server

---

python/tests/test_account.py

just replace `set_blocked()` by `block()`

tests: avoid usage of deprecated contact.set_blocked()

---

src/dc_receive_imf.rs

fix #2020
When forwarding a message, the original `in_reply_to` stays in place.
I did not find any recent commit that changed anything about this,
but IIRC there was a bug that prevented setting the `in_reply_to` at
all.
So, for chat messages, do not look at the `InReplyTo` header (and also not
at the References header).
Possible additions:
- If there is no quote attached, we can remove `in_reply_to` when forwarding; not sure whether we should do that. This would have the advantage that if the other client is older, the message would appear in the right chat, too.
- If a normal MUA forwards a message, it could also appear wrongly in a group chat because of the `In-Reply-To`. Maybe when extracting a group id from `In-Reply-To` or `References` we should also check if the recipients list …

Saved-messages do not pop up in original chat in multi-device anymore

---

python/tests/test_account.py

as proposed by @link2xt in https://github.com/deltachat/deltachat-core-rust/pull/2034#pullrequestreview-515184291

Add test for "Saved-messages do not pop up in original chat in multi-device anymore"

---

python/src/deltachat/account.py
python/src/deltachat/chat.py
python/tests/test_account.py

fix chat.remove_contact()

---

examples/repl/main.rs

fixes #2026 
btw i don't think it makes much sense to have "good first issue" issues like this.

remove reference to star-commands.

---

src/dc_tools.rs

the test just did not work on the last day of a month 🎃

fix outdated test

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

maybe there are also some more fixed that should get it :)

prepare 1.48

---

src/mimefactory.rs

It is already done for voice messages and makes saving attachments to
one folder easier.

Add timestamps to images and videos

---

python/src/deltachat/tracker.py
python/tests/test_account.py
src/dc_tools.rs
src/imex.rs

I can't add tests to https://github.com/deltachat/deltachat-core-rust/pull/1999 as tar backups are still disabled, but I'll add tests for the smooth progress here. Update: I just included https://github.com/deltachat/deltachat-core-rust/pull/1999 here now so that I we don't have to take care to merge it first, so fix #1892

Re-enable Export to the new backup format, add backup progress, add a test for the backup progress

---

src/imap/idle.rs
src/scheduler.rs

In order to find out about #2065, I added some more verbose logging. I would like to merge this PR so that the logs get into the nightlys; we can revert it after #2065 is fixed.
**It is not necessary to read through all of the comments below :)**

Add verbose logging for #2065

---

src/mimefactory.rs
src/mimeparser.rs
test-data/message/attach_filename_apostrophed_invalid.eml

closes #2101 
see commit messages for detailed information.

use asterisk in filename-key more carefully

---

src/dehtml.rs
src/mimeparser.rs
src/simplify.rs
test-data/message/blockquote-tag.eml
test-data/message/gmx-quote-body.eml
test-data/message/gmx-quote.eml

Parse name="quote" divs 

---

src/chat.rs
src/config.rs
src/ephemeral.rs
src/job.rs
src/message.rs
src/sql.rs
src/test_utils.rs

- Make sure delete_expired_messages and housekeeping runs once a day
- delete more info about messages when putting them to trash (esp. also
delete txt_raw, from_id and to_id as we don't need those anymore, so
they are data that was unnecessarily kept)
fix #1926, fix #2090

Delete messages more thoroughly (and at all)

---

examples/repl/cmdline.rs

send-garbage has been removed, and setqr was not listed in help

repl: update list of commands

---

python/src/deltachat/message.py
python/tests/test_account.py

python: add `error` property to messages

---

python/tests/test_account.py
src/dc_receive_imf.rs

Don't ignore incoming mails without Received-header

---

deltachat-ffi/deltachat.h

document DC_STR in ffi

---

.github/workflows/ci.yml
ci_scripts/docker-coredeps/deps/build_rust.sh
deltachat-ffi/src/lib.rs
src/chat.rs
src/imex.rs
src/key.rs
src/message.rs
src/mimefactory.rs
src/mimeparser.rs
src/securejoin.rs
src/simplify.rs
src/test_utils.rs

The rust toolchain was bumped: https://github.com/deltachat/deltachat-core-rust/pull/2150
But sadly we need to do more than just updated that one file.
Plus, new toolchain, new lints to fix!

Update toolchain in all our files

---

src/config.rs
src/smtp/send.rs
src/sql.rs

fix #2157
Didn't test for the lack of a Nauta account :)

do not disable server-deletion when enabled by provider-db

---

src/test_utils.rs

I accidentally removed this in an earlier PR.

Add Debug back to TestContext

---

.github/workflows/ci.yml
src/chat.rs
src/events.rs
src/securejoin.rs

This fixes a bunch of doc comments and also adds the run to CI so that
failures get caught early.

Add rustdoc to CI and fix some doc comments

---

src/chat.rs
src/dc_receive_imf.rs
src/dc_tools.rs
src/imap/mod.rs

Stop relying on group IDs stored in message-IDs

---

src/dc_receive_imf.rs

Previously it was assigned to 1:1 chat.
To keep "reply privately" working, old behaviour is retained for chat messages.
Follow-up to #2164

Assign classic replies to two-member groups to group chat

---

src/contact.rs

This seems to be our standard way to do this.
Followup on #2168

Use bail macro

---

src/imap/idle.rs

This also makes info message "IMAP-fake-IDLEing folder=..." nicer,
because the folder name is not wrapped into Some() anymore.

fake_idle: unwrap watch_folder early to avoid doing it in a loop

---

Cargo.lock
src/mimeparser.rs

fix From:-header bug

---

src/job.rs

The current behaviour of deltachat is, that after a smtp_send job is failing for 17 times with a transient error (the smtp server tells us this is temporary) (not sure how long this takes, probably 30minutes) the next time the job will get scheduled is in 3 weeks (I think?). I think this behaviour is quite unhelpful because:
1. The use doesn't know that deltachat failed so send the message. The icon is only indicating that deltachat is _trying_ to send the message. In case of a error the user cannot even figure out the error that is happening. And looks and feels like it's some network issue or something opaque. Also reporting this issue is hard. I had to dive through logs to find those errors.
2. A message that is getting postponed to be sent in 3 weeks is not really helpful for a …

Make transient bad destination address error permanent after n tries

---

src/mimeparser.rs

follow-up of https://github.com/deltachat/deltachat-core-rust/pull/2193

comment on the quoted-encoded test

---

src/message.rs

Show sender name override in chatlist summary

---

src/imap/scan_folders.rs

This should fix the duplicate-messages-bug

Don't scan watched folders

---

python/src/deltachat/testplugin.py

tests from deltabot got into a deadlock while setting up accounts.  Be more specific with the "get online acocunt" helpers.

the test machinery is too stateful in waiting for accounts getting ready

---

src/chat.rs

just some tests i did while playing around with https://github.com/deltachat/deltachat-core-rust/pull/2199

add some tests for lookup_by_contact_id()

---

standards.md

add XEP-0392 to standards.md

---

src/dc_tools.rs
src/imex.rs

fix https://github.com/deltachat/deltachat-android/issues/1768

legacy (.bak) import: If backup files can't be opened, just try one that couldn't be opened

---

CHANGELOG.md

this needs to be collected before a 1.51 anyway and was requested just now by @Simon-Laux :)

add recent PRs between 1.50 and now to CHANGELOG

---

CHANGELOG.md
src/dc_receive_imf.rs

set correct name for mailchimp mailinglists

---

examples/repl/cmdline.rs
src/constants.rs
src/contact.rs
src/dc_tools.rs

It was not even doing what the documentation says: the implementation worked correctly only for bitindex=1 and bitindex=2.

Remove dc_tools::listflags_has

---

src/imap/mod.rs

check From: address on collecting recipients without creating/altering a contact-record if it is not SELF.
@Hocuri this is what i meant in https://github.com/deltachat/deltachat-core-rust/issues/2234#issuecomment-784529374 - did this pr while playing around, maybe code explains things better :)
i tried it out, and it works for me :) however, as always, might be i still understood things wrong :)
might close #2234

check From: address

---

src/dc_receive_imf.rs
src/mimeparser.rs

This lint is enabled by default in 1.50 toolchain.

Fix clippy::unnecessary_wraps warnings

---

src/dc_receive_imf.rs
src/mimeparser.rs
test-data/message/mailinglist_with_mimepart_footer.eml

remove mailinglist-footer coming as extra mimepart

---

src/dc_receive_imf.rs
src/ephemeral.rs
src/message.rs

Esp. remove some information for newly-arriving messages

Trash messages more thoroughly

---

src/test_utils.rs

This should solve this "Thread ... panicked while panicking"

Rust-tests: Don't panic while panicking

---

src/imap/mod.rs

fix #2188
Also, if we notice that the server rewinded uid_next, _also_ do a `ResyncFolders`, because the server likely forgot to change uid_validity and is re-using old uids.

Update uid_next if the server rewinded it

---

python/tests/test_account.py
src/dc_receive_imf.rs

Do not reset contact status after receiving a read receipt

---

.gitignore

(libdeltachat generated with cmake)

add /build directory to .gitignore

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

if that may cause a merge-conflict with #2089, maybe better wait a bit.

prepare 1.51

---

src/contact.rs
src/location.rs

fix `test_mailing_list_decide_block_then_unblock()`

exists() expects COUNT() in sql-statement

---

src/dehtml.rs
src/mimeparser.rs
test-data/message/allinkl-quote.eml

There probably won't be any merge conflicts with #2089, but it's probably better to wait, anyway.

Parse <blockquote> tags for better quote detection

---

deltachat-ffi/src/lib.rs
src/dc_receive_imf.rs
src/job.rs
src/message.rs

In order to find the cause of #2335, I think we should merge this, so that when it happens, we have a better log.
Before the release, we should revert this.

More logging for "core spams imap events"

---

python/src/deltachat/message.py

Add sticker viewtype

---

src/dehtml.rs

i wrote that little test to test the new coveage script :)
(that part was uncovered before and is covered now :)

test dehtml for pre-tag

---

python/src/deltachat/message.py
python/tests/test_account.py

Add "override_sender_name" API

---

python/src/deltachat/message.py
python/tests/test_account.py

Add html API

---

src/context.rs

ct.name was insufficient, as authname, overridden name and email address
fallback were not taken into account.
Dropping this condition increases performance by 25% according to the
benchmark.
Also add a test for search_msgs.

search_msgs: do not match contact names

---

src/mimefactory.rs

this should be merged to #2232 and tests that the `Subject:` header is not moved to the inner (hidden) header; currently, this test is failing.
in addition to the wrong moved `Subject:`, also `Chat-Disposition-Notification-To:` is moved from imf- to hidden header; this is not tested here, however, as i am not sure if that might be understood by the mimeparser already. maybe we should add another test for that bit.

test base64-avatar header moving

---

src/imap/scan_folders.rs
src/job.rs

Make logging less verbose

---

src/sql.rs

so that we do not forget about that test
and the issues we had with that :)
not sure if that is really useful, mostly i was wondering why one test was missing :)

re-add test_db_reopen

---

deltachat-ffi/deltachat.h
src/message.rs
src/stock_str.rs

this affects notifications and the chatlist.
So that its clearer that the message might not be written by the person which/who forwarded it.

add "Forwarded:" to summary2

---

CHANGELOG.md
python/tests/test_account.py
src/dc_receive_imf.rs

A regression due to switching from/to rusqlite

check_verified_properties: handle NULL in verified_key_fingerprint

---

src/mimeparser.rs

Add extension to avatars base64-encoded in headers

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

changelog was already maintained before, thanks a lot, @link2xt :)

prepare 1.54

---

scripts/set_core_version.py

make the hint about tagging in `scripts/set_core_version.py` a bit clearer; every some weeks i am stumbling over about when/how to tag :)

clarify tagging hint

---

python/tests/test_account.py

There was a bugreport for previous versions of DC that BCC-self
messages are not marked as seen if server-side Sieve rule moves them.
This test is an unsuccessful attempt to reproduce the bug,
which was confirmed to be fixed.
Related issue: #1979

dc_receive_imf: add python test for server-side message moving

---

src/contact.rs

Even if chat has no messages, contacts should not be deleted.
Otherwise chat will reference invalid contact ID which can't be loaded
from the database, resulting in broken contact list in group chats.

Do not allow to delete contacts with ongoing chats

---

src/securejoin.rs

securejoin: display error reason if there is any

---

examples/repl/cmdline.rs
src/chat.rs
src/mimeparser.rs

fix gif-stickers

---

src/sql.rs
src/test_utils.rs

I wanted to add a function like `get_info_contains` and a possibility to iterate over events in tests for quite some time (when writing other tests, but then I never actually did), now is the time :)
test_migration_flags will now quite reliably fail if sb forgets to update the db version (assuming they don't also forget the `info!(context, "[migration] v...");`)

Improve test_migration_flags, add EvTracker to test_utils

---

src/sql.rs
src/test_utils.rs

Tweak migration test

---

src/sql.rs
src/sql/migrations.rs
src/test_utils.rs

closes #2485, see commit messages for details.

fix migrate

---

src/accounts.rs

did that while playing around with dc_accounts_t during AEAP porting for iOS ...

add a test to make sure, the selected account is persisted on reopening

---

src/dc_receive_imf.rs

Do not process names, avatars, location XMLs, message signature
etc. for duplicate messages.
Previously only `add_parts` was stopped early, but not
`dc_receive_imf`. Also, `dc_receive_imf` processed From: and To:
fields and applied names to contacts even before checking the
Message-ID.
Fake Message-ID generation procedure is changed to operate on raw
header values to avoid interacting with the database.

dc_receive_imf: exit early if Message-ID is duplicate

---

src/dc_receive_imf.rs

Do not send any events in case of `add_parts` error.

dc_receive_imf: remove cleanup() closure

---

Cargo.toml
src/chat.rs

The test I wrote `test_sticker_forward` runs through but another test I wrote for verification `test_forward` doesn't because `is_forwarded()` somehow outputs `false`. 
I either forgot to do something in the testing framework or this really is a bug. 
Anyway, I need a review because I don't know how to fix this.

Fix #2325 (Stickerforwarding)

---

deltachat-ffi/src/lib.rs
src/chat.rs
src/dc_receive_imf.rs

Fix can_send for users not in a group

---

CHANGELOG.md

maybe its time to implement a check for it like we have in desktop

update core changelog july 17

---

README.md

Add information about system wide libdeltachat

---

src/accounts.rs

accounts: update EventEmitter on add_account

---

src/chat.rs
src/chatlist.rs
src/sql/migrations.rs

fixes #2562, see there and commit messages for details.
successor of #2514

fix archiving requests

---

src/message.rs

Previously handle_mdn() returned Ok(None) in response to SQL errors as
if SQL simply returned no rows.

message: bubble up SQL errors in handle_mdn()

---

src/dc_receive_imf.rs

dc_receive_imf: don't create chats when MDNs are received

---

README.md

Actually not sure where we have to set it. I guess at the first cmake command? Pleaaase help @link2xt @dotlambda

Add -DCMAKE_INSTALL_PREFIX flag example to README

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

after commit, on master make sure to:
git tag -a 1.57.0
git push origin 1.57.0

prepare 1.57

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

after commit, on master make sure to:
git tag -a 1.58.0
git push origin 1.58.0

prepare 1.58

---

src/mimeparser.rs

This bug sometimes results in sending read receipts to self in
multi-device setups.
It happens consistently in a setup where the first device is
configured to move messages to DeltaChat folder and the second device
is not. When both devices receive BCC-self message simultaneously, the
first device moves the message to DeltaChat folder, while the second
device tries to mark the message as seen in the Inbox. Regardless of
whether the second device marks the message as seen successfully or
fails because the message is already moved by the first device,
`Job.markseen_msg_on_imap()` sends the read receipt to the From
address.

fix: do not set WantsMdn param for outgoing messages

---

src/accounts.rs

as suggested by @link2xt on irc.
successor of #2559
closes #2606

add migrated accounts to events emitter

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

git tag -a 1.59.0
git push origin 1.59.0

prepare 1.59

---

src/imex.rs

On big backups it's possible that the progress calculation `let progress = 1000 * written_files / count;` calculates to the same number multiple times. It's unnecessary to emit multiple events with the same number (and spammed desktop quite a lot).

Backup import: Dont emit same event multiple times

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

after commit, on master make sure to:
```
git tag -a 1.60.0
git push origin 1.60.0
git tag -a py-1.60.0
git push origin py-1.60.0
```

Prepare 1.60

---

deltachat-ffi/src/lib.rs
src/accounts.rs

Make dc_accounts_t thread-safe

---

src/message.rs
src/mimeparser.rs

These sometimes arrive happen due to a bug in previous versions of
Delta Chat.
Fixes #2634

Ignore MDNs sent to self

---

src/imap.rs

It is always the same as Imap.session.is_some().

imap: remove unnecessary Imap.connected variable

---

src/dc_receive_imf.rs

This should make it easier to debug problems related to timer
rollbacks and reported failure to disable the timer in some chats.

Log all decisions when applying ephemeral timer to chats

---

src/peerstate.rs
src/sql.rs

Deduplicate peerstates during housekeeping

---

src/dc_receive_imf.rs
src/ephemeral.rs

This change also makes protection work for messages with quotes.

Fix ephemeral timer rollback protection

---

src/chat.rs
src/quota.rs

see commit messages for details

let quota-warning reappear after import, rewarn at 95%

---

python/tests/test_account.py
src/imap.rs
src/imap/select_folder.rs
src/job.rs

Create configured folders if they are deleted

---

src/configure.rs
src/configure/auto_mozilla.rs
src/configure/auto_outlook.rs
src/configure/server_params.rs

Try to lock strict TLS if certificate checks are automatic

---

src/provider.rs

Use system resolver configuration instead of Google DNS for MX queries

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

for the next android/ios release, probably next week - what else should go in?
git tag -a 1.62.0
git push origin 1.62.0
git tag -a py-1.62.0
git push origin py-1.62.0

prepare 1.62

---

deltachat-ffi/deltachat.h
deltachat-ffi/src/lib.rs
src/context.rs
src/log.rs

add dc_get_last_error()

---

src/securejoin.rs

currently, this message appears also for setup-contact, which is wrong

add 'waiting for being added to the group' only for group-joins

---

src/dc_receive_imf.rs
src/download.rs

closes #2810 
~~a test is missing, however.~~ also added a test.

do not assume 'no ephemeral timer' on partial downloads

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

another bugfix release :)
git tag -a 1.65.0
git push origin 1.65.0
git tag -a py-1.65.0
git push origin py-1.65.0

prepare 1.65

---

CHANGELOG.md
deltachat-ffi/deltachat.h
python/tests/test_account.py
src/chat.rs
src/chatlist.rs
src/stock_str.rs

Companion for https://github.com/deltachat/deltachat-android/pull/2134

Don't set draft after creating group

---

Cargo.lock
Cargo.toml
src/chat.rs
src/configure.rs
src/contact.rs
src/dc_receive_imf.rs
src/job.rs
src/mimefactory.rs
src/param.rs
src/peerstate.rs
src/simplify.rs
src/smtp/send.rs
src/summary.rs
src/sync.rs

This removes 8 dependencies from `Cargo.lock` and updates sqlite3 crates
See commit messages for details.
Another indirect dependency removal is submitted for rPGP: https://github.com/rpgp/rpgp/pull/147

Remove and update some dependencies

---

python/src/deltachat/account.py
python/src/deltachat/contact.py
python/src/deltachat/cutil.py
python/src/deltachat/events.py
python/src/deltachat/message.py
python/src/deltachat/provider.py

`cutil.from_dc_charpointer()` is guaranteed to return `str`, while
`cutil.from_optional_dc_charpointer()` may return `None` if C function
returns `NULL`.

python: add cutil.from_optional_dc_charpointer()

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

git tag -a 1.66.0
git push origin 1.66.0
git tag -a py-1.66.0
git push origin py-1.66.0
(we'll see this is forgotten again :)

prepare 1.66

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

git tag -a 1.67.0
git push origin 1.67.0
git tag -a py-1.67.0
git push origin py-1.67.0

prepare 1.67

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

git tag -a 1.68.0
git push origin 1.68.0
git tag -a py-1.68.0
git push origin py-1.68.0

prepare 1.68

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

git tag -a 1.69.0
git push origin 1.69.0
git tag -a py-1.69.0
git push origin py-1.69.0

prepare 1.69

---

src/param.rs

unknown keys may come from upgrades (previously used key no longer defined)
or from downgrades (when an upgrade before uses a new key).
the latter was probalby responsible for some avatar loss,
mainly by testers, that usually switch versions forth and back much more often.

do not abort Param parsing on unknown keys

---

src/chat.rs
src/dc_receive_imf.rs

@link2xt @adbenitez this is what we were talking about in the Delta Chat group?
i also tried to summarize the reasoning in the code comment a bit (i first was not sure about why we do not completely reconstruct on removal at all - but we had that before ;)
the change/bug as such was recently for the download-on-demand feature, https://github.com/deltachat/deltachat-core-rust/pull/2642
finally, that needs a test ...
@adbenitez i am not sure how often that happens for nauta - so, might be reasonable to do a core70 so that this change can come in to 1.26 series.

execute `Chat-Group-Member-Removed` even when arrived out of oder

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

git tag -a 1.70.0
git push origin 1.70.0
git tag -a py-1.70.0
git push origin py-1.70.0

prepare 1.70

---

src/mimefactory.rs

See commit messages for details

Put removed member in Bcc instead of To in the message about removal

---

python/tests/test_account.py
src/chat.rs
src/chatlist.rs
src/contact.rs
src/context.rs
src/dc_receive_imf.rs
src/download.rs
src/e2ee.rs
src/ephemeral.rs
src/html.rs
src/key.rs
src/login_param.rs
src/message.rs
src/mimefactory.rs
src/mimeparser.rs
src/qr.rs
src/securejoin.rs
src/stock_str.rs
src/test_utils.rs
src/update_helper.rs
test-data/message/AutocryptSetupMessage.eml
test-data/message/gmx-forward.eml
test-data/message/many_images_amazon_via_apple_mail.eml
test-data/message/protonmail-mixed-up.eml
test-data/message/protonmail-repaired.eml
test-data/message/subj_with_multimedia_msg.eml
test-data/message/text_alt_plain_html.eml
test-data/message/wrong-html.eml

The key stored in test-data has @example.org identity.

test_utils: fix Alice's address in alice_keypair()

---

src/dc_receive_imf.rs

Fix https://github.com/deltachat/deltachat-core-rust/issues/2867

Fix: Make add_parts() not early-exit

---

deltachat-ffi/deltachat.h

i came over that when working on the draft issue of https://github.com/deltachat/deltachat-core-rust/pull/2826

update draft docs

---

src/dc_receive_imf.rs
src/e2ee.rs
src/pgp.rs
test-data/message/rfc1847_encapsulation.eml

Validate detached signatures

---

CHANGELOG.md
deltachat-ffi/deltachat.h
python/src/deltachat/__init__.py
python/src/deltachat/testplugin.py
python/tests/test_account.py
src/config.rs
src/configure.rs
src/context.rs
src/imap/scan_folders.rs
src/provider/data.rs
src/scheduler.rs
src/scheduler/connectivity.rs

Remove `mvbox_watch` option and use `mvbox_move` instead

---

src/dc_receive_imf.rs
src/dc_tools.rs
src/message.rs
src/mimeparser.rs
src/sql/migrations.rs

Follow up to #2568 to get a clean history

add hop_info

---

src/sql/migrations.rs

that bit was missing in https://github.com/deltachat/deltachat-core-rust/pull/2751

migrate log for hop_info added

---

.github/workflows/ci.yml

Use cacing in a few more places, replace the manual caching by the
action to simplify.

Add some more caching to CI

---

python/tests/test_account.py

Time is weird, and really this assert doesn't add that much to the
party.
Fixes #2904

Fix flaky test

---

deltachat-ffi/src/lib.rs
src/chat.rs
src/contact.rs
src/dc_receive_imf.rs
src/dehtml.rs
src/imap.rs
src/job.rs
src/location.rs
src/message.rs
src/mimeparser.rs
src/peerstate.rs
src/qr.rs
src/securejoin.rs
src/securejoin/bobstate.rs

They result in compilation of duplicate code.

Reduce number of AsRef generics

---

src/sql.rs

Previously default of `auto_vacuum=NONE` was used.
`PRAGMA auto_vacuum=INCERMENTAL` allows running `PRAGMA
incremental_vacuum`. Unlike `VACUUM`, `PRAGMA incremental_vacuum`
frees unused pages without rebuilding the whole database, like the
`VACUUM` does, so it does not require additional disk space to build a
vacuumed copy of the database. This may even free enough space on the
disk to run `VACUUM` afterwards.
New setting will only be enabled for new databases or if the `VACUUM`
command runs successfully. Currently `VACUUM` is only executed on
backup export, but may fail nevertheless if there is not enough space
on the disk.
Also try to run `PRAGMA incremental_vacuum` during housekeeping. It
may not be the best strategy, but likely does not make any difference
under normal usage when the …

sql: enable `auto_vacuum=INCREMENTAL`

---

Cargo.lock
python/tests/test_account.py
src/chat.rs
src/imap.rs
src/imap/select_folder.rs
src/job.rs
src/message.rs
src/sql/migrations.rs
src/test_utils.rs
standards.md

Synchronize Seen status across devices

---

src/context.rs

Also hide derive_blobdir and derive_walfile.

context: hide ongoing process internals from public API

---

deltachat-ffi/deltachat.h

that was overseen in https://github.com/deltachat/deltachat-core-rust/pull/2951

remove outdated DC_STR_STATUSLINE link

---

src/blob.rs

This was written in a way which attempted to avoid easily creating an
infinite loop.  But really that's a python idiom and doesn't work very
well in Rust.  Worse, as shown by #2972 it is really easy to still get
this wrong.  Instead do this the rust way, this way the compiler can
also reason properly about the branches and what is unreachable
removing some bogus dead code.

Re-write the blob filename creation loop

---

CHANGELOG.md
src/context.rs
src/sql.rs

Add "database_encrypted" field to Context.get_info()

---

CHANGELOG.md
src/job.rs
src/smtp.rs
src/smtp/send.rs

smtp: retry immediately if connection is stale

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

git tag -a 1.71.0
git push origin 1.71.0
git tag -a py-1.71.0
git push origin py-1.71.0

prepare 1.71

---

draft/webxdc-dev-reference.md

counterpart of https://github.com/deltachat/deltachat-android/pull/2209 and https://github.com/deltachat/webxdc-dev/pull/17
changes in the rust part are not needed.

adapt draft to new api

---

draft/webxdc-dev-reference.md

idea from https://github.com/deltachat/deltachat-core-rust/pull/3017#discussion_r794893073

add a link to search for #webxdc on github to the webxdc-docs

---

CHANGELOG.md
deltachat-ffi/deltachat.h
src/config.rs

Don't watch Sent folder by default

---

CHANGELOG.md
src/mimeparser.rs
src/webxdc.rs

fix splitting off text from webxdc messages

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

git tag -a 1.73.0
git push origin 1.73.0
git tag -a py-1.73.0
git push origin py-1.73.0

prepare 1.73

---

deltachat-ffi/deltachat.h

targets https://github.com/deltachat/deltachat-android/pull/2206#pullrequestreview-868103431

Only fetch mvbox deltachat.h additions

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

git tag -a 1.74.0
git push origin 1.74.0
git tag -a py-1.74.0
git push origin py-1.74.0

prepare 1.74

---

CHANGELOG.md
src/ephemeral.rs

For me this reduced query time from 0.3 s to 0.05 s.

Optimize delete_expired_imap_messages()

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml

prepare 1.75

---

CHANGELOG.md
python/tests/test_account.py
src/imap.rs

imap: batch message deletion

---

CHANGELOG.md
src/smtp.rs

smtp: set message state to failed when retry limit is exceeded

---

CHANGELOG.md
src/smtp.rs

Add more SMTP logging for #3092 debugging.

smtp: add more logging

---

Cargo.lock
Cargo.toml

Update rusqlite to stable version

---

CHANGELOG.md
python/tests/test_account.py
src/config.rs
src/context.rs
src/imap.rs

closes https://github.com/deltachat/deltachat-core-rust/issues/2897 , see there for details and reasoning (came over that just on issue gardening :)

remove sentbox_move

---

deltachat-ffi/deltachat.h

Various corrections #1

---

.github/workflows/upload-docs.yml
.github/workflows/upload-ffi-docs.yml

For the corresponding server config, see https://github.com/deltachat/sysadmin/tree/master/rs.delta.chat

GitHub Action to build & upload the rust documentation to rs.delta.chat

---

README.md

add note about perl requirement to readme closes #3106

---

CHANGELOG.md
python/tests/test_account.py
src/imap.rs

Start ephemeral timer when seen status is synchronized via imap

---

src/message.rs

Resultify delete_poi_location()

---

src/chat.rs
src/imap.rs
src/job.rs

See https://github.com/deltachat/deltachat-core-rust/pull/3129#discussion_r828381560

Use `repeat_vars()` more

---

CHANGELOG.md
examples/repl/cmdline.rs
src/sql.rs
src/sql/migrations.rs

Makes `dc_receive_imf()` (and probably other parts of the core) about 6% faster.
Measured with #3128

Introduce config caching

---

src/dc_receive_imf.rs

Do not overwrite better_msg if apply_group_changes returns None

---

Cargo.toml
benches/get_chat_msgs.rs
benches/get_chatlist.rs

add chatlist loading benchmark

---

src/sql.rs

i was looking at it because of ways to fix #3166 -- but this is an independent readability improved. no code logic changed. 

housekeeping cleanup: factor out remove-unused-files logic

---

examples/repl/cmdline.rs

- allow spaces in queries
- show query and scope below result
came over these minor things when targeting https://github.com/deltachat/deltachat-ios/issues/1505

improve repl message search

---

src/contact.rs
src/dc_receive_imf.rs

Caught another case of using Display instead of ToSql, now all tests
pass again.

Re-enable custom Display for ContactId

---

CHANGELOG.md
src/dc_receive_imf.rs

Consider outgoing messages to just one receiver as "private message"

---

CHANGELOG.md
src/scheduler.rs
src/smtp.rs

smtp: retry message sending automatically if loop is not interrupted

---

Cargo.lock

update deps for 1.30 release series

---

CHANGELOG.md
src/config.rs
src/dc_tools.rs
src/ephemeral.rs
src/imap.rs

Take `delete_device_after` into account when calculating ephemeral loop timeout

---

CHANGELOG.md
src/scheduler.rs

This is an alternative solution to speed up message receiving. See #3201 for related discussion.

do imap expiration/deletion after fetching messages

---

CMakeLists.txt
python/install_python_bindings.py

This patch has been working well in Nixpkgs for a while: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/libdeltachat/darwin-dylib.patch

dynamic libraries use dylib extension on Darwin

---

draft/webxdc-dev-reference.md

update dev-reference to reflect new promise feature for setup

---

draft/webxdc-dev-reference.md

see https://github.com/deltachat/deltachat-core-rust/pull/3220/files#r852073733

webxdc documentation: make function declaration correct JavaScript

---

src/chat.rs
src/job.rs
src/message.rs
src/scheduler.rs

Run housekeeping directly from the inbox loop
instead of creating inbox loop job.

Remove housekeeping job

---

python/src/deltachat/direct_imap.py
python/tests/test_account.py

enhance waiting for direct imap idle events to prevent randomness

---

src/job.rs

Further cleanup of jobs after #3235

Remove job::{Action,Thread}::Unknown variants

---

.github/workflows/ci.yml
benches/get_chat_msgs.rs
benches/get_chatlist.rs

Also run clippy for benchmarks in CI

---

src/blob.rs

Speeds up running the rust tests by about a factor of 2.
BTW using `cargo nextest` (after installing nextest e.g. with `pacman -Syu cargo-nextest` or `cargo install cargo-nextest`) you can see which tests take longest. 
With this PR, the longest tests are:
```
PASS [   8.380s] deltachat context::tests::test_limit_search_msgs
PASS [   6.775s] deltachat imex::tests::test_render_setup_file
PASS [  11.286s] deltachat chat::tests::test_modify_chat_disordered
PASS [   7.221s] deltachat imex::tests::test_render_setup_file_newline_replace
PASS [  18.530s] deltachat blob::tests::test_recode_image_1
PASS [  36.478s] deltachat blob::tests::test_recode_image_2
Summary [  36.614s] 549 tests run: 549 passed, 0 skipped
```
(all other tests are under 3s) (note that tests are run in parallel)
Probably …

Speedup rust tests

---

src/scheduler.rs

The limit on the number of jobs executed in a row was introduced to
prevent large queues of small jobs like MarkseenMsgOnImap, MoveMsg and
DeleteMsgOnImap from delaying message fetching. Since all these jobs
are now removed and IMAP operations they did are now batched, it is
impossible to have 20 or more queued IMAP jobs.

Don't count IMAP jobs in scheduler

---

python/tests/test_account.py

don't test python's imap idle as it's not needed. also add some more logging.

try fix a sometimes failing test

---

python/tests/bench_test_setup.py

see module comment for how to run it.  

add a little bench file for measuring test overheads 

---

CHANGELOG.md
src/job.rs
src/location.rs
src/scheduler.rs

Replace location jobs with async location loop

---

python/src/deltachat/testplugin.py

Fix logging for pseudo configured accounts, and introduce "--debug-setup" option to show more events

---

deltachat-ffi/src/lib.rs
python/src/deltachat/account.py
python/src/deltachat/events.py
python/tests/test_lowlevel.py
src/context.rs

i don't get segfaults anymore, and can also hit control-c at will without segfaults. 

fix segfaults with python runs by slight tweak

---

deltachat-ffi/src/lib.rs
src/contact.rs
src/dc_receive_imf.rs
src/login_param.rs

Reduce number of generic `impl AsRef`

---

draft/webxdc-dev-reference.md

Link to webxdc organization

---

draft/webxdc-dev-reference.md

Might be better to put this lower or at the end, but if more people see it they might feel prompted to help us merge with the guidebook.

Link to guidebook

---

draft/webxdc-dev-reference.md

this bit was forgotten in https://github.com/deltachat/deltachat-core-rust/pull/3314/files

document source_code_url in reference

---

draft/webxdc-dev-reference.md

unify language and method names

---

CHANGELOG.md
src/imap/select_folder.rs

Better error reporting when creating a folder fails

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml
package.json

this is the first release that also integrates node, the build script also modified `package.json` - if there are issues, feel free to directly push to this pr :)
git tag -a 1.81.0
git push origin 1.81.0
git tag -a py-1.81.0
git push origin py-1.81.0

prepare 1.81

---

src/ephemeral.rs

Use params_iter() instead of manually constructing Vec

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml
package.json

this pr should be rebased after https://github.com/deltachat/deltachat-core-rust/pull/3335 is reviewed+merged (#3335 is already part of the changelog in this pr)
after merge, on master make sure to: 
git tag -a 1.82.0
git push origin 1.82.0
git tag -a py-1.82.0
git push origin py-1.82.0

prepare 1.82

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml
package.json

after merge, on master make sure to:
git tag -a 1.83.0
git push origin 1.83.0
git tag -a py-1.83.0
git push origin py-1.83.0

prepare 1.83.0

---

CHANGELOG.md
deltachat-ffi/src/lib.rs
src/accounts.rs
src/blob.rs
src/dc_receive_imf.rs
src/events.rs
src/html.rs
src/key.rs
src/lib.rs
src/location.rs
src/login_param.rs
src/mimeparser.rs
src/oauth2.rs
src/pgp.rs
src/securejoin.rs
src/sql.rs

Reduce unwrap and expect usage

---

CHANGELOG.md
src/config.rs
src/key.rs
src/test_utils.rs

When changing self addr, transfer private key to new addr

---

CHANGELOG.md
src/securejoin.rs
src/securejoin/bob.rs
src/securejoin/bobstate.rs

Refactoring to reduce the number of custom error types.

securejoin: replace thiserror with anyhow

---

.github/workflows/node-tests.yml

Node tests should not only run for pull requests

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml
package.json

after merge, on master make sure to:
git tag -a 1.84.0
git push origin 1.84.0
git tag -a py-1.84.0
git push origin py-1.84.0

prepare 1.84.0

---

CHANGELOG.md
src/dc_tools.rs
src/pgp.rs

Reduce thiserror usage

---

python/examples/echo_and_quit.py
python/examples/group_tracking.py
python/examples/test_examples.py
python/pyproject.toml
python/src/deltachat/__init__.py
python/src/deltachat/_build.py
python/src/deltachat/account.py
python/src/deltachat/chat.py
python/src/deltachat/contact.py
python/src/deltachat/cutil.py
python/src/deltachat/direct_imap.py
python/src/deltachat/events.py
python/src/deltachat/hookspec.py
python/src/deltachat/message.py
python/src/deltachat/props.py
python/src/deltachat/provider.py
python/src/deltachat/testplugin.py
python/src/deltachat/tracker.py
python/tests/auditwheels.py
python/tests/package_wheels.py
python/tests/stress_test_db.py
python/tests/test_0_complex_or_slow.py
python/tests/test_1_online.py
python/tests/test_2_increation.py
python/tests/test_3_offline.py
python/tests/test_4_lowlevel.py
python/tox.ini

the only manual change was to the tox.ini file, the rest is automatic formatting

apply isort and black formatters, add format checking to CI

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml
package.json

after merge, on master make sure to:
```
git tag -a 1.85.0
git push origin 1.85.0
git tag -a py-1.85.0
git push origin py-1.85.0
```

bump version to 1.85.0

---

CHANGELOG.md
src/imex.rs
src/sql.rs

sql: do not reset our database if backup cannot be decrypted

---

CHANGELOG.md
src/config.rs
src/configure.rs
src/context.rs
src/imap.rs
src/job.rs
src/scheduler.rs

Refactoring to remove more jobs

Remove Action::FetchExistingMsgs

---

CHANGELOG.md
python/src/deltachat/account.py
python/src/deltachat/chat.py
python/src/deltachat/message.py
python/src/deltachat/testplugin.py
python/tests/test_3_offline.py

update python api

---

src/chat.rs
src/e2ee.rs
src/html.rs
src/lib.rs
src/mimefactory.rs
src/pgp.rs
src/webxdc.rs

Enable clippy::unused_async lint

---

deltachat-ffi/src/lib.rs
src/lib.rs

Remove unused extern crates

---

.github/mergeable.yml

Fix small typo

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml
package.json

git tag -a 1.86.0
git push origin 1.86.0
git tag -a py-1.86.0
git push origin py-1.86.0

prepare 1.86

---

deltachat-ffi/src/lib.rs
src/chat.rs
src/message.rs
src/webxdc.rs

just came over that when reviewing and playing around with https://github.com/deltachat/deltachat-core-rust/pull/3402

bubble up errors from update_param() and some related functions

---

python/install_python_bindings.py
python/setup.py
python/tox.ini

python: autoformat setup.py and install_python_bindings.py

---

src/blob.rs
src/chat.rs
src/param.rs

Replace BlobError type with anyhow

---

src/events.rs
src/test_utils.rs

Those are the things that I implemented when working on tests in https://github.com/deltachat/deltachat-core-rust/pull/3385.
Pulling them out for 1. reviewing already and 2. not making the other PR too big

test_utils.rs improvements from my AEAP PR

---

.github/workflows/node-package.yml
CHANGELOG.md
node/README.md
node/scripts/generate-constants.js
package.json

- node: remove split2 dependency
- node: make sure to also generate constants again in npm package build (in case there are new constants that were forgotten to be updated before core tagging)
- node: add git installation info to readme
closes: #3414

remove split2 dependency

---

CHANGELOG.md
Cargo.lock
Cargo.toml

*some description to make mergeable happy*

feat: update pgp to 0.8 and rand to 0.8

---

CHANGELOG.md
deltachat-ffi/deltachat.h
deltachat-ffi/src/lot.rs
src/qr.rs

probably the code is a bit ugly, rust compiler is awesome, I could call this PR "compiler-driven programming" :D
feel free to edit and make it more idiomatic (what is the equivalent of "pythonic" for rust? rusty? XD)

Detect draft from QR with mailto data

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml
package.json

git tag -a 1.90.0
git push origin 1.90.0
git tag -a py-1.90.0
git push origin py-1.90.0

release 1.90.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml
package.json

git tag -a 1.91.0
git push origin 1.91.0
git tag -a py-1.91.0
git push origin py-1.91.0

Prepare release 1.91.0

---

node/lib/chat.ts
node/lib/types.ts
node/src/module.c

the node part of https://github.com/deltachat/deltachat-core-rust/pull/3520
not tested, we'll see if ci gets green :)

add getMailinglistAddr() to node

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml

use same encoded-words as deltachat/rust-email

---

CHANGELOG.md
deltachat-ffi/deltachat.h
deltachat-ffi/src/lib.rs
node/lib/contact.ts
node/src/module.c
src/contact.rs

closes #3558 
i skipped node/jsonrpc for now, maybe only one of them is needed when it finds its way to desktop at some point in the future.

add was_seen_recently()

---

deltachat-ffi/deltachat.h

this was missing in https://github.com/deltachat/deltachat-core-rust/pull/3567/files

document new bot behavior wrt accepting chats

---

CHANGELOG.md
deltachat-jsonrpc/src/api/types/chat.rs
deltachat-jsonrpc/src/api/types/chat_list.rs
deltachat-jsonrpc/src/api/types/contact.rs
deltachat-jsonrpc/typescript/generated/client.ts
deltachat-jsonrpc/typescript/generated/types.ts

- jsonrpc: add `is_broadcast` property to `ChatListItemFetchResult`
- jsonrpc: add `was_seen_recently` property to `ChatListItemFetchResult`, `FullChat` and `Contact`

jsonrpc chatlistitem missing properties

---

CHANGELOG.md
src/receive_imf.rs
src/webxdc.rs

Only apply webxdc updates for members of group 

---

src/tools.rs

link2xt is this what you had in mind or is there a prettier way?

remove usage of clippy::indexing_slicing in truncate_by_lines

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml
deltachat-jsonrpc/Cargo.toml
deltachat-jsonrpc/typescript/package.json
package.json

after commit, on master make sure to:
git tag -a 1.96.0
git push origin 1.96.0
git tag -a py-1.96.0
git push origin py-1.96.0

prepare 1.96.0

---

CHANGELOG.md
src/sql/migrations.rs

They cluttered the test output.

 Join all migration messages into one

---

node/test/test.js

the solution was to ignore events

fix nodejs jsonrpc smoke tests

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml
deltachat-jsonrpc/Cargo.toml
deltachat-jsonrpc/typescript/package.json
package.json

git tag -a 1.97.0
git push origin 1.97.0
git tag -a py-1.97.0
git push origin py-1.97.0

Prepare 1.97.0 release

---

CHANGELOG.md
src/context.rs

allow searching for unaccepted requests

---

examples/repl/cmdline.rs
examples/repl/main.rs
src/chat.rs
src/html.rs
src/lib.rs
src/mimefactory.rs
src/plaintext.rs
src/qr.rs
src/reaction.rs
src/receive_imf.rs
src/scheduler/connectivity.rs
src/tools.rs
src/webxdc.rs

Fix clippy warnings

---

CHANGELOG.md
src/message.rs

This is to make debugging #3688 easier.

Add IMAP UIDs to message info

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml
deltachat-jsonrpc/Cargo.toml
deltachat-jsonrpc/typescript/package.json
deltachat-rpc-server/Cargo.toml
package.json

git tag -a 1.101.0
git push origin 1.101.0
git tag -a py-1.101.0
git push origin py-1.101.0

prepare 1.101.0

---

src/authres.rs

Doesn't make a difference at this point, since the test is ignored anyway.

Small test fix

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml
deltachat-jsonrpc/Cargo.toml
deltachat-jsonrpc/typescript/package.json
deltachat-rpc-server/Cargo.toml
package.json

git tag -a 1.102.0
git push origin 1.102.0
git tag -a py-1.102.0
git push origin py-1.102.0

Release 1.102.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deltachat-ffi/Cargo.toml
deltachat-jsonrpc/Cargo.toml
deltachat-jsonrpc/typescript/package.json
deltachat-rpc-server/Cargo.toml
package.json

git tag -a 1.104.0
git push origin 1.104.0
git tag -a py-1.104.0
git push origin py-1.104.0

release 1.104.0

---

deltachat-rpc-client/examples/echobot.py
deltachat-rpc-client/examples/echobot_advanced.py
deltachat-rpc-client/src/deltachat_rpc_client/__init__.py
deltachat-rpc-client/src/deltachat_rpc_client/_utils.py
deltachat-rpc-client/src/deltachat_rpc_client/account.py
deltachat-rpc-client/src/deltachat_rpc_client/chat.py
deltachat-rpc-client/src/deltachat_rpc_client/client.py
deltachat-rpc-client/src/deltachat_rpc_client/const.py
deltachat-rpc-client/src/deltachat_rpc_client/contact.py
deltachat-rpc-client/src/deltachat_rpc_client/deltachat.py
deltachat-rpc-client/src/deltachat_rpc_client/events.py
deltachat-rpc-client/src/deltachat_rpc_client/message.py
deltachat-rpc-client/src/deltachat_rpc_client/pytestplugin.py
deltachat-rpc-client/tests/test_something.py

improve deltachat-rpc-client lib (part #2) 

---

CHANGELOG.md
deltachat-ffi/deltachat.h
deltachat-ffi/src/lib.rs
python/src/deltachat/contact.py
python/tests/test_0_complex_or_slow.py
src/chat.rs
src/contact.rs
src/e2ee.rs
src/lib.rs
src/location.rs
src/mimeparser.rs
src/peerstate.rs
src/qr.rs
src/receive_imf.rs
src/securejoin.rs
src/securejoin/bobstate.rs
src/sql/migrations.rs
src/test_utils.rs
src/tools.rs

Add verifier information

---

node/test/test.js

remove unused imports
and fail without revealing the token

improve error of node tests

---

CHANGELOG.md
python/tests/test_1_online.py
src/chat.rs
src/receive_imf.rs

Emit DC_EVENT_MSGS_CHANGED for DC_CHAT_ID_ARCHIVED_LINK when the number of archived chats with     unread messages increases (#3940)

---

node/README.md

fix node readme

---

CHANGELOG.md
Cargo.toml
benches/contacts.rs
benches/send_events.rs
src/chat.rs
src/config.rs
src/context.rs
src/debug_logging.rs
src/events.rs
src/lib.rs
src/message.rs
src/param.rs
src/receive_imf.rs
src/sql.rs
src/webxdc.rs

Follow up to #3871 
This implements @Hocuri's suggestions to put the background loop onto contex, so quite a lot change.

Debug logging v2

---

python/src/deltachat/events.py

capture unexpected exceptions in EventThread

---

deltachat-rpc-client/src/deltachat_rpc_client/events.py
deltachat-rpc-client/tests/test_something.py

add is_bot to NewMessage event filter

---

CHANGELOG.md
deltachat-ffi/deltachat.h
deltachat-ffi/src/lib.rs
src/message.rs
src/mimefactory.rs

See https://github.com/deltachat/deltachat-core-rust/issues/4056

Add dc_msg_set_subject() C FFI

---

src/provider/update.py

Update provider/update.py according to the `struct Provider` changes

---

src/receive_imf/tests.rs

this is the test created during review of #4083 (see comment there fore details)

add test for Context::update_contacts_timestamp()

---

.github/workflows/upload-docs.yml

Also document private items for rust docs

---

deltachat-ffi/Doxyfile.css
deltachat-ffi/deltachat.h

Update doxygen for cffi docs

---

deltachat-ffi/deltachat.h

just some minor things to let  doxygen sort add all methods and classes correctly.
should be merged to #4007 - i did not push that directly there to not mess up with current rebasings :)

send backup doxygen fixes

---

CHANGELOG.md
src/imex.rs

Fix #3889
@r10s or someone else with an iOS device, is the new message also accurate on iOS?

More accurate maybe_add_bcc_self device message text

---

src/imex/transfer.rs

not sure if jsonrpc is affected somehow

typo: CollectionReceived

---

src/sql.rs

in order to make the reason for our decision as clear as possible to future readers
follow-up to #4100 
#skip-changelog I guess it's not an interesting change for changelog readers?

Improve comment on `write_lock()`

---

deltachat-ffi/deltachat.h

add define missing from send-backup pr

---

python/examples/test_examples.py
python/src/deltachat/testplugin.py
python/tests/test_1_online.py

python: Wait for initial Resync in the bot tests

---

CHANGELOG.md
Cargo.lock
deltachat-rpc-server/Cargo.toml
deltachat-rpc-server/src/main.rs

Do it as per "Thread safety" section in deltachat-ffi/deltachat.h. Also terminate on ctrl-c.

Cleanly terminate deltachat-rpc-server (#4234)

---

CHANGELOG.md
src/contact.rs
src/qr.rs

Part of #4188.
See commit messages for details.

Small verification fixes

---

CHANGELOG.md
src/imap.rs

It doesn't seem to add value and gives the impression that something went wrong.

Remove confusing log "ignoring unsolicited response Recent(…)"

---

CHANGELOG.md
src/receive_imf.rs
src/receive_imf/tests.rs
src/test_utils.rs

Fix #4313
Ping @flub since this adds a new `test_utils` API, which you may have opinions on.

Don't let blocking be bypassed using groups

---

src/imex/transfer.rs
src/qr.rs
src/receive_imf/tests.rs

Clippy; remove forgotten dbg!

---

deltachat-jsonrpc/src/api/mod.rs
deltachat-jsonrpc/src/api/types/events.rs
deltachat-jsonrpc/src/api/types/mod.rs
deltachat-jsonrpc/src/lib.rs
deltachat-jsonrpc/typescript/src/client.ts
deltachat-rpc-client/src/deltachat_rpc_client/rpc.py

also move events.rs to types
close #4371

jsonrpc: use camel-case for Event struct and move events.rs to types folder

---

deltachat-ffi/deltachat.h

clarify transitive behaviour of dc_contact_is_verfified()

---

deltachat-ffi/deltachat.h

this was changed some time ago, see https://docs.webxdc.org/spec.html#sendupdate

fix example in ffi docs

---

src/receive_imf.rs

Looks like it's some forgotten check. If so, i think it's better to do before #4597.
Also don't set protection to ProtectionBroken if it already is.

fix: receive_imf: Set protection only for Chattype::Single (#4597)

---

src/chat.rs
src/chatlist.rs
src/receive_imf/tests.rs
src/tests/verified_chats.rs

fix: Return from dc_get_chatlist(DC_GCL_FOR_FORWARDING) only chats where we can send (#4616)

---

src/receive_imf.rs
src/receive_imf/tests.rs

It can be not good for membership consistency if we missed a message adding a member, but improves security because nobody can add themselves to a group from now on.

fix: apply_group_changes(): Forbid membership changes from possible non-members (#3782)

---

deltachat-ffi/deltachat.h
src/chatlist.rs

api: allow to filter by unread in chatlist:try_load

---

CHANGELOG.md

Add Changelog entry for `is_protection_broken`

---

python/src/deltachat/testplugin.py

fix: remove unused --liveconfig option

---

src/imap/idle.rs
src/scheduler.rs

Fix timeout handling for IMAP and SMTP retries

---

python/tests/test_0_complex_or_slow.py
src/chat.rs
src/mimefactory.rs
src/mimeparser.rs
src/receive_imf.rs
src/securejoin.rs
src/tests/verified_chats.rs

See https://github.com/deltachat/securejoin/blob/main/uxscenarios/resetup.md#i-happy-path-and-resetup-scenarios-with-green-checkmarked-chatting
The last commit fixes https://github.com/deltachat/deltachat-core-rust/issues/4982

fix: Make sure the resetup happy path works

---

src/chat.rs
src/receive_imf.rs
test-data/golden/chat_test_msg_with_implicit_member_add

@link2xt, thanks alot for #4986! Better not to make such bugs. But that means we still don't have enough tests. Here i add a test that actually tests your fix.

feat: Never drop better message from apply_group_changes()

---

src/chat.rs

Chats synchronisation fixups

---

src/mimefactory.rs

For encrypted ones it's already done.

feat: Add "From:" to protected headers for signed-only messages

---

src/receive_imf.rs

Some SMTP servers are running slow before-queue filters, most commonly Postfix with `rspamd` filter which is implemented as a [before-queue Milter](https://www.postfix.org/MILTER_README.html). Some of `rspamd` plugin filters are slow on large mails.
We previously had problems with timing out during waiting for SMTP response: https://github.com/deltachat/deltachat-core-rust/issues/1383. This is largely fixed by https://github.com/async-email/async-smtp/pull/29 and currently we have 60-second timeout just for reading a response but apparently it is not sufficient -- maybe connection gets killed by NAT while we are waiting for response or `rspamd` takes more than 60 seconds for large messages.
As a result a message is resent multiple times and eventually fails with "too many retries" while …

fix: Delete received outgoing messages from SMTP queue (#5115)

---

src/message.rs
src/receive_imf/tests.rs

fix: message::update_msg_state(): Reset error if message is delivered (#5119)

---

src/chat.rs
src/contact.rs

feat: Sync contact creation/rename across devices (#5163)

---

src/smtp.rs

Add some docs to smtp functions

Add more docs

---

Cargo.lock
Cargo.toml
src/e2ee.rs
src/mimefactory.rs

feat: Use Quoted-Printable for the text part (#3986)

---

deltachat-jsonrpc/src/api/types/message.rs
src/mimeparser.rs
src/smtp.rs
src/stock_str.rs

feat: Add system message when provider does not allow unencrypted messages (#5161)

---

src/qr.rs

Accepts invite links with `https://i.delta.chat[/]#FINGERPRINT&a=ADDR[&OPTIONAL_PARAMS]` scheme. Only `i.delta.chat` domain is supported now not to intersect with the common HTTPS scheme.
Close #5217

feat: qr::check_qr(): Accept i.delta.chat invite links (#5217)

---

python/tests/test_1_online.py

test: test_import_export_online_all: Send the message to the existing address to avoid errors (#5220)

---

python/src/deltachat/account.py
python/tests/test_1_online.py
src/chat.rs
src/download.rs
src/imap.rs
src/message.rs
src/reaction.rs
src/receive_imf.rs
src/receive_imf/tests.rs
src/webxdc.rs

fix: Delete resent messages on receiver side (#5155)

---

src/imap.rs
src/imap/select_folder.rs

Fixes related to mvbox creation

---

CHANGELOG.md

somehow a whole issue sneaked in :)

cleanup changelog

---

src/tests/verified_chats.rs

test: Fix test_verified_oneonone_chat_broken_by_device_change() (#5280)

---

src/decrypt.rs
src/mimeparser.rs
src/peerstate.rs

Accordingly, there's no need in `Peerstate` for self addresses (and in the db too).
Close #5259

refactor: Don't even parse Autocrypt header for outgoing messages (#5259)

---

deltachat-rpc-client/src/deltachat_rpc_client/const.py

Not sure if all of them are really needed, please comment what to remove.
Close #5110

chore: RPC client: Add missing constants (#5110)

---

deltachat-rpc-client/pyproject.toml

build: add README to deltachat-rpc-client Python packages

---

src/blob.rs

fix: Add white background to recoded avatars (#3787)

---

.gitignore
flake.nix

Add nix development shell to flake.nix.

build: add development shell

---

deltachat-ffi/deltachat.h
deltachat-jsonrpc/src/api.rs
deltachat-rpc-client/src/deltachat_rpc_client/account.py
src/securejoin.rs
src/token.rs
standards.md

docs: update references to SecureJoin protocols

---

.github/workflows/upload-docs.yml
flake.nix

Necessary for https://github.com/deltachat/sysadmin/issues/156

Build typescript / jsonrpc docs with nix + CI

---

Cargo.toml
deltachat-contact-tools/src/lib.rs

Add a function making a vCard containing given `VcardContact`s.

feat(contact-tools): Add make_vcard()

---

deltachat-jsonrpc/src/api.rs

Adds 
_setWebxdcIntegration_ 
_initWebxdcIntegration_

Add webxdc internal integration commands in jsonrpc

---

deltachat-ffi/deltachat.h

to be merged into https://github.com/deltachat/deltachat-core-rust/pull/5550

add new securejoin strings to deltachat.h

---

deltachat-contact-tools/src/lib.rs
deltachat-jsonrpc/src/api.rs
src/contact.rs

Add a function returning a vCard containing contacts with the given ids.

api: Add make_vcard() (#5203)

---

deltachat-rpc-server/src/main.rs

see also #5599 (this logs that error atleast, but does not fix it yet)

fix: log/print exit error of deltachat-rpc-server

---

src/chat.rs
src/receive_imf/tests.rs

fix: Set Param::Bot for messages on the sender side as well (#5615)

---

src/chat.rs
src/context.rs
src/sql/migrations.rs

feat: Remove limit on number of email recipients for chatmail clients (#5598)

---

src/chat.rs
src/message.rs
src/receive_imf.rs
src/receive_imf/tests.rs

feat: Prefer references to fully downloaded messages for chat assignment (#5645)

---

src/mimeparser.rs
src/receive_imf/tests.rs

fix: Use and prefer Date from signed message part (#5716)

---

src/mimeparser.rs
src/receive_imf/tests.rs

There are many reasons why we may fail to find valid signatures in a message, e.g. we don't yet know a public key attached in the same message, anyway, if From is forged, the message must be rejected.
Also always take the displayname from encrypted From, even if no valid signatures are found.

fix: Reject message with forged From even if no valid signatures are found

---

src/imap.rs

It appeared that some servers require namespace-style names for folders created via IMAP, like "INBOX.DeltaChat". This partially reverts 05c256dd5bbf348e6c03dfa5a72685ea012544d0.
Though not a fix of #5870 yet as in that issue there are existing messages having `imap.target=DeltaChat` for some unknown reason.

fix: Still try to create "INBOX.DeltaChat" if couldn't create "DeltaChat" (#5870)

---

deltachat-jsonrpc/src/api/types/contact.rs
src/contact.rs

This can be helpful for the chatmail case, the app can warn the user at least.

feat(jsonrpc): Add ContactObject::e2ee_avail

---

src/smtp/connect.rs

fix: Fix skip_smtp_greeting() (#5911)

---

src/securejoin.rs

https://github.com/deltachat/deltachat-core-rust/pull/5847#issuecomment-2308981292:
> IIRC the reason it was not set for secure join was because then the account would be marked as a bot, it would be nice to have a test that check that after a QR-invite is scanned contact.is_bot is still false for non-bot accounts while true for bot account, do we have such test already?

test: Alice is (non-)bot on Bob's side after QR contact setup

---

deltachat-rpc-client/tests/test_securejoin.py
src/chat.rs
src/sync.rs

fix: Don't sync QR code token before populating the group (#5935)

---

src/chat.rs
src/test_utils.rs

This makes possible to schedule one more sending of the message, the existing jobs are not cancelled. Otherwise it's complicated to implement bots that resend messages when a new member joins the group.
Close #5817

feat: Make resending OutPending messages possible (#5817)

---

src/chat.rs
src/context.rs
src/mimeparser.rs
src/tools.rs

fix: Shorten message text in locally sent messages too (#2281)

---

src/mimefactory.rs

If a displayname equals to the address, adding it looks excessive. Moreover, it's not useful for Delta Chat receiving the message because `sanitize_name_and_addr()` removes such a displayname anyway. Also now at least DC Android requires specifying profile name, so there should be a fallback for users having meaningful addresses to keep the old behaviour when Core generates `From` w/o the profile name, and this question has already appeared on the forum, so maybe documenting it in FAQ makes sense.

feat: Don't put displayname into From/To/Sender if it equals to address

---

src/config.rs
src/quota.rs

fix: Reset quota on configured address change (#5908)

---

src/chat.rs
src/mimeparser.rs

fix: Save full text to mime_headers for long outgoing messages (#6091)

---

src/chat.rs
src/chatlist.rs
src/configure.rs
src/context.rs
src/download.rs
src/ephemeral.rs
src/html.rs
src/imap.rs
src/imex/transfer.rs
src/location.rs
src/message.rs
src/mimefactory.rs
src/mimeparser.rs
src/quota.rs
src/reaction.rs
src/receive_imf.rs
src/receive_imf/tests.rs
src/sql.rs
src/stock_str.rs
src/summary.rs
src/test_utils.rs
src/tests/verified_chats.rs
src/tools.rs
src/webxdc/maps_integration.rs

Follow-up to https://github.com/deltachat/deltachat-core-rust/pull/6123

refactor: Use Message::new_text() more

---

deltachat-jsonrpc/src/api/types/qr.rs

Copy over some docs as requested in the associated issue.
close #5503

Copy over some docs as requested in the associated issue.

---

src/webxdc.rs

it may be handy for an xdc to have only one list of all adresses, or there may just be bugs.
in any case, do not notify SELF, e.g. in a multi-device setup; we're also not doing this for other messages.
this is also a preparation for having an option to notify ALL.

fix: never notify SELF

---

src/webxdc.rs

this PR changes `update.notify` to a dict of addr:text_to_notify and allow to notify all using the special addr `*`

allow to notify multiple users with different texts

---

deltachat-ffi/deltachat.h

this was partly missing at https://github.com/deltachat/deltachat-core-rust/pull/6223
this is not meant as being exhaustive :)

docs: update dc_msg_get_info_type() and dc_get_securejoin_qr()

---

src/webxdc.rs

Sorry for being late to the party, i just find this way of checking more brief and idiomatic, feel free to merge/close

refactor: create_status_update_record: Remove double check of info_msg_id

---

src/webxdc.rs

this partly reverts experimental #3516
that allowed any .xdc sent to "Saved Messages" to request internet. this helped on pushing map integration forward.
meanwhile, however, we have that map integration (#5461 and #5678), that implies `info.internet_access` being set.
experimental `manifest.request_internet_access` is no longer needed therefore.
future will tell, if we revive the option at some point or go for more intrations ('sending' is discussed often :) - but currently it is not needed.

api: remove experimental `request_internet_access` option from webxdc's `manifest.toml`

---

src/net/http.rs

Follow-up to #6337.
This is to avoid revalidating HTTP cache too frequently (and have many parallel revalidation tasks) if revalidation fails or the HTTP request takes some time. The stale period >= 1 hour, so 1 more minute won't be a problem.

feat: Revalidate HTTP cache entries once per minute maximum

---

deltachat-rpc-client/tests/test_securejoin.py
src/headerdef.rs
src/securejoin.rs

feat: Delete vg-request-with-auth from IMAP after processing (#6208)

---

deltachat-rpc-client/src/deltachat_rpc_client/const.py

fix(rpc-client): Add INCOMING_REACTION to const.EventType (#6349)

---

src/chat.rs
src/configure.rs
src/message.rs
src/peer_channels.rs

Let's apply them now before they let CI fail at the next release

chore: Beta Clippy suggestions

---

src/receive_imf.rs

I think it's easier to follow the logic because to follow the group membership logic, you can ignore the code for the group changes messages

refactor: Extract `group_changes_msgs()` function

---

deltachat-ffi/deltachat.h
src/blob.rs
src/chat/chat_tests.rs
src/imex/transfer.rs
src/message.rs
src/mimeparser.rs
src/receive_imf/receive_imf_tests.rs

feat: Keep file extension on deduplicated files

---

deltachat-jsonrpc/src/api.rs
deltachat-jsonrpc/src/api/types/message.rs

relates to https://github.com/deltachat/deltachat-desktop/issues/4596

feat: save messages API in JSON RPC

---

deltachat-jsonrpc/src/api/types/message.rs

This is a follow-up to
https://github.com/deltachat/deltachat-core-rust/pull/6550.
Partially addresses
https://github.com/deltachat/deltachat-desktop/issues/4694.

feat: jsonrpc: add `MessageObject.is_edited`

---

src/contact.rs
src/sql.rs

fix: get_config(Config::Selfavatar) returns the path, not the name

---

deltachat-repl/src/cmdline.rs
src/blob.rs
src/blob/blob_tests.rs
src/imex.rs
src/message.rs
src/test_utils.rs
src/tools.rs
src/tools/tools_tests.rs

Traits are bad for readability and compile times.

refactor: Don't use traits where it's not necessary

---

deltachat-ffi/deltachat.h
deltachat-ffi/src/lib.rs
src/chat/chat_tests.rs
src/headerdef.rs
src/message.rs
src/mimefactory.rs
src/mimeparser.rs
src/param.rs
src/receive_imf.rs

this PR adds an API allowing users to delete their messages on other member's devices
this PR is build on top of https://github.com/deltachat/deltachat-core-rust/pull/6573 which should be merged first
it is working already in https://github.com/deltachat/deltachat-ios/pull/2611

message deletion request API

---

src/chat.rs
src/sync.rs

See discussion at https://github.com/deltachat/deltachat-core-rust/pull/6573#discussion_r1968743482

fix: chat::save_msgs: Interrupt inbox loop to send a sync message

---

src/chat/chat_tests.rs
src/message.rs
src/receive_imf.rs

test: Deletion request fails in an unencrypted chat and the message remains

---

deltachat-ffi/deltachat.h
src/stock_str.rs

this PR just adapts to discussion and reasoning from https://github.com/deltachat/deltachat-android/pull/3709

chore: update 'takes longer' fallback wording

---

src/chat/chat_tests.rs

Follow-up to 175145969c256c8d9b29b140d071ca150abd8209.

test: Autocrypt-Gossip header isn't sent in broadcast messages

---

deltachat-jsonrpc/src/api.rs
deltachat-rpc-client/src/deltachat_rpc_client/account.py
deltachat-rpc-client/src/deltachat_rpc_client/pytestplugin.py
deltachat-rpc-client/tests/test_account_events.py
deltachat-rpc-client/tests/test_something.py
src/configure.rs

api: Rename add_transport() -> add_or_update_transport()

---

src/configure.rs
src/qr.rs

fix https://github.com/chatmail/core/issues/6801

fix: Parse login scheme in `add_transport_from_qr()`

---

src/login_param.rs

Before this PR, ConfiguredAddr (which will be used to store the primary transport) would have been changed when adding a new transport. Doesn't matter yet because it's not possible yet to have multiple transports. But I wanted to fix this bug already so that I'm not suprised by it later.

fix: Don't change ConfiguredAddr when adding a transport

---

src/sql/migrations.rs

Fix #6941 
Haven't tested yet. EDIT: The migration works for me, but i'm not sure that i have such a group. Please test on your databases.

fix: Key-contacts migration: ignore past members with missing keys (#6941)

---

src/mimefactory.rs
src/mimefactory/mimefactory_tests.rs

feat: mimefactory: Order message recipients by time of addition (#6872)

---

deltachat-jsonrpc/src/api/types/chat.rs
src/chat.rs
src/chatlist.rs
src/context.rs
src/receive_imf.rs
src/sql/migrations.rs
src/stock_str.rs
src/tests/verified_chats.rs

feat: Remove ProtectionBroken, make such  chats Unprotected (#7041)

---

src/sql.rs

Fix #6089 
See commit messages. Checked in `deltachat-repl`.
The `RESTART` mode is better for performance because fs blocks don't need to be reallocated after `wal_checkpoint(RESTART)`, but we anyway need to truncate the WAL sometimes, so let's not complicate the code for now.

fix: Run wal_checkpoint during housekeeping (#6089)

---

src/contact.rs
src/contact/contact_tests.rs
src/receive_imf.rs
src/sql/migrations/migrations_tests.rs

feat: Contact::lookup_id_by_addr_ex: Prefer returning accepted and key-contacts

---

src/chat.rs
src/receive_imf.rs
src/receive_imf/receive_imf_tests.rs
src/securejoin.rs

Moved some code from #7056 here.

Some improvements split out of "Add encrypted ad-hoc groups"

---

src/receive_imf.rs
src/receive_imf/receive_imf_tests.rs

fix: Add messages that can't be verified as DownloadState::Available

---

src/config.rs
src/context.rs
src/imex.rs
src/imex/transfer.rs
src/scheduler.rs
src/scheduler/connectivity.rs

fix: get_connectivity(): Get rid of locking SchedulerState::inner (#7124)

---

src/chat.rs
src/chat/chat_tests.rs

test: Message is OutFailed if all keys are missing (#6849)

---

python/tests/test_1_online.py
src/imap.rs
src/imap/scan_folders.rs

feat: Don't fetch messages from unknown folders (#7190)

---

deltachat-rpc-client/src/deltachat_rpc_client/chat.py
deltachat-rpc-client/tests/test_something.py

Needed for the https://github.com/deltachat-bot/group-editor-bot/ rewrite.

api(deltachat-rpc-client): add Chat.resend_messages()
