chatmail/core

- deltachat-ffi/deltachat.h
- src/constants.rs
- src/dc_tools.rs
- src/message.rs
- src/mimeparser.rs
- Use the same limit for info: full text can be read in HTML anyway.
- Remove DC_MAX_GET_{TEXT,INFO}_LEN constants from deltachat.h
- Fix a typo: s/DC_ELLIPSE/DC_ELLIPSIS/
- Do not truncate the text when loading from the database.
- Update the documentation: limit is in Rust chars, not bytes
> Reduce message length limit to 5000 chars

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/scheduler/connectivity.rs
- get rid of "Quota" title, many  users and testers do not really understand what this is about - instead, say "Storage on domain.com" - any other suggestions are welcome here, maybe there is sth. even better :)
- ~~the resource-titles are only shown if there are multiple quotas or a single quota that is _not_ "Storage"~~ it is just always skipped, see code-comment for reasoning.
- show the percentage as a bar - margins and paddings are already tweaked a bit, so this screenshot is not totally up-to-date
(the white percentage display also benefits from the additional padding (not on screenshot). using black here does not look good, also, wrt the other background colors) (one could tweak css here further, however, we have to keep things simple to allow good display also on old phones with …
> tweak quota display

- deltachat-ffi/src/lib.rs
Previously errors such as empty query ("missing query") silently
returned NULL.
> Log dc_get_chatlist() errors

- Cargo.lock
- Cargo.toml
- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/config.rs
- src/configure.rs
- src/context.rs
- src/imap.rs
- src/imap/client.rs
- src/imap/session.rs
- src/login_param.rs
- src/oauth2.rs
- src/provider.rs
- src/smtp.rs
- standards.md
Implements socks5 support. 
This adds following settings:
- Socks5Enabled,
- Socks5Host,
- Socks5Port,
- Socks5User,
- Socks5Password
Currently http requests and dns requests are not getting executed as they currently can't get tunneled through socks5 proxy. Therefore gmail with oauth2 wont work through tor.
> Add socks5 support

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/repl/main.rs
- src/login_param.rs
- src/oauth2.rs
Otherwise we may accidentally connect directly due to temporary error.
> Never ignore SQL errors when reading SOCKS5 settings

- scripts/coverage.sh
Debian deprecated `which` in `debianutils` in favor of `command`.
`which` outputs this to stderr now:
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
> scripts/coverage.sh: use POSIX `command` instead of `which`

- deltachat-ffi/Doxyfile.css
esp. lists as used for [dc_get_config()](https://c.delta.chat/classdc__context__t.html#aff3b894f6cfca46cab5248fdffdf083d) are hard to read otherwise 
nb: seems as if rebuild of c.delta.chat was not triggered recently, [dc_get_config()](https://c.delta.chat/classdc__context__t.html#aff3b894f6cfca46cab5248fdffdf083d) lacks the new [socks5-options](https://github.com/deltachat/deltachat-core-rust/blob/master/deltachat-ffi/deltachat.h#L274). we'll see on merging this pr if this is a general issue.
> better readable code fragments on c.delta.chat

- deltachat-ffi/src/lib.rs
- src/accounts.rs
Also make Accounts uncloneable. It is still possible to derive Clone,
but does not make sense to do so, as .clone() creates two separate
account managers which use the same files but different unsynchronized
in-memory data structures.
> accounts: remove Arc and RwLock from Accounts.accounts

- src/dc_receive_imf.rs
- src/lib.rs
- src/param.rs
- src/update_helper.rs
this is a preparation for the download-on-demand-feature of #2631 - i suggest to review/merge this pr first, to make #2631 easier to review/merge.
this pr makes sure, older messages do not overwrite chat- or contact-"items" [1] set by newer messages. 
this could _always_ been happening by messages received out-of-order - however, it happens _much more_ when we start with download-on-demand in #2631
to simplify checking, there is a new module `update_helper.rs` that does the timestamp checks. timestamps given to the helper are already "effective dates" [2].
separate items targeted:
things checked, no modification seems to be needed:
some items have some initial protection as they are sent in separate messages that are small enough to be downloaded directly - however, even then, it seems …
> update chat/contact data only when there was no newer update

- src/configure.rs
- src/imap.rs
- src/smtp.rs
There is a real risk of an active attack when connecting to non-.onion
servers over Tor, as bad Tor exit nodes are cheap to set up.
It's probably not needed for .onion domains, but we don't make an
exception for now.
> Always check certificate when connecting over SOCKS5 in Automatic mode

- CMakeLists.txt
The `CMAKE_INSTALL_FULL_<dir>` variables are only defined if `GNUInstallDirs` is included.
I must have made a mistake while testing this. Sorry!
cc @link2xt
> fix pkg-config file

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/chatlist.rs
- src/lib.rs
- src/lot.rs
- src/message.rs
- src/summary.rs
summary::Summary replaces Lot in the Rust API for methods returning
chatlist summaries.  Lot is a legacy type for C API compatibility, so
Summary can be converted into Lot.
> Introduce `summary` module

- src/imex.rs
- src/mimefactory.rs
since some time, core handles per-message-subjects
and Mimefactory also picks that up.
therefore, we can remove the old special handling.
came over that bit on checking things out wrt sync-messages #2669
> simpler subject of Autocrypt-Setup-Message

- src/dc_receive_imf.rs
- test-data/message/mailinglist_xt_local_microsoft.eml
- test-data/message/mailinglist_xt_local_spiegel.eml
these mailinglist probably come from the xt:Commerce system and are pretty widely used.
i have not seen an .xt.local mailinglist with name set in `List-Id:`, however, if that happens, it will still be taken.
only if the `List-Id:`-name is unset, we use the name from the `From:`-header.
> get correct names of .xt.local mailinglists

- src/chat.rs
- src/dc_receive_imf.rs
- src/ephemeral.rs
Integer overflows crash the application by default.
On a first sight this is only a potential crash that can't be
triggered, because timestamps are stored as i64 and ephemeral timer
duration is u32.
> Use saturating addition for ephemeral timers

- src/dc_receive_imf.rs
- src/mimeparser.rs
- test-data/message/testrun_ndn_2.eml
I sent a message, and the ndn (Non Delivery Notification) was not parsed correctly, so here comes
the fix and the test.
> Fix: Recognize ndns that put the headers into "message/global-headers" part

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/repl/main.rs
- src/config.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/download.rs
- src/ephemeral.rs
- src/imap.rs
- src/job.rs
- src/lib.rs
- src/message.rs
- src/mimeparser.rs
- src/param.rs
- src/sql/migrations.rs
- src/stock_str.rs
this pr allows large messages not being downloaded automatically. instead, only the header is downloaded and the body is skipped. goal is to save traffic.
- messages that are not downloaded completely have the status `DC_DOWNLOAD_AVAILABLE` returned by `dc_msg_get_download_status()`. in the easiest case, the message only has a text saying "This is a 10 MiB message", full download will replace the message by eg.  a video then.  
(in more advanced scenarios, the type of the message would be known already, maybe there is even some low-res image or so - that would be harder core-wise, the api would already make this possible)
- `dc_schedule_download()` will allow downloading the incomplete message; 
- with `dc_set_config("download_limit")` the limit can be adapted, changes affect future …
> download on demand

- deltachat-ffi/deltachat.h
- do not use term "Message-ID" for msg_id. instead use "Message id".
- clarify that on downloading also complete replacements may happen.
successor of #2631
> clarify docs

- src/dc_receive_imf.rs
- test-data/message/mailinglist_ttline.eml
- test-data/message/mailinglist_xing.eml
this pr improves finding out names of mailing lists:
- if there is no name set for the mailinglist, as a last resort, we already use the `List-Id:` as the name (we cannot just always use `From:` as that may refer to the sender, not to the chat, see xing example).  
however, this `List-Id:` may be prefixed by a "long hash", sth. as `1234567890abcdef1234567890abcdef.company.com`.  
this pr removes that "long hash" and adds a test for a real-life mailinglist.
- if there is no name set for the mailing list, for `From:` addresses starting with `newsletter@`, we use the `From:` name as the mailing list name -  sth. similar is already done for other prefixes.
> better names for more mailinglist-types

- deltachat-ffi/Doxyfile
- deltachat-ffi/deltachat.h
some of the most important constants in deltachat.h did not have real hyperlinks nor explicit documentation - whereas most less important things have :)
fixed by this pr, only documentation is changed.
> document DC_STATE and DC_CHAT_TYPE explicitly

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/config.rs
this pr allows UIs to store own config settings in the database. as multi-account, becomes more a thing, this gets much more important.
also, that way, ui settings go to the backup, this is also a thing that was requested several times - resp. ppl are wondering why on export/import not everything is restored.
the ui settings are stored in the same database as the other config, however, must be prefixed by ' ui.`.
the pr is a revival of #503, targeting most comments made there.
to the [idea of adding `Ui(String)`](https://github.com/deltachat/deltachat-core-rust/pull/503#issuecomment-531183450) to the `Config` enum - well, i tried that, however, all my attempts result in lots of rust issues (missing Copy-trait or complicated lifetimes).  
if someone has a concrete idea here, feel free to …
> implement `set/get_ui_config()` resurrection

- deltachat-ffi/deltachat.h
- src/dc_receive_imf.rs
- src/events.rs
before, `MsgsChanged(chat_id, new_msg_id)`  was emitted,
but that does not cover the deleted message.
in theory, we could emit both,
however, that would just be a waste of refresh in uis.
also before, events were used this way,
however, also the documentations are updated to
reflect reality better.
needed to fix a bug on ios, that does not delete the old message if only  `MsgsChanged(chat_id, new_msg_id)` is emitted; android does not really care and always does the same :)
> emit `MsgsChanged(chat_id, 0)` on full downloads

- deltachat-ffi/deltachat.h
- src/quota.rs
- src/scheduler/connectivity.rs
- src/stock_str.rs
- i picked up the "Updating..." wording we agreed on in the ui, "Receiving messages..." is not always correct from the user's point of view as there may be no visible message received at the end
- server errors and errors that are a result of library misuse are not translated.
- ~~for the "Inbox" and "Outbox" titles, i think we should use the same wording as already present in configuration screen~~ in general true, but the existing wording in the connectivity view seems to be better, so configuration should be adapted, if at all.
- wrt #2626 - i am just leaving things as is - "Storage on used-domain.com" is not that bad, and there were not much complains about that
> make connectivity and quota views translatable

- deltachat-ffi/deltachat.h
see title
DC_EVENT_CHAT_EPHEMERAL_TIMER_MODIFIED already sends the chat id, but this was not yet documented.
> add parameter description for DC_EVENT_CHAT_EPHEMERAL_TIMER_MODIFIED

- src/dc_receive_imf.rs
- src/ephemeral.rs
Also extend the tests to catch regressions.
Fixes #2704
> ephemeral: always apply timers from system messages

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/accounts.rs
- src/events.rs
Errors and warnings are emitted with a special 0 account ID.
> Emit events from account manager

- src/chat.rs
- src/message.rs
in the past, group-messages were marked as "read by recipient"
only when at least 50% of the group members have send a read receipt -
in practise, this does happen never or much too late esp. in larger groups.
setting the state OutMdnRcvd already on the first read-receipt
seems to be much more intuitive and useful as you at least know
one person has read the message.
this is also what other messengers as telegram are doing here.
moreover, this fixes a bug that did not add all read-receipts
to the "Info" screen - once "enough" read-receipts were received,
and the state was already set to OutMdnRcvd, subsequent read-receipts
were ignored.
probably because the "Info" screen did not show the read-receipts since forever -
and for the second tick, the additional read-receipts are not needed.
> set message-state OutMdnRcvd on first read-receipt

- src/chat.rs
- src/dc_receive_imf.rs
functionality is not changed.
this is needed for targeting "non-blocking group QR joins"
as `create_multiuser_record()` will also be needed from other places.
this will make rebasing/rewriting and finally reviewing #2508 easier - and removes some lines from receive_imf :)
> move create_multiuser_record() to ChatId

- deltachat-ffi/deltachat.h
- src/scheduler/connectivity.rs
- src/stock_str.rs
that was just forgotten in https://github.com/deltachat/deltachat-core-rust/pull/2694
once that is merged, a corresponding string should be added to transifex and passed to core by the UIs.
> make string `123 MiB of 456 MiB used` translatable

- src/securejoin.rs
as already pointed out at #2611, the issue was that a stale/running secure-join/setup-contact made any subsequent joins unusable.
this pr aborts any existing secure-join/setup-contact, as it is also described [in the docs ("Subsequent calls of dc_join_securejoin() will abort unfinished tasks")](https://c.delta.chat/classdc__context__t.html#ae49176cbc26d4d40d52de4f5301d1fa7)
nb: calls to stop_ongoing_process() does not help, however, in case of setup-contact the function is not blocking anyway (and the same is [planned for secure-join](https://github.com/deltachat/deltachat-core-rust/pull/2508))
fixes #2611
> fix "QR process failed" error and add a test

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
- scripts/set_core_version.py
```
git tag -a 1.61.0
git push origin 1.61.0
git tag -a py-1.61.0
git push origin py-1.61.0
```
i like to consider/discuss also to get ~~#2707 and~~ #2669 in. both can be considered as experimental and do not execute much code when not actively used. EDIT: #2707 is in, we can also merge #2669 after 1.61 if it we want to release soon :)
> prepare 1.61

- src/job.rs
- src/quota.rs
When opening the connectivity view while there is no network,
get_connectivity_html() calls schedule_quota_update(), which schedules a
UpdateRecentQuota job. But in update_recent_quota(), connecting fails
and a ConnectivityChanged event is emitted (connectivity changes from
Error to Connecting and back). Therefore the UI calls
get_connectivity_html() again, and the loop is complete.
This made the UI completely unresponsible. To reproduce, just turn wi-fi
off and open the connectivity view.
The fix is:
schedule_quota_update() now only schedules a new job if there is no old
job. To prevent the possible (though probably unlikely) problem that an
old quota update job has a backoff of, like, a day and therefore quota
is not updated, I reduced the backoff time for quota jobs to …
> Fix: Don't update quota in an endless loop

- src/dc_receive_imf.rs
- src/location.rs
See commit messages for description, there are multiple commits further refactoring `dc_receive_imf` module.
Outgoing messages still use the `hidden` column, e.g, in `send_handshake_message` and `send_sync_msg`.
> Stop using the `hidden` column for incoming messages

- proptest-regressions/dc_tools.txt
- src/dc_tools.rs
It was failing for approx_chars = 0.
Also reduce approx_chars range so approx_chars = 0 is tested more frequently.
> Fix dc_truncate proptest

- python/src/deltachat/chat.py
- python/src/deltachat/cutil.py
- python/src/deltachat/message.py
- python/tests/test_account.py
- src/chat.rs
- src/dc_receive_imf.rs
- src/job.rs
- src/mimefactory.rs
- src/mimeparser.rs
Update gossiped_timestamp when someone else sends autocrypt gossip in
the group, so we postpone sending gossip again ourselves.
- Warn about failures to parse Autocrypt-Gossip header
- Move gossip-related methods into ChatId impl
- Fix a "gossi_pp_ed" typo
Closes #1027
> Optimize Autocrypt gossip

- src/chat.rs
- src/dc_receive_imf.rs
- src/securejoin.rs
fixes #2790 
see commit messages for detailed information and reasoning.
> fix permanently hiding of one-to-one chats after secure-join

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
bug-fix-release of core62, mainly because of #2791
git tag -a 1.63.0
git push origin 1.63.0
git tag -a py-1.63.0
git push origin py-1.63.0
> prepare 1.63

- CHANGELOG.md
- src/dc_receive_imf.rs
`apply_group_changes` is executed regardless of whether the group is
created via `create_or_lookup_group` or found via
`lookup_chat_by_reply`. This change removes the need for
`lookup_chat_by_reply` to return `None` when group ID exists in the
database to let `create_or_lookup_group` run. As a side effect of this
Delta Chat replies to ad hoc groups are now correctly assigned to
chats when there are multiple groups with the same group ID, such as
ad hoc groups with the same member lists.
Fixes #2573
> Factor `apply_group_changes` out of `create_or_lookup_group`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
this is a bugfix release for 1.63 and is mainly needed for the fix #2797, which is quite user-visible.
for the refactoring of the other commits between 1.63 an 1.64 - i think, that needs some testing. however, an 1.24.3 that is first released for the testers only is planned anyway (because of several android changes and fixes), so it is probably fine.
afaik, no further blocking core-bugs were found during the first testing round of 1.24.
git tag -a 1.64.0
git push origin 1.64.0
git tag -a py-1.64.0
git push origin py-1.64.0
> prepare 1.64

- src/imap.rs
It happened twice to me now that this device message was shown even though my password is correct.
Generally we could also just remove the device message as we have the
connectivity view, OTOH if you are not using DC a lot, it may be useful
to be notified without opening DC.
And apart from this one bug it's working fine.
> Fix: Only show the "Cannot login" device message if it's actually authentication that failed

- src/securejoin.rs
A message is added into 1:1 chat anyway, and user does not know what `StockMessage::ContactNotVerified` means.
> Replace error! on verification failure with warn!

- .github/workflows/ci.yml
- python/mypy.ini
- python/src/deltachat/__init__.py
- python/src/deltachat/account.py
- python/src/deltachat/chat.py
- python/src/deltachat/const.py
- python/src/deltachat/cutil.py
- python/src/deltachat/direct_imap.py
- python/src/deltachat/events.py
- python/src/deltachat/provider.py
- python/src/deltachat/testplugin.py
- python/tox.ini
`deltachat.const` module now defines `__getattr__` and `__dir__` as
suggested by https://www.python.org/dev/peps/pep-0562/
mypy detects that `__getattr__` is defined and does not show errors
for `DC_*` constants which cannot be detected statically.
mypy is added to `tox.ini`, so type check can be run with `tox -e mypy`.
> python: add mypy support and some type hints

- src/scheduler/connectivity.rs
I originally wrote them when wanting to do https://github.com/deltachat/deltachat-core-rust/issues/2773, but then https://github.com/deltachat/deltachat-core-rust/issues/2773 decreased in priority when I noticed that we don't have the string "Not connected" in Core, only in the UIs
> Add section comments to get_connectivity_html()

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- python/src/deltachat/contact.py
- src/contact.rs
- src/dc_receive_imf.rs
It was there since the C core, labeled with "/* last_seen is for
future use */" but never actually used. The comment was lost during
the translation from C to Rust.
> contact: use `last_seen` column

- Cargo.lock
- Cargo.toml
- src/dc_receive_imf.rs
- src/quota.rs
`indexmap` is a large dependency (4K SLoC) containing `unsafe` code.
Contact IDs are now passed around as a Vec<u32> or &[u32].
QUOTA roots are now sorted by name instead of perserving original order.
> Remove `indexmap` dependency

- examples/repl/cmdline.rs
- src/qr_code_generator.rs
closes #2837, see commit messages for details
things are fine in most common cases now, even yggmail addresses with longer names. 
if things get to more than 4 lines (yggmail-plus :) the text runs over the watermark, however, well, then the watermark is a watermark :)
> tweak qr svg

- src/chat.rs
- src/dc_receive_imf.rs
reason for the "system messages appearing as normal messages" is `apply_group_changes()` as introduced recently in https://github.com/deltachat/deltachat-core-rust/pull/2795 not being called for outgoing messages - therefore the changes are not visible in a multi device setup.
> fix group changes in multi device setup

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/configure.rs
- src/oauth2.rs
- src/provider.rs
switching completely to /etc/resolv.conf (see #2780)
does not work at least on some Androids
(see https://github.com/deltachat/deltachat-android/issues/2151 )
therefore, we use the old approach as a fallback.
fixes https://github.com/deltachat/deltachat-android/issues/2151
@link2xt i am not deep in that stuff, maybe there is a more elegant solution or sth. to tweak upstream, however, this one works :) (tested on android)
for review: the fix is in the first commit, the second one only adds a warning - and introduces some noise as we have to pass context around.
> fix missing MX resolver eg. on android

- src/oauth2.rs
before, we did not test MX lookup as google.com is in our provider-db (for whatever reason).
moreover, a second check makes sure that _without_ MX lookup, we get another result.
> really test MX lookup in test_oauth_from_mx()

- src/provider.rs
successor of https://github.com/deltachat/deltachat-core-rust/pull/2852 to focus more on that: @link2xt is `map_err()` the correct way to convert to an Anyhow result? or better use `?` (seems more handy to me, indeed :)
(tbh, i also like to have one pr for myself as reference for anyhow :)
(i know, that it may also be better to log the error at another level, but that may need larger changes)
> use anyhow-result for get_resolver

- python/tests/test_account.py
- src/chat.rs
- src/dc_receive_imf.rs
- src/download.rs
- src/imap.rs
When there is an outgoing message in a chat, mark all older messages in this chat as seen.
Android already has a similar behavior, however, this led to the issue https://github.com/deltachat/deltachat-android/issues/2163 and should be changed back.
--
From the issue description at https://github.com/deltachat/deltachat-android/issues/2163, I implemented these fixes:
> Core should take care that if the last message in a chat is not fresh|noticed, no messages in the chat can be fresh. [...] Do this [...] in a function that's called at the end of fetch_new_messages(). Then dc_receive_imf() wouldn't get slower by this and we could re-use the same function for migration.
So, I didn't do this inside `dc_receive_imf()` in order not to make it take even longer. This obviously has the downside of …
> Fix unread count

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- python/src/deltachat/message.py
- src/e2ee.rs
- src/imex.rs
- src/message.rs
- src/securejoin/bobstate.rs
This will allow implementing a special command for download bot to request that it sends back the downloaded file unencrypted.
> Add `dc_msg_force_plaintext()` API for bots

- src/dc_receive_imf.rs
There is no mutable `message_timestamp` variable anymore, it's obvious now that `sort_timestamp` isn't used before, and no one will try to compute the `sort_timestamp` before we have the `chat_id` because this would give a compiler error.
> Remove wrong comment in add_parts

- src/mimeparser.rs
- test-data/message/ms_exchange_report_disposition_notification.eml
They contain X-MSExch-Correlation-Key header, but no
Original-Message-ID, so they cannot be used to find the original
message, but we want to recognize them as MDN nevertheless to assign
them to the trash chat.
Fixes #2878
> Recognize MS Exchange read receipts as read receipts

- src/blob.rs
- src/chat.rs
needed for #2826 
in short, web30 needs the msg_id not to change when finally sending a draft - this is because already in draft-mode, updates are assigned to the msg_id.
however, that seems to be a good idea in general, eg. there were always thoughts about adding blob-meta-data to a special table - that would run into the same issues as w30.
the single commit messages show some more details and the pr also adds some tests wrt drafts.
for review, it makes sense to hide whitespace.
> do not change the draft's message-id on updates and sending

- python/tests/test_account.py
- src/dc_receive_imf.rs
- Check that member modifying the group is in the group themselves.
It is not allowed to readd yourself to the group or remove someone without being in the group themselves.
- Unify code for group member addition and removal.
Removing a member now recreates the group member list from the To: field.
Removed member from the Chat-Group-Member-Removed was in the To: field in previous Delta Chat versions,
so it is excluded explicity. New versions of Delta Chat put removed member in Bcc: instead.
- Apply avatar changes after updating the group member list.
This allows to check that the contact modifying the avatar is actually a group member.
> Improve group updates

- src/chat.rs
This was fixed in d98d1857a4511a85dd04177744255a67613e1bb5 but not
tested.
Revert d98d1857a4511a85dd04177744255a67613e1bb5 to check that the test
is working.
> Test recovery from lost member removal message

- src/dc_tools.rs
- src/mimeparser.rs
- test-data/message/encrypted_with_received_headers.eml
Before, the hop_info was shown only for unencrypted messages.
Credits: The bug was noticed by @link2xt
Follow-up for #2751
> Fix: Also show the hop_info for encrypted messages

- .github/workflows/ci.yml
This runs all CI jobs with -Dwarnings, turning warnings into errors
for CI.
This is useful since we run rustfmt and clippy on CI on stable rust,
while the builds and tests run with a specific older rustc.  The
latter is also used for local development usually since it is encoded
in the rust-toolchain file.  This warnings in clippy jobs of stable
rust would often go unnoticed, however stable rust usually finds more
genuine issues than the older compiler we use.
> Run CI with -Dwarnings

- examples/repl/cmdline.rs
- python/tests/test_account.py
- src/chat.rs
- src/chatlist.rs
- src/contact.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/download.rs
- src/ephemeral.rs
- src/html.rs
- src/imap.rs
- src/imap/scan_folders.rs
- src/job.rs
- src/message.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/scheduler.rs
- src/sql.rs
- src/sql/migrations.rs
- src/test_utils.rs
- src/update_helper.rs
`imap` table maps Message-IDs to UIDs on the server. `dc_receive_imf`
no longer gets the UID of the message as an argument and does not
insert the folder and UID of the message into the `msgs`
table. `server_folder` and `server_uid` columns in `msgs` table are
deprecated.
MoveMsg and DeleteMsgOnImap jobs are removed. Now messages are moved
and deleted only in the `fetch_move_delete` procedure that consults
the `target` column of the `imap` table to determine where the message
should go.
Where the message should go is determined after prefetching by the
`imap::target_folder()` procedure.  Messages are only downloaded once
they reach their target folder to avoid race conditions in multidevice
setting, such as:
1. One device trying to FETCH the message while the other tries to
MOVE it.
2. …
> Add `imap` table to keep track of message UIDs

- src/contact.rs
- src/dc_receive_imf.rs
- src/e2ee.rs
- src/imex.rs
- src/key.rs
- src/keyring.rs
- src/securejoin.rs
- src/sql.rs
- src/test_utils.rs
Tests made sure to log their events, however when you have multiple failures the results were all over the place.  This introduces a LogSink to ensure the test failures look good and each has their own log reports.  If you only have a single context nothing changes since the TestContext keeps a reference to the LogSink and since the TestContext is dropped at the end of each test this works correctly.  If you have multiple TestContexts in a test and want to see the logs intermingled, both TestContexts need to use the same LogSink and you need to create it explicitly.
It is best to review this commit-by-commit, because one thing led to another:
- With the LogSink having to be injected early, the ways to create the TestContext exploded and creating a builder for it seemed much more sane.
- …
> Make test output appear in the correct failing test

- deltachat-ffi/src/lib.rs
- src/imap.rs
We had an unhelpful log in the Testing group:
- it repeatedly says "src/imap.rs:1010: dc_receive_imf error: add_parts error" but the actual error is not shown
- it says "deltachat-ffi/src/lib.rs:186: dc_get_config(): invalid key" but it doesn't say what key it's trying to get
> Improve log

- deltachat-ffi/deltachat.h
- python/tests/test_account.py
- src/config.rs
- src/context.rs
- src/imap/scan_folders.rs
- src/quota.rs
- src/scheduler.rs
- src/scheduler/connectivity.rs
Also resultified `get_watched_folders`.
Python test `test_moved_markseen` is modified to test using incoming
message instead of BCC-self message, because BCC-self message is
detected immediately in the Inbox.
Closes #2921
> Remove `inbox_watch` option

- src/chat.rs
- src/dc_receive_imf.rs
- src/headerdef.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/param.rs
- src/securejoin.rs
See https://github.com/deltachat/deltachat-core-rust/issues/748, https://github.com/deltachat/deltachat-core-rust/pull/1964 and https://github.com/deltachat/deltachat-core-rust/blob/3ba4c6718e31fe89e3f921e12dc547cc61907c0c/draft/mailing_list_managers.md
---
Also fix https://github.com/deltachat/deltachat-core-rust/issues/2735
Currently there remains a small "bug", #2735 is not completely fixed, do you think we should fix this? -> @r10s said no
1. You need a mailing list where you never received an email from before. Write to this mailing list address using a normal MUA -> a 1:1 chat will be created
2. later receive a message from this mailing list -> a mailing list will be created
3. write to the mailing list again using a normal MUA or DC
Expected: The outgoing messages from step 1 …
> Start making it possible to write to mailing lists

- README.md
I'm not sure about the emojis, but I think the extra links are going to be helpful for new devs.
when reviewing I recommend looking at it in the "rich diff" or at https://github.com/deltachat/deltachat-core-rust/tree/add_more_links_to_language_bindings#language-bindings-and-frontend-projects
> add more links to the language bindings in readme

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/chat.rs
- src/message.rs
- src/mimefactory.rs
allow `dc_msg_set_quote(msg, NULL)` and `msg.set_quote(None)`
to simplify draft handling keeping message-ids (as needed for webxdc updates).
closes #2948
> allow removing quotes on existing drafts

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/accounts.rs
- src/aheader.rs
- src/chat.rs
- src/chatlist.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/download.rs
- src/e2ee.rs
- src/imap.rs
- src/imap/idle.rs
- src/imap/scan_folders.rs
- src/job.rs
- src/key.rs
- src/message.rs
- src/mimefactory.rs
- src/pgp.rs
- src/qr.rs
- src/quota.rs
- src/sql.rs
- src/sql/migrations.rs
- src/stock_str.rs
- Replace .ok_or_else() and .map_err() with anyhow::Context where possible.
- Use .context() to check Option for None when it's an error
- Resultify Chatlist.get_chat_id()
- Add useful .context() to some errors
- IMAP error handling cleanup
> Error handling refactoring

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- python/src/deltachat/account.py
- python/tests/test_account.py
- python/tests/test_lowlevel.py
- src/accounts.rs
- src/context.rs
- src/dc_tools.rs
- src/imex.rs
- src/sql.rs
To create encrypted account with account manager, call
dc_accounts_add_closed_account(). On this account call
dc_context_set_passphrase() and then open it with dc_context_open().
When application is loaded next time and account manager is created,
it will open all accounts that have no passphrase set. For encrypted
accounts dc_context_is_open() will return 0. To open them, call
dc_context_set_passphrase(), then dc_context_open(). After opening,
call dc_context_start_io() on this account or just
dc_accounts_start_io() to start all accounts that are not started yet.
Support for legacy SQLite-based backup format is removed in this
commit.
> Add API to set the database password

- draft/webxdc-dev-reference.md
- src/webxdc.rs
see commit messages for details, esp. the second commit.
once this is merged, we can easily add more parameters as `sendUpdate({msg: summary: ...})`.
> tweak webxdc sendUpdate()

- src/chat.rs
- src/webxdc.rs
see code comment for reasoning.
@hpk42 i increased the limit to 100K as this fits nicely to the already existing limit for "worse quality" images.
if this pr is merged, we should also add a warning to the script at https://github.com/deltachat/webxdc-dev/blob/master/create-xdc.sh if the created .xdc gets too large.
> limit webxdc-sizes for a better ux

- src/blob.rs
In https://github.com/deltachat/deltachat-android/pull/2186, configure sometimes fails because of `create_new_file()`, so let's start by letting it return a sensible error.
The thing is that below we are checking `if attempt == max_attempt {<return error>}` which is supposed to run in the last iteration of the loop.
BTW @link2xt the error I'm getting is `Failed to create blob icon-saved-messages-1803424689.png in /data/user/0/com.b44t.messenger.beta/files/accounts/0e402b37dcd14a9586aea46294c908f2/dc.db-blobs: No such file or directory (os error 2)` - do you have a quick idea why this could be? Otherwise I'll continue debugging and possibly ask you for help again (or just let `create_new_file()` create the parent dir on error)
> Actually return a sensible error from create_new_file()

- deltachat-ffi/deltachat.h
- draft/webxdc-dev-reference.md
- src/param.rs
- src/webxdc.rs
this pr adds the possibility to send a summary and a info message together with an status update.
- the summary will be shown beside the app-icon and can be triggered by:  
`window.webxdc.sendUpdate({summary: "Highscore: 12", payload: ...})`
- the info will be shown as an info-message similar to "Member added" and can be triggered by:  
`window.webxdc.sendUpdate({info: "Alice scored 12 points in Game", payload: ...})`
- both can be used in the same update
not totally sure about the `info` and `summary` wording, maybe we should get a bit more specific - otoh, the context is defined already as an "webxdc update", so maybe this is just fine.
what's missing in this pr is the possibility to get from a tap on the info-message back to the instance; that needs a bit of work as it is a bit …
> allow chat-interactions from webxdc.sendUpdate()

- python/tests/test_account.py
- src/chat.rs
- src/dc_receive_imf.rs
- src/job.rs
- src/message.rs
- src/mimefactory.rs
- src/param.rs
- src/scheduler.rs
- src/smtp.rs
- src/smtp/send.rs
- src/sql.rs
- src/sql/migrations.rs
- src/test_utils.rs
It replaces SendMsgToSmtp job.
Prepared outgoing SMTP payloads are stored in the database now rather
than files in blobdir.
> Add `smtp` table

- src/blob.rs
With this PR, my encrypted-storage Android PR now works, at least I didn't directly stumble over any further bugs.
Without it, configuring fails with: `Failed to create blob
icon-saved-messages-1803424689.png in
/data/user/0/com.b44t.messenger.beta/files/accounts/0e402b37dcd14a9586aea46294c908f2/dc.db-blobs:
No such file or directory (os error 2)`.
Also see https://github.com/deltachat/deltachat-core-rust/pull/2972.
> Create parent directory if creating a new file fails

- src/configure.rs
While experimenting with encrypted storage, once configuring failed between 920 and 940. But as the "configured" config had already been written after progress 910, some part of the code thought we are configured, some didn't.
Is there a reason we don't wait with
ctx.sql.set_raw_config_bool("configured", true).await?;
until the very end of configure()?
> Save "configured" flag later

- .github/mergeable.yml
- deltachat-ffi/README.md
Mergeable is very configurable so we can customise it to our needs, for example changing on changes tho which files the changeling needs to be updated.
Currently I set it up so that it requires changelog changes for changes in `src/` and `deltachat-ffi/`.
mergeable docs: https://mergeable.readthedocs.io/en/latest/
Also the check is not required so its goal is to be a **reminder**, sometimes we don't need a changelog change, for example for a bugfix for a bug that was introduced in a recent unreleased/untagged previous commit.
> add mergable changelog check

- CHANGELOG.md
I did not document the changes Changes to rust api and python api, just what changed generally for the lib users.
So some internal non-user-facing changes as error handling refactoring are not included now,
if you think they should be included, feel free to add them, same for other points I might have missed.
> update changelog for 1.71

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/chat.rs
- src/message.rs
- src/webxdc.rs
set the parent for webxdc info-messages and add an ffi to get it.
there is already a similar functions for quotes, however, that checks if there is actually a quote and if the message is not forwarded - maybe we discard dc_msg_get_quoted_msg() at some point, however, for now i did not want to change working things in that area.
once merged, the webxdc implementations can use it to go "up to the app" when tapping an webxdc info message.
targets https://github.com/deltachat/deltachat-android/issues/2191
> handle parent for webxdc info-messages

- CHANGELOG.md
- src/webxdc.rs
targets the webxdc part of https://github.com/deltachat/deltachat-core-rust/issues/2985, however, if #2985 gets implemented, we can remove the removal of GuaranteeE2ee here.
> make update messages work if a key is missing

- .github/mergeable.yml
several pr do not need the changelog to be updated (as this one :), by adding #skip-changelog to the description, this test is skipped and ci is green again (before, the test was not required as well, however, ci was red which was a bit annoying)
used documentation:
https://mergeable.readthedocs.io/en/latest/configuration.html#validators
https://mergeable.readthedocs.io/en/latest/operators/or.html
nb: i can say i still hate this sort of yml configs ...
> allow to #skip-changelog test

- CHANGELOG.md
- draft/webxdc-dev-reference.md
- src/webxdc.rs
already before,
we did _not_ sent updates to contact requests or other read-only-chats.
however, we _did_ modify the local database,
so that getAllUpdates() returns an update that was not sent out to other peers.
this is fixed by checking can_send() soon.
that way, all peers have the same state
also for contact requests or other read-only-chats
and webxdc in contact requests can be opened as usual.
further ui improvements may be needed for contact requests
(maybe allow the webxdc to know about that state or
let sendUpdate() return false,
maybe show a warning in the ui somewhere),
however, this is not part of this pr.
EDIT: a simple idea for a subsequent pr may be to just show a toast from the ui (not the app) in case sendUpdate() fails, or, at some later point maybe even an alert that …
> webxdc: synchronous state for read-only-chats

- CHANGELOG.md
- src/webxdc.rs
as discussed in dev chat,
100 kb is too low if one wants to use any (game) framework.
also, many game that doesn't have poor graphics
or uses magic CSS-tricks to do fancy draws,
will have more than 100 kb probably just in tiles and sprites.
even for regions with low resources,
100 kb is low for a game -
esp. if we compare that with stickers that are send around as well,
are not deduplicated and also easily have several 100 kb in size -
for much less effect.
we should still encourage ppl to create tiny apps,
however, a too low limit also restricts possibilities wrt adaption.
> raise webxdc sending limit to 640 kb

- CHANGELOG.md
- src/imex.rs
- src/sql.rs
As of https://github.com/deltachat/deltachat-core-rust/pull/2980/, the migrations were not run after importing a backup. This lead to errors like "Failed to send message: no such table: smtp" if you imported a backup from a previous DC version.
#skip-update - hmmm, this doesn't seem to work, Mergable still fails. Edit: has to be #skip-changelog
> Fix: Run migrations after importing backup again

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
this fixes the missing migration after imports, esp. needed for testing :)
git tag -a 1.72.0
git push origin 1.72.0
git tag -a py-1.72.0
git push origin py-1.72.0
> prepare 1.72

- src/config.rs
Fix https://github.com/deltachat/deltachat-core-rust/issues/3012
#skip-changelog because it's not exposed to the FFI and rarely used
> Fix set_config_bool()

- CHANGELOG.md
- src/summary.rs
- src/webxdc.rs
this uses `get_webxdc_info().name` for chatlist etc.
the previuosly used static strings comes from a time
where we just did not had the correct name.
i was also thinking about adding `get_webxdc_info().summary`,
however, as this information is dynamic,
that may open several issues, eg. quoted text may change
so that the answer is out of context.
> use webxdc app name in chatlist/quotes/replies etc.

- CHANGELOG.md
- src/smtp.rs
thiserror still remains in submodules of smtp, but this one was easy to remove
> smtp: replace thiserror with anyhow

- CHANGELOG.md
- src/smtp.rs
This restores the logic removed in
afd8c0d879fa0fdd625a3317fa334f975e3f9754
> smtp: cancel message sending by removing the message

- CHANGELOG.md
- src/imap.rs
- src/scheduler.rs
This operation takes roughly 0.3 s on a moderate size database.
Calling it once before scanning all folders and scanning
the watched folder instead of each time after downloading
a message from a folder speeds up IMAP loop.
> imap: call delete_expired_imap_messages() less often

- CHANGELOG.md
- src/imap.rs
- src/message.rs
If FETCH result has no UID (possibly an unsolicited response), ignore it
instead of trying to pass None into SQL query.
Update highest seen MODSEQ regardless of whether any message state has
changed or not.
Log special MsgIds on attempt to pass them into SQL query.
Closes #3005
> Improve error reporting in sync_seen_flags and make it more robust

- CHANGELOG.md
- src/imap.rs
- src/scheduler.rs
Synchronizing seen flags doubles the time required to scan all
folders. Delta Chat only marks messages as Seen on Inbox or DeltaChat,
so there is no need to check for Seen flag on other folders.
Addresses #3035
> imap: do not synchronize Seen flags on unwatched folders

- CHANGELOG.md
- src/imap/scan_folders.rs
- src/scheduler.rs
This should help on iOS which kills the app before it gets to scan the Inbox.
Targets #3035
> imap: fetch Inbox before scanning other folders

- CHANGELOG.md
- src/imap.rs
- src/scheduler.rs
- do not attempt to mark reserved meessages as seen when
messages with empty Message-ID are marked as seen on IMAP
- do not reconnect on Seen flag synchronization failures This avoid
reconnection loops in case of permanent errors in `sync_seen_flags`
Fixes #3005
> imap: avoid reconnection loop when message without Message-ID is marked as seen

- CHANGELOG.md
- src/chat.rs
this avoids archived chats containing fresh messages:
before, it could happen that between the two SQL calls
a new fresh message arrives,
unarchives the chat that is immediately archived by the second SQL call -
resulting in an archive chat containing fresh messages.
as fresh messages counter are shown on app icon etc.
this is pretty weird for the user as they do not see what is "fresh".
the other way round,
there is no transaction in receive_imf(),
however, receive_imf() only unarchives chats,
so that is visible and no big issue for the user.
maybe the issue could also have been fixed by changing the order,
however, that may result in other rare cornercases i have currently not in mind :)
the issue is rare at all,
however, annoying if you get that as the badge counter may be stuck at "1" …
> do set_visibility() in a transaction

- CHANGELOG.md
- src/chat.rs
- src/config.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/job.rs
- src/lib.rs
- src/login_param.rs
- src/message.rs
- src/webxdc.rs
Enable clippy::cast_lossless lint and get rid of
some conversions pointed out by  clippy::as_conversions.
> Reduce number of unsafe `as` conversions

- CHANGELOG.md
- python/tests/test_account.py
- src/imap.rs
Also change how NO response is treated. NO response means there is an
error moving/copying the messages. When there are no matching
messages, the response is "OK No matching messages, so nothing copied"
according to some RFC 9051 examples.
> imap: move messages in batches

- python/src/deltachat/direct_imap.py
- python/src/deltachat/testplugin.py
- python/tests/test_account.py
pytest-timeout already handles all deadlocks and is configurable with
--timeout option. With this change it is possible to disable timeout
with --timeout 0 to run tests on extremely slow connections.
> python: remove arbitrary timeouts from tests

- CHANGELOG.md
- src/sql.rs
Fix https://github.com/deltachat/deltachat-android/issues/2184
The problem is that housekeeping deletes all hidden messages that don't have a server UID, which was introduced two years ago in 9febc762dababa73ecdb45c9e5c17bacd528b27e - I don't even know if we even had drafts at this point, or if it affected them.
Hidden messages are (I hope the list is complete):
- drafts
- location updates
- multi-device sync messages (see src/sync.rs)
- webxdc status updates
- some securejoin messages
We can't just delete webxdc status updates, either; while we could delete the other types of hidden messages, this seems kind of risky to me for little gain. So, this PR just completely stops deleting hidden messages in housekeeping - even though I'm not 100% sure on this.
> Fix disappearing drafts

- CHANGELOG.md
- src/mimeparser.rs
- test-data/message/ms_exchange_report_disposition_notification.eml
- test-data/message/ms_exchange_report_original_message.eml
Fix https://github.com/deltachat/deltachat-core-rust/issues/2891
MS Exchange MDNs don't contain a Original-Message-ID, so we need to use In-Reply-To instead.
> Let MS Exchange MDNs mark the In-Reply-To message as read

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
bugfixes (and a bit more) for a 1.28.2
git tag -a 1.76.0
git push origin 1.76.0
git tag -a py-1.76.0
git push origin py-1.76.0
> prepare 1.76

- CHANGELOG.md
- src/mimefactory.rs
This moves most common headers like From, To, Subject etc. that spam filters may be interested in before the large Autocrypt header.
Was supposed to help with #3078 but the issue is actually different so now it's a standalone enhancement.
> mimefactory: place important headers before Autocrypt

- src/securejoin.rs
- src/test_utils.rs
This reduces boilerplate code, improving the
signal-noise-ratio and reducing the mental barrier to start
writing a unit test.
Proposed by @flub at https://github.com/deltachat/deltachat-core-rust/pull/2901#issuecomment-998285039
Slightly off-topic:
I didn't add any advanced functions like `manager.get("alice");` because
they're not needed yet; however, once we have the AcManager we can
think about fancy things like:
```rust
acm.send_text(&alice, "Hi Bob, this is Alice!", &bob);
```
which automatically lets bob receive the message.
However, this may be less useful than it seems at first, since most of
the tests I looked at wouldn't benefit from it, so at I personally won't do
it until I have a test that would benefit from it.
> Add AcManager

- CHANGELOG.md
- src/chat.rs
- src/context.rs
- src/key.rs
- src/securejoin.rs
- src/securejoin/bob.rs
- src/securejoin/bobstate.rs
- src/securejoin/qrinvite.rs
- src/sql/migrations.rs
- src/sql/tables.sql
- src/stock_str.rs
- src/test_utils.rs
The state bob needs to maintain during a secure-join process when
exchanging messages used to be stored on the context.  This means if
the process was killed this state was lost and the securejoin process
would fail.  Moving this state into the database should help this.
This still only allows a single securejoin process at a time, this may
be relaxed in the future.  For now any previous securejoin process
that was running is killed if a new one is started (this was already
the case).
This can remove some of the complexity around BobState handling: since
the state is in the database we can already make state interactions
transactional and correct.  We no longer need the mutex around the
state handling.  This means the BobStateHandle construct that was
handling the interactions between …
> Securejoin: store bobstate in database instead of context

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- draft/webxdc-dev-reference.md
- src/events.rs
- src/webxdc.rs
(r10s, adb, hpk) remove getAllUpdates() and add a typical replica-API. 
The change is meant to rather backwards compatible: 
- getAllUpdates() could return an empty array unconditionally 
- if you don't specify a "serial" with setUpdateListener it is 0 (give all updates) 
The `serial` and `max_serial` properties on the update item area meant to allow the webxdc instance to know how many updates are pending or if it's receiving the (for now) last one.  The webxdc can internally (in local storage) keep track of which update serials it successfully processed and on restart set the update listeneer to only start with receiving updates after the last successful one).
> remove getAllUpdates() and add a typical replicatio API for the update call

- standards.md
it seems to be a bug on the Mozilla servers,
however, they take months to fix that, cmp.
https://bugzilla.mozilla.org/show_bug.cgi?id=1744432
so we just use archive.org for now.
closes https://github.com/deltachat/deltachat-core-rust/issues/2771
> Fix link to Mozilla

- CHANGELOG.md
- src/dc_receive_imf.rs
@hpk42 had a case where he wrote with someone using a classing MUA.
He opened a two-member-group with this person (which also allowed him to
set the subject).
At some point the other person replied from a different email address.
What he expected: This reply should be sorted into the two-member-group.
What happened: This reply was sorted into the 1:1 chat.
---
I had added the line `&& chat_contacts.contains(&from_id)` months ago when I wrote
this code because it seemed vaguely sensible but without any real
reason. So, let's remove it and see if it creates other problems -
my gut feeling is no.
> Assign replies from different address to two-member-groups

- deltachat-ffi/deltachat.h
fix docs: dc_markseen_msgs() is typically called when scrolling through message list, not chat list.
> fix docs wrt dc_markseen_msgs()

- CHANGELOG.md
- src/mimefactory.rs
Should fix #2885 by implementing the workaround I proposed in https://github.com/deltachat/deltachat-core-rust/issues/2885#issuecomment-991027388.
@link2xt you said this also happens with Mailgun - can we somehow find out whether Mailgun is being used?
> Set X-Microsoft-Original-Message-ID on outgoing emails for amazonaws

- Cargo.lock
- Cargo.toml
- benches/receive_emails.rs
Follow-up for #2819
I had noticed that, when receiving tons of emails at once, and you turn off the wi-fi, e-mails keep coming in for a while.
So, apparently it's not the network that's the limiting factor, but `dc_receive_imf()`.
Soooo, I started by creating a benchmark.
Run it with:
`cargo +1.56.0 criterion --bench receive_emails`
View the report by opening `target/criterion/report/index.html`.
Create a lovely flamegraph by installing `perf` (or `linux-perf`, and possibly some other packages that were already present on my system - please tell me in this case) and running:
`CARGO_PROFILE_BENCH_DEBUG=true cargo flamegraph --bench receive_emails -o receive_emails_flamegraph.svg -- --bench` and opening `receive_emails_flamegraph.svg` in the browser (that's better than in an image viewer) …
> Benchmark dc_receive_imf()

- CHANGELOG.md
- src/blob.rs
- src/dc_receive_imf.rs
The problem was that `splitn` was used to separate the name from the
extension, which split `"docu.ment.pdf"` into `["docu", "ment.pdf"]`
This was a problem when there was a very long filename _after_ the first
dot, because all of it was treated as the file ending and cropped after
32 characters.
Fix https://github.com/deltachat/deltachat-core-rust/issues/3090
> Fix long filenames containing dots

- src/contact.rs
- src/dc_receive_imf.rs
- src/sql.rs
This brings the Display of ContactId in line with those of ChatId etc,
which is a bit clearer is logs and such places.
It also updates an SQL query to rely on the ToSql impl of ContactId
rather than it's Display when building the query.
> Customise Display impl of ContactId

- CHANGELOG.md
- src/imap.rs
Currently if user moves the message into some other folder and then
moves the message back, the message is considered duplicate even
though previous copy was already deleted. This is a common problem
reported by users at least twice.
Keeping duplicates does no harm except for additional storage usage.
If the message is later deleted by the user, all the copies on the
server will be deleted. anyway.
Fixes #3130
> imap: do not delete duplicates

- CHANGELOG.md
- src/ephemeral.rs
- src/message.rs
Use a single SELECT statement for all messages and start ephemeral timers for all messages at once.
See discussion in https://github.com/deltachat/deltachat-android/pull/2233#issuecomment-1068505639
Closes #3140
> Optimize markseen_msgs

- src/imex.rs
due to an bug from Apple copying files from/to iPhones
(cmp. https://support.delta.chat/t/import-backup-to-ios/1628/7 )
it may easily happen that one gets corrupted/partly backups.
such imports usually fail with some error,
however, for debugging it is nice to have the concrete file size in the log.
replaces https://github.com/deltachat/deltachat-ios/pull/1501/commits/f15fb526e9412b97c3df74c88c0ce3bf35f7ca54
> log file size on backup import

- CHANGELOG.md
- src/imex.rs
- src/sql.rs
- src/sql/migrations.rs
- this pr fixes the bug https://github.com/deltachat/deltachat-android/issues/2242 introduced by #3131 - reason was just a missing clear() after import, so nothing conceptually wrong or so :)
- moreover the pr targets a potential race when between SELECT and writing config_cache another thread updates the database. the race is avoided by doing db-update and config_cache-update together; see commits for details.
as we already got reports by some  noticeable  speed increase (in testing group and by measurements/remarks in #3131), i think, we could give config_cache another try - even if caches are considered harmful in general. if it turns out, more issues pop up, we can get rid of config_cache easily.
fixes https://github.com/deltachat/deltachat-android/issues/2242 - 
alternative fix would …
> config_cache fixes

- Cargo.toml
- benches/get_chat_msgs.rs
Using `CARGO_PROFILE_BENCH_DEBUG=true cargo +1.56.0 flamegraph --bench get_chat_msgs -o flamegraph.svg --image-width 5000 -- --bench --profile-time 7` confirms that `delete_expired_messages` takes most of the time (which @link2xt noticed first).
> Add get_chat_msgs benchmark

- CHANGELOG.md
- src/dc_receive_imf.rs
Replaced mutable out parameters with explicit return of structure.
Also moved all decisions about emitted events out of add_parts(). Chat
ID is removed from created_db_entries as it is the same for all parts.
> Return results from add_parts() via structure

- CHANGELOG.md
- python/tox.ini
- src/sql/migrations.rs
This reduced get_chat_msgs() benchmark time from 400ms to 170ms.
> Add ephemeral_timestamp index for msgs table

- src/mimeparser.rs
- src/webxdc.rs
This seems not only wasteful but genuinly has the risk someone makes
their device useless by accidentally adding a huge file.
This also re-structures the checks a little: The if-conditions are
flattened out and cheap checks are done before more expensive ones.
> Do not read whole webxdc file into memory

- CHANGELOG.md
- src/dc_receive_imf.rs
- src/mimeparser.rs
This change is aimed at decoupling parsing and
add_parts() stages to eventually separate parsing
from database changes and pipeline message parsing and
decryption.
> Pass better message around instead of mutating mimeparser

- CHANGELOG.md
- src/chat.rs
this addresses and fixes https://github.com/deltachat/deltachat-core-rust/issues/3167 . This results in this speedup on the get_chat_msgs benchmark: 
```
Load all chats  time:   [260.44 ms 261.59 ms 262.74 ms]                           
change: [-11.101% -10.584% -10.070%] (p = 0.00 < 0.05)
Performance has improved.
```
Note that in another branch i tested [some tweaks to the SQL](https://github.com/deltachat/deltachat-core-rust/blob/fix_sql_order_by/src/chat.rs#L2310) but it did not result in an improvement.
> speedup get_chat_msgs

- CHANGELOG.md
- src/ephemeral.rs
These fields are cleared in other places,
but in the case of delete_device_after setting
only txt column was cleared previously.
> ephemeral: clear more fields in delete_expired_messages

- CHANGELOG.md
- src/job.rs
- src/smtp.rs
Previously first try used an old connection and. If using stale
connection, an immediate retry was performed using a new connection.
Now if connection is stale, it is closed immediately without trying to
use it.
This should reduce the delay in cases when old connection is unusable.
Fixes #3092
> smtp: do not try to use stale connections

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/chat.rs
- src/chatlist.rs
- src/constants.rs
- src/contact.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/ephemeral.rs
- src/html.rs
- src/imap.rs
- src/imex.rs
- src/location.rs
- src/message.rs
- src/qr.rs
- src/qr_code_generator.rs
- src/securejoin.rs
- src/stock_str.rs
- src/summary.rs
- src/sync.rs
- src/test_utils.rs
This tidies up the ContactId API a bit more:
- Move the constants to be associated with ContactId itself.
- Do not expose to the entire application that they are ordered and
treat them as opaque.  Introduces the ContactId.is_special() method
which also exists on most of our other IDs.
Main downside here is the need to switch to HashSet from a BTreeSet
in one location.
- Replace a few ContactId::new() calls directly with their constants.
> Consolidate ContactId constants

- CHANGELOG.md
- src/chat.rs
- src/dc_receive_imf.rs
this little change let archived chats stay archived on new messages if they are also muted.
this gives the user some more options to organize things, 
keeping unimportant chats in a separate section.
Telegram and WhatsApp (and maybe other messengers) have ~~the same~~ a similar behavior,
ui changes are not required.
(we have discussed that several times with different groups - and i needed something simple to do :)
> muted chats stay archived

- CHANGELOG.md
- src/sql/migrations.rs
Today, we solved an issue with holger's phone that he couldn't export
his account anymore because during the `VACUUM` the Android system
killed the app because of OOM. The solution was to drop the table
`backup_blobs`, so let's automatically do this in migration.
This table was used back in the olden days when we backuped by exporting
the dbfile and then putting all blobs into it. During import, the
`backup_blobs` table should have been dropped, seems like this didn't
work here.
> Drop unused table `backup_blobs` in migration

- Cargo.lock
- Cargo.toml
By default file and sendmail transports are enabled,
but deltachat does not use them.
> Disable unused async-smtp transports

- CHANGELOG.md
- src/chat.rs
- src/chatlist.rs
- src/peerstate.rs
- src/webxdc.rs
send setup-changed messages only in the chats we share with the peer, do not create contact request
closes #2557 
with this all shared chats with the peer will be sorted at the top with the "setup changed for X" so maybe some other dev can improve this PR so this system messages don't cause the chats to be sorted at the top, still this is better than getting annoying empty contact requests with "setup changed for X" which is confusing for users "this mean this person wants to talk with me?"
also the markers in the chats are much more useful than in the 1:1 chat with the contact since you can easily see what messages in chats are valid and what messages are compromised because they come after the "setup changed" marker in the chat
> Send setup-changed messages only in the chats we share with the peer

- CHANGELOG.md
- src/configure/server_params.rs
Fix half of #3158.
Try "imap.ex.org"/"smtp.ex.org" and "mail.ex.org" first because if a server exists
under this address, it's likely the correct one.
Try "ex.org" last because if it's wrong and the server is configured to
not answer at all, configuration may be stuck for several minutes.
This will make configure work fine with systemli even if you removed systemli from `provider/data.rs`.
> Configure: Try "imap.*"/"smtp.*"/"mail.*" first

- CHANGELOG.md
- src/chat.rs
- src/chatlist.rs
- src/context.rs
- src/ephemeral.rs
- src/scheduler.rs
- src/sql.rs
1. in start_io start ephemeral async task, in stop_io cancel ephemeral async task
2. start ephemeral async task which loops like this:
- wait until next time a message deletion is needed or an interrupt occurs (see 3.)
- perform delete_expired_messages including sending MSGS_CHANGED events
3. on new messages (incoming or outgoing) with ephemeral timer:
- interrupt ephemeral async task
The question we (@hpk42 and I) had was if the shutdown works the way we implemented it.
- Starting and stopping imap and smtp tasks is done using lots of channels (shutdown_receiver, stop_sender, ...) - is this necessary also for our task?
- In `stop_io()` we are just calling `cancel()` on the task. Is it necessary to close the interrupt channel and react on the closed channel in the loop? Or is calling …
> Do ephemeral deletion in async task background loop

- .github/dependabot.yml
it's probably better anyway to do dep updates synced with the release schedule. E.G. for the upcoming 1.30 we want to update now and then stick with the dependencies unless there is a good reason to upgrade a particular one.
> only do monthly dependabot updates

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
at least desktop waits for a new core for new webxdc api, but it makes sense anyway - we can easily do a core78 to get latest changes in for a 1.30 :)
git tag -a 1.77.0
git push origin 1.77.0
git tag -a py-1.77.0
git push origin py-1.77.0
> prepare 1.77

- CHANGELOG.md
- src/configure.rs
- src/configure/read_url.rs
Fix #3158
closes #2963 
Turns out that the main problem in #3158 was only that we don't follow html redirects. The redirect is given in the header which is always ASCII, so there is no need to try and decode the body at all.
(For redirects (and obviously also 4xx errors), the body encoding is specified as `iso-8859-1`, which led to the error message in https://github.com/deltachat/deltachat-core-rust/issues/3158.)
> Follow http redirects for autoconfigure

- CHANGELOG.md
- src/scheduler/connectivity.rs
in practise, Android and Desktop already disallow scaling
by some other methods,
however, for iOS this is needed as we otherwise
have to do far more complicated things as drafted at
https://github.com/deltachat/deltachat-ios/pull/1531/files
> make Connectivity-View-HTML not scalable

- .github/workflows/dependabot.yml
There is very little to be gained by having to approve those PRs, and
it is a lot of UI interaction to get them approved.
They still will need to be merged manually regardless, so they might
as well be approved by a bot.
> Auto-approve dependabot PRs

- draft/webxdc-dev-reference.md
at least on iOS we would need to inject a script to force a behavior,
that is hard to merge with options set by the Webxdc, cmp. https://github.com/deltachat/deltachat-ios/pull/1472 - and also not really needed as it removes the option of the Webxdc to _allow_ scaling.
therefore, the easiest approach seems to be to leave that completely up to the Webxdc -
and, in practise, many Webxdc already set viewports, including scaling.
> Webxdc scaling/viewport is implementation specific

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/events.rs
- src/webxdc.rs
this bypasses the replication safety [introduced by letting the caller track the last serial](https://github.com/deltachat/deltachat-core-rust/pull/3081),
however, in case of bots that do not track much state and do not playback updates anyway,
it is still useful.
i am not too happy with adding that again, as i fear it gets misused and we get races again. otoh, @adbenitez reported that it helps in some cases (@adbenitez maybe you can comment in more detail about that), so this is also an strong argument :)
> add status_update_serial to webxdc_status_update event

- src/accounts.rs
This is just a minor fix I made while working on dreamer. Uses a variable instead of a hard-coded file-name.
> improve error message

- src/chat.rs
- src/config.rs
- src/configure.rs
- src/contact.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/e2ee.rs
- src/imap.rs
- src/imex.rs
- src/key.rs
- src/location.rs
- src/login_param.rs
- src/mimefactory.rs
- src/scheduler/connectivity.rs
- src/securejoin.rs
- src/smtp.rs
- src/sql/migrations.rs
- src/test_utils.rs
- first commit gets rid of using "configured_" strings and rather provides two clean load_candidate_params and load_configured_params APIs 
- second commit gets rid of the many verbose places to access the configured addr. 
This small streamlining is meant to not change any semantics but just shorten source code and make it better readable. 
It came up during discussing with @hocuri on https://github.com/deltachat/deltachat-core-rust/pull/2896
> Streamline access/working with configured params and configured addr

- Cargo.lock
- Cargo.toml
stop-token 0.2.0 is required by async-imap. This Cargo.toml entry
additionally pulled in unused stop-token 0.7.0.
> Remove unused stop-token dependency

- src/context.rs
to not have the error event in this case which would be displayed by dc-desktop as toast to users
> don't start io on unconfigured context

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- src/scheduler/connectivity.rs
- src/stock_str.rs
'One moment' is a bit misleading in case the device is offline
as it will take more than a moment until that will be updated :)
closes #2773
> show 'Not connected' if storage information are not yet available

- CHANGELOG.md
- src/dc_receive_imf.rs
- src/imap.rs
- src/job.rs
- src/message.rs
- src/scheduler.rs
- src/sql.rs
- src/sql/migrations.rs
MarkseenMsgOnImap job, that was responsible for marking messages as
seen on IMAP and sending MDNs, has been removed.
Messages waiting to be marked as seen are now stored in a
single-column imap_markseen table consisting of foreign keys pointing
to corresponding imap table records.
Messages are marked as seen in batches in the inbox loop. UIDs are
grouped by folders to reduce the number of requests, including folder
selection requests. UID grouping logic has been factored out of
move_delete_messages into UidGrouper iterator to avoid code duplication.
Messages are marked as seen right before fetching from the inbox
folder. This ensures that even if new messages arrive into inbox while
the connection has another folder selected to mark messages there, all
messages are fetched before going …
> Mark messages as seen in IMAP loop

- CHANGELOG.md
- benches/receive_emails.rs
- examples/repl/cmdline.rs
- src/chat.rs
- src/chatlist.rs
- src/contact.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/download.rs
- src/ephemeral.rs
- src/html.rs
- src/imap.rs
- src/message.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/test_utils.rs
- src/update_helper.rs
- src/webxdc.rs
Proper draft detection was implemented in
bf7f64d50ba30f63b1338c66aed780dab9461dfc
Removing this heuristic also removes the need to pass IMAP folder name
around.
> dc_receive_imf: remove Received: based draft detection heuristic

- CHANGELOG.md
- src/dc_tools.rs
the ids created by `dc_create_id()` are used, among other things, for the random room name for video-chat-urls.
for this purpose, the IDs need to be URL-safe. this is even promised in the documentation, however, the used base64 encoding scheme "STANDARD"  uses the `/` character which results in _some_ IDs being not URL-safe.
this pr fixes that by switching to explicit  URL-safe base64 encoding scheme. moreover, a test is added that checks 1000 random IDs to not contain slashes.
thanks to the delta-testing-group to figure out this issue!
> url-safe id generation

- CHANGELOG.md
- src/accounts.rs
When removing an account, try 60 times with 1 second sleep in between
in case removal of database files fails. This happens on Windows
platform sometimes due to a known bug in r2d2 which may result in 30
seconds delay until all connections are closed [1].
[1] https://github.com/sfackler/r2d2/issues/99
> accounts: retry remove_account multiple times on failure

- CHANGELOG.md
- python/src/deltachat/direct_imap.py
- python/tests/test_account.py
- src/config.rs
- src/context.rs
- src/imap.rs
- src/imap/idle.rs
- src/imap/scan_folders.rs
- src/job.rs
- src/scheduler.rs
For example, if there is both a Spam and Junk folder,
both of them should be ignored, even though only one
of them can be a ConfiguredSpamFolder.
Fixes #3245
> Ignore messages from all spam folders if there are many

- .gitignore
- examples/repl/cmdline.rs
- src/chat.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/ephemeral.rs
- src/message.rs
- src/webxdc.rs
All MsgsChanged and IncomingMsg events are now generated by three `context.emit_*` functions.  While reducing LOCs and improving readability this also is meant to help future experiments with caching of chat list loading (`ChatList::try_load`) where we would make the three emit functions invalidate the in-RAM cache of the chatlist.  This PR is not that, though, and meant to be an easy "approve" :)  
> streamline emitting MsgsChanged and IncomingMsg event emission

- CHANGELOG.md
- src/chat.rs
- src/config.rs
- src/configure.rs
- src/contact.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/e2ee.rs
- src/ephemeral.rs
- src/imap.rs
- src/imex.rs
- src/job.rs
- src/key.rs
- src/location.rs
- src/login_param.rs
- src/message.rs
- src/mimefactory.rs
- src/scheduler/connectivity.rs
- src/securejoin.rs
- src/sql.rs
- src/sql/migrations.rs
- src/test_utils.rs
That's a prerequesite for automatic email address porting (AEAP) because after porting, the user will have two email addresses
> Allow using secondary email addresses

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/repl/main.rs
- src/chat.rs
this pr is currently mainly to check out the effort of resending messages using the same Message-ID as suggested and discussed skeptically at https://github.com/deltachat/deltachat-core-rust/issues/3236 
so ...
- the approach is quite simple - without the boilerplate, this is only few lines of new code, exiting code is not really touched, so no new states etc.
- i tested that with resending an webxdc to a new group member - works like a charme
notes:
- if "delete on server" is enabled, resend messages, that are not downloaded as already known by a client, are probably not deleted. this is not targeted by this pr, also, not sure if this is a big issue at the end.
and, there are the general concerns about resending messages this way.
so, wondering how we can proceed here:
1. use the pr and …
> resend messages using the same Message-ID

- CHANGELOG.md
- src/dc_receive_imf.rs
- src/location.rs
Assign location.kml message parts to the trash chat,
but return non-trash chat_id so locations are assigned
to the correct chat.
Due to a bug introduced in
7968f5519186a820ebe2f39211917fd51498058f
previously location.kml messages resulted in
empty message bubbles on the receiver.
Fixes #3249
> Trash location.kml messages

- Cargo.lock
maybe best merged before #3261 after which we should only update deps if there is a strong reason
> update depss before we have a few stable core releases

- python/mypy.ini
- python/pyproject.toml
- python/setup.py
- python/src/deltachat/direct_imap.py
- python/tests/test_account.py
the python bindings have a direct_imap module responsible for direct IMAP calls. It's mostly used in the python tests. I replaced the old imapclient library with a different library which is much more up-to-date.
#skip-changelog 
With testrun.org as a mail server the tests pass so far.
What's still ugly: sometimes direct_imap uses strings, sometimes bytes, and this could be brought in a better order.
> replaced imapclient python library with imap-tools

- src/key.rs
see #3267 though -- still makes sense to remove this here and resolve the issue separatel.y 
> strike last hard-coded configured_addr access

- Cargo.lock
- python/tests/test_account.py
Actual bugfix is in the async-smtp crate.
Depends on https://github.com/async-email/async-smtp/pull/49
Fixes #2635
> Correctly escape messages consisting of a dot in SMTP protocol

- python/tests/test_account.py
Fix #3269. I couldn't reproduce the flakiness, but I think that this should fix it.
I don't understand why I added these lines back when I wrote this test; there is no need to call `maybe_network()` since DC core will see that there is a new email all by itself, and doing `idle_wait_for_new_message()` just delays the call to `wait_for_connectivity_change()` so that we possibly miss it.
Technically, this is still a race condition since we have to assume that the python test realizes that the connectivity is WORKING before the core is done receiving the message. But Python only has to execute a single-digit number of lines while the core has to receive a whole email involving lots of I/O (and takes long enough that a human will see it), so that should be fine.
> Hopefully make test_connectivity() unflaky

- CHANGELOG.md
- src/context.rs
- src/scheduler.rs
Hold scheduler lock during the whole procedure of
scheduler stopping. This ensures that two
processes can't get two read locks in parallel
and send the stop signal twice.
Also remove shutdown channels: it is enough to wait
for the loop handle without receiving a shutdown signal
from the end of the loop.
> Remove panics from the scheduler and simplify stop_io() 

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
i think, this should go in before dong 1.30 at https://github.com/deltachat/deltachat-android/pull/2286 resp. https://github.com/deltachat/deltachat-ios/pull/1562
git tag -a 1.79.0
git push origin 1.79.0
git tag -a py-1.79.0
git push origin py-1.79.0
> prepare 1.79

- python/examples/test_examples.py
- python/src/deltachat/__init__.py
- python/src/deltachat/account.py
- python/src/deltachat/direct_imap.py
- python/src/deltachat/events.py
- python/src/deltachat/testplugin.py
- python/tests/bench_test_setup.py
- python/tests/stress_test_db.py
- python/tests/test_account.py
- python/tests/test_increation.py
- python/tests/test_lowlevel.py
- python/tox.ini
make account setup more deterministic, safer and simpler for use from tests:
- introduces a tested ACSetup class to manage the transition between configuring/started/ready-to-receive states of multiple accounts 
- removes global deltachat plugin to perform test initialization 
- adds more doc strings and reduces number of API methods and intricate dependencies between test initialization code and tests 
- introduces "--extra-info" pytest option which enables showing of imap state on test failures and stdout during teardown. By default output is less verbose now, so one is closer to the logs and the actual python test failure. tox runs use --extra-info so CI runs should show this extra info as before. 
- prepares a subsequent optimization step that would cache "configured live accounts" -- …
> streamline python test machinery

- python/src/deltachat/direct_imap.py
- python/tests/test_account.py
, so we never miss sending "idle done" when the test scope is left. There was at least one test that did not properly finish idle, leading to possibly mangled state and problems with shutdown. 
> make direct_imap idle usage safe from tests

- src/scheduler.rs
i was wondering mainly about the whole line
"Failed to start IO: scheduler is already stopped".
i think it has to be "already started" and not "already stopped".
> fix "scheduler already started" log entry

- CHANGELOG.md
- src/qr_code_generator.rs
`tagger.put_raw()` has changes semantics and escapes strings on its own now
an explicit escaping leads to double escaping and to wrong display.
this should also improve lenght calculation,
as a quote and other specials counts as 1 character and not as 4-6.
closes https://github.com/deltachat/deltachat-core-rust/issues/3293
> fix qr-code display

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
this is a small update for 1.79, that is already in testing. this pr mainly updates provider database. 
we can also get some more minor things and fixes in, but as we are short before a 1.30 release, it is probably wise to not merge larger refactorings with the potential to break things :)
~~i'd like to get https://github.com/deltachat/deltachat-core-rust/pull/3295 in as this is a highly visible bug :)~~ EDIT: done.
git tag -a 1.80.0
git push origin 1.80.0
git tag -a py-1.80.0
git push origin py-1.80.0
> prepare 1.80

- python/src/deltachat/direct_imap.py
- python/src/deltachat/testplugin.py
- python/tests/bench_test_setup.py
- python/tests/test_1_online.py
- python/tests/test_4_lowlevel.py
previously it was creating (>100) online test accounts 8)
also slight refinements on idle waiting, and on the benchmark for setting up tests
> actually enable online account caching. 

- Cargo.toml
@adbenitez just had a bug where the inbox loop seems to be gone. One possible reason for this is a panic in the inbox loop. So, instead of just stopping fetching messages altogether, we should rather abort so that the user or the system (as done on Android) can restart it.
I also noticed that it's undefined behavior to unwind over the FFI boundary.
With this change:
1. When a background task aborts, we get a nice stacktrace on the Android log. Before, there was no indication of the crash at all in the log:
<Details>
<Summary>Android stacktrace example</Summary>
```
04-28 13:27:50.295  9234  9275 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9275 (async-std/runti), pid 9234 (.messenger.beta)
04-28 13:27:50.399  9330  9330 I crash_dump64: obtaining output fd from …
```
> Abort instead of unwinding on panic

- src/pgp.rs
.expect() may panic, which is probably not what we want here.
it seems better to bubble up the error (as we are doing in the other cases).
or is it on purpose for some reason? then we should maybe add a comment as create_keypair() bubbles up errors in the other cases.
we do not had issues with that in practise, however,
i was just checking some .expect usages after we had a similar issue at #3264
> bubble up signing error instead of panicing

- CHANGELOG.md
- src/job.rs
- src/message.rs
- src/scheduler.rs
- src/smtp.rs
- src/sql/migrations.rs
Unlike jobs which are executed before sending normal messages, MDNs
from `smtp_mdns` table are sent after sending messages from `smtp`
table. This way normal messages have higher priority than MDNs.
> Replace SendMdn job with smtp_mdns table

- CHANGELOG.md
- src/configure.rs
- src/context.rs
- src/imex.rs
- src/scheduler.rs
- src/scheduler/connectivity.rs
Scheduler has no Stopped state anymore. If Scheduler exists, it is
always started. Scheduler is stopped via Scheduler.stop(), which
consumes Scheduler and cannot fail.
> scheduler: make Scheduler stateless

- python/mypy.ini
- python/src/deltachat/testplugin.py
- python/tests/test_4_lowlevel.py
cache configured live account within a live test process, leading to a roughly 15% speed improvement on the overall test run as it removes an often multi-second overhead for the setup of live accounts from most tests.   You can measure with "pytest --durations=10 tests/bench_test_setup.py". 
This cache is only an in-process RAM dictionary for caching successfully configured live accounts from/to the filesystem.  
> Introduce caching of configured live accounts in each test process

- CHANGELOG.md
- benches/get_chat_msgs.rs
- deltachat-ffi/deltachat.h
- deltachat-ffi/src/dc_array.rs
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/chat.rs
- src/constants.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/ephemeral.rs
- src/message.rs
- src/securejoin.rs
- src/stock_str.rs
- src/sync.rs
- src/test_utils.rs
It is not used by iOS/Android/Desktop.
> Deprecate marker1before argument of dc_get_chat_msgs()

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- src/webxdc.rs
this allows webxdc to set a source-code-url which can then be read by the implementations, offered as a menu entry with the title "Source Code" or so.
closes #3313
> add source_code_url to manifest

- CHANGELOG.md
- python/tests/test_1_online.py
- src/chat.rs
- src/contact.rs
- src/stock_str.rs
Group contacts by peerstate and make it easier
to find contacts that prevent encryption by sorting them
to the top of the list.
> Improve Chat.get_encryption_info() format

- CHANGELOG.md
- src/e2ee.rs
- test-data/message/google-workspace-mixed-up.eml
Google Workspace has an option "Append footer" which appends standard
footer defined by administrator to all outgoing messages. However,
there is no plain text part in encrypted messages sent by Delta Chat,
so Google Workspace turn the message into multipart/mixed MIME, where
the first part is an empty plaintext part with a footer and the second
part is the original encrypted message.
This commit makes Delta Chat attempt to repair such messages,
similarly to how it already repairs "Mixed Up" MIME structure in
`get_mixed_up_mime`.
> Decrypt encrypted mails turned into attachments

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- draft/webxdc-dev-reference.md
- src/param.rs
- src/webxdc.rs
some webxdc are more document-based than application based, eg. in contrast to a game, for an webxdc editor, the "document name" is an important property.
current implementation use the "summary" property to show the document name, which, however, is not super-nice as the less important thing is shown in bold: 
this pr adds a "document" property that, if set, contains the name  of the document. the property is sent around similar to the summary, so that it can be shown even without opening the webxdc.
UI implementation should show the document name in front (or, on few space, instead of) of the webxdc name, eg. the title could be  `DocumentName - WebxdcName - ChatName`.
> allow webxdc document names

- src/securejoin.rs
securejoin no longer allocates ongoing processes
> securejoin: remove unused error types related to ongoing processes

- CHANGELOG.md
- src/chat.rs
- src/contact.rs
this leaves group-colors based on group names as is,
so, "MY GROUP" creates a different color than "my group",
as these names are better synced and also not an ID in this sense,
this is probably fine here.
(also when looking at the examples from
https://xmpp.org/extensions/xep-0392.html#testvectors-fullrange-no-cvd ,
case-sensistifity for group names seems to be fine)
> create same contact-colors when addresses differ in upper-/lowercase

- CHANGELOG.md
- src/context.rs
- src/securejoin.rs
Hold the same write lock while checking if ongoing
process is already allocated and while allocating it.
Otherwise it is possible for two parallel processes
running alloc_ongoing() to decide that no ongoing
process is allocated and allocate two ongoing processes.
> Fix race condition in alloc_ongoing()

- deltachat-ffi/deltachat.h
in fact, `get_chat_msgs()` with `marker1before` is not used on iOS,
however, iOS  [needs the special msg-id](https://github.com/deltachat/deltachat-ios/search?q=DC_MSG_ID_MARKER1).
in #3274 we did not check this possibility.
it may be changed, of course, however, that would reqiore some refactorings
in an anyway complicated area and is probably not worth the effort.
> re-add removed DC_MSG_ID_MARKER1 as in use on iOS

- .github/workflows/node-package.yml
I tested this already in https://github.com/missytake/deltachat-core-rust/pull/1, this is why this PR is on a fork, because I was afraid to create tags in the origin repository.
It works now [both when it's executed on a tag](https://github.com/missytake/deltachat-core-rust/actions/runs/2351997572) and [when it's executed on a commit to a PR](https://github.com/missytake/deltachat-core-rust/runs/6507054640).
So when it's executed on a tag (like `test-tag2`), this file is uploaded:
- https://download.delta.chat/node/deltachat-node-test-tag2.tar.gz
And when it's executed by a PR (https://github.com/missytake/deltachat-core-rust/pull/1 in this case), this file is uploaded:
- https://download.delta.chat/node/preview/deltachat-node-1.tar.gz
> Fix github action to publish node bindings

- CHANGELOG.md
- src/imap.rs
If there are no MOVE/DELETE operations pending, the folder
should not be SELECTed.
When `only_fetch_mvbox` is enabled, `fetch_new_messages` skips
most folders, but `move_delete_messages` always selects the
folder even if there are no operations pending. Selecting
all folders wastes time during folder scan and turns
recent messages into non-recent.
Fixes #3332
> imap: do not unnecessarily SELECT folder in move_delete_messages()

- CHANGELOG.md
- python/tests/test_1_online.py
- src/chat.rs
Android seems to display it, making the message box larger.
> Trim last newline in the chat encryption info

- python/src/deltachat/chat.py
False is returned not only for 1:1 chat, but also in
other cases, such as mailing lists.
Fixes #3343
> python: fix Chat.is_group() documentation

- CHANGELOG.md
- src/imex.rs
- src/peerstate.rs
The problem was in the handle_fingerprint_change() function which
attempted to add a warning about fingerprint change to all chats with
the contact.
This failed because of the SQL query failing to find the contact for
self in the `contacts` table. So the warning was not added, but at the
same time the whole decryption process failed.
The fix is to skip handle_fingerprint_change() for self addreses.
Fixes #3291
> Fix failure to decrypt first message to self after key synchronization

- CHANGELOG.md
- src/chat.rs
- src/contact.rs
- src/dc_receive_imf.rs
- src/ephemeral.rs
- src/imap.rs
- src/message.rs
- src/smtp.rs
- src/sql.rs
- src/sync.rs
Using &str instead of AsRef<str> is better for compile times, binary size and code complexity.
> Remove some AsRef<str>

- .github/workflows/node-package.yml
- .github/workflows/node-tests.yml
- node/scripts/postLinksToDetails.js
> Improve node publish ci

- CHANGELOG.md
- src/imap.rs
- src/imap/scan_folders.rs
Skipping of all [Gmail] folders was introduced to avoid scanning
virtual "[Gmail]/All Mail" folder. However, it also skips Sent and
Spam folders which reside inside [Gmail]. As a result
configured_sentbox_folder becomes unset after folder scan, making it
impossible to watch Sent folder, and Spam folder is never scanned.
This change makes Delta Chat identify virtual Gmail folders by their
flags, so virtual folders are skipped while Sent and Spam folders are
still scanned.
> Do not skip Sent and Spam folders on Gmail

- CHANGELOG.md
- src/e2ee.rs
- src/mimeparser.rs
mimeparser now handles try_decrypt() errors instead of simply logging
them. If try_decrypt() returns an error, a single message bubble
with an error is added to the chat.
The case when encrypted part is found in a non-standard MIME structure
is not treated as an encryption failure anymore. Instead, encrypted
MIME part is presented as a file to the user, so they can download the
part and decrypt it manually.
Because try_decrypt() errors are handled by mimeparser now,
try_decrypt() was fixed to avoid trying to load private_keyring if the
message is not encrypted. In tests the context receiving message
usually does not have self address configured, so loading private
keyring via Keyring::new_self() fails together with the try_decrypt().
> mimeparser: explicitly handle decryption errors

- CHANGELOG.md
- src/dc_receive_imf.rs
Gmail saves all outgoing messages to the Sent folder,
including MDNs. Delete MDNs sent by Delta Chat immediately
to keep DeltaChat or INBOX clean.
Fixes #3349
> Delete outgoing MDNs detected in the Sent folder

- CHANGELOG.md
- src/context.rs
This ensures that no invalid states are possible,
like the one where cancel channel exists, but
no ongoing process is running, or the one where
the ongoing process is not allocated, but
should not be stopped.
> Reduce number of possible ongoing process states

- CHANGELOG.md
- src/chat.rs
- src/contact.rs
current master does not update `chat.name` when authname of a contact changes - for reproducing the bug:
- add a contact manually without setting a name
- receive a message from that contact that includes a name
the name is now shown in the chatlist as expected, but you will not be able to discover that chat using the global search.
fixes https://github.com/deltachat/deltachat-core-rust/issues/3376
> make chat names always searchable

- CHANGELOG.md
- src/test_utils.rs
I added this poison_sender and poison_receiver stuff back when we had event listeners (which were called "sinks", too, but anyway), i.e. user-definable closures that were run in the events loop. This was to make sure that the test fails if the closure panics. But since we don't have them anymore and this code isn't supposed to panic anyway:
```rust
while let Some(event) = events.recv().await {
for sender in senders.read().await.iter() {
sender.try_send(event.clone()).ok();
}
}
```
> test_utils.rs / TestContext: Remove poison channel, don't fail test if events loop panics (because it can't panic anymore)

- CHANGELOG.md
- package.json
It's only used in `node/scripts/generate-constants.js`.
> node: move split2 to devDependencies

- CHANGELOG.md
- scripts/run_all.sh
Recent manylinux2014 images contain Python 3.10 and Python 3.11.
Python 3.11 is in beta, so adding only Python 3.10.
> python: build wheels for python 3.10

- CHANGELOG.md
- draft/webxdc-dev-reference.md
- src/chat.rs
- src/dc_receive_imf.rs
- src/mimeparser.rs
- src/peerstate.rs
- src/webxdc.rs
this pr combines series of webxdc info messages to one message.
cleaning-up approach is:
- if on adding a new info message, the last message is an info message from the same sender _and_ for the same webxdc instance ...
- ... replace the text of the existing info message instead of adding a new one
i assume, this works out of the box on all platforms.
this will solve all issues we currently have with the existing highscores (only the last highscore is shown, that's fine) and "edited" information (they often have the same text anyway). 
of course, one can imagine situations where the cleaning up is not what is optimal for the webxdc, however, i think, the advantages of a cleaned up chat are much bigger.
and webxdc can deal with that, therefore, i added a hint to the reference (should go to …
> cleanup series of webxdc info messages

- src/provider/data.rs
ran `./src/provider/update.py ../provider-db/_providers/ > src/provider/data.rs` 
this fixes the hermes subdomain issue for now, to move forward, cmp. https://github.com/deltachat/deltachat-core-rust/issues/3383
> update provider database

- CHANGELOG.md
- package.json
this broke flathub build. (it tried to download node gyp again, but flathub builds are offline).
I need a new tag with this merged to continue fixing the flathub build.
> node: remove `npx` from build script,

- python/pyproject.toml
- python/tox.ini
instead of passing it in command line usage in tox.ini, this allows isort usage with editors to pick the right configuration without manually tweaking it in the editors
> move isort configuration to pyproject.toml

- CHANGELOG.md
- src/context.rs
- src/lib.rs
- src/ratelimit.rs
- src/scheduler.rs
- src/smtp.rs
- src/smtp/send.rs
New ratelimiter module counts number of sent messages and calculates
the time until more messages can be sent.
Rate limiter is currently applied only to MDNs. Other messages are
sent without rate limiting even if quota is exceeded, but MDNs are not
sent until ratelimiter allows sending again.
> Limit rate of MDNs

- CHANGELOG.md
- src/sql.rs
Fix for https://support.delta.chat/t/bug-report-data-not-deleted/2107
> Remove msgs_mdns references to deleted messages during housekeeping

- src/configure.rs
- src/context.rs
- src/imap.rs
- src/login_param.rs
- src/smtp.rs
This makes sure that under normal circumstances the LoginParam struct
is always fully validated, ensure future use does not have to be
careful with this.
The brittle handling of `server_flags` is also abstraced away from
users of it and is now handled entirely internally, as the flags is
really only a boolean a lot of the flag parsing complexity is removed.
The OAuth2 flag is moved into the ServerLoginParam struct as it really
belongs in there.
> Validate and simplify LoginParam struct

- CHANGELOG.md
- src/smtp/send.rs
i tried some other approaches as having optional ratelimiter
or handle `can_send()` for bots differently,
but all that results in _far_ more code and/or indirections -
esp. as the "bot" config can change and is also persisted -
and the ratelimiter is created
at a point where the database is not yet available ...
of course, all that could be refactored as well,
but this two-liner also does the job :)
closes #3436
> do not use ratelimiter for bots

- deltachat-ffi/deltachat.h
- src/chat.rs
this pr does not change any functionality.
when working on forwarding on ios, the question came up what to do with info messages:
- desktop allows forwarding single info-messages (there is no multi-select)
- android has some logic that hides the forwarding option when in multi-select contains info-messages
- core allows forwarding, however, removes the `is_info` flag
i think, desktop and core is just fine - however, we should make sure, that a forwarded info-message is no info-message in the destination chat - therefore, this pr added a test for exactly that.
for android, i did a pr to remove the extra check, so that all messages can be forwarded.
allowing forwarding info-messages seems also be nicer ux-wise - less to explain, simple, user can forward what is shown on the screen, simpler …
> forward_msgs(): add a test, refine docs

- CHANGELOG.md
- src/dc_receive_imf.rs
some mailinglists have their name in square brackets prepended to the subject.
we pick up that name and remove the square brackets,
as these do not look good as the chat name in delta chat.
if a mailing list has a sequence of square brackets, we use all of them
(this seems to be okayish, i do not know of any complains).
however, the removal of square brackets was not nice for sequences,
resulting in `ml topic] [sub topic`.
this pr removes the square brackets only for the first name
and leave the other ones as is: `ml topic [sub topic]`
> smarter mailinglist's square bracket prefixes

- CHANGELOG.md
- src/dc_receive_imf.rs
mailinglist footers often contains additional infomation or are created at all from the mailinglist.
therefore, we should not use them as "status" of the contact.
closes #3459
> ignore status footer updates from mailinglists

- deltachat-ffi/src/lib.rs
- src/lib.rs
- src/peerstate.rs
It happened multiple times now that I wanted to quickly execute a test, but because of a warning that had become an error, it didn't execute.
This turns warnings into warnings again; our CI will fail if there is a warning, anyway (because of `RUSTFLAGS: -Dwarnings`)
> Turn off hard errors for lints

- CHANGELOG.md
- src/message.rs
- src/mimeparser.rs
- src/receive_imf.rs
if the NDN has no specific error text,
but we know the failed recipient address,
add these information the final message.
successor of https://github.com/deltachat/deltachat-core-rust/pull/3410
@adbenitez this should further improve the originally empty error message you (?)  encountered in some testing delta group, if you have further infomation or mail `.eml` ource code, please add :)
> add more details to fallback NDN

- examples/repl/cmdline.rs
that bit was missing, the command `chat` has shown just nothing for webxdc messages.
> show webxdc information in repl tool

- src/provider/data.rs
ran `./src/provider/update.py ../provider-db/_providers/ > src/provider/data.rs` 
with chance things are now fine because of [IMAP ID added](https://github.com/deltachat/deltachat-core-rust/pull/3468).
> update 163.com in provider database

- CHANGELOG.md
- src/context.rs
we want to prevent runaway things,
not restrict normal usage too much,
this limit seems to be more reasonable
also for most round-based games.
> increase ratelimit

- src/context.rs
ordering is by `id` since #2364, selecting `timestamp` is not needed.
(came over this when keeping `id` on downloading in #3487 -
had in mind there was sth. special with ids ...
however, the assumption of #2364 is even more true with #3487 -
before, new (and then maybe much larger) ids were inserted
and could result in wrong search result ordering)
> do not `SELECT timestamp` if not used

- CHANGELOG.md
- src/download.rs
- src/receive_imf.rs
- src/webxdc.rs
with this pr, received webxdc status updates are handled if the webxdc instance is not yet downloaded.
as the updates in `msgs_status_updates` are identified by `msg_id`, this id must not change on download (changing `msg_id` on download was just done because it was easier to implement that time) (if a download expands to multiple messages, they get additional ids then, of course, but this does not affect webxdc instances or other messages sent by Delta Chat)
the method to keep the `msg_id` is not super-elegant, but working - i tried some alternatives to keep the `msg_id` (UPDATE etc.), but all of them result in much more complicated code. maybe someone has a nicer idea :)
closes #3262
> handle webxdc updates for not downloaded instances

- CHANGELOG.md
- src/peerstate.rs
- src/tests/aeap.rs
It all began with this message:
> we trust autocrypt key, even if it has been changed a minute ago. What prevents an attacker from forging a message with a From: and a new key generated by attacker immediately followed by a message signed with this key and another From: ? All that is required is the ability to forge From: which is not secure.
Some ideas were:
1. Transition in verified group should not happen if verified key is different [(@hpk)](https://github.com/deltachat/deltachat-core-rust/compare/master...hoc%2Faeap-only-replace-in-one-chat?body=&expand=1#)
2. Transition in normal group should not happen if autocrypt key was changed recently
But then we looked for something simpler for 1.32.
Alternatively to these two points/ideas, we also thought about requiring an incoming mail to …
> Only do the AEAP transition in the chat where it happened

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- src/e2ee.rs
- src/peerstate.rs
- src/stock_str.rs
- src/tests/aeap.rs
#3491 introduced a bug that your address is only replaced in the first group you write to, which was rather hard to fix. In order to be able to release something, we agreed to revert it and instead only replace the contacts in verified groups (and in broadcast lists, if the signing key is verified).
More ideas for later:
- dkim verification to generally make from-forgery harder (and we could use it as a neccessary signal for autocrypt key changes) (see #3507 and #3508)
- making the AEAP change into an interactive UX: if you change your address and post to an opportunistic group, someone will have to say "ok, perform the transition" and will then send an added/removed message. this requires UI changes/additions.
- tracking when autocrypt keys changed and how often a key was used -- if it's …
> (AEAP) Revert #3491, instead only replace contacts in verified groups

- CHANGELOG.md
- python/src/deltachat/__init__.py
- python/src/deltachat/account.py
`run_cmdline()` is a really useful function - so useful that I re-implemented it two times already:
- https://github.com/deltachat/eppdperf/blob/main/src/eppdperf/analysis.py#L288
- https://github.com/deltachat/mailadm/blob/bot-refactored/src/mailadm/cmdline.py#L69
In both cases I would have loved to use it, but as the bot was only part of a larger project and was started from python code instead of a bash command line, I couldn't use it.
This PR reduces `run_cmdline()` to a thin wrapper, which only calls `account.run_account()`, the function which now does the useful configure and start_io calls.
`tests/test_1_online.py::test_set_get_group_image` also fails on master, don't know what's up there.
> python bindings: move account initialization to separate function

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/chat.rs
- src/receive_imf.rs
that bit was missing. in the ui, the address could be shown in the profile somewhere, this is how it looks like on ios with https://github.com/deltachat/deltachat-ios/pull/1654:
if it turns out, the addresses are quite readable most times, on desktop, maybe we can add them to the chat's subtitle directly eg. as `Mailing list - delta@codespeak.net` in this case.
> add ffi to get mailinglist post address

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
- package.json
this pulls in the mailinglist api from https://github.com/deltachat/deltachat-core-rust/pull/3524, we'd like to have that feature in the currently prepared ios 1.32 version.
git tag -a 1.92.0
git push origin 1.92.0
git tag -a py-1.92.0
git push origin py-1.92.0
> prepare 1.92

- CHANGELOG.md
- src/qr.rs
This pr improves the error handling of create account from arcade generated/powered by mailadm.
missytake did the mailadm part: https://github.com/deltachat/mailadm/pull/39
This pr represents the core part.
I’m not glad on the error wording, so I'd be happy to hear some suggestions.
This will close: https://github.com/deltachat/deltachat-core-rust/issues/3192
The old version of mailadm that is still deployed to test run at time of writing.
Before:
```
> setqr DCACCOUNT:https://testrun.org/new_email?t=wrong
Cannot set config from QR code: Cannot create account, request to 
"https://testrun.org/new_email?t=wrong" failed
Caused by:
0: error decoding response body: expected ident at line 1 column 2
1: expected ident at line 1 column 2
```
After:
```
> setqr …
```
> improve error handling for account setup from qrcode closes #3192

- .github/workflows/ci.yml
- CHANGELOG.md
- examples/repl/cmdline.rs
- src/accounts.rs
- src/blob.rs
- src/chat.rs
- src/color.rs
- src/contact.rs
- src/job.rs
- src/lib.rs
- src/login_param.rs
- src/provider.rs
- src/qr.rs
- src/securejoin/bobstate.rs
- src/webxdc.rs
Turn clippy warnings into errors in CI, check `repl` feature and fix some warnings related to `PathBuf`.
I think the problem with warnings being ignored was introduced in #3441, which turned errors into warnings by default, but did not update CI to keep treating warnings as errors. `RUSTFLAGS=-Dwarnings` seems to affect compiler errors, but not clippy errors.
> Clippy fixes

- python/src/deltachat/account.py
- python/tests/test_1_online.py
- python/tests/test_3_offline.py
closes #3529 
...actually, I'm not sure if it is this easy. Maybe we should add some more tests if the AEAP change goes fine. What would be proper test cases?
> python: don't raise an error if addr changes

- src/config.rs
- src/stock_str.rs
My project uses `deltachat-core-rust` as a dependency and I encountered a build error in a specific situation.
When some crates in the dependency tree enables `derive` feature in `strum` crate, the following error occurs:
```
error[E0252]: the name `EnumProperty` is defined multiple times
--> /home/picoHz/.cargo/git/checkouts/deltachat-core-rust-632648ad67f90089/50e53f2/src/config.rs:5:49
|
4 | use strum::{EnumProperty, IntoEnumIterator};
|             ------------ previous import of the macro `EnumProperty` here
5 | use strum_macros::{AsRefStr, Display, EnumIter, EnumProperty, EnumString};
|                                                 ^^^^^^^^^^^^--
|                                                 |
|                                                 `EnumProperty` reimported here
| …
```
> rename strum::EnumProperty to avoid name conflict

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
- package.json
this is mainly needed to release 1.32 for flathub, cmp. https://github.com/deltachat/deltachat-desktop/issues/2859 - but there are probably some more steps needed i am not aware of.
moreover, with 1.93 also JSON RPC gets released :)
git tag -a 1.93.0
git push origin 1.93.0
git tag -a py-1.93.0
git push origin py-1.93.0
> prepare 1.93

- CHANGELOG.md
- src/mimeparser.rs
- test-data/message/attached-eml.eml
Before this PR, when you try to attach a .eml file using a classic email client, it's shown as a normal message instead of an attachment.
(see @adbenitez' screenshot in the Core Rust group)
> Show attached .eml files as such

- CHANGELOG.md
- src/chat.rs
- src/contact.rs
in several offline discussions, the idea shaped up to change the ordering of the contact lists from "a-z" to "last seen".
esp. with the new ["seen recently indicator"](https://github.com/deltachat/deltachat-android/pull/2371), the "new chat" and "member lists" seem to be more useful:
- no weird addresses/names as "-1" stucking atop of the "new chat" list forever
- recently used addresses are shown first, eg. when searching for @adbenitez , the first hit is the correct address (i have that with several ppl; when adding them to groups, it is always unclear what to use)
- together with the "seen recently indicator" you see with one glance, who is online - either in a group or globally
- just blocked contacts are shown atop of the list (important in case you accidentally blocked)
- the new …
> order contact lists by "last seen" instead of name/address

- deltachat-ffi/deltachat.h
> fix doc, dc_accounts_get_next_event() is gone

- CHANGELOG.md
- src/receive_imf.rs
As mentioned in #3300, bot code is kind of verbose because contact requests have to be manually accepted. This PR introduces auto accept for contact requests if the client has the config option `Config::Bot` enabled, and is hence a bot. 
As @Hocuri mentioned, auto accepting contact requests also means sending a confirmation email to spammers who might then continue sending spam emails. For bots this is not as bad as for real users, but we still have to decide whether we want to go with this solution.
> Auto-accept contact requests for bots

- deltachat-jsonrpc/src/api/mod.rs
- src/contact.rs
- src/scheduler/connectivity.rs
these two functions don't compile, I get this error:
```
error: generator cannot be sent between threads safely
--> deltachat-jsonrpc/src/api/mod.rs:74:1
|
74 | #[rpc(all_positional, ts_outdir = "typescript/generated")]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ future created by async block is not `Send`
|
= help: the trait `Sync` is not implemented for `core::fmt::Opaque`
= note: required for the cast to the object type `dyn Future<Output = Result<Value, yerpc::Error>> + Send`
= note: this error originates in the attribute macro `rpc` (in Nightly builds, run with -Z macro-backtrace for more info)
error: could not compile `deltachat-jsonrpc` due to previous error
cargo failed with code 101
```
any ideas what we need to change in order to fix it?
also if you try it out, …
> jsonrpc: add two functions, but they don't compile  yet, being not "threadsafe"

- src/webxdc.rs
this was probably forgotten by recent refactorings in this area.
> simplify return value of `flush_status_updates()`

- CHANGELOG.md
- src/constants.rs
- src/mimeparser.rs
- src/tools.rs
because many line-breaks seem to cause the chat open delay on deltachat-ios. (https://github.com/deltachat/deltachat-core-rust/issues/3478)
I only starts counting lines if text is longer than `DC_DESIRED_TEXT_LINES_THRESHOLD`, so should not have an speed impact for most messages.
I already tested this on iOS and it worked as expected there.
The old truncate function is still used for message-info(we might remove message text there) and chat summary (will stay for summary).
Related to #3478, but does not fully fix it.
> truncate incoming messages by lines

- CHANGELOG.md
- src/chat.rs
- src/config.rs
- src/webxdc.rs
enabling `BccSelf` improves user experience as
it is easier to set up another device
and ppl will also see "all" messages in other user agents directly.
for uncounted user problems, after diving into the issue,
the resulting device was "turn on BccSelf".
disabled `BccSelf` was probably the the number one single reason
of user problems.
(just recently again, this is the reason for this change, that, however, was discussed offline many times, but it never ends in a pr  :)
main drawback of the change are potentially double notifications
when using a shared account and having another mail app on the same device (see https://github.com/deltachat/deltachat-core-rust/pull/825).
however, we meanwhile do not recommend shared accounts at all,
the issue is also fixable by the other mail apps (as …
> enable `BccSelf` by default 

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
- deltachat-jsonrpc/Cargo.toml
- deltachat-jsonrpc/typescript/package.json
- package.json
this is the core probably used for the approaching 1.34 releases.
git tag -a 1.95.0
git push origin 1.95.0
git tag -a py-1.95.0
git push origin py-1.95.0
> prepare 1.95

- .github/workflows/jsonrpc-client-npm-package.yml
- CHANGELOG.md
- deltachat-jsonrpc/typescript/package.json
- node/scripts/postLinksToDetails.js
- package.json
npm does not really like importing it over deltachat-node, so this pr 
makes it a full dedicated package that we can upload to npm and 
import directly.
this will fix the nix build again and make other things easier as 
well.
TODO:
> jsonrpc js client: ci upload and new name

- .github/workflows/node-tests.yml
set timeout for node ci tests to 10min for the test step,
macOS takes 12min for the whole workflow with cached core build,
so 10min just for the test step should be plenty.
> set timeout for node ci tests to 10min

- Cargo.lock
- Cargo.toml
The current version is unsatisfyable if you use deltachat as a
dependency itself.
> Update textwrap dependency

- CHANGELOG.md
- src/context.rs
Since I've been writing a bit of rust bot now, this hurts.  Let's
improve it.
The way to create a Context is now rather burdensome, users have to
create and import a bunch of things just to get a Context.  So let's
introduce a builder.
Notice that the builder can only produce an open context, if the
context can not be opened it is dropped.  This is on purpose, the
Context itself can become RAII again at some point by doing this.
Only the FFI needs to have the concept of an open and a closed
Context.
> Introduce a ContextBuilder struct

- src/message.rs
- src/param.rs
It was used as `.as_ref().to_string()`, so may as well just call `.to_string()` directly.
Addresses #3669 
#skip-changelog (refactoring)
> Accept ToString instead of AsRef<str> in Params.set()

- src/receive_imf.rs
- src/test_utils.rs
Seems like consume_events() didn't work properly, i.e. in some cases it didn't see the latest events and failed to consume them. So, the IncomingMsg event from receiving the first mailinglist message stayed in the events channel, which made this fail:
```rust
// Check that no notification is displayed for blocked mailing list message.
while let Ok(event) = t.evtracker.try_recv() {
assert!(!matches!(event.typ, EventType::IncomingMsg { .. }));
}
```
Fix it by explicitly waiting for the first IncomingMsg event.
fix #3727 
> Fix flaky test_block_mailing_list()

- deltachat-jsonrpc/typescript/src/client.ts
reason:
the array solution has many empty elements in between accounts in practice,
which is annoying when debugging desktop
> jsonrpc: ts-client use object instead of array for `contextEmitters`

- Cargo.lock
- Cargo.toml
If building DC failed for you with some long error message about "spurious network error" and "async_io_utilities", then this PR fixes that.
Majored deleted the rs-async-io-utilities repo because he [doesn't need it anymore](https://github.com/Majored/rs-async-zip/commit/618f700811362189bb46d9e736c7ea983ecf6266), so that https://github.com/dignifiedquire/rs-async-zip doesn't have its dependency anymore. The latter was a hotfix-fork of https://github.com/Majored/rs-async-zip because https://github.com/Majored/rs-async-zip/pull/27, fixing https://github.com/deltachat/deltachat-core-rust/issues/3476, wasn't merged.
But apparently the problem of https://github.com/deltachat/deltachat-core-rust/issues/3476 is fixed in `async_zip = "0.0.9"`, at least all the webxdcs from https://webxdc.org/ …
> Go back to standard async_zip, fix build failures

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- python/tests/test_3_offline.py
- src/contact.rs
we are quite often getting requests of users [^1]
who want to get rid of some contact in the "new chat" list. there is already a "delete" option,
but it does not work for referenced contacts -
however, it is not obvious for users that a contact is in use, esp. of some mailing list or larger chat, old contacts, whatever.
this pr revives an old idea [^2] of "soft deleting" referenced contacts - this way, the user can remove the annoying entry
without the need to understand complicated things
and finally saying that deletion is impossible :)
once the contact is reused, it will reappear,
however, this is already explained in the confirmation dialog of the UIs.
technically, this pr was simpler as expected as we already have a Origin::Hidden, that is just reused here.
[^1]: just recently again, …
> allow deleting referenced contacts in UI

- CHANGELOG.md
- src/imap.rs
Looks like this very simple commit does the job. But if you wish, i can simplify the whole fetch_new_messages() so it would do the only fetch (full or partial) in its run.
Tested it by hands now, using Gmail with mvbox_move disabled as @link2xt suggested
> fetch_new_messages(): fetch messages sequentially (#3688)

- CHANGELOG.md
- python/tests/test_1_online.py
- src/imap.rs
- src/receive_imf.rs
That's a bug which @Simon-Laux and probably also @hpk42 had, where one malformed incoming (Spam-) mail blocked the receiving of all emails coming after it.
The problem was that from_field_to_contact_id() returned `ContactId::UNDEFINED`, and then `lookup_by_contact()` returned `Err`.
> Bugfix: Don't let malformed From: headers block the receiving pipeline

- python/src/deltachat/_build.py
- python/src/deltachat/events.py
- python/src/deltachat/hookspec.py
- python/src/deltachat/message.py
- python/src/deltachat/reactions.py
- python/tests/test_1_online.py
Hello! I have a couple of questions here:
- In the test, how do i check on a recipient side that it is a partially fetched message and that it is a file message? Looks like we should add an API for checking whether it is a partially or fully fetched message. Also i tried Message.is_file(), but it is likely not working for partially fetched messages. Does dc_msg_get_viewtype() return just 0 for them? I believe, in DC should be a way to see at least a type of message before downloading it. Also i see no API for checking that a received message is one that was sent, i.e. for comparing these Message-Id-s: Mr.MsE3xF0RQX8.zhUwsZ7n1sb@x.testrun.org
- I use in the test Account.stop_io() and .set_config() functions. Can i use acfactory.get_online_accounts() then? If my test finishes successfully, …
> Add Python API to send reactions (#3762)

- CHANGELOG.md
- python/tests/test_1_online.py
- src/receive_imf.rs
It's a w/a for "Space added before long group names after MIME serialization/deserialization" issue. DC itself never creates group names with leading/trailing whitespace, so it can be safely removed.
> receive_imf: trim() "Chat-Group-Name{,-Changed}:" headers content (#3650)

- CHANGELOG.md
- deltachat-ffi/src/lib.rs
- deltachat-jsonrpc/src/api/mod.rs
- src/chat.rs
- src/config.rs
- src/configure.rs
- src/ephemeral.rs
- src/login_param.rs
- src/mimefactory.rs
- src/peerstate.rs
- src/scheduler/connectivity.rs
- src/sql.rs
- src/sql/migrations.rs
- src/stock_str.rs
- src/test_utils.rs
- src/tools.rs
Using &str instead of AsRef is better for compile times, binary size and code complexity.
The only place it's left is tools.rs:595 (`impl<T> IsNoneOrEmpty<T> for Option<T>`), but i think it is too common place to change T to String/&str there (and to struggle with lifetimes in case of &str)
> Remove the remaining AsRef<str> (#3669)

- CHANGELOG.md
- benches/receive_emails.rs
- src/chat.rs
- src/peerstate.rs
- src/receive_imf.rs
- src/securejoin/bob.rs
- src/sql.rs
- src/sql/migrations.rs
This esp. speeds up receive_imf a bit when we recreate the member list (`recreate_member_list == true`).
It's a preparation for https://github.com/deltachat/deltachat-core-rust/issues/3768, which will be a one-line-fix, but recreate the member list more often, so that we want to optimize this case a bit.
It also adds a benchmark for this case. It's not that easy to make the benchmark non-flaky, but by closing all other programs and locking the CPU to 1.5GHz it worked. You can see that `./with-optim` is consistently a few percent faster than `./without-optim`:
<details>
<pre><font color="#00B400"><b>➜  </b></font><font color="#55FFFF"><b>deltachat-core-rust</b></font> <font color="#5555FF"><b>git:(</b></font><font color="#FF5555"><b>hoc/bulk-member-adding</b></font><font …
>  Add members to chats in a single sql transation

- CHANGELOG.md
- deltachat-jsonrpc/src/api/types/message.rs
I need it for #3734 so echo bot can skip undecipherable messages etc.
> jsonrpc: add message errors to MessageObject

- CHANGELOG.md
- python/tests/test_1_online.py
- src/imap.rs
When a batch of messages is moved from Inbox to DeltaChat folder with a single MOVE command, their UIDs may be reordered (e.g. Gmail is known for that) which leads to that messages are processed by receive_imf in the wrong order. But the INTERNALDATE attribute is preserved during a MOVE according to RFC3501. So, use it for sorting UIDs before fetching messages.
Checked by hands for now, will publish a test soon
> Fetch messages in order of their INTERNALDATE (#3756)

- CHANGELOG.md
- python/src/deltachat/account.py
> python: do not pass NULL to ffi.gc if the context can't be created

- .github/workflows/ci.yml
- .github/workflows/repl.yml
It is unmaintained and throws many warnings about using deprecated Node and GitHub Actions commands.
> ci: remove dependency on actions-rs/cargo

- src/receive_imf.rs
We were already using context.get_config_bool(Config::Bot) in some places, this unifies this.
`get_config(Config::Bot).await?.is_some()` is wrong since it considers `Some("0")` to be `true`, and `set_config_bool(Config::Bot, false)` will set the config to `Some("0")`.
followup for #3831
> use context.get_config_bool() for Config::Bot everywhere

- CHANGELOG.md
- src/receive_imf.rs
fix #3768
TODO:
@Septias I also requested a review from you since that's relevant for https://github.com/deltachat/deltachat-core-rust/pull/3807 (idk if changes are necessary, just something to be aware of)
> Add new recipients of MUA emails to the group member list

- CHANGELOG.md
- src/decrypt.rs
- src/mimeparser.rs
- src/peerstate.rs
- src/receive_imf.rs
- test-data/message/thunderbird_with_autocrypt_unencrypted.eml
Decided to enable a mutual encryption immediately upon a receipt of PGP key attachment, not waiting for an encrypted message to be received, for the following reasons:
- This way we set up encryption earlier making a communication more secure. In Autocrypt we have an explicit "prefer-encrypt" flag, but here we have no, and i think going more securily is a better choice.
- It's more like that we had with a User-Agent-based solution.
Also decided to preserve the current pubkey if it's already set up, that makes code simpler, f.e. this way we don't need to know when it was set up -- when parsing an Autocrypt header of current message or earlier.
> Treat attached PGP keys as peer keys with mutual encryption preference (#3778)

- .gitattributes
- CHANGELOG.md
- src/decrypt.rs
- src/mimeparser.rs
- src/peerstate.rs
- src/receive_imf.rs
- test-data/message/thunderbird_signed_unencrypted.eml
- test-data/message/thunderbird_with_autocrypt_unencrypted.eml
#3844
Note that if the message is encrypted, we don't check whether it's signed with an attached key currently, otherwise a massive refactoring of the code is needed because for encrypted messages a signature is checked and discarded first now.
> Prefer encryption for the peer if the message is encrypted or signed with the known key

- CHANGELOG.md
- src/decrypt.rs
- src/mimeparser.rs
If we move the detached signatures validation code out of try_decrypt(), we don't need to convert an already parsed signed message part to Vec and then parse it back. Also this simplifies the try_decrypt() semantics and return type. It can't make a good coffee anyway.
> Don't parse the message again after detached signatures validation

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
this will avoid some incompatibilities and castingss in UI.
successor of https://github.com/deltachat/deltachat-core-rust/pull/3839
> use u32 as id as done elsewhere

- CHANGELOG.md
- src/chat.rs
- src/test_utils.rs
this pr is a successor of #3918:
- fix test_utils
- let marknoticed_chat() work for the pseudo archive-link chat (the idea is to have a button to make all of archive as noticed quickly)
- add tests for the archived-link counters and archive-mark-noticed
as usual, for review, hiding whitespace makes some sense :)
> mark all archived read

- CHANGELOG.md
- deltachat-jsonrpc/src/api/types/chat_list.rs
this is a followup to #3918
I went with option "C" from my comment:
https://github.com/deltachat/deltachat-core-rust/pull/3918#issuecomment-1371224339
- Archive link is (still) very different from a normal chat, so most of the options would be empty / not relevant
- avatar path is not needed as desktop renders it differently anyway,
it's not really a chat like saved messages or device messages where it made more sense
for the core to supply the icon, vs. using the svg directly.
- translating the string in the coreas stock-string is more annoying than doing it from the ui, especially when
this special pseudo chat has different rendering anyway so also no need to provide a name property
We could also try the other options, but I think this is the cleaner way for the jsonrpc api. I …
> jsonrpc: add fresh message count to the archive-link chatlistitem variant

- CHANGELOG.md
- src/contact.rs
(no events for contacts that are already offline again)
This dramatically speeds up replay after backup import on desktop.
~~seems like this doesn't work....~~ ~~probably was my unfinished desktop pr instead, this pr looks fine~~ edit: works as expected, was just using a broken desktop pr
> fix: only send contact changed event for recently seen if it is relevant

- src/test_utils.rs
E.g.
```
========== Chats of bob: ==========
Single#Chat#10: alice@example.org [alice@example.org]
--------------------------------------------------------------------------------
Msg#10:  (Contact#Contact#10): hellooo [FRESH]
Msg#11:  (Contact#Contact#10): hellooo without mailing list [FRESH]
--------------------------------------------------------------------------------
========== Chats of alice: ==========
Single#Chat#10: bob@example.net [bob@example.net]
--------------------------------------------------------------------------------
Msg#10: Me (Contact#Contact#Self): hellooo  √
Msg#11: Me (Contact#Contact#Self): hellooo without mailing list  √
--------------------------------------------------------------------------------
```
I found this very useful sometimes, so, let's try to …
> Print chats when a test failed

- CHANGELOG.md
- deltachat-ffi/src/lib.rs
- deltachat-jsonrpc/src/api/types/contact.rs
- src/contact.rs
also refactor it so that it is not a static method anymore
(would have resulted in two load-Contact-from-db-calls in jsonrpc)
looks like this was forgotten in #3839
> add verified-by api to jsonrpc

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- python/tests/test_0_complex_or_slow.py
- python/tests/test_1_online.py
- src/events.rs
- src/imex.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/peerstate.rs
- src/receive_imf.rs
- src/securejoin.rs
- src/securejoin/bobstate.rs
I don't like much that actually gossip headers are handled before observe_securejoin_on_other_device() that just takes the peer's current gossip pubkey, because if the first device forgets to add the gossip header, we may proceed with the outdated key, but this isn't a security issue unless the old key is compromised. But looking through all gossip headers again is an excessive work. Maybe it's worth adding some map for processed gossip headers
> Securejoin: Fix adding and handling Autocrypt-Gossip headers

- src/message.rs
it shoud read "filename.ext, 123 bytes" and not "filename.ext, 123, bytes"
> remove comma from unit in message-details

- CHANGELOG.md
- src/peerstate.rs
this was making `Contact::lookup_id_by_addr` fail inside of `get_verifier_id`.
> fix verifier-by addr was empty string instead of None

- python/src/deltachat/account.py
We noticed that disabling watching the DeltaChat folder is bad for bots which run with mailcow accounts, as mailcow instances by default have a Sieve rule which automatically moves all messages with a Chat-Version header to the DeltaChat folder. This led to lost messages.
There is no reason that these default options are set here, tbh I didn't really think about them before I added them. So let's remove them.
The affected function is so far only used by mailadm, where the bug was originally discovered, and this quickstart echo bot example: https://github.com/deltachat-bot/bot-pages/pull/45 which doesn't care about the default config. So we can still safely remove this without affecting implementations.
> python bindings account setup: remove deviation from default config

- Cargo.toml
- deltachat-ffi/Cargo.toml
This was to test pgp early on, but that's not deltachat's business.
If needed the PGP project can always do this with patching.
> Remove the nightly PGP feature

- Cargo.toml
They are only built once, but the time of
`cargo nextest run` is reduced by around 40% as a result.
> Always optimize dependencies

- src/authres.rs
- src/decrypt.rs
- src/mimeparser.rs
Reverts #3728
Closes #3735
Reopens #3700
This makes https://github.com/deltachat/deltachat-android/issues/2299 a bit worse, because there will be errors on more messsages, and also on incoming messages. This should also be fixed before releasing this.
Now might be a good time, since #3933 was just merged?
> Re-enable DKIM-checks

- CHANGELOG.md
- deltachat-jsonrpc/src/api/mod.rs
- deltachat-jsonrpc/src/api/types/message.rs
- deltachat-jsonrpc/typescript/example/example.ts
fixes #3980
`get_messages` now returns an `MessageLoadResult` enum similar to `ChatListItemFetchResult`.
The new returned type looks like this:
```ts
getMessages(accountId: T.U32, messageIds: (T.U32)[]): Promise<Record<T.U32,T.MessageLoadResult>>
export type MessageLoadResult =
| ({ variant: "message" } & Message)
| ({ variant: "loadingError" } & { error: string });
```
This pr implements solution B from #3980, look there fro slightly more info.
> jsonrpc: `get_messages` now returns a map with `MessageLoadResult` instead of failing completely if one of the requested messages could not be loaded.

- .github/workflows/jsonrpc.yml
- Cargo.lock
- deltachat-jsonrpc/Cargo.toml
the axum update broke the websocket server, because yerpc still uses a the old 5.9 version.
So I needed to downgrade the dependency until https://github.com/deltachat/yerpc/pull/35 is merged.
I want to retry the kaiOS client experiment, for this I need a working websocket server binary.
> fix websocket server & add ci test for building it

- CHANGELOG.md
- python/tests/test_1_online.py
- src/config.rs
- src/configure.rs
- src/constants.rs
- src/context.rs
- src/download.rs
- src/ephemeral.rs
- src/imap.rs
- src/imap/idle.rs
- src/imap/scan_folders.rs
- src/job.rs
- src/message.rs
- src/provider.rs
- src/provider/data.rs
- src/receive_imf.rs
- src/scheduler.rs
- src/scheduler/connectivity.rs
- src/smtp.rs
- src/smtp/send.rs
Gmail archives messages marked as `\Deleted` by default if those messages aren't in the Trash. But
if move them to the Trash instead, they will be auto-deleted in 30 days.
Fixes #3957
> Delete messages to the Trash folder for Gmail by default (#3957)

- deltachat-jsonrpc/typescript/package.json
@Simon-Laux needs a CommonJS build of deltachat-jsonrpc. This adds this. It should just work in recent versions of Node.js as it uses the `"exports" ` key in `package.json`.
Depends on https://github.com/deltachat/yerpc/pull/36
> JSON-RPC: Add CommonJS build

- CHANGELOG.md
- src/imex.rs
- src/sql.rs
Fix https://github.com/deltachat/deltachat-android/issues/2263.
- Import started
- The config cache was cleared[^1]
- The user turned off and on the screen -> `is_configured()` was called by the UI -> the result `false` was correctly loaded from the database -> it was put into the config cache
- Import finished
- ConversationListActivity (that's the main activity with the chats) was started
- It called is_configured() -> the result `false` was loaded from the config cache.
- It starts the WelcomeActivity again because it thinks that we're not configured yet.
The fix is: Clear the config cache right after the import finished.
What I'm unsure about: Should I remove [^1] (the line where the config cache was cleared before this PR already)?
Pro: It's not necessary anymore and …
> Correctly clear database cache after import

- CHANGELOG.md
the speedup of #4065 is larger than measured first
running `cargo test`, first we thought there is only a slight speedup from 13.5 seconds to 12.5 seconds on a m1pro.
however, there is one test that does 11 seconds of sleep() (test_modify_chat_disordered) as this test is not run very first, this slows down things overall.
skipping this test,
speedup is from 13.5 seconds to 9.5 seconds -
28% faster - and this is something we should mention in the changelog :)
(this pr does not remove or change the slow test.
i think, due to the number of cores, this is not needed until someone has a machine where the other tests run in 2 seconds or so)
> mention speedup of #4065 in CHANGELOG

- python/pyproject.toml
- python/src/deltachat/__init__.py
Use of `pkg_resources` is discouraged in favor of `importlib.resources`, `importlib.metadata`, and their backports.
closes #4069
> python: replace pkg_resources with importlib.metadata

- CHANGELOG.md
- src/authres.rs
- src/decrypt.rs
- src/mimeparser.rs
Reverts deltachat/deltachat-core-rust#3935 because apparently that makes things easier for releasing again
Reopens #3735
Closes #3700
DKIM checks still are not reliable enough (esp. deltachat.de randomly not signing a message).
Path forward:
- Only if we get a message with a peerstate change AND wrong DKIM, we show a warning symbol. We need to think carefully about the error message that's shown when clicking on it. Mabye sth. like `Failed to check if this message was actually sent by Bob. If you want to be sure, ask back if Bob actually sent it.`
- We don't disallow keychanges since this only makes sense if we want to fully enable AEAP, which is questionable considering the state of DKIM-checks in the wild.
- Maybe later: If we get a well-signed message with wrong DKIM, reset DKIM …
> Re-disable DKIM-checks

- CHANGELOG.md
- src/config.rs
- src/context.rs
- src/e2ee.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/pgp.rs
This makes DC compatible with "multipart/signed" messages thus allowing switching to them someday
from the current "multipart/mixed" unencrypted message format.
> Handle headers from the signed part of unencrypted signed message (#3986)

- src/chat.rs
the slowest test was `test_modify_chat_disordered`; due to several sleep(), it lasts at least 11 seconds.
however, many of the sleep() are not needed and were added just to get things done that time.
this pr removes 7 superfluous sleeps,
making the test finish in about 3 seconds,
so that this test is no longer the bottleneck when running `cargo test` on fast machines.
(this is not only useful to safe some seconds -
but also to notice degradations as of
https://github.com/deltachat/deltachat-core-rust/issues/4051#issuecomment-1436995166 )
> make slowest test faster

- standards.md
noticed that this is missing
while working on https://github.com/deltachat/invite
> add countermitm and openpgp4fpr to "standard used"

- deltachat-jsonrpc/typescript/.npmignore
to remove files from the npm package that is not needed by end users.
> jsonrpc: ts bindings: update .npmignore

- deltachat-ffi/src/lib.rs
- scripts/clippy.sh
Also disable missing_docs_in_private_items as this is like 300+ errors
currently.
> ci: Make sure clippy script checks everything

- .github/workflows/ci.yml
- deny.toml
This adds more configuration to cargo-deny so that the output is not a
giant list of warnings hiding new entries.  Instead the config now
lists the things that would emit warnings.  It also adds -Dwarnings to
the CI job so that new warnings will be cleaned up: they can be added
to the config easily to fix the warnings.
> Configure cargo-deny fully

- deltachat-ffi/Doxyfile.css
the contrast was decreased at
https://github.com/deltachat/deltachat-core-rust/pull/4136 , there were also suggestions to fix it there,
but it was probably just forgotten :)
this pr increases the contrast
between code background and code font again to the level it was before
and also to what similar themes are doing.
before/after:
> restore original Doxygen contrasts

- CHANGELOG.md
- src/receive_imf/tests.rs
- src/simplify.rs
standard footers meanwhile go to the "contact status", so they are no longer a reason to trigger "full message view".
this was already discussed when the HTML view was introduced at #2125 however, forgotten to change when the "contact status" was added at #2218
this pr will result in a cleaner chat view
with less "Show Full Message..." buttons
and will also save some storage
(in fact, i came over that when reviewing #4129 )
> "full message view" not needed because of footers

- CHANGELOG.md
- src/html.rs
- src/plaintext.rs
`<meta name="color-scheme" content="light dark" />` is a hint to the browsers that the page can be rendered in light as well as in dark mode and that the browser can apply corresponding defaults.
as we do not add css colors on our own,
this is sufficient for letting generated html messasge being rendered in dark mode.
cmp. https://drafts.csswg.org/css-color-adjust/#color-scheme-prop
closes #4146
cc @WofWca (i cannot mark you for review)
> allow generated html being rendered in dark mode

- CHANGELOG.md
- src/sql/migrations.rs
This requires currently too much memory, crashing on larger instances
> fix: do not delete columns

- src/imex/transfer.rs
> Pause I/O in get_backup()

- deltachat-ffi/deltachat.h
- src/imex.rs
- src/imex/transfer.rs
- src/scheduler.rs
This makes the BackupProvider automatically invoke pause-io while it
is needed.
It needed to make the guard independent from the Context lifetime to
make this work.  Which is a bit sad.
Closes #4176
> feat: Pause IO for BackupProvider

- deltachat-ffi/src/lib.rs
This adds a result extension trait to explicitly set the last error,
which *should* be the default for the FFI.  Currently not touching all
APIs since that's potentially disruptive and we're close to a release.
The logging story is messy, as described in the doc comment.  We
should further clean this up and tidy up these APIs so it's more
obvious to people how to do the right thing.
----
This is an alternative to #4187, hopefully addressing @Hocuri's
fears.  I believe these APIs need further cleaning up as described,
but let's leave that for after the release.
Closes https://github.com/deltachat/deltachat-core-rust/issues/4186, https://github.com/deltachat/deltachat-core-rust/issues/4178
Since this now does not affect anything other than core-internal:
> Explicitly call Context::set_last_error in ffi

- deltachat-jsonrpc/src/api/mod.rs
- src/context.rs
- src/imex/transfer.rs
This changes the JSON-RPC APIs to get a QR code from the backup
provider to block.  It means once you have a (blocking) call to
provide_backup() you can call get_backup_qr() or get_backup_qr_svg()
and they will block until the QR code is available.
Calling get_backup_qr() or get_backup_qr_svg() when there is no backup
provider will immediately error.
Closes #4191
> ref(jsonrpc): Getting backup provider QR code now blocks

- Cargo.lock
- Cargo.toml
The relevant changes are now in the main branch again.  And the main branch is a bit better to depend on.
> deps(iroh): switch back to iroh main branch

- deltachat-ffi/src/lib.rs
The documentation says this blocks.  This should block because it also
means the error reporting is more accurate by calling set_last_error
just before returning.
#skip-changelog since this makes it behave as is documented
> ref(ffi): dc_receive_backup should block

- CHANGELOG.md
- python/tests/test_1_online.py
- src/receive_imf.rs
Exactly: delivery reports, webxdc status updates.
> receive_imf: Mark special messages as seen (#3054)

- deltachat-ffi/src/lib.rs
this is what we're doing in most comparable unref() functions.
came over this when checking crashes on "quick abort during prepare" on android, cmp. https://github.com/deltachat/deltachat-android/pull/2514/commits/e42918daf0193f244725d777fe096ee2ff28e324 - android checks against null now on its own, but i think, it should be here as well.
https://github.com/deltachat/deltachat-android/pull/2514/commits/e42918daf0193f244725d777fe096ee2ff28e324 fixes some reproducible crashes as "always crash on abort during prepare", but there still seems more complicated cases, also desktop has some reports iirc
related: #4179, #4192
> check against null in dc_backup_provider_unref()

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/deltachat.h
- src/imex/transfer.rs
This ensures that the BackupProvider will be stopped as soon as the struct is dropped and the imex progress error event is emitted.  This makes it easier to use and also makes sure that the ffi call dc_backup_provider_unref() does not lead to dangling resources.
There were some alternatives to doing this, but I wanted to make sure dropping before it is finished also results in a Imex(0) aka SendProgress::Failed event.
Closes #4179
> feat(imex): Cancel BackupProvider when dropped

- Cargo.lock
- Cargo.toml
- deny.toml
- src/imex/transfer.rs
This moves us back to a released version:
- Ticket is now opaque, need to use accessor functions.
- Ticket now ensures it is valid itself, no need to inspect it's inners.  Deserialisation would fail if it was bad.
- The git version was accidentally used with default-features enabled and thus pulled in a few too many dependencies.  They are now gone.
> ref(deps): Upgrade to iroh 0.4.0

- deltachat-ffi/src/lib.rs
- src/configure.rs
- src/imap/scan_folders.rs
- src/log.rs
- src/receive_imf.rs
- src/sql.rs
This removes the message that needed to be supplied to LogExt::log_err
calls.  This was from a time before we adopted anyhow and now we are
better off using anyhow::Context::context for the message: it is more
consistent, composes better and is less custom.
The benefit of the composition can be seen in the FFI calls which need
to both log the error as well as return it to the caller via
the set_last_error mechanism.
It also removes the LogExt::ok_or_log_msg funcion for the same reason,
the message is obsoleted by anyhow's context.
> ref(logging): Remove message from LogExt::log_err

- deltachat-repl/src/cmdline.rs
- src/blob.rs
- src/ephemeral.rs
- src/imex.rs
- src/log.rs
- src/scheduler.rs
- src/scheduler/connectivity.rs
This further reduces the cognitive overload of having many ways to do
something.  The same is very easily done using composition.  Followup
from 82ace72527648ef2dc32e08cf177880732394565 or #4235.
> ref(logging): remove LogExt::log_or_ok

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/chat.rs
- src/message.rs
- src/receive_imf.rs
- src/sql.rs
- src/sql/migrations.rs
- src/tools.rs
It compresses for me HTML emails more than twice (10468 -> 4988 bytes f.e.), but for some reason in my db they take 0% of total disk usage, so, @link2xt, better measure how it helps to u. But currently i use the max. compression level (11), it's too slow and takes much time when upgrading a db. So, for ur db u probably need to reduce it, maybe even to 6.
UPD: Forgot to do `vacuum` on my db. Remeasured -- it reduces my db in 1.797 times.
> Compress `mime_headers` column with HTML emails stored in database (#4077)

- src/sql.rs
It is perfectly normal for this directory to not exist.
> ref(sql): Do not warn if BLOBS_BACKUP_NAME does not exist

- src/imex.rs
- src/imex/transfer.rs
- src/scheduler.rs
- src/scheduler/connectivity.rs
This is more verbose, but makes reasoning about things easier.
Followup from #4246.
> ref(scheduler): Make InnerSchedulerState an enum

- CHANGELOG.md
- src/scheduler/connectivity.rs
(best reviewed with whitespace disabled)
some providers say that they support QUOTA in the IMAP CAPABILITY, but return an empty list without any quota information then.
in our "Connectivity", this looks a bit of an error.
i have not seen this error often - only for testrun.org - if it is usual, we could also just say "not supported" (as we do in case QUOTA is not returned).
a translations seems not to be needed for now,
it seems unusual, and all other errors are not translated as well.
@missytake maybe this can also be fixed on testrun?
before/after (gxc8z at testrun):
this is how it looks if quota is really supported (tunis4 at testrun):
> show some text instead of nothing on empty quota list

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- src/imex/transfer.rs
- src/stock_str.rs
that way, UI can just close the transfer dialog, so that, at the end, both devices end in the chatlist.
we can also use  this for troubleshooting - if the device message is not present, transfer did not succeed completely.
(a separate device message may be nice in that case - but that is another effort, same for making the device message reappear after deletion or after some time)
> add a device message when backup transfer ends

- src/context.rs
- src/imex/transfer.rs
This adds a few log items for imex::transfer::get_backup and the
ongoing process to give some more insights.
IO is now also paused after the ongoing process is allocated in
get_backup to avoid needlessly pausing IO.
Notice this is targetting `stable-1.112`, feel free to disagree with that.
> ref: More logging for ongoing and get_backup

- CHANGELOG.md
- deltachat-jsonrpc/src/api/mod.rs
- deltachat-jsonrpc/src/api/types/chat.rs
- deltachat-jsonrpc/src/api/types/chat_list.rs
- deltachat-jsonrpc/typescript/example/example.ts
- deltachat-rpc-client/src/deltachat_rpc_client/account.py
- src/chatlist.rs
What?
Remove message id from chatlistentry and chatlistentry now becomes just the chat id, now the last message used by the summary is fetched when loading the chatlistitem via the chatId. This should decrease the likelihood of races when sending a message in desktop because it deletes the draft and sends a new message so a cached draft message id can result in an error blinking up such as this one:
This makes the code simpler and prevents races due to desktop caching the message id of chatlistEntries.
EDIT: I investigated a bit more about the speed, still somewhat subjective, but this is what I think I understand: scrolling/initial-load is a little bit slower (because it has more sql queries), but updating (tested with backup import) might be a bit faster because less stuff is …
> jsonrpc: remove msgId from chatlistentry (#3071)

- src/receive_imf.rs
The callers of `check_verified_properties` also add a dot, which lead to messages like `Verification problem: This message is not encrypted..`
> fix: Don't put a double dot at the end of error messages

- deltachat-jsonrpc/src/api/mod.rs
- deltachat-jsonrpc/src/api/types/message.rs
- src/message.rs
feat: api: `get_msg_read_receipts` - get the contacts that send read receipts for a message
api: jsonrpc: new `MessageReadReceipt` type and `get_message_read_receipts` jsonrpc method
Basically an api to get the info who read a message when, that is currently only accessible as 
part of the message info text.
> api to get read receipts by contacts for a message

- Cargo.lock
- Cargo.toml
- src/test_utils.rs
Add `golden_test_chat`, which takes a chat_id and a golden file that describes how the chat should look.
If e.g. the chat should be verified, but isn't, the test output looks like this: (the nice diff is thanks to `pretty_assertions`)
Using `UPDATE_GOLDEN_TESTS=1 cargo test`, you can update the golden tests.
This is in preparation for #4315; I wanted to pull out some changes to not make that PR huge. See 343c072af for a test that actually uses it.
> test: Add golden tests infrastructure

- LICENSE
- python/LICENSE
New text was downloaded from https://www.mozilla.org/en-US/MPL/, specifically https://www.mozilla.org/media/MPL/2.0/index.f75d2927d3c1.txt
The difference is that the URL is changed from http:// to https://
> chore: update MPL 2.0 license text

- src/tests/verified_chats.rs
1:1 chats are automatically created as protected if the contact is verified, there is no need to explicitly do this.
Plus, by removing this call, the test also tests that automatically creating 1:1 chats as protected works.
Follow-up for #4315
Part of #4188
> test: Remove unnecessary inner_set_protection() call

- src/chat.rs
- src/tests/verified_chats.rs
Follow-up for #4315
Part of #4188
> fix: Don't create 1:1 chat as protected for contact who doesn't prefer to encrypt

- src/chat.rs
- src/tests/verified_chats.rs
If the verification is broken, `can_send()` is false.
But if the user was typing a message right when a verification-breaking message came in, the UI still needs to be able to save it as a draft.
Steps to reproduce the bug:
- Set a draft
- Your chat partner breaks verification
- Go back to the chats list
- Go to the chat again
- Accept the breakage
- Expected: The draft is still there
- Bug behavior: The draft is gone
> fix: Allow to save a draft if the verification is broken

- Cargo.lock
- src/imex/transfer.rs
Two issues:
- the token got lost. It is a part of the request, not the connection options. So it must be added to each request.
- the provider needs to know that we want to support iroh collections
> Fix transfer test

- src/receive_imf.rs
- src/tests/verified_chats.rs
- test-data/golden/test_old_message_1
- test-data/golden/test_old_message_2
- test-data/golden/test_old_message_3
Correctly handle messages with old timestamps for verified chats:
- They must not be sorted over a protection-changed info message
- If they change the protection, then they must not be sorted over existing other messages, because then the protection-changed info message would also be above these existing messages.
This PR fixes this:
1. Even seen messages can't be sorted into already-noticed messages anymore. **This also changes DC's behavior in the absence of verified 1:1 chats**. Before this PR, messages that are marked as seen when they are downloaded will always be sorted by their timestamp, even if it's very old.
2. protection-changed info messages are always sorted to the bottom.
**Edit:**
3. There is an exception to rule 1: Outgoing messages are still allowed to be sorted purely …
> fix: Fix info-message orderings of verified 1:1 chats

- src/contact.rs
It was unused since https://github.com/deltachat/deltachat-core-rust/pull/4315, and all occurences I could find [on GitHub](https://github.com/search?q=%22is_verified_ex%22&type=code&p=1) are either forks of deltachat-core-rust or of deltachat-core (which is the old C core).
> api!(Rust): Remove unused function is_verified_ex()

- src/contact.rs
- src/tests/verified_chats.rs
If a contact's key changed since the verification, then it's very unlikely that they still have the old, verified key. So, don't show them as verified anymore.
This also means that you can't add a contact like this to a verified group, which is good.
The documentation actually already described this (new) behavior:
```rust
/// and if the key has not changed since this verification.
```
so, this adapts the code to the documentation.
> feat: Don't show a contact as verified if their key changed since the verification

- src/receive_imf/tests.rs
- src/securejoin.rs
- src/test_utils.rs
- src/tests/verified_chats.rs
Turns out that all usages of get_chat() directly unwrapped, because in a test it doesn't make sense to handle the error of there being no chat.
I had this on my computer for a while, but forgot to push. (I'm still mostly offline, but just had some IDLE time)
> test: Directly unwrap in TestContext::get_chat()

- src/chat.rs
- src/test_utils.rs
- src/tests/aeap.rs
- src/tests/verified_chats.rs
In one of the tests I wrote, I called `send_recv_accept()`, which accepted the protection-brokenness, and I spent a long time debugging this.
So, `send_recv_accept()` asserts that the chat is a request, and if a chat is not a request, accept() doesn't accept the protection-brokenness.
> test: Don't accidentally accept that a chat protection is broken

- .github/workflows/ci.yml
It can make debugging such failures easier: https://github.com/deltachat/deltachat-core-rust/actions/runs/5835594006/job/15827494064?pr=4344 . As for DCC_MIME_DEBUG, it helped me several times, but looks like it slows down running tests
> ci: Run Rust tests with RUST_BACKTRACE set

- src/receive_imf.rs
- src/tests/verified_chats.rs
- test-data/golden/test_old_message_5
If the Inbox is fetched before the Sentbox (as done currently), messages from the Sentbox will
correctly mingle with the Inbox messages in the end. So, this commit changes message ordering only
if we already have processed outgoing messages, e.g. if we just sent them in the chat as described
in https://github.com/deltachat/deltachat-core-rust/issues/4621. Otherwise new incoming messages are displayed somewhere in the middle of the chat which
doesn't look usable.
Fixes #4621
> fix: Sort old incoming messages below all outgoing ones (#4621)

- src/ephemeral.rs
- src/message.rs
- src/smtp.rs
I.e. from delete_msgs(). Otherwise messages must not be deleted from there, e.g. if a message is ephemeral, but a network outage lasts longer than the ephemeral message timer, the message still must be sent upon a successful reconnection.
> fix: Delete messages from SMTP queue only on user demand (#4579)

- src/receive_imf.rs
- src/receive_imf/tests.rs
Other MUAs don't set add/remove headers, so the only way for them to re-add us to the group is to add us to To/CC/wherever. Previously it worked only for other members that are still in the group so that they properly handled our re-addition, but we didn't.
Fixes #4624
> fix: Allow membership changes by a MUA if we're not in the group (#4624)

- src/chat.rs
- src/chatlist.rs
- src/receive_imf/tests.rs
**It's a backport from `master`.**
I.e. exclude from the list the following chats as well:
- Read-only mailing lists.
- Chats we're not a member of.
But as for ProtectionBroken chats, we return them, as that may happen to a verified chat at any time. It may be confusing if a chat that is normally in the list disappears suddenly. The UI need to deal with that case anyway.
(cherry picked from commit 83ef25e7de9c5f2ba8bbe544964aa6f7a96aaf3f)
> fix: Return from dc_get_chatlist(DC_GCL_FOR_FORWARDING) only chats where we can send (#4616)

- src/imex.rs
If the user makes a backup from a UI that supports the experimental verified 1:1 chats (e.g. nightly Android) and imports it into a UI that doesn't, then this config should be cleared.
We already talked about this a long time ago after @Simon-Laux noticed this problem, but I think we didn't actually solve it back then?
Best to review with whitespace changes disabled.
> fix: Clear VerifiedOneOnOneChats config on backup

- src/chat.rs
- src/receive_imf.rs
- src/receive_imf/tests.rs
- If we don't know the parent (=In-Reply-To) message, then completely recreate the group member list
(i.e. use the member list of the incoming message) (because we assume that we missed some messages
& have a wrong group state).
- If the message has a "Chat-Group-Member-Removed: member@example.com" header, then remove this
member.
- If the message has a "Chat-Group-Member-Added: member@example.com" header, then add this member.
That means:
- Remove checks for the presense of `ContactId::SELF` in the group. Thus all recipients of a message
take the same decision about group membership changes, no matter if they are in the group
currently. This fixes a situation when a recipient thinks it's not a member because it missed a
message about its addition before.
NOTE: But always recreate …
> fix: Switch to original Hocuri's group membership consistency algo (#3782)(#4624)

- src/pgp.rs
These constants are current defaults in `pgp` crate, this change would prevent accidental change due to rPGP upgrade and make it easier to change in a single place.
> refactor(pgp): add constants for encryption algorithm and hash

- src/receive_imf.rs
- src/receive_imf/tests.rs
https://github.com/deltachat/deltachat-core-rust/commit/9bd7ab728035f44e6155e5254bd51f38d9493c97 brings a possibility of group membership inconsistency to the original Hocuri's algo
described and implemented in https://github.com/deltachat/deltachat-core-rust/commit/e12e026bd80ea7d468e35f200011a65afc75f3ad in sake of security so that nobody can add themselves to a
group by forging "InReplyTo" and other headers. This commit fixes the problem by removing group
members locally if we see a discrepancy with the "To" list in the received message as it is better
for privacy than adding absent members locally. But it shouldn't be a big problem if somebody missed
a member addition, because they will likely recreate the member list from the next received
message. The problem occurs only if that …
> feat: Remove extra members from the local list in sake of group membership consistency (#3782)

- src/reaction.rs
- src/receive_imf.rs
- src/simplify.rs
Reactions do not have footer since 6d2ac30. However, mailing lists still add the footer to the messages, and receiver interpreted words as a reaction.
> fix: Remove footer from reactions on the receiver side (#4780)

- src/download.rs
- src/mimeparser.rs
- src/receive_imf.rs
- src/receive_imf/tests.rs
**fix: Assign encrypted partially downloaded group messages to 1:1 chat (#4757)**
Before they were trashed. Note that for unencrypted ones DC works as expected creating the requested
group immediately because Chat-Group-Id is duplicated in the Message-Id header and Subject is
fetched.
**fix: Don't update timestamp, timestamp_rcvd, state when replacing partially downloaded message (#4700)**
Also add a test on downloading a message later. Although it doesn't reproduce #4700 for some reason,
it fails w/o the fix because before a message state was changing to `InSeen` after a full download
which doesn't look correct. The result of a full message download should be such as if it was fully
downloaded initially.
> Partially downloaded messages fixes

- src/contact.rs
- src/receive_imf/tests.rs
> fix: show all contacts in Contact::get_all for bots

- python/tests/test_1_online.py
There was a recent failure of the test probably as a result of message reordering on the server: https://github.com/deltachat/deltachat-core-rust/actions/runs/6464605602/job/17549624095?pr=4813.
> test: test_qr_new_group_unblocked(): W/a message reordering on server

- deltachat-ffi/deltachat.h
- python/tests/test_0_complex_or_slow.py
- src/config.rs
- src/context.rs
- src/mimefactory.rs
**feat: Make gossip period configurable (#4346)**
This is needed to test periodic re-gossiping in existing chats.
Also add a test for verified groups on that even if "member added" message is missed by a device of
newly added member, after re-gossiping Autocrypt keys to the group it successfully learns these keys
and marks other members as verified.
> Test that unverified contact can become verified via gossip in existing group (#4346)

- deltachat-jsonrpc/src/api/mod.rs
- src/blob.rs
- src/chat.rs
- src/message.rs
- src/param.rs
This approach uses a param field to enable forcing the sticker `viewtype`. The first commit has the memory-only flag implemented, but this flag is not persistent through the database conversion needed for draft/undraft. That's why `param` has to be used.
follow up to #4814 
fixes #4739
> api(json-rpc): force stickers to be sent as stickers

- src/contact.rs
- src/message.rs
- src/mimeparser.rs
- src/receive_imf.rs
- src/sql/migrations.rs
> feat: add bot field to contact

- deltachat-ffi/deltachat.h
- deltachat-jsonrpc/src/api/mod.rs
- src/chat.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/receive_imf.rs
feat: Make broadcast lists create their own chat - UIs need to ask for the name when creating broadcast lists now (see https://github.com/deltachat/deltachat-android/pull/2653)
That's quite a minimal approach: Add a List-ID header to outgoing broadcast lists, so that the receiving Delta Chat shows them as a separate chat, as talked about with @r10s and @hpk42. I know that @adbenitez will love it :)
To be done in other PRs:
Fixes https://github.com/deltachat/deltachat-core-rust/issues/4597
BREAKING CHANGE: This means that UIs need to ask for the name when creating a broadcast list, similar to https://github.com/deltachat/deltachat-android/pull/2653.
> feat: Make broadcast lists create their own chat

- deltachat-ffi/deltachat.h
in fact, it was already used like that,
eg. to detect an AEAP change on android.
but it was never documented officially.
> document `configured_addr`

- src/tools.rs
close #4620 
This PR introduces a new core API to parse mailto links into a uniform data format. This could be used to unify the different implementations on the current platforms.
To complete this PR we have to decide for which APIs we want to expose this (now) internal API (c, python, json-rpc,  etc.), and if we want such an API at all as it doesn't have a corresponding UI-PR and is not _really_ needed.
> api: add mailto parse api

- deltachat-jsonrpc/src/api.rs
- deltachat-jsonrpc/src/api/types/message.rs
- src/message.rs
~~I couldn't find where `Param::ErroneousE2ee` is set or what format it is, so this is still todo. Because I would like to show the 
state when TB enrypted but did not sign the message correctly, so we can point people to a FAQ article on how to solve it.~~
link2xt told me `Param::ErroneousE2ee` is not set anymore, so let's postpone the e2e encryption errors and let this pr just address #4556.
closes #4556
> api(jsonrpc): add get_message_info_json

- python/tests/test_1_online.py
- src/securejoin.rs
Fixes  #4894 
so that a "left-over" bobstate does not block a receiver of a MemberAdded message from adding the member if it was added through an unrelated secure-join process (i.e. the receiver was not the member being added through the secure-join protocol)
> properly add a member triggered by unrelated secure-join protocol

- src/chat.rs
documentation and reasoning is fully in `delete_chat()`, the remove line does not add much to it, also, the hint to "above" is wrong.
> remove comment pointing to nothing

- src/net.rs
This is a follow-up for #4921 
If more users report errors like https://support.delta.chat/t/no-dns-resolution-result/2778 from environments with bad DNS, we will be able to hardcode fallback as well.
> refactor: add hostname to "no DNS resolution results" error message

- src/imap/idle.rs
This prevents accidentally going IDLE
when the last new message has arrived
while the folder was closed.
For example, this happened in some tests:
1. INBOX is selected to fetch, move and delete messages.
2. One of the messages is deleted.
3. INBOX is closed to expunge the message.
4. A new message arrives.
5. INBOX is selected with (CONDSTORE) to sync flags.
6. Delta Chat goes into IDLE without downloading the new message.
To determine that a new message has arrived
we need to notice that UIDNEXT has advanced when selecting the folder. However, some servers such as Winmail Pro Mail Server 5.1.0616 do not return UIDNEXT in response to SELECT command.
To avoid interdependencies with the code
SELECTing the folder and having to implement
STATUS fallback after each SELECT even when we
may not …
> fix: check UIDNEXT with a STATUS command before going IDLE

- deltachat-rpc-client/src/deltachat_rpc_client/rpc.py
- deltachat-rpc-client/tox.ini
This is necessary to debug the tests.
> test(deltachat-rpc-client): log all events as debug messages

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- deltachat-jsonrpc/src/api/types/contact.rs
- deltachat-rpc-client/tests/test_securejoin.py
- src/chat.rs
- src/contact.rs
this pr keeps and refines documentation added in #4951, however, reverts the api introduced by #4951
which turns out to be not useful for UI in practise:
UI anyway check for chat/no-chat beforehand,
so a simple condition in profiles as
`green_checkmark = chat_exist ? chat_is_protected() : contact_is_verified()`  
is more useful in practise and is waht UI need and did already in the past. (https://github.com/deltachat/deltachat-android/pull/2836 shows a detailed discussion)
(as a side effect, beside saving code,
this PR saves up to three database calls
(get contact from chat in UI to pass it to profile_is_verified(), get chat from contact in core, load is_protected in core) - instead, core can use already is_protected from already loaded chat object)
/me did check rust-tests, fingers …
> back to two verification-check functions

- src/mimefactory.rs
List-ID header is added for broadcast lists.
UTF-8 in email headers is allowed only if
all recipient MTAs support SMTPUTF8 extension,
which is not always the case even if our submission service reports SMTPUTF8 support.
Fixes #4969
> fix: encode chat name in the List-ID header

- src/chat.rs
- src/contact.rs
- src/receive_imf.rs
- src/securejoin.rs
- src/sync.rs
See commit messages. I'd like also to implement:
- DONE: Sync of chat names.
- DONE: Fix of the bug described in https://github.com/deltachat/deltachat-core-rust/issues/4953#issuecomment-1805032415.
- Sync of chats removal (this one is definitely in another PR).
UPD: Actually https://github.com/deltachat/deltachat-core-rust/issues/4953#issuecomment-1805032415 isn't a bug, but just a missed feature. Done.
> Sync broadcast lists (#4953)

- src/scheduler/connectivity.rs
The returned error is unexpected and no UI, that I tested with stoped IO, really handled it, besides maybe displaying a toast.
(desktop and iOS do not handle the error, deltatouch shows a toast, all tested UIs show an empty/blank space where the connectivity view should be)
This should not be shown to the user normally, it is only shown to the user, if the UI has a bug, so that bug should be clearly visible.
Now wit this pr looks like this (screenshot from desktop):
CC @lk108
> fix: return connectivity html even when IO is stopped.

- Cargo.lock
> fix: update async-imap to 0.9.4 which does not ignore EOF on FETCH

- deltachat-ffi/deltachat.h
- deltachat-jsonrpc/src/api.rs
- deltachat-rpc-client/src/deltachat_rpc_client/account.py
- src/securejoin.rs
We forked the countermitm to https://github.com/deltachat/securejoin/ and are low in the process of making it reflect the current sate of what is actually implemented in DC.
> docs: Update securejoin links

- src/imex.rs
- src/key.rs
- src/mimeparser.rs
Before a keyring with the only default key was used, i.e. the key used for signing and encrypting to self.
Fixes #5046
> fix: Use keyring with all private keys when decrypting a message (#5046)

- src/imap.rs
Limit the number of IMAP connections to 1 per minute regardless of the reason of reconnection, but allow one immediate retry. This is more reliable than ratelimiting only in error conditions because ratelimiting can't be skipped by mistake. Anyway connections shouldn't be frequent in normal operation mode.
Close #4940
> feat: Ratelimit IMAP connections (#4940)

- src/mimeparser.rs
- src/peerstate.rs
- src/receive_imf.rs
- src/receive_imf/tests.rs
- test-data/message/thunderbird_encrypted_unsigned_with_unencrypted_subject.eml
If a message is encrypted, but unsigned:
- Don't set `MimeMessage::from_is_signed`.
- Remove "secure-join-fingerprint" and "chat-verified" headers from `MimeMessage`.
- Minor: Preserve "Subject" from the unencrypted top level if there's no "Subject" in the encrypted
part, this message is displayed w/o a padlock anyway.
Apparently it didn't lead to any vulnerabilities because there are checks for
`MimeMessage::signatures.is_empty()` in all necessary places, but still the code looked dangerous,
especially because `from_is_singed` var name didn't correspond to its actual value (it was rather
`from_is_encrypted_maybe_signed`).
> feat: Don't affect MimeMessage with "From" and secured headers from encrypted unsigned messages

- src/accounts.rs
`lock_task` is anyways always `None` on iOS
to avoid lock files held open and cause 0xdead10cc crashes.
not sure if that is a "good rust way" for handling things, however, it works - feel free to improve or change and take over this PR if neeed
successor of https://github.com/deltachat/deltachat-core-rust/pull/5081 and https://github.com/deltachat/deltachat-core-rust/pull/4314
closes #5083
> fix: do not check `lock_task` on iOS before syncing

- src/chat.rs
- src/message.rs
- src/receive_imf.rs
Ad-hoc groups don't have grpid-s that can be used to identify them across devices and thus wasn't synced until now.
The same problem already exists for assigning messages to ad-hoc groups and this assignment is done by `get_parent_message()` and `lookup_chat_by_reply()`. Let's reuse this logic for the synchronisation, it works well enough and this way we have less surprises than if we try to implement grpids for ad-hoc groups. I.e. add an `Msgids` variant to `chat::SyncId` analogous to the "References" header in messages and put two following Message-IDs to a sync message:
- The latest message A having `DownloadState::Done` and the state to be one of `InFresh, InNoticed, InSeen, OutDelivered, OutMdnRcvd`.
- The message that A references in `In-Reply-To`.
This way the logic is almost the …
> feat: Sync user actions for ad-hoc groups across devices (#5065)

- src/chat.rs
- src/mimeparser.rs
- src/receive_imf.rs
- src/securejoin.rs
- src/securejoin/bob.rs
There's no test yet, verified by hand only. Need to come up with more simple scenario than in #5088.
Fixes #5088
> Fixes to the sort timestamp of messages

- src/receive_imf.rs
- src/securejoin.rs
- src/securejoin/bob.rs
As per the comment in `receive_imf.rs`, `chat.protected` must be maintained regardless of the
`Config::VerifiedOneOnOneChats`. The only thing that mustn't be done if `VerifiedOneOnOneChats` is
unset (i.e. for non-supporting UIs) is marking chats as "protection broken" because this needs
showing the corresponding dialog to a user.
> fix: Securejoin: Mark 1:1s as protected regardless of the Config::VerifiedOneOnOneChats

- src/chat.rs
- src/mimefactory.rs
- src/receive_imf.rs
- src/receive_imf/tests.rs
- test-data/message/messed_up_message_id.eml
Put a copy of Message-ID into hidden headers and prefer it over the one in the IMF header section
that servers mess up with.
Fixes #4798
> fix: Put Message-ID into hidden headers and take it from there on receiver (#4798)

- src/receive_imf.rs
The bug was made in 44227d7b866f4aa173c63ffc989f38b44774e40d. Sql::execute() with placeholders must be used to escape strings, one never should escape them manually as strings themselves can contain escape symbols. Thanks to @link2xt for noticing.
> fix: Properly escape `target` in receive_imf_inner()

- src/chat.rs
- src/constants.rs
- src/message.rs
- src/receive_imf.rs
- src/smtp.rs
- src/smtp/send.rs
- src/sql/migrations.rs
a27e84ad8909a03fb1fb49fec719fadee06d692f "fix: Delete received outgoing messages from SMTP queue" can break sending messages sent as several SMTP messages because they have a lot of recipients: `pub(crate) const DEFAULT_MAX_SMTP_RCPT_TO: usize = 50;`
We should not cancel sending if it is such a message and we received BCC-self because it does not mean the other part was sent successfully. For this, split such messages into separate jobs in the `smtp` table so that only a job containing BCC-self is canceled from `receive_imf_inner()`. Although this doesn't solve the initial problem with timed-out SMTP requests for such messages completely, this enables fine-grained SMTP retries so we don't need to resend all SMTP messages if only some of them failed to be sent.
Close #5115
> fix: Split SMTP jobs already in `chat::create_send_msg_jobs()` (#5115)

- src/message.rs
- src/receive_imf/tests.rs
@link2xt
> Maybe error state should be reset immediately when "resend" is clicked and not when message is delivered? That would simplyify the code/test even.
I don't see how it can simplify the code, it only adds a couple of additional checks to the test, but overall the suggestion is very reasonable.
Fix #5119
> fix: Reset message error when scheduling resending (#5119)

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- deltachat-jsonrpc/src/api/types/events.rs
- src/config.rs
- src/events/payload.rs
Add an event for a case if a multi-device synced config value changed. Maybe the app needs to refresh smth on such an event. For uniformity it is emitted on the source device too. The value is omitted, otherwise it would be logged which might not be good for privacy.
Needed for https://github.com/deltachat/deltachat-desktop/issues/3624
> feat: Add ConfigSynced event

- src/scheduler.rs
Send `EventType::ConnectivityChanged` when using the context methods `start_io` and `stop_io`.
close #5097
> fix: emit events more reliable when starting and stopping io #5097

- src/mimefactory.rs
This PR stops MDNs from being forced to be sent unencrypted. 
If no encryption is possible (by `should_encrypt`), the fix #5152 still applies.
close #5168
> feat: Encrypt MDNs #5168

- python/src/deltachat/testplugin.py
- python/tests/test_1_online.py
- src/chat.rs
fixes #5123 
~~the test passes actually, I think it's not the same problem the teams-bot has.~~ seems the test fails for the right reasons now :)
> fix forwarding messages from encrypted to unencrypted chat without creating a new message object

- node/lib/deltachat.ts
- node/test/test.mjs
- package.json
> fix(node): run tests with native ESM modules instead of `esm`

- deltachat-ffi/deltachat.h
in #5161, it was forgotten to adapt deltachat.h;
moreover, this PR tweaks some other minor things.
a general note: jsonrpc-only is fine for _completely new_ api (reactions, http-get ..); _existing_ api need maintenance for android/ios/unbuntu-touch
> add missing 'unencrypted message' defines

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- deltachat-jsonrpc/src/api/types/contact.rs
@adbenitez wants this feature on Deltalab to display a bot tag. 
Other UIs might also want to adopt this feature :)
> feat(api): Add `is_bot` to cffi and jsonrpc

- src/mimefactory.rs
- src/receive_imf.rs
- src/receive_imf/tests.rs
> fix: No new chats for MDNs with alias (#5196)

- src/qr.rs
> fix: add tolerance for macOS and iOS changing # to %23

- src/message.rs
- src/mimeparser.rs
- src/param.rs
- src/receive_imf.rs
- src/receive_imf/tests.rs
> fix: Treat only "Auto-Submitted: auto-generated" messages as bot-sent (#5213)

- src/dehtml.rs
If `escaper::decode_html_buf_sloppy()` just truncates the text (which happens when it fails to html-decode it at some position), then it's probably not HTML at all and should be left as is. That's what happens with hyperlinks f.e. and there was even a test on this wrong behaviour which is fixed now. So, now hyperlinks are not truncated in messages and should work as expected.
Fixes #5223
> fix: dehtml: Don't just truncate text when trying to decode (#5223)

- src/mimeparser.rs
- src/peerstate.rs
- src/receive_imf.rs
- src/securejoin.rs
I don't think it's feasible to write a test for this.
> fix: Mark the gossip keys from the message as verified, not the ones from the db

- src/ephemeral.rs
This should fix most of the failures of `test_verified_group_vs_delete_server_after()`. But sometimes it fails in a different way, maybe we have some race in IMAP handling (see https://github.com/deltachat/deltachat-core-rust/issues/5201#issuecomment-1915239566), so let's leave the issue open for now.
EDIT: Looks like this should be tested in the Rust test `test_delete_expired_imap_messages()`.
> fix: Guarantee immediate message deletion if delete_server_after == 0 (#5201)

- src/mimeparser.rs
We must finish what was started in
https://github.com/deltachat/deltachat-core-rust/issues/5088.
> fix: Never allow a message timestamp to be a lot in the future

- deltachat-jsonrpc/src/api.rs
- src/config.rs
- src/context.rs
- src/peerstate.rs
Part of https://github.com/deltachat/deltachat-android/issues/2909
For now, this is only sending a few basic metrics.
Also, it's sending to `self_reporting@testrun.org`, but this account doesn't exist yet. I know nothing about Promotheus, so, I'll need some help with this from @link2xt or so - alternatively, I can create a very simple bot myself (that doesn't use Promotheus).
> Basic self-reporting, core part

- src/config.rs
Before it was emitted only on the source device and `test_sync()` didn't catch the bug because of the interference of the previous call to `set_config_bool()`. Now there's a separate test that does its job well.
Needed for https://github.com/deltachat/deltachat-desktop/issues/3624
> fix: Emit ConfigSynced event on the second device

- node/test/test.mjs
- src/config.rs
- src/context.rs
- src/mimeparser.rs
- src/receive_imf.rs
- src/receive_imf/tests.rs
- src/stock_str.rs
- test-data/message/thunderbird_encrypted_signed.eml
>  feat: Add device message about outgoing undecryptable messages (#5164)

- deltachat-ffi/deltachat.h
- deltachat-jsonrpc/src/api.rs
- deltachat-repl/src/main.rs
- python/tests/test_1_online.py
- src/authres.rs
- src/chat.rs
- src/config.rs
- src/configure.rs
- src/constants.rs
- src/contact.rs
- src/context.rs
- src/imap.rs
- src/imap/scan_folders.rs
- src/message.rs
- src/qr.rs
- src/qr/dclogin_scheme.rs
- src/quota.rs
- src/receive_imf.rs
- src/scheduler.rs
- src/sql.rs
- src/sql/migrations.rs
> Context::set_config(): Restart IO scheduler if needed (#5111)

- src/chat.rs
- src/constants.rs
- src/contact.rs
- src/context.rs
- src/imap/idle.rs
- src/imap/scan_folders.rs
- src/imex.rs
- src/imex/transfer.rs
- src/key.rs
- src/location.rs
- src/quota.rs
- src/scheduler.rs
- src/smtp.rs
- src/smtp/send.rs
- src/tools.rs
> fix: Use SystemTime instead of Instant everywhere

- src/key.rs
- src/sql/migrations.rs
PR #5099 removed some columns in the database that were actually in use.
usually, to not worsen UX unnecessarily
(releases take time - in between, "Add Second Device", "Backup" etc. would fail), we try to avoid such schema changes (checking for db-version would avoid import etc. but would still worse UX),
see discussion at #2294.
these are the errors, the user will be confronted with otherwise:
it is not great to maintain the old columns, but well :)
as no official releases with newer cores are rolled out yet, i think, it is fine to change the "107" migration
and not copy things a second time in a newer migration.
(this issue happens to me during testing, and is probably also the issue reported by @lk108 for ubuntu-touch)
> do not change db schema in an incompatible way

- Cargo.lock
- Cargo.toml
- deltachat-time/Cargo.toml
- deltachat-time/src/lib.rs
- src/chat.rs
- src/contact.rs
- src/context.rs
- src/ephemeral.rs
- src/securejoin.rs
- src/sql.rs
- src/sync.rs
- src/tests/verified_chats.rs
- src/timesmearing.rs
- src/tools.rs
> feat: Mock SystemTime::now() for the tests

- src/imap.rs
If a folder is named "Trash" or like this, it should be recognised as such even if it does not have a \Trash attribute.
Close #5275
> feat: Recognise Trash folder by name (#5275)

- src/mimefactory.rs
- src/mimeparser.rs
Before group avatar was sent as an attachment. Let's do the same as with user avatar and send group avatar as base64. Receiver code uses the same functions for user and chat avatars, so base64 avatars are supported for most receivers already.
Close #5253
> feat: Send Chat-Group-Avatar as inline base64 (#5253)

- src/config.rs
- src/contact.rs
Sync messages should only be sent in response to user actions.
Fix #5289
> fix: Don't send sync messages on self-{status,avatar} update from self-sent messages (#5289)

- python/src/deltachat/account.py
- python/src/deltachat/events.py
- python/src/deltachat/testplugin.py
- python/tests/test_1_online.py
The way it was implemented it threw out all remaining messages after finding the next incoming message. Better use FFIEventTracker functions, they are used in all the tests anyway.
Close #5207 
Not sure this actually fixes the problem, but quite possible. Let's see if this helps.
> test: get_protected_chat(): Use FFIEventTracker instead of dc_wait_next_msgs() (#5207)

- src/mimeparser.rs
- src/receive_imf/tests.rs
If Subject is multiline-formatted, `mailparse` adds the leading whitespace to it. The solution is to always remove the leading whitespace, because if Subject isn't multiline-formatted, it never contains the leading whitespace anyway. But as for the trailing whitespace -- i checked -- it's never removed, so let's keep this as is.
Fix #5106
> fix: Remove leading whitespace from Subject (#5106)

- src/decrypt.rs
- src/peerstate.rs
- src/securejoin.rs
- src/sql.rs
- src/tests/aeap.rs
This is aimed to solve the @adbenitez's problem with sharing the same key by several accounts.
> fix: Create new Peerstate for unencrypted message with already known Autocrypt key, but a new address

- src/config.rs
- src/scheduler.rs
> feat: Start IMAP loop for sentbox only if it is configured (#5105)

- CHANGELOG.md
no idea, how that sneaked in :)
@lk108 thanks for noticing!
> fix: remove duplicate CHANGELOG entries for 1.135.1

- src/chat.rs
- src/mimefactory.rs
- src/receive_imf/tests.rs
`Param::MemberListTimestamp` was updated only from `receive_imf::apply_group_changes()` i.e. for received messages. If we sent a message, that timestamp wasn't updated, so remote group membership changes always overrode local ones. Especially that was a problem when a message is sent offline so that it doesn't incorporate recent group membership changes.
> fix: Update MemberListTimestamp when sending a group message

- src/sql.rs
this PR fixes one of the issues we had with an (honestly accidentally) huge database of >2gb.
this database could not be exported on iOS, as ram memory is limited there, leading to the app just crashing.
it is unclear if that would be better on eg. Android, however, temp_store=FILE is not working as well there, this is the smaller drawback there.
before merging, this PR should be tested on time with export/import on iOS (export/import uses VACUUM which uses /tmp) EDIT: did so, works on iphone7 with ios15
> fix: on iOS, use FILE (default) instead of MEMORY

- src/context.rs
as turned out on recent researches wrt a slow database, setting `save_mime_headers` will result in 25x larger databases.
this is definetely something we want to know at least in the debug info.
(the option cannot be enabled in current UIs,
however, esp. devs find options to set this.
apart from that, save_mime_headers is only used in some python tests)
ftr: the huge database was more than 10 times slower, leading to missing notifications on ios (as things do not finish within the few seconds iOS gave us).
moreover, the hugeness also avoids exporting; this is fixed by https://github.com/deltachat/deltachat-core-rust/pull/5349
> add `save_mime_headers` to debug info

- src/dehtml.rs
this PR fixes a bug that lowercases all links handleld by `dehtml()`, which is wrong.
closes #5361
> fix: preserve upper-/lowercase of links parsed by `dehtml()`

- python/tests/test_1_online.py
- src/config.rs
The test still doesn't check the threads themselves, but it looks not bad to have at least the mentioned check.
> fix: Rescan folders after changing Config::SentboxWatch

- src/receive_imf/tests.rs
the rendered time output seems different on different systems and timezomes, eg. on my local machine, it is
`Sent: 2024.03.20 10:00:01 ` and not `Sent: 2024.03.20 09:00:01`, maybe because of winter/summer time, idk.
as the gist of the test is to check the name,
however, i just removed the whole time check.
> test: Remove flaky time check from test_list_from()

- python/tests/test_0_complex_or_slow.py
- src/chat.rs
- src/mimefactory.rs
> fix: Don't send selfavatar in SecureJoin messages before contact verification (#5354)

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- node/src/module.c
- src/accounts.rs
- src/scheduler/connectivity.rs
it was used by iOS to know when a background fetch was complete; meanwhile the superiour `dc_accounts_background_fetch()` is used for that.
there is still the corresponding context function `dc_all_work_done()`, this not used by any UI as well, however, it is in use by a python tests.
not sure, what to do with it, at a first glance, the test still seems useful.
> api: remove unused `dc_accounts_all_work_done()`

- deltachat-repl/src/cmdline.rs
- src/param.rs
- src/sql.rs
this PR does some cleanup on `jobs` and `Params`:
- the `jobs` table is no longer in use, no need to track files on housekeeping, no need to clear it from repl tool
- some `Params` were used for jobs table only, they can be used freely for other purposes on other tables. param 'protection settings timestamp' was never used in practise, its code is removed as well, so we can free the Param as well.
> cleanup `jobs` and `Params` relicts

- src/reaction.rs
- src/receive_imf.rs
this PR sets correct `chat_id` for `DC_EVENT_REACTIONS_CHANGED` events.
detection of correct chat-id went wrong sometimes somewhere deep inside `receive_imf()`, i tried the most less intrusive fix (changing `is_probably_private_reply()`, see commit message for details) with probably few side effects, as changing too many things in `receive_imf()` with good chance raises other issues :)
also, it the `is_probably_private_reply()` seems to be really the cause, changing `receive_imf()` in a way that without  `allow_creation` the correct chat is still returned may be an alternative, however, feels wrong as it works around somehow and seems not be needed otherwise. also, it would need a deeper understanding of `receive_imf()` where i currently do not have the mindset for :)
closes #5418
> fix: always set correct `chat_id` for `DC_EVENT_REACTIONS_CHANGED`

- deltachat-ffi/deltachat.h
- src/chatlist.rs
- src/message.rs
- src/param.rs
- src/reaction.rs
- src/receive_imf.rs
- src/stock_str.rs
- src/summary.rs
this PR **shows the last reaction in chatlist's summaries if there is no newer message.** 
the reason to show reactions in the summary, is to make them a _little_ more visible when one is not in the chat. esp. in not-so-chatty or in one-to-ones chats this becomes handy: imaging a question and someone "answers" with "thumbs up" ... 🥚
otoh, reactions are still tuned down on purpose: no notifications, chats are opend as usual, the chatlist is not sorted by reactions and also the date in the summary refer to the last message - i thought quite a bit about that, this seems to be good compromise and will raise the fewest questions. it is somehow clear to the users that reactions are not the same as a real message. also, it is comparable easy to implement - **no UI changes required :)**
all that …
> feat: show reactions in summaries

- src/reaction.rs
- src/summary.rs
this PR makes reaction summaries shorter and more on-point.
as we do not show the author of the original message in the reaction summary, it does not make sense to show the even more common "Forwarded" string there.
this is esp. useful as there is few space anyways and the summaries need to be short.
so, instead of showing `Alice reacted 👍 to "Forwarded: G...` we can show `Alice reacted 👍 to "Great image"`
this does not affect all the other places where the forwarded prefix is shown and very useful (eg. to make sure it does not look as if the forwarder said sth theirself).
moreover, this PR adds tests wrt forwarding messages and reactions in general, eg. making sure, reactions are not forwarded.
successor of #5387
> feat: on-point reaction summaries, improve tests

- src/message.rs
- src/reaction.rs
we [checked for tombstones already using `is_trash()`](https://github.com/deltachat/deltachat-core-rust/pull/5387/files#diff-0f1f65bfdc551eeaa293befb40ac1d6c8b3eadaa142d2f7b88f5af9ea30f210cR352), however, we've overseen that tombstones get deleted at some point :)
therefore, just do not treat loading failures of the weak msg_id as errors - usually, they are not - and if, just the normal summary is shown. in theory, we could check for existence explicitly before trying load_from_db, however, that would be additional code (and maybe another database call) and not worth the effort.
anyways, this commit also adds an explicit test
for physical deletion after housekeeping.
> fix: do not show empty summary if message reacted to is deleted

- src/reaction.rs
- src/receive_imf.rs
- src/receive_imf/tests.rs
Instead, look up the 1:1 chat in `receive_imf::add_parts()`. This is a more generic approach to fix assigning outgoing reactions to 1:1 chats in the multi-device setup. Although currently both approaches give the same result, this way we can even implement a "react privately" functionality. Maybe it sounds useless, but it seems better to have less reaction-specific code.
> refactor: is_probably_private_reply: Remove reaction-specific code

- src/chatlist.rs
- src/message.rs
- src/summary.rs
this PR fixes a bug in `Message::get_summary()`, that must not return reaction summary. the PR introduces an explicit function when a reaction summary is really wanted.
the bug was introduced by https://github.com/deltachat/deltachat-core-rust/pull/5387 and is not part of any official release.
closes https://github.com/deltachat/deltachat-core-rust/issues/5437
> fix: `Message::get_summary()` must not return reaction summary

- src/contact.rs
- src/events/payload.rs
- src/scheduler.rs
- src/test_utils.rs
- Always emit `ContactsChanged` from `contact::update_last_seen()` if a contact was seen recently just for simplicity and symmetry with `RecentlySeenLoop::run()` which also may emit several events for single contact.
- Fix sleep time calculation in `RecentlySeenLoop::run()` -- `now` must be updated on every iteration, before the initial value was used every time which led to progressively long sleeps.
Fix #5377 
EDIT: I took @Simon-Laux's test from https://github.com/deltachat/deltachat-core-rust/tree/simon/i5377-test-for-recently-seen and modified it a little.
> fix: Fix emitting ContactsChanged events on "recently seen" status change (#5377)

- src/chat.rs
- src/constants.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/receive_imf.rs
- src/receive_imf/tests.rs
- src/test_utils.rs
- test-data/golden/chat_test_msg_with_implicit_member_add
- test-data/golden/chat_test_parallel_member_remove
> fix: Add tolerance to MemberListTimestamp (#5366)

- src/debug_logging.rs
- src/ephemeral.rs
- src/webxdc.rs
If `delete_device_after` is configured, that period should be counted for webxdc instances from the last status update, otherwise nothing prevents from deleting them. Use `msgs.timestamp_rcvd` to store the last status update timestamp, it anyway isn't used for anything except displaying a detailed message info. Also, as `ephemeral::select_expired_messages()` now also checks `timestamp_rcvd`, we have an improvement that a message is guaranteed not to be deleted for the `delete_device_after` period since its receipt. Before only the sort timestamp was checked which is derived from the "sent" timestamp.
Fix #5365
> fix: Keep webxdc instance for delete_device_after period after a status update (#5365)

- src/chat.rs
- src/configure.rs
- src/imap.rs
- src/login_param.rs
- src/mimeparser.rs
- src/peerstate.rs
- src/receive_imf.rs
`a.clone_from(&b)` is equivalent to `a = b.clone()` in functionality, but can be overridden to reuse the resources of a to avoid unnecessary allocations.
> fix: use clone_from()

- python/tests/test_1_online.py
- src/imap/scan_folders.rs
- src/scheduler.rs
This fixes things for Gmail f.e. Before, `Imap::fetch_move_delete()` was called before looking for Trash and returned an error because of that failing the whole `fetch_idle()` which prevented configuring Trash in turn.
EDIT: Haven't yet tested it. The bug was reported to me by a Gmail user.
EDIT: The user said also that they don’t like that this critical error also wasn't perceived by the app and reported to the user. Probably we need to report such errors somehow.
EDIT: Going to add a Python test on this... DONE.
> fix: Don't try to do fetch_move_delete() if Trash is needed but not yet configured

- .github/workflows/ci.yml
Nextest doesn't run doc tests, so we need to run them with `cargo test --workspace --doc`.
See https://github.com/nextest-rs/nextest/issues/16
Follow-up for #5457
> ci: Run doc tests with cargo test --workspace --doc

- Cargo.lock
- Cargo.toml
- deltachat-contact-tools/Cargo.toml
- deltachat-contact-tools/src/lib.rs
- deltachat-contact-utils/Cargo.toml
- deltachat-contact-utils/src/lib.rs
- src/authres.rs
- src/chat.rs
- src/config.rs
- src/configure.rs
- src/contact.rs
- src/decrypt.rs
- src/imap.rs
- src/imex.rs
- src/key.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/peerstate.rs
- src/pgp.rs
- src/provider.rs
- src/qr.rs
- src/qr/dclogin_scheme.rs
- src/reaction.rs
- src/receive_imf.rs
- src/scheduler/connectivity.rs
- src/securejoin.rs
- src/sql/migrations.rs
- src/test_utils.rs
- src/tools.rs
- src/webxdc.rs
I would like to implement
https://github.com/deltachat/deltachat-core-rust/issues/5422 in its own crate, but it will depend on some functions that are in the `deltachat` crate.
So, this PR extracts these functions into its own crate so that I can add https://github.com/deltachat/deltachat-core-rust/issues/5422 into the new crate.
> Split off functional contact tools into its own crate

- src/mimeparser.rs
- src/webxdc.rs
Webxdc status update messages are always "Auto-Submitted: auto-generated", so they must be excluded for is_bot flag calculation.
> fix: Don't set is_bot for webxdc status updates (#5445)

- src/contact.rs
Until the issue is fixed, keep others from running into the same issue.
> test: Explain test_was_seen_recently false-positive and give workaround instructions

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- deltachat-jsonrpc/src/api.rs
- src/blob.rs
- src/imex/transfer.rs
- src/message.rs
- src/receive_imf/tests.rs
This is moved out of #4583 for easier reviewing.
> api: Add dc_msg_save_file() which saves file copy at the provided path (#4309)

- deltachat-rpc-client/examples/echobot.py
- deltachat-rpc-client/examples/echobot_advanced.py
- deltachat-rpc-client/examples/echobot_no_hooks.py
- deltachat-rpc-client/tox.ini
- python/tox.ini
We use `ruff` anyway, so it is one less dependency.
> ci: replace `black` with `ruff format`

- src/chat.rs
this PR checks if the quotes are used in a reasonable way:
- quoted messages should be send to the same chat
- or to one-to-one chats
if the quote's chat ID is not the same than the sending chat _and_ the sending chat is not a one-to-one chat, sending is aborted.
usually, the UIs does not allow quoting in other ways, so, this check is only a "last defence line" to avoid leaking data in case the UI has bugs, as recently in https://github.com/deltachat/deltachat-android/issues/3032
@iequidoo @link2xt @adbenitez i am not 100% sure about this PR, maybe i've overseen a reasonable usecase where other quotes make sense
> limit quote replies

- src/chat.rs
- src/config.rs
- src/contact.rs
- src/ephemeral.rs
- src/message.rs
E.g. the multi-device synchronisation creates the "Saved Messages" chat as blocked, in this case the chat icon wasn't updated before and the user avatar was displayed instead.
Fix #5509 
EDIT: In the most other places `ChatIdBlocked`'s method must be used as well, fixed them too.
> fix: Update special chats icons even if they are blocked (#5509)

- Cargo.lock
- deltachat-contact-tools/src/lib.rs
- deltachat-ffi/deltachat.h
- deltachat-jsonrpc/Cargo.toml
- deltachat-jsonrpc/src/api.rs
- deltachat-jsonrpc/src/api/types/contact.rs
- deltachat-jsonrpc/src/api/types/message.rs
- src/color.rs
- src/lib.rs
- src/message.rs
- src/mimeparser.rs
- src/receive_imf/tests.rs
- src/stock_str.rs
- src/summary.rs
> api: Add Viewtype::Vcard and parse_vcard()

- deltachat-rpc-server/npm-package/.gitignore
- deltachat-rpc-server/npm-package/scripts/make_local_dev_version.py
- deltachat-rpc-server/npm-package/scripts/update_optional_dependencies_and_version.js
typescript was complaining about missing `@deltachat/jsonrpc-client` when it wasn't installed locally
> fix: rpc npm: fix local desktop development

- deltachat-jsonrpc/src/api.rs
closes #5533
adds the functions that were still missing for migration to jsonrpc (the ones that the cffi already had, so just should be quick to review ;)
> jsonrpc: add api `migrate_account` and `get_blob_dir`

- src/sql/migrations.rs
- **fix: db migration version 59, it contained an sql syntax error**
- **fix: sql syntax error in db migration 27**
The sql commands contained syntax errors.
> fix: db migration 59 and 27

- deltachat-rpc-server/npm-package/README.md
- deltachat-rpc-server/npm-package/index.d.ts
- deltachat-rpc-server/npm-package/index.js
- deltachat-rpc-server/npm-package/src/const.js
- **fix: npm rpc: set default options for `startDeltaChat`**
- **api!(npm rpc server): change api: don't search in path unless `options.takeVersionFromPATH` is set to `true`**
> npm rpc server don't search path by default

- src/blob.rs
> test: Viewtype::File attachments are sent unchanged and preserve extensions

- src/peerstate.rs
- src/tests/aeap.rs
When doing an AEAP transition, we mustn't just delete the old peerstate as this would break encryption to it. This is critical for non-verified groups -- if we can't encrypt to the old address, we can't securely remove it from the group (to add the new one instead).
I think this is the minimal fix making encryption to the old address and unverified groups continue to work as it was before b6db0152b0ef0e0e317a5520b966315664ebc84c.
Fix #5535
> fix: AEAP: Remove old peerstate verified_key instead of removing the whole peerstate (#5535)

- src/sql/migrations.rs
This should speed up `get_msg_reactions()` filtering reactions by `msg_id`, but also queries in
other places involving both `msg_id` and `contact_id`.
Close #5507
> feat: Add a db index for reactions by msg_id (#5507)

- standards.md
came over that missing bit when re-reading https://delta.chat/en/2024-05-31-instant-onboarding#new-introduce-a-contact-to-chat-partners :)
> add vCard as supported standard

- src/configure.rs
`IsChatmail` is set also by `inbox_fetch_idle()`, but it isn't called during `configure()`. Setting `IsChatmail` from `inbox_fetch_idle()` is necessary to handle client/server upgrades, but `IsChatmail` also should be available for the app after configuring an account, e.g. DC Android needs it to know whether to ask the user to disable battery optimisations.
> fix: Set Config::IsChatmail in configure()

- python/src/deltachat/testplugin.py
A bot process is run asynchronously, so some messages can arrive before the bot is fully initialised.
Close #4976
> test: Set fetch_existing_msgs for bots (#4976)

- src/imap.rs
There was a comment in `fetch_existing_msgs()`: "Bots don't want those messages". If a bot doesn't want this setting, why enable it? It's disabled by default anyway.
Close #4976
> fix: Allow fetch_existing_msgs for bots (#4976)

- src/chat.rs
- src/receive_imf/tests.rs
- src/securejoin.rs
- src/webxdc.rs
- test-data/golden/chat_test_msg_with_implicit_member_add
- test-data/golden/chat_test_parallel_member_remove
@adbenitez, so, i can't reproduce the problem you described in #5508. Also i checked it code-wise, `remove_contact_from_chat()` first sends the message and only then removes the contact. There's even a comment:
```
// we remove the member from the chat after constructing the                                                                                                                                             
// to-be-send message. If between send_msg() and here the                                                                                                                                                
// process dies the user will have to re-do the action.  It's …
```
> fix: Remove existing/new group member locally if send_msg() fails (#5508)

- deltachat-jsonrpc/src/api.rs
- src/message.rs
- src/receive_imf/tests.rs
Add a function setting a vCard containing the given contacts to the message draft. This should
simplify sending contacts as vCards for apps.
> api(jsonrpc): Add set_draft_vcard(.., msg_id, contacts)

- src/mimefactory.rs
- src/mimeparser.rs
- src/tests/verified_chats.rs
If a display name should be protected (i.e. opportunistically encrypted), only put the corresponding
address to the unprotected headers. We protect the From display name only for verified chats,
otherwise this would be incompatible with Thunderbird and K-9 who don't use display names from the
encrypted part. Still, we always protect To display names as compatibility seems less critical here.
When receiving a messge, overwrite the From display name but not the whole From field as that would
allow From forgery. For the To field we don't really care. Anyway as soon as we receive a message
from the user, the display name will be corrected.
close #5166
> feat: Protect From name for verified chats and To names for encrypted chats (#5166)

- deltachat-ffi/deltachat.h
- python/src/deltachat/testplugin.py
- src/receive_imf.rs
- src/receive_imf/tests.rs
This should finally fix #4976
After the second commit only webxdc realtime tests are failing.
> fix: Fetch existing messages for bots as `InFresh` (#4976)

- Cargo.toml
- deltachat-contact-tools/Cargo.toml
- deltachat-ffi/Cargo.toml
- deltachat-jsonrpc/Cargo.toml
- deltachat-repl/Cargo.toml
- deltachat-rpc-server/Cargo.toml
Deduplicate dependency versions by specifying them only once in Cargo.toml for the whole workspace under `[workspace.dependencies]`.
Where possible, also deduplicate the dependencies' features (if different crates use different set of features, of course these can't be deduplicated).
> refactor: Deduplicate dependency versions

- src/chat.rs
- src/context.rs
- src/ephemeral.rs
- src/message.rs
- src/receive_imf.rs
- src/sql/migrations.rs
SQLite search with `LIKE` is case-insensitive only for ASCII chars. To make it case-insensitive for all messages, create a new column `msgs.txt_normalized` defaulting to `NULL` (so we do not bump up the database size in a migration) and storing lowercased/normalized text there when the row is created/updated. When doing a search, search over `IFNULL(txt_normalized, txt)`.
Close #5052
> feat: Case-insensitive search for non-ASCII messages (#5052)

- src/receive_imf.rs
- src/receive_imf/tests.rs
Just a small improvement while looking at #5385. See commit messages.
> feat: Remove subject prefix from ad-hoc group names (#5385)

- python/tests/test_0_complex_or_slow.py
- src/ephemeral.rs
- src/imap.rs
- src/message.rs
- src/mimefactory.rs
- src/receive_imf.rs
- src/receive_imf/tests.rs
- src/sql.rs
- src/sql/migrations.rs
> Fix deletion of messages quickly deleted after sending (#3685)

- src/config.rs
- src/context.rs
NB: We don't restart IO from the synchronisation code, so `MvboxMove` isn't effective immediately if `ConfiguredMvboxFolder` is unset, but only after a reconnect to IMAP.
Close #5680
> feat: Sync `Config::MvboxMove` across devices (#5680)

- src/mimefactory.rs
- src/securejoin.rs
- src/test_utils.rs
**feat: Don't reveal profile data to a not yet verified contact (#5166)**
Follow-up to b77131159392daa0bfb8e2ce99c219e1f7bd4823. Since that commit names are not revealed in
verified chats, but during verification (i.e. SecureJoin) they are still sent unencrypted. Moreover,
all profile data mustn't be sent even encrypted before the contact verification, i.e. before
"v{c,g}-request-with-auth". That was done for the selfavatar in
304e902fcec36ce8fde263aa7a45759ed9a2fdaf, now it's done for From/To names and the self-status as
well. Moreover, "v{c,g}-request" and "v{c,g}-auth-required" messages are deleted right after
processing, so other devices won't see the received profile data anyway.
**feat: Don't reveal profile data in MDNs (#5166)**
Looks like it has no sense to send any profile data …
> feat: Don't reveal profile data to a not yet verified contact and in MDNs (#5166)

- src/configure.rs
- src/net/http.rs
saying it is 'preferred' encrypted is misleading,
therfore, just remove it.
i do not think, it is worth saying that we do not query 'http', this is clear from the source code.
moreover, fix two typos.
target #5706
> docs: remove misleading configuration comment

- python/examples/test_examples.py
- python/src/deltachat/testplugin.py
Bot processes are run asynchronously, so we shouldn't send messages to a bot before it's fully initialised and skipped existing messages for processing, i.e. before DC_EVENT_IMAP_INBOX_IDLE is emitted.
Close #5699
> test(python): Wait for bot's DC_EVENT_IMAP_INBOX_IDLE before sending messages to it (#5699)

- src/mimefactory.rs
- src/tests/verified_chats.rs
See commit messages. In fact both commits are fixes, but as the first fixes the bug, the second one becomes just a refactoring.
> fix: Don't fail if going to send plaintext, but some peerstate is missing

- deltachat-contact-tools/src/lib.rs
- src/chat.rs
- src/config.rs
- src/contact.rs
- src/imap.rs
- src/mimeparser.rs
- src/receive_imf.rs
- src/receive_imf/tests.rs
- src/tools.rs
- src/update_helper.rs
- src/webxdc.rs
Best reviewed commit-by-commit; the commit messages explain what is done.
> Correctly sanitize input everywhere

- spec.md
Also, move the `Miscellaneous` section to the end again and update the table of contents with https://derlin.github.io/bitdowntoc/.
> Document vCards in the specification

- src/context.rs
- src/quota.rs
- src/scheduler.rs
And add a unit test for this function. At least this way we protect from the recently fixed bug when a wrong comparison operator was used.
Close #5683. I think if it's verified by at least some test, it can be closed.
> refactor: Move quota_needs_update calculation to a separate function (#5683)

- deltachat-contact-tools/src/lib.rs
About the first TODO: I tried this out, but it didn't actually improve things, for two reasons:
1. The trick with `#![cfg_attr(not(test), warn(clippy::indexing_slicing))]` that enables the lint everywhere except for tests doesn't work with workspace-wide lints. (Context: We want to lint against indexing because it might panic, but in a test panicking is fine, so we don't want to enable the lint in tests).
2. Most of our crates have different sets of lints right now, so it would only be very few crates that use the workspace-wide list of lints.
About the second TODO:
It's not feasible right now to fully parse vCards, and for our good-enough parser the current behavior is fine, I think. If we fail to parse some realworld vCards because of this, we can still improve it.
> chore: Remove two TODOs that are not worth fixing

- src/config.rs
- src/sync.rs
If currently there are no multi-device bots, let's disable sync messages for bots at all. Another option is to auto-disable sync messages when `Config::Bot` is set, so sync messages can be reenabled if needed. But let's leave this option for the future.
> feat: Disable sending sync messages for bots (#5705)

- src/mimefactory.rs
- src/receive_imf/tests.rs
For purposes of building a message it's better to consider the self-chat as verified. Particularly, this removes unencrypted name from the "From" header.
> fix: MimeFactory::verified: Return true for self-chat

- src/imex.rs
- src/key.rs
If no matching key packet was found, report which key is needed to make it clear to the user.
Close #5539
> feat: Report better error from DcKey::from_asc() (#5539)

- deltachat-rpc-client/tests/test_securejoin.py
- src/imex.rs
This way it's clearer which key is which and also adding the key fingerprint to the file name avoids overwriting another previously exported key. I think this is better than adding an incremental number as we do for backups, there's no need to export a key several times to different files.
Also i decided not to add a date to file names, seems it's not as useful as for backups.
Close #5694
> feat: Add email address and fingerprint to exported key file names (#5694)

- src/contact.rs
Follow-up to 5fa7cff46. Let's still not send a sync message if the contact wasn't modified. This is not very important, but just for consistency with the `chat::rename_ex()` behaviour.
> feat: Contact::create_ex: Don't send sync message if nothing changed (#5705)

- deltachat-jsonrpc/src/api/types/message.rs
- src/message.rs
> feat(jsonrpc): Allow to set message quote text without referencing quoted message (#5695)

- src/chat.rs
- src/mimefactory.rs
- src/webxdc.rs
> feat: Limit the size of aggregated WebXDC update to 100 KiB (#4825)

- src/receive_imf.rs
- src/receive_imf/tests.rs
Close #5618
Although the task is about "group left" messages, i think it's ok to not create/unarchive groups for all member removal messages. At least currently for DC-style groups `create_group()` already avoids group creation for any member removals. Then, if we don't consider member removal messages important enough to create groups, why unarchive already existing ones.
> Don't create/unarchive groups on member removal messages (#5618)

- deltachat-rpc-client/tests/test_something.py
- src/chat.rs
- src/config.rs
- src/qr.rs
- src/securejoin.rs
- src/sync.rs
- src/test_utils.rs
`Context::send_sync_msg()` mustn't be called from multiple tasks in parallel to avoid sending the same sync items twice because sync items are removed from the db only after successful sending. Let's guarantee this by calling `send_sync_msg()` only from the SMTP loop. Before `send_sync_msg()` could be called in parallel from the SMTP loop and another task doing e.g. `chat::sync()` which led to `test_multidevice_sync_chat` being flaky because of events triggered by duplicated sync messages.
Fix #5780
> fix: Call `send_sync_msg()` only from the SMTP loop (#5780)

- src/chat.rs
- src/imap.rs
- src/message.rs
Follow-up to 3cf78749df36126d35d8c6a88e2f2b598e7edb77 "Emit DC_EVENT_MSGS_CHANGED for DC_CHAT_ID_ARCHIVED_LINK when the number of archived chats with unread messages increases (#3940)".
In general we don't want to make an extra db query to know if a noticied chat is archived. Emitting events should be cheap, better to allow false-positive `MsgsChanged` events.
Fix #5768
> fix: Emit MsgsChanged if the number of unnoticed archived chats could decrease (#5768)

- src/summary.rs
- src/webxdc.rs
This is a hint for apps that a WebXDC icon should be shown in the summary, e.g. in the chatlist. Otherwise it's not clear when it should be shown, e.g. it shouldn't be shown in a reaction summary.
#5782 should be closed after the corresponding DC Desktop fix.
> feat: Set summary thumbnail path for WebXDCs to "webxdc-icon://last-msg-id" (#5782)

- src/imex.rs
- src/sql.rs
No tests, i only checked this manually with `deltachat-repl`.
> Fixes to the backup import

- src/message.rs
- src/mimeparser.rs
This state can be computed from the `msgs_mdns` table without significant overhead as we have an index by msg_id there. A little more code, but overall the logic is simpler.
EDIT: This allows to add some `OutRcvd` message state for received outgoing messages which doesn't need to be upgraded to `OutMdnRcvd` and to fix the scenario in #5813 by sorting such messages the same way as `InFresh` ones.
> refactor: Don't update message state to `OutMdnRcvd` anymore

- python/tests/test_1_online.py
- src/config.rs
- src/configure.rs
- src/constants.rs
- src/context.rs
- src/headerdef.rs
- src/imap.rs
- src/imap/session.rs
- src/scheduler.rs
Recently there are many questions on the Delta Chat forum why some unexpected encrypted messages appear in Inbox. Seems they are mainly sync messages, though that also obviously happens to SecureJoin messages. Anyway, regardless of the `MvboxMove` setting, auto-generated outgoing messages should be moved to the DeltaChat folder so as not to complicate co-using Delta Chat with other MUAs.
> feat: Always move outgoing auto-generated messages to the mvbox

- standards.md
The old draft was expired and abandoned, and the new draft should be possible to generate cleanly without breaking compatibility with old clients.
> Point to active Header Protection draft

- src/config.rs
- src/message.rs
- src/mimefactory.rs
- src/smtp.rs
Fixup for 5ce44ade1. It is good that read receipts are sent by bots to see the bot received the message. Thanks to @adbenitez for pointing this out.
> fix: Still send MDNs from bots by default

- scripts/update-provider-database.sh
- src/provider/data.rs
what i did:
- update `REV` in `./scripts/update-provider-database.sh`
- run `./scripts/update-provider-database.sh`
the update is needed to get the updated `before_login_hint` for getting [rid of oauth2 from android](https://github.com/deltachat/deltachat-android/pull/3234) (core is unchanged here)
when this is merged, we can do a new core and a new android testing release with the larger changes api34, jcenter, oauth2
> chore: update provider database

- deltachat-jsonrpc/src/api.rs
On big accounts, it can take more than 10s, so that QR generation failed.
cc @link2xt @hpk42
> fix: Increase timeout for QR generation to 60s

- src/mimefactory.rs
- src/securejoin.rs
I.e. to all messages except "v{c,g}-request" as they sent out on a QR code scanning which is a manual action and "vg-member-added" as formally this message is auto-submitted, but the member addition is a result of an explicit user action. Otherwise it would be strange to have the Auto-Submitted header in "member-added" messages of verified groups only.
Together with #5755 this will move appropriate outgoing SecureJoin messages to the mvbox regardless of the `mvbox_move` setting.
> feat: Add "Auto-Submitted: auto-replied" header to appropriate SecureJoin messages

- src/mimefactory.rs
- src/securejoin.rs
- src/test_utils.rs
- src/tests/verified_chats.rs
This fixes the bug that sometimes made QR scans fail.
When sorting headers into unprotected/hidden/protected, the From: header was added twice for all messages: Once into unprotected_headers and once into protected_headers. For messages that are `is_encrypted && verified || is_securejoin_message`, the display name is removed before pushing it into unprotected_headers.
Later, duplicate headers are removed from unprotected_headers right before prepending unprotected_headers to the message. But since the unencrypted From: header got modified a bit when removing the display name, it's not exactly the same anymore, so it's not removed from unprotected_headers and consequently added again.
> fix: Only include one From: header in securejoin messages

- src/config.rs
> fix: Display Config::MdnsEnabled as true by default (#5948)

- python/src/deltachat/testplugin.py
- python/tests/test_1_online.py
- src/config.rs
- src/imex.rs
I.e. treat `DeleteServerAfter == None` as "delete at once". But when a backup is exported, set
`DeleteServerAfter` to 0 so that the server decides when to delete messages, in order not to break
the multi-device case. Even if a backup is not aimed for deploying more devices, `DeleteServerAfter`
must be set to 0, otherwise the backup is half-useful because after a restoration the user wouldn't
see new messages deleted by the device after the backup was done. But if the user explicitly set
`DeleteServerAfter`, don't change it when exporting a backup. Anyway even for non-chatmail case the
app should warn the user before a backup export if they have `DeleteServerAfter` enabled.
Also do the same after a backup import. While this isn't reliable as we can crash in between, this
is a problem only …
> feat: Delete messages from a chatmail server immediately by default (#5805)

- src/config.rs
https://github.com/deltachat/deltachat-core-rust/pull/5949#discussion_r1741295618:
> `get_config_bool_opt` not returning `None` is actually surprising, but let's not fix this in this PR.
> refactor: get_config_bool_opt(): Return None if only default value exists

- python/tests/test_1_online.py
- src/mimefactory.rs
- src/receive_imf/tests.rs
`chat::create_send_msg_jobs()` already handles `Config::BccSelf` as needed, so i have no idea why `MimeFactory` adds the From address to recipients for the self-chat. Well, the self-chat is special because of sync messages, but they aren't sent if `BccSelf` is disabled anyway. This change unifies the logic for the self-chat and groups only containing `SELF`.
DONE: test.
> feat: Don't SMTP-send messages to self-chat if BccSelf is disabled

- deltachat-rpc-client/tests/test_securejoin.py
- src/chat.rs
- src/qr.rs
- src/securejoin.rs
- src/sql/migrations.rs
- src/sync.rs
- src/token.rs
Groups promotion to other devices and QR code tokens synchronisation are not synchronised processes, so there are reasons why a QR code token may arrive earlier than the first group message:
- We are going to upload sync messages via IMAP while group messages are sent by SMTP.
- If sync messages go to the mvbox, they can be fetched earlier than group messages from Inbox.
Fix #5954 
TODO(done): Test. I think that `test_securejoin.py:test_qr_securejoin()` may be left unmodified, it's very unlikely that the `alice2` device won't receive the QR code token by the moment Fiona joins (moreover, Alice doesn't have the mvbox in this test). But a new test checking that QR code tokens are saved if arrive earlier than first group messages is needed. EDIT: `sync::test_unpromoted_group_qr_sync()` tests …
> fix: Save QR code token regardless of whether the group exists (#5954)

- Cargo.lock
- Cargo.toml
- deltachat-jsonrpc/typescript/test/online.ts
- python/tests/test_1_online.py
- src/chat.rs
- src/config.rs
- src/imap.rs
- src/mimefactory.rs
- src/qr.rs
- src/scheduler.rs
- src/securejoin.rs
- src/smtp.rs
- src/sql/migrations.rs
- src/sync.rs
- src/test_utils.rs
> feat: Use IMAP APPEND command to upload sync messages (#5845)

- src/receive_imf.rs
- src/receive_imf/tests.rs
- src/sql/migrations.rs
This should fix ad-hoc groups splitting when messages are fetched out of order from different
folders or otherwise reordered, or some messages are missing so that the messages reference chain is
broken, or a member was removed from the thread and readded later, etc. Even if this way two
different threads are merged, it looks acceptable, having many threads with the same name/subject
and members isn't a common use case.
Fix #5385
> feat: Assign message to ad-hoc group with matching name and members (#5385)

- src/qr.rs
It did not interpolate the `{prefix}`,
it just printed it in plain text.
> refactor: better log message for failed QR scan

- src/securejoin.rs
- src/securejoin/bob.rs
The "Cannot establish guaranteed end-to-end encryption with ..." info message can have lots of causes, and it happened twice to us now that it took us some time to figure out which one it is.
So, include some more detail in the info message by simply adding the non-translated error message in parantheses.
If we want to put in some more effort for nicer error messages, we could:
- Introduce one new translated string "Cannot establish guaranteed end-to-end encryption with …. Cause: %2$s" or similar (and remove the old stock string)
- And/Or: Introduce new translated strings for all the possible errors
- And/Or: Maybe reword it in order to account better for the case that the chat already is marked as g-e2ee, or use a different wording (because if the chat is marked as g-e2ee then it might …
> feat: More context for the "Cannot establish guaranteed..." info message

- Cargo.lock
futures-util 0.3.30 is yanked.
> chore(cargo): bump futures-* from 0.3.30 to 0.3.31

- src/download.rs
If a race happens and the message disappears, there's just nothing to do and no sense to fail. Follow-up to 22e5bf85715d2911da456c4cc84821726eff9c2d.
This is `refactor` because such a race is unlikely.
> refactor: MsgId::update_download_state: Don't fail if the message doesn't exist anymore

- src/blob.rs
- src/receive_imf/tests.rs
> fix: Assume file extensions are 32 chars max and don't contain whitespace (#5338)

- CONTRIBUTING.md
- src/sql/migrations.rs
Otherwise backups exported from the current core and imported in versions < 1.144.0 have QR codes not working. The breaking change which removed the column is 5a6efdff44b1d374ea0752ac394423ba258c134b.
Fix #6038
> fix: Readd tokens.foreign_id column (#6038)

- src/chat.rs
- src/download.rs
- src/message.rs
- src/sql/migrations.rs
Fix #6053
Follow-up to 07fa9c35ee4feb02b421026ca0a968b4155de559
> fix: ChatId::maybe_delete_draft: Don't delete message if it's not a draft anymore (#6053)

- src/tests/verified_chats.rs
- test-data/golden/verified_chats_message_from_old_dc_setup
If a message from an old contact's setup is received, the outdated Autocrypt header isn't applied, so the contact verification preserves. But the chat protection breaks because the old message is sorted to the bottom as it mustn't be sorted over the protection info message (which is `InNoticed` moreover). Would be nice to preserve the chat protection too e.g. add a "protection broken" message, then the old message and then a new "protection enabled" message, but let's record the current behaviour first.
> test: Message from old setup preserves contact verification, but breaks 1:1 protection

- CMakeLists.txt
- Cargo.toml
On main, when running `cargo build`, the following warning is emitted:
> warning: /home/jonathan/deltachat-android/jni/deltachat-core-rust/deltachat-ffi/Cargo.toml: `default-features` is ignored for deltachat, since `default-features` was not specified for `workspace.dependencies.deltachat`, this could become a hard error in the future
This is because when referring to a workspace dependency, it's not possible to remove features, it's only possible to add features, so that the `vendored` feature was always enabled with no possibility to disable it.
This PR restores the wanted behavior of enabling vendoring by default with the possibility to disable it with "default-features = false".
It fixes `nix build .#python-docs` by not passing
`--no-default-features` when building deltachat with …
> fix: Resolve warning about default-features, and make it possible to disable vendoring

- deltachat-ffi/src/lib.rs
rust-analyzer was showing warnings here because it is always also building in the Test configuration, and EventType has a 
```rust
#[cfg(test)]
Test,
```
variant, which was not matched.
> chore: Silence a rust-analyzer false-positive

- deltachat-ffi/deltachat.h
- src/config.rs
- src/context.rs
this PR allows setting a "private tag" for a profile, see https://github.com/deltachat/deltachat-android/pull/3373 for a possible UI.
currently, the core does not do anything with the tag (so, it could also be a ui.-config option), however, this may change in the future - it might bet synced, and become also otherwise useful in core. also, having this in core is better documentation-wise, as otherwise each UI easily does its own things :)
> feat: internal profile names

- python/tests/test_1_online.py
- src/configure.rs
- src/imap.rs
> fix: Set Config::NotifyAboutWrongPw before saving configuration (#5896)

- deltachat-jsonrpc/src/api.rs
- deltachat-repl/src/cmdline.rs
- src/chat.rs
- src/message.rs
This adds a function to `Message`:
```rust
pub fn new_text(text: String) -> Self {
Message {
viewtype: Viewtype::Text,
text,
..Default::default()
}
}
```
I keep expecting that a function like this must exist and being surprised that it doesn't.
Open question is whether it should be `pub` or `pub(crate)` - I made it `pub` for now because it may be useful for others and we currently we aren't thinking about the Rust API that much, anyway, but I can make it `pub(crate)`, too (then it can't be used in deltachat-jsonrpc and deltachat-repl).
I replaced some usages of Message::new(Viewtype::Text), but not all yet, I'm going to do this in a follow-up, which will remove another around 65 LOC.
> api: Add Message::new_text()

- deltachat-ffi/deltachat.h
- src/config.rs
- src/peer_channels.rs
Mainly after discussions between @hpk42, @r10s, and @adbenitez.
Todo for the UIs:
- Move the option from experimental to a normal advanced setting.
Considerations:
- if someone ants to get your IP address, they can just send you a link to some server where they can look into the log files
- So, opening a Webxdc is similar to sending a link
- Your chat partner will have to modify their DC app or monitor network traffic to actually see your IP address
Open questions:
- Should this PR wait until all the UIs moved the option from "experimental" to a normal advanced setting?
Future possibilities:
- Add a button the UI "set all settings to be maximally secure" or similar that disables this and other settings
> feat: Enable Webxdc realtime by default

- src/contact.rs
- src/qr.rs
- src/securejoin.rs
> fix: Save contact name from SecureJoin QR to `authname`, not to `name` (#6115)

- src/mimeparser.rs
- src/receive_imf/tests.rs
close #2338
Concat error messages when receiving new ndns.
This PR adds a newline followed by the new NDN error to the error text. Maybe we should use something more prominent like 
```
-----------------------------------------------------------------------
```
or more newlines, but I'm not sure. This maybe has to be tested on a real device to see what works best.
> fix: concat ndns

- src/imap.rs
Over the past years, it happend two times that a user came to me worried about a false-positive "Cannot login as ***. Please check if the e-mail address and the password are correct." message.
I'm not sure why this happened, but I think we should make the logic for showing this notification stricter:
- Before: The notification is shown if connection fails two times in a row, and the second error contains the word "authentication".
- Now: The notification is shown if the connection fails two times in a row, and _both_ error messages contain the word "authentication".
The second commit just renames `login_failed_once` to `authentication_failed_once` in order to reflect this change.
> fix: Prevent accidental wrong-password-notifications

- src/chat.rs
- src/receive_imf.rs
- src/receive_imf/tests.rs
There were many cases in which "member added/removed" messages were added to chats even if they actually do nothing because a member is already added or removed. But primarily this fixes a scenario when Alice has several devices and shares an invite link somewhere, and both their devices handle the SecureJoin and issue `ChatGroupMemberAdded` messages so all other members see a duplicated group member addition.
Fix #5992
> fix: Only add "member added/removed" messages if they actually do that (#5992)

- src/simplify.rs
with this PR,  up to 120 characters for the line-before-quite are allowed. 80 characters are a bit limited in practise ...
```
On Mon, 3 Jan, 2022 at 8:34 PM "Anonymous The Mighty" <anonymous@example.com> wrote:
```
... already breaks the limit. it is good to allow up to 40 additional characters for name + email address.
closes #2958
allowing any length, however, may catch too much,
as the line could also be a normal paragraph with important content, so 120 characters seems reasonable.
the idea of adding more complexity here would probably lead only to, well more complexity - things can anyways go wrong -
and, we have the "show full message..." button for exactly that purpose, so that the user can access everything as original.
so, if things go wrong sometimes,
this is expected and fine.
> fix: line-before-quote may be up to 120 character long.

- src/scheduler/connectivity.rs
due to async processing,
it may happen `getConnectivityHtml()` is called from UI before `startIO()` is actually called.
eg. on iOS, we may delay `startIo()` [if another process is still processing a PUSH notification](https://github.com/deltachat/deltachat-ios/pull/2393) - when during this time, the connectivity view is opened, it is weird if a big error "CONTACT THE DEVELOPERS!11!!!" is shown :) (i have seen that also on desktop, but i cannot reproduce that there, maybe some races, maybe fixed meanwhile)
just showing "Not Connected" seems to be nicer in that case, this is even localised - and also correct (that IO is not started does not matter from the view of the user - and devs can still see the reasons as the view does not has folders listed)
also, there is not really a function …
> tune down io-not-started info in connectivity-html

- deltachat-ffi/deltachat.h
there was a bug on iOS before (https://github.com/deltachat/deltachat-ios/pull/2397)
that assumed that the proxy needs to be added to the proxy list additionally, also the normalization was unexpected.
> docs: scanned proxies are added and normalized

- src/chat.rs
This PR prevents overwriting drafts when the text and file are the same. 
close #6211
> Fix: Dont overwrite equal drafts

- src/context.rs
This is needed for iOS, see comment in the code. An alternative would be to add an API `invalidate_config_cache()` or to do nothing and just assume that things will be fine.
We _could_ mention this in the doc comment of `start_io()`, but right now this PR does not, since it's only important for one platform.
> feat: Clear config cache in start_io()

- python/tests/test_3_offline.py
- src/securejoin.rs
As discussed in #5467 we want to use `i.delta.chat` in QR codes in favor of `OPENPGP4FPR:` scheme. This PR does the replacement in `get_securejoin_qr` which is used in `get_securejoin_qr_svg`.
close #5467
> Use i.delta.chat in qr codes

- src/receive_imf.rs
- src/securejoin.rs
`receive_imf() is only used in tests and the REPL, which enables the "internals" feature. This PR marks it as such, so that it's clear not only from the comment that this function is not used for anything else.
> test: Mark `receive_imf()` as only for tests and "internals" feature

- Cargo.lock
- Cargo.toml
- deltachat-ffi/deltachat.h
- deltachat-jsonrpc/src/api/types/webxdc.rs
- deltachat-rpc-client/tests/test_webxdc.py
- src/summary.rs
- src/webxdc.rs
this PR adds the address to be used by the UI for `window.webxdc.selfAddr` to webxdc-info. UIs need to be changed accordingly and must not use configured_addr any longer.
the address is created by sha256(private-key + rfc724_mid) , which results in different addresses for each webxdc, without the option to find out the real address of the user.
this also returns the same address for a multi-device-setup - sending totally random self address around might be an alternative, however would require connectivity (both devices may be offline on first start). 
for existing app, after the change, there will be a new user, resulting eg. in a new highscore, otherwise, things should be mostly fine. this assumption is also important as we might change the thing another time when it comes to …
> feat: use privacy-preserving webxdc addresses

- deltachat-ffi/deltachat.h
I found the old documentation rather hard to understand. The new doc string:
- uses whole sentences, leaving less space for misinterpretation
- explicitly mentions that it can happen that there is no webxdc-info-message
- is clearly structured using bullet points.
I didn't understand what "in case of summary change" means, maybe this needs to be added to the new doc string.
> docs: Clarify DC_EVENT_INCOMING_WEBXDC_NOTIFY documentation

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/debug_logging.rs
- src/webxdc.rs
- src/webxdc/maps_integration.rs
add `update.href` property option to update objects send via `Context::send_webxdc_status_update()`.
when set together with `update.info`,
UI can implement the info message as a link that is passed to the webxdc via `window.location.href`.
for that purpose, UI will read the link back from `Message::get_webxdc_href()`.
Practically,
this allows e.g. an calendar.xdc
to emits clickable update messages
opening the calendar at the correct date.
closes #6219
documentation at https://github.com/webxdc/website/pull/90
> feat: `update.href` api

- src/tests/aeap.rs
A part of closed #6240.
There was a question related to this behaviour: https://github.com/deltachat/deltachat-core-rust/issues/6222#issuecomment-2484549336. It seems nobody knew how it really works, but it turned out that it works correctly.
> test: After AEAP, 1:1 chat isn't available for sending, but unprotected groups are (#6222)

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- deltachat-jsonrpc/src/api.rs
- deltachat-repl/src/cmdline.rs
- src/download.rs
- src/webxdc.rs
- src/webxdc/maps_integration.rs
this PR removes most usages of the `descr` parameter.
- to avoid noise in different branches etc. (as annoying on similar, at a first glance simple changes), i left the external API stable
- also, the effort to do a database migration seems to be over the top, so the column is left and set to empty strings on future updates - maybe we can recycle the column at some point ;)
closes #6245
> api: deprecate webxdc `descr` parameter

- src/peerstate.rs
A part of closed #6240.
Probably it's not easy to add a test on that, but at least the comment should prevent reverting the code.
> feat: AEAP: Check that the old peerstate verified key fingerprint hasn't changed when removing it

- src/webxdc.rs
It's used in the only place. Also this way `get_webxdc_self_addr()` which makes a db query is only called when necessary.
> refactor: create_status_update_record: Get rid of `notify` var

- RELEASE.md
using long options make things less mystical, it is clearer what happens.
(apart from that i also disallowed `git -a` on my machine in general, as `git commit -a` is considered harmful. as my approach to disallow that is a bit greedy and disallows `-a` just for any git commands, this is the only place where i regularly struggle :)
> prefer long options in RELEASE.md

- src/reaction.rs
- src/test_utils.rs
See https://github.com/deltachat/deltachat-core-rust/pull/6213#discussion_r1855237414 for reasoning
> test: Check that IncomingMsg isn't emitted for reactions

- deltachat-ffi/deltachat.h
- deltachat-jsonrpc/src/api/types/webxdc.rs
- deltachat-ratelimit/src/lib.rs
- deltachat-rpc-client/tests/test_webxdc.py
- src/webxdc.rs
this PR implements the spec of https://github.com/webxdc/website/pull/91/files 
`sendUpdateInterval` interval is then 1,000 milliseconds for chatmail and 10,000 ms otherwise.
`sendUpdateMaxSize` is about 18 mb unconditionally
closes https://github.com/deltachat/deltachat-core-rust/issues/6220 , once merged, we should create PR/issues for Android/iOS (desktop already has an issue-draft for missing things)
> add webxdc limits api

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- deltachat-jsonrpc/src/api/types/events.rs
- src/events/payload.rs
- src/webxdc.rs
this PR adds the `href` from `update.href` to the IncomingWebxdcNotify event (DC_EVENT_INCOMING_WEBXDC_NOTIFY in cffi)
purpose is to add a "Start" button to the notifications that allow starting the app immediately with the given href
> feat: add href to IncomingWebxdcNotify event

- src/chat.rs
> fix: Sync chat action even if sync message arrives before first one from contact (#6259)

- src/mimeparser.rs
- src/sql.rs
Already apply rust beta (1.84) clippy suggestions now, before they let CI fail in 6 weeks.
The newly used functions are available since 1.70, our MSRV is 1.77, so we can use them.
> chore: Beta clippy suggestions

- .github/workflows/ci.yml
- Cargo.toml
Replaces https://github.com/deltachat/deltachat-core-rust/pull/6272
The only `cargo` invocation that would have caught this is `cargo --all-features` (without `--workspace`) because `--workspace` means that `deltachat-repl` is also compiled, which will enable the `internals` feature for the whole workspace. So, this is what I added to CI in the first commit.
The second commit fixes the problem.
> test: fix cargo check for receive_emails benchmark

- benches/receive_emails.rs
The benchmark function (e.g. `recv_all_emails()`) is executed multiple times on the same context. During the second iteration, all the emails were already in the database, so, receiving them again failed.
This PR fixes that by passing in a second `iteration` counter that is different for every invocation of the benchmark function.
> test: Fix panic in `receive_emails` benchmark

- src/chat.rs
- src/mimeparser.rs
> fix: Store plaintext in mime_headers of truncated sent messages (#6273)

- src/chat.rs
- src/contact.rs
- src/securejoin.rs
- src/test_utils.rs
This PR:
- Moves the note about the false positive to the end of the test output, where it is more likely to be noticed
- Also notes in test_modify_chat_disordered() and test_setup_contact_*(), in addition to the existing note in test_was_seen_recently()
> test: Notifiy more prominently & in more tests about false positives when running `cargo test`

- src/receive_imf.rs
- src/receive_imf/tests.rs
- src/stock_str.rs
- test-data/golden/receive_imf_recreate_contact_list_on_missing_messages
- test-data/golden/receive_imf_recreate_member_list_on_missing_add_of_self
> Add info messages about implicit membership changes if group member list is recreated (#6314)

- src/message.rs
without the prefix,
it looks as if it is part of the Message-ID,
esp. if Message-ID is longer,
a break on different delimiters may look exactly the same.
see deltachat/deltachat-desktop#4401 for some screenshots that initially confused me :)
> feat: prefix server-url in info

- src/imex/transfer.rs
UIs may want to display smth like "Transferring..." after "Establishing connection between devices..." on nonzero progress. Before, progress on the receiver side was starting with `2` after receiving enough data.
> feat: Emit ImexProgress(1) after receiving backup size

- src/location.rs
- src/message.rs
Explicit transaction does the only commit (and fsync()).
Checked other usages of `call_write()`, it seems in other places it doesn't make sense or isn't possible to use `transaction()`.
> feat: delete_msgs: Use transaction() instead of call_write()

- src/chat.rs
- src/receive_imf.rs
It was called from `receive_imf` when an outgoing message is received. But `Imap::fetch_new_messages()` already calls `chat::mark_old_messages_as_noticed()` which does the job better (per-message).
> refactor: Remove marknoticed_chat_if_older_than()

- src/blob.rs
> fix: sanitise_name: Don't consider punctuation and control chars as part of file extension (#6362)

- src/configure.rs
- src/download.rs
- src/imap.rs
- src/imap/idle.rs
- src/imap/scan_folders.rs
- src/imap/select_folder.rs
Close #5870. I think a test isn't really necessary, though can add if someone thinks differently
> feat: Remove "jobs" from imap_markseen if folder doesn't exist (#5870)

- deltachat-ffi/deltachat.h
- deltachat-jsonrpc/src/api/types/message.rs
- src/blob.rs
- src/chat.rs
- src/message.rs
> fix: Never change Viewtype::Sticker to Image if file has non-image extension (#6352)

- src/chat.rs
- src/config.rs
- src/imex.rs
- src/sql/migrations.rs
> fix: Change BccSelf default to 0 for chatmail (#6340)

- src/location.rs
- src/mimeparser.rs
- src/sync.rs
> fix: Don't treat location-only and sync messages as bot ones (#6357)

- src/chat.rs
Replacement for #6423. See commit messages
> refactor: Add why_cant_send_ex() capable to only ignore specified conditions

- src/chat.rs
- src/contact.rs
- src/message.rs
- src/receive_imf.rs
- src/sql.rs
> refactor: Eliminate remaining repeat_vars() calls (#6359)

- src/sql/migrations.rs
cmp https://github.com/deltachat/deltachat-core-rust/issues/6432#issuecomment-2589016104
> fix: migration: Set bcc_self=1 if it's unset and delete_server_after!=1 (#6432)

- src/sql/migrations.rs
Some migrations change the `config` table, but they don't update the cache. While this wasn't the cause for
https://github.com/deltachat/deltachat-core-rust/issues/6432, it might have caused a similar bug, so, let's clear the config cache after every migration.
> fix: Clear the config cache after every migration

- deltachat-ffi/deltachat.h
- deltachat-repl/src/cmdline.rs
- src/blob.rs
- src/chat.rs
- src/config.rs
- src/contact.rs
- src/imex/key_transfer.rs
- src/mimeparser.rs
- src/net/http.rs
- src/stock_str.rs
Deduplicate:
- In the REPL
- In `store_from_base64()`, which writes avatars received in headers
- In a few tests
- The saved messages, broadcast, device, archive icons
- The autocrypt setup message
1-2 more PRs, and we can get rid of `BlobObject::create`, `sanitise_name()`, and some others
> feat: Deduplicate in more places

- src/blob.rs
- src/message.rs
> refactor: Remove BlobObject::create(), use create_and_deduplicate_from_bytes() instead

- node/test/test.mjs
- src/blob.rs
- src/chat.rs
- src/config.rs
- src/webxdc/integration.rs
See commit messages for details.
I'll rebase-merge this PR.
Part of #6265
> Miscellaneous blob file deduplication improvements/fixes

- deltachat-jsonrpc/src/api.rs
there are not really unused, desktop uses them
also see #4474
> docs(jsonrpc): update documentation for `select_account` and `get_selected_account_id`

- deltachat-jsonrpc/src/api/types/events.rs
- src/events/payload.rs
- src/reaction.rs
For the same reasons as mentioned in #6356 and to streamline the "Incoming" Event API. (all have a chat_id)
If this makes sense from core architecure perspective has to be decided. Of course it is possible to fetch the chatId by fetching the Message but that is true for all the other events too.
> feat: add IncomingReaction.chat_id

- deltachat-jsonrpc/src/api/types/message.rs
For the "Reply Privately" feature.
> improvement: add `MessageQuote.chat_id`

- deltachat-jsonrpc/src/api.rs
- deltachat-jsonrpc/src/api/types/message.rs
- deltachat-rpc-client/src/deltachat_rpc_client/chat.py
This makes it so that files will be deduplicated when using the JsonRPC API.
@nicodh and @WofWca you know the Desktop code and how it is using the API, so, you can probably tell me whether this is a good way of changing the JsonRPC code - feel free to push changes directly to this PR here!
This PR here changes the existing functions instead of creating new ones; we can alternatively create new ones if it allows for a smoother transition.
This brings a few changes:
- If you pass a file that is already in the blobdir, it will be renamed to `<hash>.<extension>` immediately (previously, the filename on the disk stayed the same)
- If you pass a file that's not in the blobdir yet, it will be copied to the blobdir immediately (previously, it was copied to the blobdir later, when sending)
- If …
> feat: Deduplicate blob files in the JsonRPC API

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/chat.rs
- src/chat/chat_tests.rs
- src/constants.rs
- src/headerdef.rs
- src/message.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/param.rs
- src/receive_imf.rs
> _greetings from the ice of the deutsche bahn 🚂🚃🚃🚃 always a pleasure to see how well delta chat meanwhile performs in bad networks :)_
this PR adds an API to request other chat members to replace the message text of an already sent message. scope is mainly to fix typos.  this feature is known from whatsapp, telegram, signal, and is [requested](https://support.delta.chat/t/retract-edit-sent-messages/1918) [since](https://support.delta.chat/t/edit-messages-in-delta-chat/899) [years](https://github.com/deltachat/deltachat-android/issues/198).
technically, a message with an [`Obsoletes:`](https://datatracker.ietf.org/doc/html/rfc2076#section-3.6) header is sent out.
```
From: alice@nine
To: bob@nine
Message-ID: 2000@nine
In-Reply-To: 1000@nine
Obsoletes: 1000@nine
Edited: this is the new …
```
> edit message's text

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- python/src/deltachat/message.py
- python/tests/test_3_offline.py
- src/blob.rs
- src/blob/blob_tests.rs
- src/chat.rs
- src/message.rs
- src/param.rs
Now that we are deduplicating everywhere, we can get rid of some code.
The old python bindings did not get an optional `name` parameter because they are deprecated anyway, but it would be easy to add it.
Can be reviewed commit-by-commit or all at once.
> refactor: Remove Message.set_file() and related code

- Cargo.toml
- benches/get_chat_msgs.rs
- benches/marknoticed_chat.rs
- deltachat-rpc-client/tests/test_something.py
- src/chat.rs
- src/reaction.rs
- src/receive_imf.rs
- src/test_utils.rs
This is a more minimal alternative to https://github.com/deltachat/deltachat-core-rust/pull/6213, trying to keep things simpler.
Close https://github.com/deltachat/deltachat-core-rust/issues/6210.
Also, this adds a benchmark.
> feat: Mark reactions as IMAP-seen in marknoticed_chat(), second try

- src/chat.rs
- src/chat/chat_tests.rs
closes https://github.com/deltachat/deltachat-core-rust/issues/6561
> fix: do not allow to edit html messages

- deltachat-rpc-client/src/deltachat_rpc_client/account.py
- deltachat-rpc-client/tests/test_securejoin.py
- src/chat.rs
- src/chat/chat_tests.rs
- src/peerstate.rs
- src/receive_imf.rs
When there is a broken group (which might happen with multi-transport), people want to leave it.
The problem is that every "Group left" message notifies all other members and pops up the chat, so that other members also want to leave the group.
This PR makes it so that "Group left" messages don't create a notification, don't cause a number-in-a-cirle badge counter on the chat, and don't sort up the chat in the chatlist.
If a group is deleted, then the group won't pop up when someone leaves it; this worked fine already before this PR, and there also is a test for it.
> feat: Don't send a notification when a group member left

- src/chat.rs
- src/headerdef.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/receive_imf.rs
- src/receive_imf/receive_imf_tests.rs
- src/update_helper.rs
> fix: Add Chat-Group-Name-Timestamp header and use it to update group names (#6412)

- src/chat.rs
this PR deletes all known messages belonging to a chat when the chat is deleted. 
this may not be an exhaustive list as a client might not know all message-ids (eg. when using different times for "delete from device"). in this case, other devices may know more IDs. otherwise, the chatmail server will eventually clean up at some point. for non-chatmail, this is up to the user then.
the deletion sql commands were inspired by [`delete_msgs_ex`](https://github.com/chatmail/core/blob/main/src/message.rs#L1743) (in fact, [a first try](https://github.com/chatmail/core/compare/r10s/clear-chat-on-delete) was adapting that part, however, that seems less performant as lots of sql commands are needed)
successor of #5007
> feat: delete messages on IMAP when deleting chat

- src/mimefactory.rs
- src/mimeparser.rs
- src/mimeparser/mimeparser_tests.rs
- test-data/message/mail_with_user_and_group_avatars.eml
- test-data/message/mail_with_user_avatar.eml
- test-data/message/mail_with_user_avatar_deleted.eml
Hidden headers are nonstandard, so they aren't DKIM-signed by e.g. OpenDKIM if they appear in IMF section.
> fix: Ignore hidden headers in IMF section

- src/mimeparser.rs
- src/mimeparser/mimeparser_tests.rs
Delta Chat already adds hidden Message-ID header because some servers mess up with it, so it should be preferred.
> fix: Prefer hidden Message-ID header if any

- src/receive_imf.rs
Follow-up to https://github.com/chatmail/core/pull/6576
> refactor: Extract handle_edit_delete() function for message edit/delete 

- deltachat-rpc-client/src/deltachat_rpc_client/pytestplugin.py
- deltachat-rpc-client/tests/test_something.py
The test now reproduces https://github.com/chatmail/core/issues/6656, and takes 2 minutes to complete (it could easily be made into a failing test by adding a timeout). (the test I added in https://github.com/chatmail/core/pull/6657 tries to use an image `d.png` which doesn't actually exist).
I have no idea how to fix it. I did find out that the bug doesn't appear with gmx.de, but it does appear with nine.testrun.org and testrun.org.
cc @link2xt
> [WIP] test: Add a test for selfavatar-sync

- src/mimefactory.rs
- src/mimefactory/mimefactory_tests.rs
fix #6662 by adding "hidden-recipients:" if To: header would be empty
> fix: Never send empty To: header

- deltachat-rpc-client/src/deltachat_rpc_client/account.py
- deltachat-rpc-client/src/deltachat_rpc_client/pytestplugin.py
- deltachat-rpc-client/src/deltachat_rpc_client/rpc.py
- deltachat-rpc-client/tests/test_something.py
- src/imex/transfer.rs
Found and fixed a bug while investigating https://github.com/chatmail/core/issues/6656. It's not the same bug, though.
Steps to reproduce this bug:
- Create a new profile
- Transfer it to a second device
- Send a message from the first device
- -> It will never arrive on the second device, instead a warning will be printed that you are using DC on multiple devices.
The bug was that the key wasn't created before the backup transfer, so that the second device then created its own key instead of using the same key as the first device.
In order to regression-test, this PR now changes `clone()` to use "Add second device" instead of exporting and importing a backup. Exporting and importing a backup has enough tests already.
This PR also adds an unrelated test `test_selfavatar_sync()`.
The bug …
> fix: Fix setting up a profile and immediately transferring to a second device

- deltachat-rpc-client/tests/test_key_transfer.py
- src/chat.rs
- src/imex/key_transfer.rs
- src/mimefactory.rs
- src/receive_imf/receive_imf_tests.rs
> fix: Don't SMTP-send self-only messages if DeleteServerAfter is "immediate" (#6661)

- deltachat-jsonrpc/src/api.rs
- deltachat-jsonrpc/src/api/types/login_param.rs
- deltachat-jsonrpc/src/api/types/mod.rs
- deltachat-rpc-client/tests/test_securejoin.py
- src/configure.rs
- src/lib.rs
- src/login_param.rs
- src/net/proxy.rs
- src/qr.rs
- src/tools.rs
Four new APIs `add_transport_from_qr()`, `add_transport()`, `list_transports()`, `delete_transport()`, as described in the draft at "API".
The `add_tranport*()` APIs automatically stops and starts I/O; for `configure()` the stopping and starting is done in the JsonRPC bindings, which is not where things like this should be done I think, the bindings should just translate the APIs.
This also completely disables AEAP for now.
I won't be available for a week, but if you want to merge this already, feel free to just commit all review suggestions and squash-merge.
For the new `deltachat-jsonrpc/src/api/types/login_param.rs` file and for the function `to_option()`, it seems to me like there should be a more straightforward way to do things, but probably they are fine as-is.
> api: Sketch add_transport_from_qr(), add_transport(), list_transports(), delete_transport() APIs

- deltachat-jsonrpc/src/api.rs
For consistency with `get_blob_dir()`
> refactor(jsonrpc): Rename copy_to_blobdir() to copy_to_blob_dir()

- src/configure.rs
- src/imap.rs
- src/login_param.rs
- src/smtp.rs
We want to store ConfiguredLoginParam in the database as Json per-login, but proxy_config should be global for all logins.
This is a preparation for multi-transport.
> refactor: Move proxy_config out of ConfiguredLoginParam

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- deltachat-rpc-client/tests/test_securejoin.py
- python/tests/test_1_online.py
- src/chat.rs
- src/chat/chat_tests.rs
- src/contact.rs
- src/message.rs
- src/param.rs
- src/peerstate.rs
- src/receive_imf.rs
- src/securejoin/bob.rs
- src/smtp.rs
- src/stock_str.rs
- src/stock_str/stock_str_tests.rs
- src/sync.rs
- src/webxdc.rs
- test-data/golden/two_group_securejoins
instead of showing addresses in info message, provide an API to get the contact-id. 
UI can then make the info message  tappable and open the contact profile in scope
the corresponding iOS PR - incl. **screencast** - is at https://github.com/deltachat/deltachat-ios/pull/2652 ; jsonrpc can come in a subsequent PR when things are settled on android/ios
the number of parameters in `add_info_msg_with_cmd` gets bigger and bigger, however,  i did not want to refactor this in this PR. it is also not really adding complexity
closes #6702
> feat: get contact-id for info messages

- deltachat-ffi/deltachat.h
- src/chat.rs
- src/securejoin/securejoin_tests.rs
- src/stock_str.rs
this PR leaves one-to-one chats that were created by a QR code scan unwritable until e2ee is established.
the logic of the timeout is reused to show a message with additional information:
if the secure-join finishes faster than the 15 seconds, the middle message is not shown.
closes #6706
> feat: no unencrypted chat when securejoin times out

- flake.nix
Without tox any python `scripts/make-python-env.sh` does not run. Maybe at some point we can even generate the environment for testing with `venvHook` like functionality. We could also add `python3` instead of fixing it to 3.11, but I don't know which version core expects
> Add python and tox to flake.nix devshell

- spec.md
this PR adds description of the `Chat-Edit` and `Chat-Delete` headers to our spec.
corresponding PR introducing the new headers were https://github.com/chatmail/core/pull/6550 and https://github.com/chatmail/core/pull/6576
moreover, the PR does tiny changes wrt wording
closes #6707
> update spec wrt edit/delete, minor rewordings

- src/stock_str.rs
for tuning down email address everywhere, that bit is missing in core.
it was never useful, as it was never shown on the receivers side. and for the sender side, the context the qr code is opened is clear
> feat: remove email address from 'add second device' qr code

- src/chat.rs
- src/receive_imf.rs
- src/receive_imf/receive_imf_tests.rs
- src/tools.rs
> fix: Set GroupNameTimestamp on group promotion (#6729)

- src/receive_imf.rs
next android/desktop/ios releases won't have the "Show Classic Emails" option for chatmail.
to avoid issues with user that have set sth else than "All", we ignore the option alltogether for chatmail profiles.
ftr, i do not expect ppl having that option changed for chatmail much, it does not make much sense. so this PR is mainly to save our limited support resources :) (usecase: "look, i am using chatmail to sign up at SERVICE, but for security reasons i set show=all only when i reset my password" :)
one could also do that in a migration, however, (a) migrations always come with some risk, even the easiest ones, and (b) the show_emails option is subject to change or disappear anyways, subsequent changes are easier in code than in additional or removed migrations, and (c) it is really only …
> handle classic emails as such only in classic profiles

- deltachat-contact-tools/src/lib.rs
Proton vCards now contain this extra `PREF=1` parameter, which threw off our parsing.
Also, Proton vCards now have an extra backslash before the comma here:
```
KEY;PREF=1:data:application/pgp-keys;base64\,
```
AFAIK this is not following the spec, but we can just parse it anyway.
This PR fixes both and adds a test.
> feat: Parse proton vCards again

- src/key.rs
The test works most of the time, but essentially tests that splitting the public key from a private key
generates the same result.
However, it fails if two signatures are generated
at different seconds.
Closes #6762
> test: remove flaky key::tests::test_load_self_existing test

- Cargo.lock
For some reason I don't understand, when I update tokio to 1.44.*, cargo deny complains about openssl.
This is needed to fix CI.
> chore(cargo): bump tokio from 1.43.0 to 1.43.1

- deltachat-ffi/deltachat.h
- src/constants.rs
- src/imex/key_transfer.rs
- src/mimefactory.rs
- src/stock_str.rs
- src/summary.rs
this PR moves now advanced/unsupported ASM strings to core, removing work from translations, esp. as another hint is added which would require retranslations. it is better to have that just in english, it is a nerd feature anyways.
moverover, this PR removes special rendering of ASM in the summary, which might be confusion, but mainly it is now unneeded, dead code
i'll do another android PR that will point to "Add Second Device" already on ASM generation EDIT: done at https://github.com/deltachat/deltachat-android/pull/3726
targets https://github.com/deltachat/deltachat-desktop/issues/4946
> chore: move ASM strings to core, point to "Add Second Device"

- deltachat-rpc-client/tox.ini
- python/tox.ini
Before this PR, it was not possible to see why `ruff format` failed
> ci: Don't make ruff format quiet

- src/configure.rs
The old error message was too confusing.
> feat: Improve error message when the user tries to do AEAP

- deltachat-rpc-client/tests/test_something.py
- python/src/deltachat/testplugin.py
- python/tests/test_1_online.py
- src/config.rs
- src/configure.rs
- src/login_param.rs
- src/provider.rs
- src/receive_imf/receive_imf_tests.rs
- src/sql/migrations.rs
- src/test_utils.rs
Move all `configured_*` parameters into a new SQL table `transports`. All `configured_*` parameters are deprecated; the only exception is `configured_addr`, which is used to store the address of the primary transport. Currently, there can only ever be one primary transport (i.e. the `transports` table only ever has one row); this PR is not supposed to change DC's behavior in any meaningful way.
This is a preparation for mt.
> refactor: Move logins into SQL table

- deltachat-ffi/deltachat.h
- src/stock_str.rs
The phrasing below seems strange, so I've submitted this proposed change
> update 'takes longer' fallback wording again

- Cargo.lock
- deltachat-jsonrpc/Cargo.toml
Move the dev dependencies to `[dev-dependencies]`,
remove the unused `log` dependency.
> chore: clean up `deltachat-jsonrpc` dependencies

- src/chat.rs
- src/securejoin/securejoin_tests.rs
Revert the biggest part of https://github.com/chatmail/core/pull/6722/ in order to fix #6816. Reopens https://github.com/chatmail/core/issues/6706.
Rationale for reverting instead of fixing is that it's not trivial to implement "if the chat is encrypted, can_send() returns true": When sending a message, in order to check whether to encrypt, we load all peerstates and check whether all of them can be encrypted to (`should_encrypt()`). We could do this in `can_send()`, but this would make it quite slow for groups. With multi-transport, the ways of checking whether to encrypt will be different, so in order not to do unnecessary work now, this PR just revert parts of [https://github.com/chatmail/core/pull/6722/](https://github.com/chatmail/core/pull/6817#), so that we can make things work …
> fix: Allow to send to chats after failed securejoin again

- src/chat/chat_tests.rs
This is instead of (closed) #6813
> test: Profile data is attached to group leave messages

- deltachat-ffi/src/lib.rs
- src/chat.rs
- src/chat/chat_tests.rs
- src/imex/key_transfer.rs
- src/message.rs
- src/message/message_tests.rs
- src/mimefactory/mimefactory_tests.rs
- src/receive_imf.rs
- src/receive_imf/receive_imf_tests.rs
- src/webxdc/webxdc_tests.rs
Set `rfc724_mid` in `Message::new()`, `Message::new_text()`, and `Message::default()` instead of when sending the message. This way the rfc724 mid can be read in the draft stage which makes it more consistent for bots. Tests had to be adjusted to create multiple messages to get unique mid, otherwise core would not send the messages out.
close https://github.com/chatmail/core/issues/6621
> Generate rfc724_mid when creating Message

- src/chat.rs
- src/webxdc/webxdc_tests.rs
Fix https://github.com/chatmail/core/issues/6621; I also tested on Android that the webxdc self-addr actually stays the same when staging a draft and then sending.
Follow-up to https://github.com/chatmail/core/pull/6704; #6704 made sure that the webxdc self-addr doesn't change when creating a message and then sending it. This PR here makes sure that the rfc724_mid (which is needed to compute the self-addr) is saved when setting a draft, so that it's loaded properly after a call to get_draft().
cc @adbenitez @r10s @Septias
> fix: Don't change webxdc self-addr when saving and loading draft

- src/receive_imf.rs
- src/tests/verified_chats.rs
- test-data/golden/test_outgoing_encrypted_msg
Particularly, this fixes a scenario when the second device sends a message to the 1:1 chat right after SecureJoin.
Fix #6856
The only thing that i don't understand is whether the pgp-contacts Core adds the contact's fingerprint to 1:1 messages. I only see that this is done for groups (EDIT: looked into logs, can confirm this). If so, the bug isn't specific to the old/current Core, i.e. it can be reproduced with two pgp-contacts devices. And then the contact's fingerprint should be added to 1:1 messages (if there are no reasons not to do so).
> fix: Assign encrypted message to PGP chat if any PGP contacts found (#6856)

- src/chat.rs
- src/chat/chat_tests.rs
closes #6873 , see there for reasoning.
tested that on iOS already, works like a charm - and was much easier than expected as @iequidoo already updated `timestamp_rcvd` on status updates  in https://github.com/chatmail/core/pull/5388
~~a test is missing, ordering is not tested at all, will check if that is doable reasonably easy~~ EDIT: added a test
> feat: sort apps by recently-updated

- .gitignore
- deltachat-jsonrpc/src/api/types/message.rs
- deltachat-jsonrpc/typescript/package.json
- deltachat-jsonrpc/typescript/test/basic.ts
- src/webxdc/webxdc_tests.rs
When an invalid webxdc is set as draft, json-rpc's `get_draft` fails, because `get_webxdc_info` which it calls, fails because the zip reader can not read a non-zip file. With this change, any error occurring in `get_webxdc_info` is ignored and the None-variant is returned instead. I also added a test, that setting invalid xdcs is draft is fine core-wise and checked that the input field stays responsive when a fake.xdc produced like in #6826 is added to draft
close #6826
> Fix(jsonrpc): Do not error on missign webxdc info

- deltachat-contact-tools/src/vcard.rs
- deltachat-contact-tools/src/vcard/vcard_tests.rs
> fix(contact-tools): Escape commas in vCards' FN, KEY, PHOTO, NOTE (#6912)

- src/message.rs
Follow-up to https://github.com/chatmail/core/pull/6925, reasoning is in this comment: https://github.com/chatmail/core/pull/6925#issuecomment-2988282425
> feat: get_showpadlock() returns true for device messages

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
We need this for https://github.com/deltachat/deltachat-android/pull/3793 because it's not clear whether Android should switch to JsonRPC for everything, because of concerns that JsonRPC might be a lot slower than the CFFI (although we still need to measure that precisely - I only did some rough measurements, in which JsonRPC was very slow).
> api(CFFI): Add dc_contact_is_key_contact()

- src/ephemeral.rs
- src/message.rs
- src/receive_imf.rs
The code before was hard to maintain and e.g. `msgs.error` may contain sensitive data.
> feat: Preserve minimum info for trashed messages

- deltachat-repl/src/cmdline.rs
- deltachat-repl/src/main.rs
- The implementation of listverified was removed in commit 37dc1f5ca05bdae8cd911ad495faa2f0e1c6d52a, but it still shows up in the help and in the auto-complete grammar.
- Removed listverified where it still appears.
closes #6971
> fix: Remove listverified from repl

- src/chat/chat_tests.rs
- src/mimeparser.rs
If there is an encrypted List-Id header, it should be preferred over an unencrypted List-Id header.
Part of #6884
> fix: Prefer encrypted List-Id header

- src/receive_imf.rs
- src/receive_imf/receive_imf_tests.rs
Non-members can't modify the member list (incl. adding themselves), modify an ephemeral timer, so they shouldn't be able to change the group name or avatar, just for consistency. Even if messages are reordered and a group name change from a new member arrives before its addition, the new group name will be applied on a receipt of the next message following the addition message because Chat-Group-Name-Timestamp increases. While Delta Chat groups aimed for chatting with trusted contacts, accepting group changes from everyone knowing Chat-Group-Id means that if any of the past members have the key compromised, the group should be recreated which looks impractical.
This is in continuation of the discussion in #6901.
> feat: Don't apply chat name and avatar changes from non-members

- src/chat.rs
- src/context.rs
- src/receive_imf.rs
- src/securejoin.rs
- src/test_utils.rs
- src/tools.rs
Add `logged_debug_assert` macro logging a warning if a condition is not satisfied, before invoking `debug_assert!`, and use this macro where `Context` is accessible (i.e. don't change function signatures for now).
Follow-up to 0359481ba487d7eea7747a4c401dfdd97423e68a.
> feat: Log failed debug assertions in all configurations

- deltachat-ffi/deltachat.h
- src/chat.rs
- src/config.rs
- src/context.rs
- src/stock_str.rs
See commit messages. There are no tests (the change is as simple as possible, i don't want to maintain tests for such "features"), have done a quick check in Desktop.
Close #6913
> feat: Donation request device message (#6913)

- deltachat-jsonrpc/src/api.rs
- src/chat.rs
- src/chat/chat_tests.rs
Let's discuss the naming here. At the Core level we don't need two separate APIs, so `create_group_ex()` or smth similar should work. The question is the naming in json-rpc (and CFFI if we decide to add it). Alternatives:
- `create_email_group_chat()` or just `create_email_chat()` (the word "chat" is needed to make it clear that a chat is created, not a message. Actually chat ID is returned). We don't use the word "email" for this purpose in the code currently, but maybe we want to switch to it. I'm not involved in the discussions a lot, so can't say much. But my "external" opinion is that technically everything is email and using this word only for a subset of chats/messages would complicate undestanding the code for newcomers and external audit. But if we switch to "email", probably we …
> api: Unencrypted group creation (#6927)

- README.md
- deltachat-repl/src/cmdline.rs
- After the revisions to support key contacts, the 'listcontacts' command in the repl only lists key-contacts.  A separate flag now has to be passed to Contact::get_all() to list address contacts. This makes it difficult to run the example in README.md because we need to see the new contact so we can get its ID for the next command in the example, that creates a chat by ID.
- Revised 'listcontacts' command to make a second call to Contact::get_all() with the DC_GCL_ADDRESS flag, then print the e-mail contacts after the key contacts.
- Revised configuration example in top-level README.md to reflect current command output.
fixes #7011
> fix: List e-mail contacts in repl listcontacts command

- deltachat-ffi/deltachat.h
- deltachat-jsonrpc/src/api/types/chat.rs
- src/chat.rs
- src/config.rs
- src/context.rs
- src/imex.rs
came over these parts while targeting the new info message of https://github.com/chatmail/core/pull/7008 in https://github.com/deltachat/deltachat-ios/pull/2778 and https://github.com/deltachat/deltachat-android/pull/3822
> docs: deprecate protection-broken and related stuff

- src/sql/migrations.rs
Previously, chat protection was only removed if the chat became an email-chat because the key-contact has a different email, but not if the chat became an email-chat for a different reason.
Therefore, it could happen that the migration produced a protected, unencrypted chat, where you couldn't write any messages.
I tested that applying this fix actually fixes the bug I had.
> fix: Mark all email chats as unprotected in the migration

- deltachat-ffi/deltachat.h
- deltachat-jsonrpc/src/api/types/chat.rs
- deltachat-jsonrpc/src/api/types/contact.rs
- deltachat-jsonrpc/src/api/types/events.rs
this PR adapts the documentation UI guidance to recent "green checkmark" discussions
cmp https://github.com/deltachat/deltachat-pages/pull/1145, https://github.com/deltachat/deltachat-ios/pull/2781, https://github.com/deltachat/deltachat-android/pull/3828, https://github.com/deltachat/deltachat-desktop/pull/5318
> docs: clarify the meaning of is_verified() vs verifier_id()

- src/context.rs
The info will look like:
```
debug_assertions=On - DO NOT RELEASE THIS BUILD
```
or:
```
debug_assertions=Off
```
I tested that this actually works when compiling on Android.
<details><summary>This is how it looked before the second commit</summary>
<p>
The deltachat_core_version line in the info will look like:
```
deltachat_core_version=v2.5.0 [debug build]
```
or:
```
deltachat_core_version=v2.5.0 [release build]
```
I tested that this actually works when compiling on Android.
</p>
</details>
> feat: Put the debug/release build version into the info

- deltachat-ffi/deltachat.h
- deltachat-jsonrpc/src/api.rs
- src/chat.rs
Fixes https://github.com/deltachat/deltachat-desktop/issues/5215.
Tested in DC Desktop by hand. Would be nice to add a Rust test. Also needs testing in DC Android at least, it somehow works correctly even w/o this fix, so it can break.
> fix: get_chat_msgs_ex(): Report local midnight in ChatItem::DayMarker

- src/smtp.rs
detection of 'invalid unencrypted mail'  is used as a condition to add a dedicated error info message to the chat, that UI even recognizes and show how information on tap
the string was recently changed from lowercase to Title Case at https://github.com/chatmail/relay/pull/538 - this PR ignores case.
with this PR, the info-message appears again as follows:
makes sense to have a test with the real relay, however, just now, i am not deep enough into python
> fix: ignore case when trying to detect 'invalid unencrypted mail' 

- deltachat-ffi/deltachat.h
- src/ephemeral.rs
- src/stock_str.rs
this PR adds strings for having disappearing messages set to "1 year".
"one year" is 365 ~ 367 days; the latter if we decide to have a little more than 1 year (there was some post about signal (?) doing that, so user can find the posts from exactly one year ago, but i cannot find that again)
counterpart of https://github.com/deltachat/deltachat-android/pull/3467 and many forum discussions
> better string when using disappearing messages of one year 

- src/test_utils.rs
In order to debug some test failures wrt broadcast channels, I need to read the log of some tests that have an alice0 and an alice1.
It's currently not possible to tell whether a line was logged by alice0 or alice1, so, I would like to change that with this PR.
Edit: Turns out that there are more tests that call their profiles "alice1"/"alice2" (or "alice"/"alice2") than "alice0"/"alice1". So, I changed the logging to count "alice", "alice2", "alice3", ….
Not sure whether I should adapt old tests; it might save someone some confusion in the future, but I might also make a mistake and make it so that the test doesn't properly test anymore.
> test: Log the number of the test account if there are multiple alices

- src/reaction.rs
- src/receive_imf.rs
[RFC 9078 "Reaction: ..."](https://www.rfc-editor.org/rfc/rfc9078.html) doesn't forbid messages with reactions to have other parts, so be prepared for this.
Replacement for #6769.
> fix: Make reaction message hidden only if there are no other parts

- src/chat.rs
- src/chat/chat_tests.rs
Will add a test for `feat: Chat::get_color(): Use grpid, if present, instead of name` if the commit is agreed... Done.
> feat: create_group_ex(): Log and replace invalid chat name with "…"

- src/tools/tools_tests.rs
test_maybe_warn_on_outdated() can also fail when run with `cargo test`, rather than `cargo nextest` (just happened to me)
> test: Add another TimeShiftFalsePositiveNote

- src/calls.rs
- src/calls/calls_tests.rs
- src/receive_imf.rs
this PR uses the initial "call messages" (that has a separate viewtype since #7174) to show all call status.
this is what most other messengers are doing as well. additional "info messages" after a call are no longer needed.
on the wire, as we cannot pickpack on visible info messages, we use hidden messages, similar to eg. webxdc status updates.
in future PR, it is planned to allow getting call state as a json, so that UI can render nicely. it is then decided if we want to translate the strings in the core.
successor of https://github.com/chatmail/core/pull/6650
> feat: hide call status change messages

- deltachat-jsonrpc/src/api/types/events.rs
- src/events/payload.rs
- src/securejoin.rs
- src/securejoin/securejoin_tests.rs
Quoting @adbenitez:
> I have been using the SecurejoinInviterProgress event to show a welcome message when user scan the QR/link of the bot (== starts a chat with the bot) 
> but this have a big problem: in that event all you know is that a contact completed the secure-join process, you don't know if it was via certain 1:1 invite link or a group invitation, then a group-invite bot would send you a help message in 1:1 every time you join a group with it
Since it's easy enough to add this information to the SecurejoinInviterProgress event, I wrote a PR to do so.
> api: Put the chattype into the SecurejoinInviterProgress event
