chatmail/core

- examples/simple.rs
E.g.
```
[ERROR_NETWORK]   
Could not connect to IMAP-server imap.deltachat.net:993 using SSL. (Error #43)
```
> print out data2 for Event::ERROR_NETWORK as well

- src/dc_location.rs
```
b"SELECT foo\
FROM bar"
```
seems to result in `SELECT fooFROM bar` instead of `SELECT foo FROM bar`.
there are probably more of these problems, i can check this.
> fix spaces at the line ends

- deltachat-ffi/src/lib.rs
> refactor: cast bool functions to libc::c_int instead of if-else

- src/dc_mimeparser.rs
- src/dc_receive_imf.rs
- tests/stress.rs
`dc_mimeparser_new()` constructor takes both blobdir and context, but only
uses the blobdir from the context and doesn't care about parser.blobdir,
this can be removed safely since only used internally.
> chore: remove blobdir member from dc_mimeparser_t struct

- src/dc_apeerstate.rs
- src/dc_imex.rs
- src/dc_key.rs
- always verify keys
- ensure serialized blobs stay allocated until written to sqlite
> fix: ensure keys are always valid

- src/dc_aheader.rs
- src/dc_e2ee.rs
- src/dc_imex.rs
- src/dc_key.rs
- src/dc_keyring.rs
- src/dc_pgp.rs
- tests/stress.rs
- assume valid keys in the db
- verify keys on import from headers + disk
- use references in keyring when possible
> perf: reduce verification load

- src/key.rs
> fix(key): return None when empty binary is loaded

- src/dc_log.rs
i think the `$crate::dc_tools::dc_strdup()` is not needed for passing strings to the ffi-callback function. the ffi-callback function must treat these strings are being `const` and must not _not_ `free()` them. if the ffi-callbacks need the strings longer (eg. for queing), they must do a copy.
not totally sure, however, `to_ptr()` should do the job here as the return value is probably valid as long as the cstring-object exists - and this is a bit longer as the call to the ffi-callback function.
> remove unneeded string duplication and fix memory leak

- python/tests/test_account.py
- src/context.rs
dc_get_info() returned the compile date in core-c (by just adding `__DATE__` and `__TIME__` to a string). by the conversion, this was replaced by a static timestamp, which is of few use.
however, apart from that i did not found an easy way to get the compile time as a usable string (okay, i searched only for 30 seconds or so ;) the compile time as a hardcoded string also has the potential problem to avoid reproducible builds which may be handy in the future.
also, it was of very few use in the past at all (handy only if i forgot to increase the version number ;)
so, i'd suggest to remove it completely.
> feat: remove compile date

- Cargo.toml
- ci_scripts/ci_upload.sh
- src/dc_tools.rs
- src/lib.rs
Flubs awesome string conversion + fmt.
> feat: Add utility to convert OsStr to CString

- examples/repl/cmdline.rs
- examples/repl/main.rs
- src/context.rs
- src/dc_array.rs
- src/dc_configure.rs
- src/dc_contact.rs
- src/dc_e2ee.rs
- src/dc_imex.rs
- src/dc_job.rs
- src/dc_location.rs
- src/dc_mimeparser.rs
- src/dc_param.rs
- src/dc_qr.rs
- src/dc_receive_imf.rs
- src/dc_securejoin.rs
- src/dc_sqlite3.rs
- src/dc_tools.rs
- src/imap.rs
- src/smtp.rs
The function does a cast and does not create a new objects.  The
stdlib convention is to use to_*() for functions which return new
objects and as_*() for functions which keep referring to the same data
but using a different type.  Follow that convention.
> Rename to_str() -> as_str() to match stdlib naming convention

- .gitignore
- ci_scripts/run_all.sh
- python/README.rst
- python/src/deltachat/__init__.py
- python/src/deltachat/_build.py
- python/tox.ini
- run-integration-tests.sh
This links the python bindings statically to libdeltachat.a if the
DCC_RS_DEV environment variable is set to the project's root.  This is
a little simpler then requiring the manual CFLAGS and LD_LIBRARY_PATH
tweaking.
It also adds a script to easily invoke the integration tests locally
without forgetting steps.
> For development statically link dcc-rs

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/repl/main.rs
- examples/simple.rs
- run-integration-tests.sh
- src/context.rs
- src/dc_chat.rs
- src/dc_configure.rs
- src/dc_contact.rs
- src/dc_imex.rs
- src/dc_job.rs
- src/dc_location.rs
- src/dc_log.rs
- src/dc_msg.rs
- src/dc_receive_imf.rs
- src/dc_securejoin.rs
- src/dc_stock.rs
- src/peerstate.rs
- tests/stress.rs
This fixes the segfault in #143 but doing this here as a separate PR to make reviews easier.  It also simplifies callback calling as bonus.
The gory details by way of commit message:
The C API allows passing a NULL pointer is for the callback function.
However when calling the callback nothing checks for this null pointer
and thus things fail badly.  Even worse since the C API is defined
using an "fn pointer" rather than a "*-ptr" or raw pointer to the
function rust does not realise this can be invalid and therefore the
typechecker does not catch this even though there are no unsafe casts.
Fix this by making the callback an Option in rust, this can be easily
checked when calling.  Also add a Context.call_cb() function which
simplifies calling the callback, hides the weird syntax due to …
> Make the callback optional again

- examples/repl/cmdline.rs
- src/context.rs
- src/dc_chat.rs
- src/dc_chatlist.rs
- src/dc_configure.rs
- src/dc_contact.rs
- src/dc_e2ee.rs
- src/dc_imex.rs
- src/dc_job.rs
- src/dc_jobthread.rs
- src/dc_location.rs
- src/dc_loginparam.rs
- src/dc_mimefactory.rs
- src/dc_move.rs
- src/dc_msg.rs
- src/dc_qr.rs
- src/dc_receive_imf.rs
- src/dc_securejoin.rs
- src/dc_sqlite3.rs
- src/dc_token.rs
- src/dc_tools.rs
- src/imap.rs
- src/key.rs
- src/keyring.rs
- src/oauth2.rs
- src/peerstate.rs
- tests/stress.rs
Experiment with refactoring the internal sql interface a bit.  My
original goal was to modify the schema and thus refactor to a state
where it would be sane to write tests for dc_sqlite_open() (and/or
however it ends up refactored) to assert schame changes before/after.
> Refactor the internal sql interface somewhat

- src/dc_sqlite3.rs
This doesn't do much, but it is significant since putting these guarantees in place makes gradually refactoring the API in this module much safer.
In general after having played a bit with #142 I'd like to enable being able to contain changes a little more, e.g with this change, it will be easier to change the sqlite backend without having to modify lots of unrelated code.  Perhaps some signatures of other functions in dc_sqlite need to change too first but each signature change/cleanup could be handled separately and much more safely.
With the API changes already done, notably .is_open(), the
implementation of the sqlite can and should now be private.
This also doesn't need to be #[repr(C)] anymore since the C API does
not need to access the fields in the struct.
> Make the SQLite struct opaque

- Cargo.toml
- ci_scripts/run_all.sh
- python/setup.py
- python/src/deltachat/__init__.py
- python/src/deltachat/account.py
- python/tests/test_account.py
- python/tox.ini
- src/dc_imex.rs
- src/dc_tools.rs
add python test for export/import and probably fix #125 -- there was a missing ``} else {`` in dc_imex.rs
also use info/error macros instead of raw dc_log_info/error in dc_imex
and run linting for the python bindings. 
remove all "sync" calls to context callback as rust-core does not do them (and thus, strictly speaking, the callback could return void instead of int but this is not part of this PR)
> Imex tests and fix for export-blobs

- src/context.rs
- src/dc_jobthread.rs
Remove the unsafe parts. Some functions in this file had to stay unsafe because they get a Context object as a parameter, which contains raw pointers.
> Make dc_jobthread_t safe

- src/context.rs
- src/dc_jobthread.rs
referencing via &jobthread.name was the culprit but not sure ;) fixes #176
> fix #176 by transforming unsafe dc_log_info calls -- i think the unsafe

- ci/run.sh
- src/key.rs
- tests/stress.rs
This makes interactively running the tests a much more pleasant
experience rather than something one dreads.  These tests will still
be run on the CI.  To run these manually run:
cargo test [TESTNAME] -- --ignored
> Ignore expensive tests by default

- src/top_evil_rs.py
PEP-0394 (https://www.python.org/dev/peps/pep-0394/) recommends to use more specific shebangs.
For example, Debian allows /usr/bin/python to be configured to python2 via `update-alternatives python`, but the script does not work with Python 2.
> src/top_evil_rs.py: fix shebang to always use Python 3 and make it executable

- python/src/deltachat/_build.py
- python/tests/conftest.py
- python/tox.ini
- run-integration-tests.sh
- Pass extra_link_args when using an installed libdeltachat
- Allow setting the liveconfig by envvar
- Show lifeconfig path in the pytest summary line
- Pass required envvars through tox
- Fix broken liveconfig passing in run-integration-test.sh
- Allow comments in the liveconfig file
> Several fixes to the intergration tests

- src/dc_chat.rs
- src/dc_imex.rs
- src/dc_job.rs
- src/dc_location.rs
- src/dc_mimefactory.rs
- src/dc_mimeparser.rs
- src/dc_msg.rs
- src/dc_param.rs
- src/dc_qr.rs
- src/dc_receive_imf.rs
- src/dc_securejoin.rs
- src/sql.rs
Also document each type they store.  This makes existing code a little
more readable and gives some hints towards refactoring this.
> Use DC_PARAM_* constants everywhere

- deltachat-ffi/build.rs
- deltachat-ffi/deltachat.pc.in
This is writes pkg-config/deltachat.pc file in the target directory,
using the PREFIX environment variable at build time.  If this is
undefined at build time /usr/local is used.
No attempt at installing this or any other files is made at this time.
Fixes #170
> Write a deltachat.pc file at build time

- examples/repl/cmdline.rs
- examples/simple.rs
- src/context.rs
- src/dc_chat.rs
- src/dc_configure.rs
- src/dc_contact.rs
- src/dc_imex.rs
- src/dc_job.rs
- src/dc_loginparam.rs
- src/dc_msg.rs
- src/dc_receive_imf.rs
- src/imap.rs
- src/oauth2.rs
- src/sql.rs
For a few of the locations where error handling is done correctly this
does the right thing.  For most other places it gracefully ignores any
issues which is what the original code did as well.  Errors are
already logged by the called functions in those cases.
> Silence warnings from ignored Result values

- python/src/deltachat/account.py
- python/tests/test_account.py
- src/dc_contact.rs
the rust-logic was inverted -- you can not delete a contact that still has messages with it.
> add test, fix and high level python api for dc_delete_contact

- src/context.rs
- src/dc_array.rs
- src/dc_location.rs
dc_location_t is an incomplete copy of _dc_location
The difference is that it lacks `int independent` field.
As a result, calloc did not allocate memory for this field.
deltachat-core (C version) has only one dc_location_t, that includes the last field.
> Remove dc_location_t

- src/dc_chat.rs
Previously, dc_send_text_msg() silently returned 0 in case of incorrect
input. This way "send" command in repl reported "Sending failed" without
any clue what exactly went wrong.
It seems that FFI functions already call `warn!`, but maybe in this particular case it would be better to add error checking on "send" is `cmdline.rs`. Opinions?
> Improve error handling in dc_send_text_msg()

- src/sql.rs
This patch changes output of following command (from README.md)
$ cargo run --example repl -- /tmp/main.db
from
First time init: creating tables in ""/tmp/main.db""
[...]
Opened ""/tmp/main.db"".
to
First time init: creating tables in "/tmp/main.db"
[...]
Opened "/tmp/main.db".
Note lack of double quotation mark, which was confusing and could have been
interpreted as part of file name.
> Improve punctuation of message, printed by "repl" program

- examples/repl/cmdline.rs
- src/constants.rs
- src/dc_chat.rs
- src/dc_contact.rs
- src/dc_imex.rs
- src/dc_job.rs
- src/dc_mimefactory.rs
- src/dc_msg.rs
- src/dc_securejoin.rs
this replaces hopefully all uses of msg state numbers and types with their respective constants. 
also declare the constants as i32 to avoid casts.  (i guess macros were defined as usize by c2rust or so)
> carefully replace msg state and type numbers with constants

- src/constants.rs
- src/dc_chat.rs
- src/dc_tools.rs
- tests/stress.rs
This is a two-commit PR where you only [need to review the first commit](https://github.com/deltachat/deltachat-core-rust/commit/8628d3d54031beff3d3ad08cdd6aeffd2c33c124).  The second commit is purely a "cargo fmt" which performs a lot of deindentation and does not need reviewing given that "cargo fmt" does not introduce errors.  So if you are fine with the first commit, please merge this PR. 
The PR also uses some DC_CHAT_TYPE_* constants but using them more consistently everywhere is for a different PR. 
FWIW I went with the "OK_TO_CONTINUE" pattern to replace the "current_block" and "match current_block ..." constructs.  This only changes few lines compared to trying to do go for a "cleanup" closure.
> remove current_block/goto reminiscenes in dc_chat.rs

- python/doc/api.rst
- python/doc/conf.py
- python/setup.py
- python/src/deltachat/account.py
- python/src/deltachat/chatting.py
- python/src/deltachat/message.py
- python/tests/test_account.py
- python/tests/test_increation.py
- python/tox.ini
- properly support prepare-msg API and implement get_message_info()
- make API safer wrt to prepare-msg usage 
- remove usage of "attr.s" across the code
- simpler, safer API usage: merge MessageType, MessageState functionality all into the Message class
- add chat.set_draft|get_draft API
- make msg.set_file() copy a file into blobdir if it isn't already
- regroup tests
- simplify caching of dc_msg
> rework python high level mechanics, re-group tests 

- examples/repl/cmdline.rs
This change replaces calls to unwrap() function with "?" operator, propagating
error up the call stack. This way "chat foo" (for example) command results in
Error: invalid digit found in string
message instead of crashing whole repl.
> Make repl program more robust

- examples/repl/cmdline.rs
Previously, just pressing "<Enter>" at prompt resulted in following error
message:
Error: Unknown command: "" type ? for help.
This message is harmless, but useless.  Also, such behaviour is different from
many (if not all) interactive environments: python, bash, dash, ...
With this change empty input string is silently ignored.
> repl: do not treat empty string as command

- python/src/deltachat/account.py
- python/tests/test_lowlevel.py
- src/dc_msg.rs
ignore if we get no rows for a message (eg desktop calls itwith msg_id=9 which is a special id -- and C just ignored it
> (jikstra, hpk) fix markseen logic to work like C

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/simple.rs
- src/chatlist.rs
- src/dc_chat.rs
- src/dc_chatlist.rs
- src/dc_imex.rs
- src/dc_lot.rs
- src/dc_tools.rs
- src/error.rs
- src/lib.rs
Split into 3 commits to make review easier.
Added some helper macros for error handling, to make it easier to use results in the process.
> Rusty Chatlist

- src/context.rs
- src/dc_array.rs
- src/dc_chat.rs
- src/dc_contact.rs
- src/dc_location.rs
The goal is to replace dc_array_t with a wrapper for Vec, while keeping the same C API.
See #50
> dc_array_t cleanup

- src/dc_msg.rs
It is broken since 8a0fc609e6c1aa61947ee9fa965d87b104b6a716
where 0i32 was replaced with true instead of false.
> Fix dc_msg_is_setupmessage

- src/dc_imex.rs
payload_c binding makes sure the memory is not freed until strdup exits.
See as_ptr documentation:
https://doc.rust-lang.org/std/ffi/struct.CString.html#method.as_ptr
> dc_decrypt_setup_file: extend lifetime of CString

- src/context.rs
- src/dc_array.rs
- src/dc_chat.rs
- src/dc_contact.rs
- src/dc_location.rs
By convention as_* functions do not consume self by taking the reference.
> Rename dc_array_t::as_ptr() into dc_array_t::into_raw()

- src/top_evil_rs.py
For example, constants.rs is completely safe now, but has "free()" in the comments.
> top_evil_rs.py: remove comments before counting

- src/constants.rs
- src/context.rs
- src/dc_chat.rs
- src/dc_configure.rs
- src/dc_contact.rs
- src/dc_e2ee.rs
- src/dc_imex.rs
- src/dc_job.rs
- src/dc_location.rs
- src/dc_loginparam.rs
- src/dc_mimefactory.rs
- src/dc_mimeparser.rs
- src/dc_msg.rs
- src/dc_receive_imf.rs
- src/dc_saxparser.rs
- src/dc_simplify.rs
- src/dc_strencode.rs
- src/dc_token.rs
- src/dc_tools.rs
- src/lib.rs
- src/types.rs
In face of ambiguity, refuse temptation to guess.
Since I was not sure how correctly convert 'iCnt', 'pathNfilename',
to snake_case, I just added override instead.
Changes:
86c0653 (Dmitry Bogatov, 4 minutes ago)
Override `non_camel_case_types` warning on per-declaration basis
f9c7a30 (Dmitry Bogatov, 40 minutes ago)
Override `non_shake_case' warning on per-function basis
This change removes global override of `non_shake_case' warning and
replaces it with per-function overrrides. This way, compiler will complain
about style guide violation in new code.
It should be noted, that `rustc' is not smart enough to emit warning when 
override is no longer needed, it must be checked manually.
3117208 (Dmitry Bogatov, 3 hours ago)
Fix 'non_upper_case_globals' compiler warnings
> Avoid per-project compiler warnings override (ref: #55)

- ci/run.sh
- src/chatlist.rs
- src/dc_array.rs
- src/x.rs
Previous pull-request on this left two warnings behind, this should fix
them and make such oversights impossible by treating warnings as errors
-- CI should catch them.
> Actually fix all compiler warnings

- Cargo.lock
- deltachat-ffi/Cargo.toml
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/constants.rs
- src/dc_chat.rs
- src/dc_imex.rs
- src/dc_job.rs
- src/dc_location.rs
- src/dc_mimefactory.rs
- src/dc_msg.rs
- src/dc_securejoin.rs
- src/lib.rs
With this change, kind of message is represented by value of type `Viewtype'
instead of raw libc::c_int, providing more type safety. There are constants
of type `Viewtype' defined, corresponding to DC_MSG_* constants.
The only way to create `Viewtype' from libc::c_int is smart constructor, which
disallow all values, except DC_MSG_* constants.
With this change, functions `dc_get_chat_media' and `dc_get_next_media' became
less forgiving about invalid message type arguments. Previously, invalid
message types were implicitly interpreted as 0 (Viewtype::Unknown). Now,
function calls with invalid message type arguments are rejected (error code
returned) on FFI boundary.
Additionally, when `Viewtype' is read from database, it is checked to have
sensible value.
No tests assumed forgiving …
> Introduce new type: Viewtype

- Cargo.lock
- Cargo.toml
A fix for the non utf8 strings has been merged and released in `0.20`
> feat(deps): update rusqlite to official version again

- examples/repl/cmdline.rs
- src/dc_imex.rs
- tests/stress.rs
For starters just a unittest.
It shows that the current setup message mixes `\r\n` and `\n` line endings.  That's something that probably requires some scrutiny.
> Safer string handling in AC setup message

- python/src/deltachat/message.py
Somewhy several tests on master fails locally for me, and root of problem was
that Message was created with NULL underlying dc_msg, so errors manifest
themself several function calls later.
This assert makes sure that error is caught as early as possible.
> python: assert that underlying dc_msg_t* for Message is not NULL

- src/dc_chat.rs
The sql statement didn't expect more than one message to have the same timestamps, so it sometimes gave back wrong results.
See the first entry having a wrong chat id.
_We should also fix this in the C core...._
> Fix "In-Reply-To acting weird"

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/repl/main.rs
- examples/simple.rs
- src/dc_chat.rs
- src/dc_location.rs
- src/dc_lot.rs
- src/dc_mimefactory.rs
- src/dc_msg.rs
- src/dc_securejoin.rs
- src/lib.rs
Also, remove `send-garbage' command from REPL, since it is not possible to send
non-utf8 string anymore.
> change type of dc_msg_t.text to String

- deltachat-ffi/src/lib.rs
Change code to panic! on invalid input (null pointers, out-of-range
identifiers) instead of silently doing nothing.
> Add more assertions to `deltachat-ffi' library

- src/dc_e2ee.rs
There are 3 methods with goto blocks, each method is processes in a seperate commit to make things understandable.
> Remove gotos from dc_e2ee

- src/chatlist.rs
- src/constants.rs
`fromid == 0`
was translated to
`(*lastmsg).from_id == DC_CONTACT_ID_SELF as u32`
in a previous refactoring https://github.com/deltachat/deltachat-core-rust/pull/238 (https://github.com/deltachat/deltachat-core-rust/pull/238/files#diff-be6aa465b7fdd075d577ca0278ac0dffL377 to https://github.com/deltachat/deltachat-core-rust/pull/238/files#diff-6c7f44e9e741553e1e92cb62ff03b7ddR295)
but `DC_CONTACT_ID_SELF` is 1
(also the code makes no sense with `DC_CONTACT_ID_SELF` because that would mean: treat my own messages as they wouldn't exist in the chatlist summary)
> fix own messages displayed as noMsgs in summary

- python/tests/test_account.py
- src/dc_dehtml.rs
- src/dc_e2ee.rs
- src/dc_job.rs
- src/dc_mimeparser.rs
- src/dc_receive_imf.rs
- src/dc_simplify.rs
Desktop with current master is heavily broken. This is a attempt of fixing it "sufficiently" and a bit of a random mix of fixing commits.  
This PR also contains three fixes that, together with friedel's changes let python liveconfig tests pass again and also probably fixes #223.  The #233 remains an open issue and is not fixed yet.
> Fix broken string allocations in message handling

- python/tests/conftest.py
- python/tests/test_account.py
- src/dc_e2ee.rs
- src/dc_mimefactory.rs
- src/peerstate.rs
this adds a rust and python test and fixes #233 -- and is on top of #306 but still against master. 
please feel free to add commits to cleanup the sql-error-handling code -- i am sure there are more elegant ways than what i came up with quickly.
> fix encryption-not-available #233

- src/constants.rs
- src/context.rs
- src/dc_move.rs
- src/dc_msg.rs
- src/sql.rs
- src/types.rs
By the way, I noticed that `MoveState = Pending` is not used anywhere. It is okay?
> Replace DC_MOVE_* constants with enum

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/contact.rs
- src/dc_configure.rs
- src/dc_e2ee.rs
- src/dc_imex.rs
- src/dc_securejoin.rs
- src/dc_tools.rs
- src/test_utils.rs
This marks the function safe and returns Result, it also now returns
the ConfiguredAddr since it has to look this up anyway and it makes
testing more easy.  Turns out it reduces some duplicate SQL query in
some callers too.
More test code has been moved from dc_imex to test_utils as it's
more genrally applicable.
> Turn dc_ensure_secret_key_existy into something more rusty

- deltachat-ffi/src/lib.rs
- examples/repl/main.rs
- src/context.rs
My goal is to make Context more Rusty by removing dc_open() and dc_close() but without changing the C API.  In a next step I plan to make some kind of wrapper struct which the ffi dc_context_new() would return which contains an Option<Context> and thus the dc_open()/dc_close() API can create and destroy the Context that way.
This removes the dc_context_unref function from the Rust API which was
just an alias for dc_close.  It still exists on the C API where it
makes sure to free the memory.
It also implements Drop for the context which just calls dc_close to
make sure all the memory is freed.  Since you can call dc_close as
many times as you like this ensures that at the Rust level you can't
Drop the struct without releasing the memory.
Finally since memory is now freed by dropping the …
> Remove dc_context_unref from Rust API

- src/dc_array.rs
- src/dc_tools.rs
They annoyed me because I couldn't stage them in my other branches because they were on files I didn't change.
> Cargo fmt: removed two empty lines

- ci_scripts/ci_run.sh
- ci_scripts/docker-coredeps/deps/build_rust.sh
- ci_scripts/run_all.sh
- python/README.rst
- python/install_python_bindings.py
- python/src/deltachat/_build.py
- python/src/deltachat/account.py
- python/tests/conftest.py
- python/tox.ini
- run-integration-tests.sh
this is a rework of python liveconfig test support, with an improved/simplified readme.  This PR also adds support for DCC_PY_LIVECONFIG pointing to an https-service that will automatically create accounts and can be used from the CI now.  However, the liveconfig tests are disabled for now because  #331 and #326 prohibit clean runs.  I still recommend to merge this PR which does not change rust code or rust-builds/tests.  Once the issues are fixed liveconfig tests will run in the CI if run_all.sh removes the "unset DCC_PY_LIVECONFIG" line which is already set as a hidden variable in circle-ci, and provides a https-url with a token to be able to create accounts on the fly on testrun.org.  The http-service counterpart code is prototyped at …
> streamline python test runs, make DCC_PY_LIVECONFIG support  https-account creation

- examples/repl/cmdline.rs
this pr fixes the `chats` command in the cmdline tool.
- show all chats if no query is given
- show whole result if a query is given
> fix 'chats' command in cmdline tool

- src/dc_receive_imf.rs
there was a logic error that avoided most of create_or_lookup_group() being executed ever.
just a misplaced curly bracket, skipped cargo fmt for now to keep things simple.
should be merged before https://github.com/deltachat/deltachat-core-rust/pull/332 is merged.
> continue processing when there is a grpid

- examples/repl/cmdline.rs
- examples/repl/main.rs
This might me controversial, but I like to have it.
Let's use :+1: and :-1: to vote for it.
> add quit command as alias to exit in cmdline

- README.md
- src/context.rs
- src/dc_e2ee.rs
The function is made safe and now returns Result.  Functionally it now
fails when it can not write the newly generated key to the database
whereas before it still returned the key but logged a warning.  There
is no reason this shouldn't be able to store the key and silently not
storing the key may result in later operations assuming the key is
available, so failing seems like a better choice.
The function now also uses a proper mutex to guard against multiple
threads generating keys.  And this mutex is Context-scoped rather than
fully global (static).
> Safe load_or_generate_self_public_key

- src/dc_e2ee.rs
Changes:
82cdb4f (Dmitry Bogatov, 54 секунды назад)
cargo fmt
127ddad (Dmitry Bogatov, 4 минуты назад)
Remove redundant check
Condition '!imffields.is_null()' is always true, since it is contained in
conditional
if !(in_out_message.is_null() || imffields.is_null()) {
which is equivalent to
if !in_out_message.is_null() && !imffields.is_null() {
> Remove redundant check

- Cargo.lock
- Cargo.toml
- deltachat_derive/Cargo.toml
- deltachat_derive/src/lib.rs
- src/constants.rs
With this macro it is possible to #[derive(ToSql, FromSql)] for enums, that do
not contain data (C-style).
This pull request is alternative to #317.
> Implement procedural macro to derive {To,From}Sql traits

- src/dc_chat.rs
- src/dc_receive_imf.rs
fix #355 -- these were unconvered by "rg dc_array_unref" which turned up valid cases for the array being null.  cc @kaction
> fix failing array asserts #355

- src/dc_configure.rs
DC_EVENT_CONFIGURE_PROGRESS shall send out 0 for failure, 1..999 for progress information and 1000 on success.
- as all DC_EVENT_CONFIGURE_PROGRESS  events are emmited by the `progress!` macro, this macro must allow all values from 0..1000
- moreover, the fist progress must not be `0` as this would indicate failure (in the c-core the progress macro was _only_ used for progress, so [calling progress(0)](https://github.com/deltachat/deltachat-core/blob/master/src/dc_configure.c#L726) worked _there_)
so, with this pr and the already merged #354 everythingShouldBeFine(tm)
> send DC_EVENT_CONFIGURE_PROGRESS(0) on failure and only on failure

- src/dc_configure.rs
do not allow bad paramters given to the maco, as suggested at https://github.com/deltachat/deltachat-core-rust/pull/358#pullrequestreview-274574939
> simplify progress! macro

- src/config.rs
- src/constants.rs
- src/context.rs
- src/dc_mimefactory.rs
This removes the duplication of the version string between the `Cargo.toml` and `constants.rs`
> feat: load package version during build

- src/dc_chat.rs
...Show the contacts display_name instead as defined in:
https://c.delta.chat/classdc__chat__t.html#a0fb1b4850bcd899eaa06d23648a1efaf
"For one-to-one chats, this is the name of the contact"
> fix chat name empty when contact has no name

- Cargo.lock
- Cargo.toml
- examples/repl/cmdline.rs
- src/dc_job.rs
- src/dc_mimeparser.rs
- src/dc_tools.rs
- src/error.rs
Uses a crate now for extracing image meta data, instead of our own hand rolled code.
> refactor(tools): cleanup and make clippy a little happier

- src/dc_chat.rs
ok_to_continue=false
Got very likely introduced by https://github.com/deltachat/deltachat-core-rust/pull/229
> Fix panic in dc_set_chat_profile_image because of missing

- src/dc_tools.rs
fixes #375 -- i guess that after @dignifiedquire's  #374 the unsafe version can go for good.
> remove redundant unsafe dc_str_to_color impl by calling safe one

- deltachat-ffi/deltachat.h
`void func();` is correct in C++ but not really correct in C, some compilers throw a warning.
the correct semantic in C is `void func(void)`.
we did this correctly for most functions, but for some reason it was forgotten for dc_lot_new(). this pr fixes that.
> declare void function as such

- Cargo.lock
- Cargo.toml
- src/dc_chat.rs
- src/dc_msg.rs
- src/lib.rs
Changes:
bcd707e (Dmitry Bogatov, 6 минут назад)
Drop old version of {dc_msg_guess_msgtype_from_suffix}
de170fc (Dmitry Bogatov, 11 часов назад)
Adjust call sites to use new version of dc_msg_guess_msgtype_from_suffix
df229f3 (Dmitry Bogatov, 12 часов назад)
Implement Rust version of {dc_msg_guess_msgtype_from_suffix}
> Implement Rust version of {dc_msg_guess_msgtype_from_suffix}

- src/top_evil_rs.py
Otherwise `configure/*` is not included in the report.
> top_evil_rs.py: use glob to walk into subdirs

- deltachat-ffi/src/lib.rs
for convenience, it should be possible to pass an empty list of messages for eg. being marked as seen.
in fact, the functions are used this way in the past and it also feels natural to allow that.
of course, the uis could also check such things, however, this is easy to forget and a panic! is a bit harsh.
a related discussion is whether to allow null-pointers eg. for messages which may easyly happen with a 
```
dc_msg_t* msg = dc_get_msg(id); // id does not exist
dc_delete_msg(msg); // currently this will fail - the old c-core just does nothing in this case
```
also here, it is hard for the ui to catch all cases and it might be better to just do nothing (in the ffi, rust-core can be different)
however, the pointer-thingie is a different dicussion that should proably be done somewhere else …
> allow passing empty arrays to ffi

- deltachat-ffi/src/lib.rs
as C lacks a good and portable error handling, in general, the old C Interface was forgiving wrt to bad parameters.
- objects returned by some functions should be passable to the functions handling that object. eg. a dc_msg_get_text(dc_get_msg(id)) did not crash but just returns an empty text on bad ids
- if in doubt, the empty string is returned on failures; this avoids panics if the ui just forgets to handle a case
- finally, this behaviour matches the old core-c API and UIs already depend on it
not saying, this is the golden way, it's more a pragmatic approach :)
> handle ffi-failures compatible to core-c

- deltachat-ffi/src/lib.rs
#414 broke tests, but I fail to see oblivious mistake. Let's split c71589a710d9dcc034153c79fe90a313649d0ff0 into many small commits and see, what exactly is causing problems.
PS. Does anybody know how to prevent  CI from aborting build when HEAD moves?
> unbreak master

- src/config.rs
this pr set the correct default value for `inbox_watch` in the same way as done for `mvbox_watch` and `sentbox_watch`.
without the default value, internally, the inbox seems to be watched anyway, but the exposed setting via `dc_get_config(inbox_watch)` returns `false` if there is no entry in the database (which is typically the case until the user plays around with some options)
fixes https://github.com/deltachat/deltachat-ios/issues/222
> set correct default value for inbox_watch

- Cargo.lock
- Cargo.toml
- src/dc_receive_imf.rs
Changes:
5eff6cc (Dmitry Bogatov, 70 seconds ago)
Refactor is_known_rfc724_mid() to use `clist_iter()`
aa7129d (Dmitry Bogatov, 7 minutes ago)
Provide Iterator interface for `clist'
* src/dc_tools.rs(clist_iter): new function that allows iterating data
(`void*')
of clist elements.
This function renders manual pointer assignments unnecessary, makes
iterating of `clist' look almost like normal Rust code.
19dfa39 (Dmitry Bogatov, 54 minutes ago)
Change return type of is_known_rfc724_mid_in_list() to bool
> Refactor clist-related functions

- src/job.rs
This change removes several `unsafe' blocks by using safe version of
`dc_read_file' function.
Note, that logic is changed slightly: if get(Param::File) returns
Some(""), it no longer triggers "missing filename warnings".
> Remove C pointer manipulation from do_DC_JOB_SEND()

- examples/repl/cmdline.rs
- src/chat.rs
- src/message.rs
this pr unifies the presentation of "no message text" in the database to an empty string.  
the empty string was used also in core-c and in core-rust for incoming messages and as the database-default-value. only outgoing messages in core-rust used NULL for that.
moreover, the message-loading-from-database becomes tolerant against invalid NULL values for message-text; this is also what core-c does in this case.
finally, this pr fixes a bug in the cmdline util that prevents sending images without text (in fact, the main reason for "no message text") 
tackles #443
> Fix msg loading

- src/sql.rs
this pr fixes #447 by really collecting all files actually in use.
(the housekeeping first collects all files in use and then throws away all other files in the blobdir)
> Fix backup and housekeeping

- src/dc_receive_imf.rs
fixes #417
the problem was that a Vec was accessed with an invalid index (the old core-c has a bounds checker inside dc_array_get_id())
> fix crash when downloading message

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/chat.rs
- src/configure/auto_mozilla.rs
- src/configure/auto_outlook.rs
- src/configure/mod.rs
- src/contact.rs
- src/context.rs
- src/dc_imex.rs
- src/dc_mimefactory.rs
- src/dc_mimeparser.rs
- src/dc_receive_imf.rs
- src/dc_strencode.rs
- src/dc_tools.rs
- src/e2ee.rs
- src/imap.rs
- src/job.rs
- src/job_thread.rs
- src/key.rs
- src/location.rs
- src/log.rs
- src/message.rs
- src/oauth2.rs
- src/qr.rs
- src/securejoin.rs
- src/smtp.rs
- src/sql.rs
- src/top_evil_rs.py
Changes:
3153d30 (Dmitry Bogatov, 2 minutes ago)
Use set_config_bool instead of set_config_int in boolean context
7c14a82 (Dmitry Bogatov, 10 minutes ago)
Use sql.get_config_bool to simplify `dc_is_configured`
c4d4bd2 (Dmitry Bogatov, 13 minutes ago)
Add Sql.{set,get}_config_bool methods
Previously, boolean configurations were implemented on top of i32
(get_config_int, set_config_it) at call sites.
Having one canonical location, containing boolean <-> database conversion
may help to avoid serialization issues.
109257c (Dmitry Bogatov, 2 hours ago)
Change return type of `dc_is_configured' to bool
1576dc1 (Dmitry Bogatov, 2 hours ago)
top_evil_rs: check for all-caps version of ok_to_continue pattern
4fbb5fb (Dmitry Bogatov, 2 hours ago)
Make it easier to run src/top_evil_rs.py from git root …
> Minor refactoring

- src/dc_imex.rs
Replace `if (ok) { }` pattern with `if (!ok) return` to reduce indentation
level.
> Reduce indentation in dc_continue_key_transfer

- src/dc_tools.rs
- tests/stress.rs
deletion of folders is currently not needed afaik, therefore dc_delete_file() should not implicitly call fs::remove_dir_all()
this pr changes the behavior and adapts the test.
> do not recursive delete folders

- src/dc_mimeparser.rs
this is the second attempt to fix #477 - hard stuff :) - however, if this fixes at least _something_ as the prior pr, it's probably fine :)
the problem were messages with bad-utf-8 in the body. calling to_string() panics in that case.
this pr replaces the corresponding calls (plus some more that came over my way) by to_string_lossy().
both, [to_string() and to_string_lossy() are defined in dc_tools.rs](https://github.com/deltachat/deltachat-core-rust/blob/master/src/dc_tools.rs#L1216) - i am wondering if we really want the panic on a string conversion. my suggestion would be to use to_string_lossy() everywhere.
> do not panic on bad-utf-8

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/chat.rs
- src/dc_imex.rs
- src/dc_mimefactory.rs
- src/job.rs
- src/location.rs
- src/message.rs
- src/securejoin.rs
The Message struct had a reference to the context which made a few
APIs a little easier.  However it has surprising consequences a long
way down the line as shown in #335: it means any object which has such
a reference needs to keep open a lock if we want to do this refactor
of no longer having a "closed" Context struct on the Rust API (which
has many benefits which will simply that Context struct and is more
the Rust way - RAII etc).
By refactoring away the context reference on the rust API as done in
here however, we push this behaviour of how these references are
handled back to the C-API pointer behaviour: that is unsafe but just
works in a C-like way.  The resulting complexity in the FFI layer is
also notably less than in the #335 alternative.
As a consequence all APIs which require …
> Remove the context reference from Message struct

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/simple.rs
- src/chat.rs
- src/chatlist.rs
- src/contact.rs
- src/dc_mimefactory.rs
- src/dc_receive_imf.rs
- src/message.rs
- src/securejoin.rs
This is one PR for Chat, Chatlist and Contact structs, they are separate commits though and each fully works.  It doesn't seem too big so I'm going to collapse all these in one PR and cancel #493.  It's all fairly mechanical once you get the idea.
> Remove context references from structs returned on the FFI API

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/chat.rs
> Fix get_draft to just return null and not produce errors if there's no

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/repl/main.rs
- examples/simple.rs
- python/tests/test_lowlevel.py
- src/context.rs
- src/dc_imex.rs
- src/error.rs
- src/stock.rs
- src/test_utils.rs
- src/types.rs
- tests/stress.rs
This is the new implementation of #335.  It is slightly less complex as it doesn't need the rental crate to keep locks open.  Instead the structs on the FFI store all the unsafe references in raw pointers, not introducing any weird new failures around clients calling dc_close().  It does mean clients could and probably do keep around unsafe objects after the context is closed, but this is the same behaviour as before and as long as they do not use any of them this should be fine.
> Remove dc_open() from the Rust API

- .gitattributes
- src/dc_mimeparser.rs
- test-data/message/issue_523.txt
Unfortunately, crash as reported in #523 does not reproduce.
Research in progress.
> Add test for mime parsing reportedly crash-inducing message

- python/src/deltachat/account.py
- python/src/deltachat/chatting.py
- python/tests/conftest.py
- python/tests/test_account.py
- src/dc_mimeparser.rs
- do not use a hack to teardown online configured accounts eagerly as it was not called on test failures and led to crashes.  Threads might produce some uncaptured logging between "setup/call/teardown" phases of a test but it's bearable in my test runs. 
- remove redundancy for the online two-account setups
- add a helper to create a chat between two online accounts
> streamline python fixtures to simplify actual test code 

- spec.md
- use shorter lines
- try to use [semantic linefeeds](https://rhodesmill.org/brandon/2012/one-sentence-per-line/)
- the pr does not change any words or adapt things
still not 100%, but probably much easier editable and adaptable to the things really happening in the core (i'd say max. 90% of the spec are correct ;)
> reformat spec

- python/src/deltachat/message.py
- python/tests/test_account.py
- src/dc_imex.rs
- src/e2ee.rs
- src/error.rs
- src/pgp.rs
fix #538 (i think you need to have in the comment here, the title is not scanned by the github-auto-close-issue code)
> fix #538 -- don't crash on wrong setup codes for ac-message, added test

- src/imap.rs
- src/oauth2.rs
- src/smtp.rs
- tests/stress.rs
Previously, `dc_get_oauth2_access_token` accepted "flags" argument,
that actually had only one possible field: 0x1 == DC_REGENERATE.
This change replaces "flags" argument with single boolean argument
"regenerate".
> Refine signature of dc_get_oauth2_access_token()

- deltachat-ffi/src/lib.rs
- src/context.rs
Clients expect empty "dbfile" argument to be treated as NULL value.
This change fulfills their expectations.
Closes: #530
> Fix ffi interoperability issue

- src/configure/mod.rs
fixes #544 
tackles https://github.com/deltachat/deltachat-ios/issues/90
nb: adding a check for `progress >= 0` results in a rust compiler warning `comparison is useless due to type limits` - i do not fully agree that this would be useless as it might happen the macro is called with an Int instead of UInt, however, i have no idea how to handle this :)
> fix configure-panic

- src/chat.rs
- src/context.rs
- src/dc_mimefactory.rs
- src/dc_mimeparser.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/imap.rs
- src/job.rs
- src/message.rs
- test-data/message/mail_with_message_id.txt
the individual commits each pass tests on their own and maybe make sense to review separately. 
I choose to not use `Option<String>` for rfc724_mid but `String` and initialize to empty-string as there is no difference in interpretation of empty or non-existing message-ids. 
the last commit factors out rfc724_mid parsing from add_parts() into a mimeparser-method and adds tests.  This allows to not need a &mut rfc724_mid.
> cleanup rfc724_mid handling to avoid char* 

- src/dc_imex.rs
Previously, this function accepted both key id (integer) and is_default
(boolean). If `is_default` flag was set, value `id` parameter wasn't used.
This commit compresses two argument into single `id: Option<i64>`.
> Reduce number of arguments of `export_key_to_asc_file`

- python/tests/test_lowlevel.py
A fixed bug should have a test.  This is an easy test to write.
Without the fix this test fails, with it it passes.
> Add a test for fix in #541

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- python/src/deltachat/account.py
- python/tests/conftest.py
- python/tests/test_account.py
- src/job.rs
as discussed add per-folder "jobs" hooks which, however, for now have an empty implementation.  
dc_perform_mvbox_jobs and dc_perform_sentbox_jobs can already be called from UIs, though.  
Next step after merging this PR is then refactoring imap-job handling to only execute jobs belonging to the respective imap folder.
> add dc_perform_{mvbox,sentbox}_jobs 

- src/dc_tools.rs
This was not substituting $BLOBDIR correctly.
Whoops.  We really should write more tests.  Simple tests for trivial things are as useful as large complicated tests.
> Fix dc_make_rel_path

- src/dc_mimefactory.rs
- src/job.rs
Changes
-------
* src/dc_mimefactory.rs(MimeFactory): change type of `loaded` field
* src/dc_mimefactory.rs(Loaded): new enum, describing possible
values of `loaded` field of `MimeFactory` structure
* src/dc_mimefactory.rs(dc_mimefactory_loaded_t): remove unused type alias
* src/job.rs(add_smtp_job): adjust call site by removing multiple casts
* src/dc_mimefactory.rs(dc_mimefactory_render): ditto
CamelCase naming convention is more natural for Rust.
https://rust-lang-nursery.github.io/api-guidelines/naming.html
> Rename dc_mimefactory_t -> MimeFactory

- src/imap.rs
- src/job.rs
Note, that since this enum never pass FFI border, its numeric values does
not need to be specified explicitly and can be left on compiler's 
discretion.
> Make return type of Image::mv an enum

- src/chat.rs
Commits with `cargo-fmt` message are exactly what it says. No need to
review them. I tried to avoid commits that change too much indentation.
So, some of commits will not pass cargo-fmt test, but compile fine.
* Factor part of `set_draft_raw` into new function `maybe_delete_draft`
* Make message argument to `set_draft_raw` no longer optional
Previously, `set_draft_raw` function was used with `msg = None` only for 
side-effect of removing current draft message in chat.
After draft removal functionality was factored into separate
`maybe_delete_draft` function, it is used directly in only call site, which
used to invoke `set_draft_raw` with optional message.
This function is private, refactoring does not change FFI interface.
* Factor another part of `set_draft_raw` into separate function. …
> Avoid ok-to-continue pattern in `set_draft_raw`

- src/dc_strencode.rs
Function "quote_word" accepts display charset argument, but on only call
site it is string constant. Change function to always use "utf-8"
display charset, and remove useless argument.
> Remove useless argument to `quote_word`

- examples/repl/cmdline.rs
- src/chat.rs
- src/constants.rs
- src/dc_imex.rs
- src/dc_mimefactory.rs
- src/dc_strencode.rs
- src/dc_tools.rs
- src/e2ee.rs
- src/job.rs
- src/message.rs
this PR grew a bit more then i wanted to -- but achieves its aims and passes all cargo/python tests locally.  The cleanup involves 
- safer more readable looping over clists 
- rustify mimefactory struct strings: references and in_reply_to 
- turn recipients_addr,recipients_names into Vec's instead of clists
- boolify various vars 
- shift var usage to where it's needed to avoid large let-headers up-front
- removing several helpers or moving them to the tests
> rustify dc_mimefactory along with related cleanups

- python/tests/test_account.py
- src/dc_mimefactory.rs
- src/dc_receive_imf.rs
- src/e2ee.rs
- src/job.rs
- src/lib.rs
- src/wrapmime.rs
- create wrapmime module for providing some initial safe functions with mmime
- cleanup message-encryption finalization, no cdata_to_free tricks for encryption, avoid one strdup() in the outgoing message path 
- more safe code
> Cleanup/e2ee and mimefactory-outsending and encryption

- Cargo.lock
- Cargo.toml
- src/message.rs
phf-crate introduced 7 deps and is  advertised for very large (100K+) tables -- we have just 10 entries or so and it's called once per message.  Let's not introduce crates just because we can ;) crates increase compile time and in the phf case also introduced a github dependency (for whatever reason -- don't want to know ;).  My general suggestions is we could see about removing some more crates if they only slightly optimize something.
> remove phf crate macro usage

- src/chat.rs
Currently we emit an error event when we call get_draft with a special chat id, this breaks api compatibility with c-core.
> Return Ok(None) when get_draft is called with a special chat id

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- python/src/deltachat/account.py
- python/tests/test_account.py
- src/constants.rs
- src/dc_imex.rs
- src/dc_tools.rs
- src/job.rs
- src/message.rs
- src/pgp.rs
- tests/stress.rs
this started from trying to fix #596 and resulted in: 
- turning several key-related functions from unsafe to safe
- adding export_self_keys and import_self_keys python API, testing roundtrip
- removing lots of char-* stuff 
and the #596 is fixed.
> rustify dc_imex, fix bug

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- python/tests/test_lowlevel.py
- src/context.rs
@hpk42 could you check if this is the best way to do the FFI-level tests?
@r10s could you check if the FFI API decisions I'm taking here are somewhat reasonable to you?
@dignifiedquire could you check if you're happy with the Rust-level API.  It certainly works but I don't find it particularly elegant.  My brain is only working at a rather reduced capacity currently though.
@Jikstra could you check this actually fixes your problem in the desktop?
Of course anyone can comment on anything they so desire :)
Commit message:
There is very little API guarantees about this, but clients seem to
expect *something* to work on a closed context.  So split this up into
static info an more dynamic context-related info, but let's not
provide any guarantees about what keys are available when.
Fixes #599
> Make dc_get_info() work on a closed context

- deltachat-ffi/src/lib.rs
- python/tests/test_account.py
- src/message.rs
and not default to `applicatopm/octet-stream`
I think in rustland a Result/Option would be a better return value, not sure. I like to keep things simple and return an empty string, can change it if people think it's important.
> get_filemime() should return an empty string if no mimetype is present

- deltachat-ffi/src/lib.rs
- python/tests/test_lowlevel.py
The Rust context is always open, the return value of this function was
simply the wrong way around.
> Revert back to only ffi-level checking of open context

- spec.md
up to now, the spec does not say anything about the minimal length of the group-id.
however, in reality, all group-ids are exactly 11 characters long. to be more flexible wrt coi, this pr defines this as the minimal length.
> adapt group-id length to reality

- src/dc_tools.rs
- src/message.rs
core-c has truncated messages in the contact requests.
this is questionable in general, as
- all messages, including contact requests,
are already truncated, unquoted, simplified etc.
- the ui should be capable of showing the full text anyway
(when the contact request is accepted, the whole messase is shown)
- also, all current ui show the contact requests by name only in the
chatlist; the user often does not even come to the contact request view.
- if the ui wants to show the contact request is a special way,
it is probably better to leave this truncation up to the ui
> do not truncate messages in contact requests

- proptest-regressions/dc_strencode.txt
- src/dc_strencode.rs
Changes
-------
* Use rust strings instead of MMapString in src/dc_strencode.rs
Since Rust strings operations are assumed to never fail, this commit
removes a lot of checking, whether appending to mmapstring fails. Now it is
Rust runtime burden.
* Rename local variables to not misleadingly refer to MMAPString
Replace variable name `mmapstr` with more generic `result` and
`dest`.
* Implement safe version of `quote_word` with Strings and slices
instead of raw pointers.
PS. First commit is better looking in side-by-side mode, last in unified.
> Simplify dc_encode_header_words function

- src/imap.rs
- src/smtp.rs
this is the behaviour of C-core ASFAIK. 
fixes  #616 
Note that To make this behaviour configurable there is #203
> allow invalid certs for smtp and imap connections 

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
typically, nearly all string-parameters in the ffi should be const.
one of the few exceptions is dc_str_unref() that really modifies the given data.
> make ffi-string-parameter const

- src/dc_mimeparser.rs
- src/dc_receive_imf.rs
- src/dc_strencode.rs
Changes:
-------
* Replace all call sites with safe version and adjust tests as apporiate.
* s/dc_decode_header_words_safe/dc_decode_header_words/
> Drop unsafe version of dc_decode_header_words

- src/context.rs
- src/dc_mimeparser.rs
- src/dc_tools.rs
- src/imex.rs
- src/job.rs
this aims to fix #597 by removing the dc_get_fine_path_filename method and introducing two helpers:
- context.new_blob_file(orig_path, data) which creates a new file in the blobdir, with the filename based on orig_path. 
- context.copy_to_blobdir(path) which copies a path into the blobdir, also with filename mangling if necessary 
the two new methods return both $BLOBDIR/<filename> strings, as they are then used to be written to the database which expects $BLOBDIR, and not absolute paths.
> cleanup blob-file creation and copying

- mmime/src/display.rs
- src/dc_mimeparser.rs
- src/dc_receive_imf.rs
- src/e2ee.rs
- src/mimefactory.rs
- src/wrapmime.rs
- shifted several mmime-helpers to wrapmime. helper methods are always called as wrapmime::... to make it obvious in the code where mmime comes in.  wrapmime-methods can be called safe but they do invoke unsafe code which depends on the overall allocation/free handling of all the unsafe-parts.   
- the only real functionality change happened with the removal of redundant code, of which 
one version was like leaking things or worse.  This is in commit https://github.com/deltachat/deltachat-core-rust/commit/fdd21edf0bd06b6842931f6e06be720b12564224 
this is part of an ongoing attempt to make the incoming-message pipeline safer and easier to debug ... still some way to go.  It'd be intersesting to run ios/desktop with my most two recent PRs (also the blobfile-one) ...
> some incoming-message cleanups, and possibly a fix for a crash

- deltachat-ffi/deltachat.h
- src/chat.rs
- src/constants.rs
- src/dc_mimeparser.rs
- src/message.rs
- src/mimefactory.rs
- src/stock.rs
this pr adds the message type 'sticker'.
stickers are handled as normal images
but tagged with the header `Chat-Content: sticker`
it's up to the ui to render these stickers appropriate.
> add sticker type

- src/dc_receive_imf.rs
- src/e2ee.rs
- src/peerstate.rs
- src/sql.rs
on some call sites fixed: peerstate.save_to_db() should bubble up errors instead of crashing.  @adbenitez had reported a crash on one of them. 
also write a test that double-creation of an addr-row is fine.
> don't let save_to_db() crash the process 

- src/chatlist.rs
contact-requests of non-blocked senders are shown in the chatlist,
so that the user gets aware of them without opening the contact-request-chat.
however, for that, the contact-request virtual-chat-id
must be added to the beginning of the list,
otherwise it won't get noticed by the user.
fixes #657
and finally fixes https://github.com/deltachat/deltachat-ios/issues/261
desktop has the same issue, however, seems not to written down somewhere :)
> move contact-requests to the beginning of chatlists

- python/README.rst
mail_pw is the option that is actually read by the tests
> python/README.rst: s/mail_pwd/mail_pw/

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- python/tests/test_account.py
- src/chat.rs
- src/config.rs
- src/constants.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/e2ee.rs
- src/imex.rs
- src/job.rs
- src/mimefactory.rs
- src/smtp.rs
- src/wrapmime.rs
- test and fix #662 introduces a new "bcc_self" bool with which you can control whether mails are BCCed out
- resultify several methods related to the outgoing-mail pipeline, better error-reporting and more precise SMTP events. 
- introduce new "context.get_config_int" and "context.get_config_bool" helpers that respect the defaults which are declared with the Config enum in config.rs ... and refactor mdns_enabled and e2ee_enabled access to use the new methods, thereby fixes #661 (in e2ee the default was wrong).  Note that by far not all usages of "sql.get_config_int" were replaced -- that's for another PR and might prevent further "default-wrong" bugs.
> introduce bcc-self setting, cleanup config access, fix e2ee, rustify outoing pipeline

- examples/repl/cmdline.rs
- src/chat.rs
- src/config.rs
- src/configure/mod.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/imap.rs
- src/imex.rs
- src/job.rs
- src/job_thread.rs
- src/location.rs
- src/login_param.rs
- src/mimefactory.rs
- src/oauth2.rs
- src/securejoin.rs
- src/sql.rs
- prefer context.get_config() over context.sql.get_config()
- do not panic on context.get_config_int(), fixes #669 
- rename raw config-getters to sql.get_raw_config*() to make more obvious that these function do no handle defaults and to make inadvertent use more obvious in the future
> tweak config

- src/configure/mod.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/job.rs
for db input/output, we still use get_config_int() to convert to/from 0/1.
also for info() we prefer get_config_int() to show the real value.
successor of #670
> prefer get_config_bool() where appropriate

- examples/repl/cmdline.rs
- src/config.rs
- src/configure/mod.rs
- src/imap.rs
- src/imex.rs
- src/login_param.rs
- src/oauth2.rs
- src/sql.rs
the rename is reasonable as the getter is called get_raw_config*()
and to make the functional difference to context.set|get_config() clearer.
successor of #670 and #671
> rename sql-config-setters to set_raw_config*()

- src/imex.rs
seems like we passed memory pointers into Rust strings to code that was expecting null-terminated strings.  Now do proper "strdup()" and free.  The real proper fix is to make dc_split_armored_string into a rust-string function and do away with all c-pointers.
> try fix #677 (this fixes only a test)

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/configure/auto_outlook.rs
- src/dc_mimeparser.rs
- src/dc_receive_imf.rs
- src/dc_strencode.rs
- src/dc_tools.rs
- src/message.rs
- src/stock.rs
- src/wrapmime.rs
always use to_string_lossy() for converting c-strings to String
the function to_string() is removed;
c-strings may always be badly formatted and this should never lead to a panic.
nb: also scanned over the remaining .to_string() member functions, seems as if  .to_string_lossy() is already called where it is needed, eg. for Path or OsString objects.
> always expect bad c-strings

- deltachat-ffi/src/lib.rs
- mmime/src/charconv.rs
- mmime/src/mailmime/write_generic.rs
- src/aheader.rs
- src/dc_mimeparser.rs
use .to_string_lossy() member of Path, CStr etc. instead of calling to_str().unwrap_or_default().
this partly reverts and improves the unwrap_or_default() calls introduced in #673
> use .to_string_lossy() member of Path, CStr etc.

- src/dc_tools.rs
as noticed in the last attempts to change the prefix,
this test is missing (as probably many more :)
> only some tests for dc_create_outgoing_rfc724_mid()

- src/configure/auto_mozilla.rs
- src/configure/auto_outlook.rs
- src/configure/mod.rs
- src/dc_tools.rs
This should fix #616 
As found by @hpk42 the problem was related to outlk_autodiscover returning Some but with 0 ports when no autodiscovery XML was found.
That is because in C version `out` was initialized to NULL and only allocated when XML was parsed. It even had this comment:
https://github.com/deltachat/deltachat-core/blob/2bb1c280d5db07ed3974d57a4b2f128bca1da9f0/src/dc_configure.c#L415
Rust version allocates `out` immediately. To avoid dealing with `unwrap`, I have not replaced `out` with an `Option<>` like a straightforward C translation should be done, but added a flag indicating whether it contains some data or not.
> Fix and refactor Outlook autodiscovery

- src/dc_receive_imf.rs
the Chat-Predecessor header was dropped about 10 month ago.
as a replacement, the standard headers are used.
> remove scanning for old Chat-Predecessor header

- python/src/deltachat/account.py
registeri/unregister with atexit (a module that manages process/interpreter shutdown and calls into registered shutdown.  Recommended way for user code still is to call account.shutdown() explcitely.
this should avoid weird crashes like reported with #690.
> fix #690 by avoiding account.__del__ 

- src/configure/mod.rs
- src/constants.rs
- src/imap.rs
- src/job.rs
this removes the last ok_to_continue's, yay! :) 
also what gets tried regarding smtp and imap should now be easier to undertand. 
first commit is the refactoring. second is pure "cargo fmt". 
FYI in my local tests i short-circuited both smtp-connect and imap-connect to always return false, and it seemed the resulting tries wrt to port/server flags were all correct.
> refactor and simplify imap/smtp connection trying / remove ok_to_continue 

- src/configure/auto_mozilla.rs
address https://github.com/deltachat/deltachat-ios/issues/328 
dont escalate xml-parsing errors to users through error! macro, just use warning.
> xml-parsing errors of autoconfig are no user-visible error

- src/dc_tools.rs
Call .to_string_lossy() without trying .to_str() first.
> Simplify to_string_lossy()

- Cargo.lock
- Cargo.toml
fix #694 by forking lettre and avoiding extra NOOP Smtp commands for connection checking.
If this works out and fixes our problem, we can submit upstream. See the analysis in that issue. 
For now, we have a fork of lettre http://github.com/deltachat/lettre 
the only one-line change to lettr we did is in this commit: https://github.com/deltachat/lettre/commit/aeec999c27a70870e4b7b149e45f24188c1ff351
> (try) fix smtp-already-established

- mmime/src/other.rs
strncasecmp() compares the given number of characters but not after a 0-byte.
this targets the open question from https://github.com/deltachat/deltachat-core-rust/pull/703#issuecomment-539998040 by not reading beyond the first 0-byte
(the different descriptions of strnlen() are not totally clear on that point, however, they guarantee to not read beyond N, so that they cannot call just strlen(). eg. the glibc-implementation stops on the first 0-byte: https://github.com/lattera/glibc/blob/master/string/strnlen.c and i assume this is also true for others)
@dignifiedquire would be cool if you can check if things still work for you :)
> len-check in strncasecmp()

- src/context.rs
- src/imex.rs
- src/sql.rs
Previously, "flags" argument of Sql.open was of type libc::c_int, but
only one bit was used: whether to open database read-only. This commit
makes it explicit by changing type to bool and renaming argument.
> Replace flags argument to Sql.open with single bool

- python/tests/conftest.py
- python/tests/test_account.py
Fixes #718
The new function `AccountMaker.peek_online_config()` returns the next configuration map from the list of live accounts, without creating an account or starting configuration. Multiple calls will return the same configuration. The next call to `get_online_*()` will use that configuration to actually create the account.
> Don't use hard-coded email addresses in tests

- src/oauth2.rs
this or does a correct POST call to get the oauth2 access tokens.
it does _not fix_ #119, there seems still to be the same hang as always in [`client.authenticate("XOAUTH2", &auth)`](https://github.com/deltachat/deltachat-core-rust/blob/master/src/imap.rs#L428), however,  this or is  necessary step for fixing that finally.
> make oauth2 POST successfully

- src/configure/mod.rs
- src/oauth2.rs
oauth2.get_addr is used for gmail-oauth2
to retrieve the address really authorized in the oauth2 process.
this pr fixes parsing the json by allowing any json-type, not only strings for the different fields (we are not interested in any stuff beside email anyway).
fixes #721
> make oauth2.get_addr work

- src/chat.rs
we tested a sort of broadcast by not marking own forwarded messages as such, however, this turned out to be to confusing and unclear.
also among developers [doing this change originally](https://github.com/deltachat/deltachat-core/pull/504/files), see eg. #725
> mark own forwarded messages as such

- deltachat-ffi/src/lib.rs
- src/dc_tools.rs
prefer to_string_lossy() for converting c-strings to String
c-strings may always be badly formatted and this should never lead to a panic.
fixes https://github.com/deltachat/deltachat-android/issues/1065
see also https://github.com/deltachat/deltachat-core-rust/pull/674 https://github.com/deltachat/deltachat-core-rust/pull/679 that already does the conversion on other places.
> do not panic on bad utf-8 received from ffi

- examples/repl/cmdline.rs
- src/dc_mimeparser.rs
this pr removes the mostly useless re-usage of the Simplifier object, it was don in c for $reasons, but i think there is no worth in rust.
this already fixes #724 - which is great, however, not sure why before this pr [`if simplifier.unwrap().is_forwarded` was always false](https://github.com/deltachat/deltachat-core-rust/blob/master/src/dc_mimeparser.rs#L661) although [`is_forwarded` is set to true in simplify.rs](https://github.com/deltachat/deltachat-core-rust/blob/master/src/dc_simplify.rs#L73)
apart from that, this pr also fixes a potential issue as is_forwarding was never set to false - beside in the constructor but not on re-use as done before this pr.
> Fix forwarding

- Cargo.lock
- Cargo.toml
- run-integration-tests.sh
- src/blob.rs
- src/chat.rs
- src/context.rs
- src/dc_mimeparser.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/error.rs
- src/imex.rs
- src/job.rs
- src/lib.rs
- src/message.rs
- src/mimefactory.rs
- src/param.rs
I never knew what kind of stuff was in one of those strings referring to blobs, so I thought fixing it with types would be a good thing.  Turns out that was more involved than hoped for.
Anyway, this tries to be strict about blobs by creating a `BlobObject`.  This object should also make it easier to in the future not store all blobs into one directory or even into an sqlite store.  Furthermore since blobs get passed through the params system a lot, the `ParamsFile` was added, basically any filename read from params should be parsable into that enum, allowing you to know if you're dealing with a pathname or already with a blob.
This doesn't always make things less verbose on call sites, I apologise for that.  In the future some of this could improve by making the storage more explicit, …
> Typed blobs

- src/chat.rs
adding a member to a group is okay if a real contact exists or for DC_CONTACT_ID_SELF
this pr emulates the [logic in core-c](https://github.com/deltachat/deltachat-core/blob/master/src/dc_chat.c#L1998), however, in fact, currently, if SELF cannot be added if SELF is not in group. but this may change and also adding a contact that is not in the group should not considered as an error.
also, the changed logic just checks if the given contact is valid; and this is true for DC_CONTACT_ID_SELF
> allow adding SELF to group

- src/config.rs
- src/constants.rs
- src/dc_receive_imf.rs
this pr targets several requests of users (eg. [here](https://support.delta.chat/t/show-classic-emails-for-all-advanced-settings-does-not-work/452) or [here](https://support.delta.chat/t/no-contact-request-is-poping-up/318/5)) that want to see "email contact requests" directly in the chatlist when show_emails set to ALL.
before, no contact-requests are shown in the chatlist even if show_emails is set to ALL; users who want to use delta as their only email-client have to manually open the contat-requests activity to not miss a mail.
i think this pr makes things a bit more obvious.
> show all contact-requests in chatlist if show_emails=ALL

- deltachat-ffi/src/lib.rs
if dc_get_chat_id_by_contact_id() does not find a chat, this is no error.
in fact, the function is used to probe if there is a chat with a given contact at several places eg. in the android-ui.
this is also the behavior of core-c.
fixes https://github.com/deltachat/deltachat-android/issues/1085
> let dc_get_chat_id_by_contact_id() returns 0 if no chat is found

- src/message.rs
this avoids weird summaries as "Voice message -", "File -" etc. and is what core-c did at its time.
> in summary, show hyphen only if there is a type and a text

- Cargo.lock
- Cargo.toml
- src/imap.rs
With this PR Delta Chat Desktop (and probably all other apps) survive network-disconnects better.  After re-connecting-to-network imap-idle will resume, messages will be fetched etc.  Before it used to hang. 
It can take up to a minute or so to detect if network is there unless dc_interrupt_idle() is called from the UI (Android and iOS do this IIRC).   If the disconnect happens during a running idle call, and network is back before the idle-timeout kicks in (23 minutes) then messages should be retrieved immediately. 
note that this draws in a somewhat experimental refactoring of rust-imap's idle-handling, currently forked at [deltachat/rust-imap](https://github.com/deltachat/rust-imap).
> Fix imap hang / survive disconnects

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/blob.rs
- src/chat.rs
- src/chatlist.rs
- src/constants.rs
- src/contact.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/error.rs
- src/events.rs
- src/imap.rs
- src/imex.rs
- src/job.rs
- src/location.rs
- src/message.rs
- src/mimefactory.rs
- src/param.rs
This more strongly types the ubiquitous message id type by no longer
making it an integer.  It keeps the actual ID opaque.  Only for the
generic job API the number keeps being used.  Some locations also need
to create it from an integer and call MsgId::new().
Initially I wanted to split this into two types, the normal MsgId which would not be allowed to contain any of the special message IDs.  However due to the way `Message` is created it lives for a fair amount of time before it gets to the database and thus gets a message id.  That would require a builder pattern to make the message and that was all just too much for one PR.  Instead this switch is a little simpler.  Still looks verbose though, there simply are so many places where message id is used.
> A MsgId newtype

- src/chat.rs
just return false from add_contact_to_chat()
this emulates the core-c behaviour, i think for now this is the better approach as otherwise, eg. on android, the user gets weird messages where nothing is really wrong.
> do not escalate attempt to add self to a group to the user

- CHANGELOG.md
- deltachat-ffi/src/lib.rs
- python/tests/test_lowlevel.py
- src/chatlist.rs
- src/imex.rs
- src/mimefactory.rs
- make dc_get_msg() return empty messages for special ids. this fixes https://github.com/deltachat/deltachat-desktop/issues/1091
- some simplifications around Message::load_from_db
> Message id / FFI cleanups 

- src/chat.rs
Without a test for this fix, a regression will happen again.
Original PR #767 aka commit 4fed875107365bd4abda5fb3399babf87f3fb456
> Add test for #767

- src/chatlist.rs
the error led to unusable contact requests,
at least on android and ios (probably also desktop)
because msg_id=dc_chatlist_get_msg_id() always returns 0
and create_chat_by_msg_id(msg_id)
or dc_marknoticed_contact(<get sender from msg_id>)
failed therefore.
fixes https://github.com/deltachat/deltachat-ios/issues/375 and fixes https://github.com/deltachat/deltachat-android/issues/1097 and probably a similar issue on desktop.
the issue was not reproducibly in the repl tools as there all ids are typically shown and used directly, dc_chatlist_get_msg_id() is not used there.
> fix boolean error in chatlist::get_msg_id()

- deltachat-ffi/src/providers.rs
- src/dc_mimeparser.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/e2ee.rs
- src/wrapmime.rs
prefer to_string_lossy() for converting c-strings to String
c-strings may always be badly formatted and this should never lead to a panic.
eg. passing the utf-8-sequence ed a0 bd ed b8 80 to the subject would cause a crash.
in fact, looking at the crash reports of eg. ios, this might be the reason for some crashes. 
this pr makes the functions as_str(), as_opt_str() and as_str_safe() superfluous; instead to_string_lossy() and to_opt_string_lossy() is now used everywhere.
as_path() may still panic, however, this is only used for creating the context - so if things are bad there, this might be a reasonable approach.
this is a successor of https://github.com/deltachat/deltachat-core-rust/pull/728 that did similar changes for string coming from ffi.
> do not panic on bad utf-8 received from mime (and some other places) 

- deltachat-ffi/deltachat.h
- examples/repl/cmdline.rs
once it is removed in node, see https://github.com/deltachat/deltachat-node/issues/387 , we can drop the function completely and also clean up a handful of then unused strings.
> avoid usage of get_subtitle() in repl-tool

- src/job.rs
1_000_000 nanosecond = 1 millisecond
> fix conversion from nanoseconds to milliseconds

- python/src/deltachat/account.py
- python/tests/test_account.py
- src/dc_tools.rs
- src/imex.rs
this is mainly for better debugging and for fixing #760 -- for export the db is copied "by hand" (opening source in read, destination in write mode, then use `io::copy`), both to provide better error logging, but it already seems to fix a real android issue (@cyberta verified #760 goes away for him).
Note that this PR does not fix an other issue https://github.com/deltachat/deltachat-ios/issues/322 but there is a python test for that which is currently marking a test for #322 as "expected to fail".   This remaining issue probably also relates to #804 which is also not fixed here. 
It still makes sense to merge this PR here as it at least fixes the "cannot export at all" issue on some Android platforms (#760).
> fix cannot export issue and test 

- examples/repl/cmdline.rs
the new MsgId type comes with a formatter that makes special formatting in the repl tool superfluous
> fix output of repl tool

- deltachat-ffi/deltachat.h
- src/configure/mod.rs
this pr restores the ui-visible parameter-set to the actually used one if configuration fails.
before that, it was "decided" in https://github.com/deltachat/deltachat-core/issues/246 that this should be done by the ui, however, in practise this never happened.
while being a bug all the time, its becoming worse with the new certificate-check settings.
so, the easiest attempt to fix that seems to be in the core.
closes https://github.com/deltachat/deltachat-android/issues/1106 and probably similar issues in other uis.
> restore config-param if configure() fails

- deltachat-ffi/deltachat.h
this constant was missing on introducing the new string - mainly because searching for an existing string and amending all tables with its occurrences becomes harder and is no longer sufficient due to different writings, CamelCase and UPPER_SNAKE_CASE.
> add missing DC_STR_DEVICE_MESSAGES

- Cargo.lock
- Cargo.toml
- src/imap_client.rs
- src/login_param.rs
- src/smtp.rs
Only "Strict" and "Automatic" are implemented for CertChecks.  The other ones (invalidcert/invalidhostname) are equivalent to Automatic which allows invalid certs or even clear.
> reimlpement certchecks for imap and smtp

- src/chat.rs
- src/imex.rs
this pr adds some tests for device-messages, avoids a random label where no label is needed and removes an accidental call.
> test and tweak bcc-self

- src/chat.rs
This way there will be a compiler error notifying that the function needs to be updated when a new message type is added.
> Do not use wildcard match in msgtype_has_file

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/chat.rs
- src/imex.rs
- src/sql.rs
this pr is about to make device messages more usable, needed eg. by https://github.com/deltachat/deltachat-android/pull/1121:
- messages deleted by the user manually must not be added again with dc_add_device_msg_once() (i've overseen this issue on the first implementation)
- for allowing different messages on new-install and updates, it would be nice to have an option to "skip" a device message
- also, a function to check if a given device-message was ever added (even if deleted by the user) is useful for the ui
> tweak device messages

- src/context.rs
- src/dc_tools.rs
if two messages have the same time, this results i all kinds of sorting failures, esp. in non-delta-muas and on forwarding messages or adding device-messages fast.
so, no two messages sent out from delta should .have the same timestamp. normally, this is no problem and happens implicitly, but when things are sent too fast, eg. on forwarding, we lend us some time from the future.
however, all this did not work because we forgot to write back the modified time, this is fixed by this pr, as well as some cleanup.
nb: i removed the `Arc` thingie, i have no idea if and why this could be needed, however, peeking at the translated_stockstrings field @hpk42  added to the same structure, a simple RwLock seems to be sufficient.
this pr is needed to push …
> fix time smearing

- ci_scripts/remote_tests_python.sh
- ci_scripts/run-python-test.sh
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/repl/main.rs
- examples/simple.rs
- python/src/deltachat/account.py
- python/tests/test_account.py
- python/tests/test_lowlevel.py
- python/tox.ini
- src/config.rs
- src/configure/mod.rs
- src/context.rs
- src/error.rs
- src/imap.rs
- src/imex.rs
- src/job.rs
- src/job_thread.rs
presumably fixes #842 and probably some other issues. 
- resultify all connect, idle and fetch commands for better and more precise error logging 
- introduce several specific Imap related Errors to ease debugging and to e able to better react from the caller side (maybe this was a bit overdone, but i guess it cannot hurt to have specific error feedback in the log) 
- unify imap thread handling (context.inbox -> context.inbox_thread)
> resultify imap connect/fetch/idle and simplify connection handling

- Cargo.lock
- Cargo.toml
- src/pgp.rs
First, try to use subkeys, because they are usually
short-term encryption keys. If none of the subkeys
are encryption keys, try to use the primary key.
rPGP is updated to the master branch because the
latest release does not have .is_encryption_key() yet.
> Implement public key selection

- Cargo.lock
- Cargo.toml
- src/dc_receive_imf.rs
- src/wrapmime.rs
This attempts to fix fetching when the inbox contains mail with non-utf8 subjects.
> Use forked version of async-imap and imap-proto

- src/wrapmime.rs
this pr is needed to make rust compile on android.
once merged, we should force-re-tag beta8 or create a beta9
> fix cast to libc::c_char, signed i8 fails eg. on android

- src/imap.rs
This identical naming of sync and async arcs is not confusing at all
btw.
> Remove unused (async)Arc

- src/imap.rs
- src/job.rs
- src/job_thread.rs
reusing the same skip_next_idle pattern as with idle
> safer interruptability of fake-idle 

- python/tests/test_account.py
- src/constants.rs
- src/context.rs
- src/imap.rs
- src/message.rs
- src/sql.rs
also move messages sent to ourselves via bcc_self to the DeltaChat folder (other messages are moved in receive_imf())
closes #896
> move self-sent-messages

- src/job.rs
- src/log.rs
Be more defensive: if somehow we got corrupt jobs in the database skip
over them rather than fail to do anything.
This only modifies the query_map() call, the rest is only split off
into it's own function to make it testable.  Smaller functions are
good anyway.
> Skip bad jobs in the database

- src/job.rs
Otherwise it is possible that desired_timestamp is in the past.
> Calculate job backoff relative to the current time

- src/chat.rs
- src/chatlist.rs
- src/dc_receive_imf.rs
- src/sql.rs
this pr sorts the chatlist so that empty chats are sorted atop of the chatlist (as long as there are not chats with messages that are even newer)
as a nice side-effect, this way also new created one-to-one-chats are shown atop even if no messages was sent yet.
closes #909
> sort newly created chats atop of chatlist

- src/securejoin.rs
This used to be 300 milliseconds in the C core
> Don't let the user wait for so long

- src/aheader.rs
Reset is an internal value that received messages should not be able to set.
Also return an error on any value other than "mutual" and "nopreference", errors are converted to NoPreference by the caller.
> Do not accept prefer-encrypt=reset value from emails

- src/chat.rs
- src/contact.rs
- src/mimefactory.rs
this pr makes the email-address-comparison in addr_cmp() case-insensitive (as it was in core-c).
moreover, this pr changes places where normal-string-comparison is used for comparing email-addresses to use addr_cmp().
closes https://github.com/deltachat/deltachat-core-rust/issues/899
> Cmp addr case insensitive

- src/blob.rs
- src/chat.rs
- src/param.rs
This deletes a lot of code and complexity.  Though comes at some cost:
- The type no longer fits in a register and will always be on the
stack.
- Constructing the errors is more verbose, no more auto Into casting.
> Convert BlobError into an enum

- python/tests/test_account.py
- src/configure/mod.rs
- src/error.rs
- src/imap.rs
- src/job.rs
with considerable help from @flub this refactors imap.select_folder() to return specific errors, and refactors the callsites to handle them properly.  While refactoring the call sites another flakyness issue occured which is also fixed with this PR: the determination of "last seen uid" is now done using imap-provided information ("uid_next") and better/leaner fetch operation to determine the maximum uid the imap server currently knows, thanks also @dignifiedquire for thinking along.
> Resultify select error and fix uid_validity flakyness

- src/chat.rs
if the user has deleted the device chat created eg. with add_device_message('welcome', ...) it must not be recreated when trying to add the same labeled message again.
this pr makes sure, we create the device chat only if the message will really be added to that.
closes #927
> do not create device-chat on skipped messages

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/stock.rs
dc_update_device_chats() add some welcome-messages to the device chat and also sets up the saved-messages-chat.
once merged, it can just be used by the ui, which, however, can add their own messages as needed.
also, after being merged, the strings will be added to transifex to get the message translated.
closes #937
> and a function to create & update device chats

- src/config.rs
- src/stock.rs
did that for configure and stock-strings as this just came over my way. skipped adapting errors to avoid merge conflicts with pending prs.
> improve readability by adding empty lines to enums with strum

- src/configure/auto_mozilla.rs
- src/configure/auto_outlook.rs
- src/configure/mod.rs
- src/configure/read_url.rs
The configure module itself (`mod.rs`) is not resultified yet and just uses `ok()`. That is left for the blocking configure, CBOR etc. refactoring of the configured function itself.
Carefully split into separate commits, do not squash.
> Resultify configure module

- src/chat.rs
- src/job.rs
- src/message.rs
eg. android relies on that and fallsback to wrong aspect ratios otherwise.
also, this makes job.rs a little more readable
as some things are moved to message.rs :)
> calculate image-size in device-messages

- python/tests/test_account.py
- src/chat.rs
- src/e2ee.rs
- Seems we had an error forever in rust-core in that reply-to-encrypted would not force encryption. add a test and fix/simplification. 
- streamline encryption/decryption logging
> Fix longstanding issue: reply-to-encrypted should encrypt

- CHANGELOG.md
The event name was changed, but not yet in the changelog.
> Fix new event name in Changelog.

- src/imap/mod.rs
- src/imap/select_folder.rs
- make setup_handle_if_needed async, call it ahead of select_folder and fetch_new_messages (renamed from fetch_from_single_folder)
- be more eager triggering reconnect on error conditions
> try to make imap reconnection handling more robust

- python/src/deltachat/message.py
- python/tests/test_account.py
- src/chat.rs
remove python-binding's create-copy logic and rather rely on core
> test for sending out a file twice, with html.zip like exts preserved

- src/imap/idle.rs
- src/imap/mod.rs
- src/job_thread.rs
Also introduce Imap.can_idle() to avoid having to match on IdleAbilityMissing error
> Split IMAP idle functions into imap::idle submodule

- deltachat-ffi/deltachat.h
just noticed at https://github.com/deltachat/deltachat-core-rust/pull/964#issuecomment-562575074 that the example was wrong.
also added some missing unref() things.
> adapt the ffi-examples to reality, free stuff

- ci_scripts/remote_tests_python.sh
- ci_scripts/remote_tests_rust.sh
- python/tests/test_account.py
- python/tox.ini
- src/dc_receive_imf.rs
- src/e2ee.rs
- src/mimefactory.rs
- src/mimeparser.rs
- test-data/message/html_attach.eml
- test-data/message/mail_attach_txt.eml
simplebot from @adbenitez calls `dc_send_file(fn, "text/html")` which DC on the receiving side does not see as a file but instead tries to parse and simplify.  This PR aims to preserve the attachment and prohibit parsing of attached text/html files.  It also simplifies and cleans up some code and CI invocations.
> fix incoming text/html attachment in multipart/mixed to remain an attachment

- src/imap/idle.rs
This should make sure that we often quickly recover from network problems. We wait 15 seconds for receiving the answer when trying to terminate an IDLE loop with "DONE".  If it doesn't arrive we kill the connection and cause a reconnection.
> make idle more robust by timing out on idle/done termination 

- python/src/deltachat/chat.py
- python/src/deltachat/message.py
- python/tests/test_account.py
- python/tests/test_increation.py
- python/tox.ini
- src/blob.rs
- src/chat.rs
- src/config.rs
- src/param.rs
This effectively reverts
https://github.com/deltachat/deltachat-core-rust/pull/964 for chat.rs,
which in that PR was thought to fix something.  So maybe something is
still broken?  But after improving tests the previous code seems to be
correct.
- Update Python bindings to not always use dc_prepare_msg path when
sending messages with attachements.  When using dc_prepare_msg the
blobs need to be created in the blobdir since they will not get
copied and many tests where not doing this.
- Add a test that ensures that calling dc_prepare_msg with a
file **not** in the blobdir fails.
- Add a test that ensures that calling dc_send_msg directly with a
file **not** in the blobdir copies the file to the blobdir.  This
test cheats a little by knowing what the filename in the blobdir
will be which is …
> Re-work some in-creation file handling

- src/dc_receive_imf.rs
- src/headerdef.rs
- src/lib.rs
- src/mimeparser.rs
- src/securejoin.rs
Made some header-name errors before and wanted to avoid them generally now. 
i guess the headerdefs.rs is a bit redundant, but i don't know how to generate the capitalized Mime-Header style from the Rust MimeHeader name.
> Define all headers in new headerdef.rs

- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- appveyor.yml
- examples/repl/cmdline.rs
- python/tests/conftest.py
- python/tests/test_account.py
- src/contact.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/error.rs
- src/imap/mod.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/securejoin.rs
> Fix various issues around group add/remove

- src/configure/mod.rs
- add offline-autoconfig for nauta as a first test case (@adbenitez please check and test) 
- fix keep_flags handling (needs checking if gmail oauth still works)
- convert 0x2 to DC_LP_AUTH_OAUTH2
> add preliminary support for offline-autoconfigure for nauta

- src/lib.rs
This reverts commit b424ef9ebb7dda5fd934f09dbae42b81589b9d64.
> Revert "Enable clippy::unreadable_literal error"

- Cargo.lock
this only updates async-smtp and not async-imap, which should be dealt with in a separate PR. 
fixes #1030
> pull in latest async-smtp master to fix smtp crash

- src/lib.rs
- src/log.rs
This is done for all logging calls, also those which call error! which
is normally directly shown to the user.
> Add filename and line no to log entries

- src/log.rs
errors are typically user-visible 
For info and warn it's fine to add file/lineno
> revert printing file/lineno in Error-messages 

- src/log.rs
I'm not sure how useful the name will be on all the apps.  Probably depends on how they are created.  I believe that if the OS facility to name threads is used the name is respected even if the thread was not started by the rust code.
> Add the thread id and name to info and warn log output

- Cargo.lock
- Cargo.toml
- src/imap_client.rs
a greeting is something like  "*OK Dovecot ready" -- without this PR a missing greeting panics.  see https://github.com/async-email/async-imap/commit/4f0852971c3f397c2b8a343ef1378992c02f61de for the fix in async-imap.  This PR also fixes DCC's own reading of the greeting in imap_client.rs. 
This might address #1054
> use dcc-stable branch that returns an error on missing greetings

- src/job.rs
- src/smtp/send.rs
This PR introduces an async-timeout on SMTP send like we do in idle/done() handling. 
alternatively we could try setting a TCP_NODELAY which i think for smtp would be fine as there is no IDLE waiting -- we are basically only doing send() and if that doesn't get traffic for a minute or two it's fine to cancel i guess.  So how about using TCP_NODELAY for smtp?
> try doing an smtp-send timeout

- src/dc_receive_imf.rs
- src/log.rs
- info/warn logging: thread-name seems to be unnamed all the time so it's use is currently theoretic
I'd also like to not print "ThreadId(NUM)" redundantly but not sure what is a good way to get at NUM :/
- remove two info! logs that were too verbose on message-receive and were rather useful for earlier debugging efforts but not now anymore.
> try trim down logging 

- src/smtp/mod.rs
15 minute timeout was used because it applied to the whole send()
operation. Now timeout applies to each I/O operation, such as read()
or write(), so it can be made much shorter. In particular, this timeout
applies to read() call right after connection to plain or STARTTLS server,
in which case it is not reasonable to wait 15 minutes to receive one
line of data.
The timeout is triggered only if no progress is made within 30 seconds. It
likely indicates a network failure anyway.
Fixes #1062
> fix(smtp): reduce SMTP I/O timeout to 30 seconds

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/repl/main.rs
- examples/simple.rs
- src/config.rs
- src/job.rs
generally, we don't know what the inbox imap thread is concurrently doing so blocking is dangerous.
> never block on interrupt_inbox_idle

- python/tests/test_account.py
- src/contact.rs
- src/dc_receive_imf.rs
- fix ordering of parsing of To header to happen after parsing From header -- the latter determines incoming_origin and therefore To-contacts were not added with the proper incoming_origin. This lead to group contacts not being shown when creating a chat 
- move some vars to become non-mut or not even passed to add_parts(), to ease reasoning about what's going on. (more can be done here but i didn't want to modify too much)
> fix group members not appearing in contact list 

- Cargo.lock
- deltachat-ffi/Cargo.toml
- deltachat-ffi/src/lib.rs
- src/chat.rs
This is the first experiment towards using structs to define the API.
The types in this struct could improve as well as many other things.
But this is a straight forward translation of the existing json! macro
into a struct.
> Change the JSON API function to be from a serialised struct

- src/dc_receive_imf.rs
- src/stock.rs
fix #1077 for unknown senders in a group chat (such as mailer daemons……): 
- don't recreate member list and
- show a special stockstring-ed message advising to hit "more info".
> treat unknown senders to a group chat specially, avoid recreating member list 

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
this also pulls in a newer imap-proto that should fix yandex/oauth parsing as it merged a PR from our chief magician @dignifiedquire
> prep beta21

- python/README.rst
-Moved wheels installation below source installation and added comment that they are outdated and not working atm
-Updated source compilation/installation to a more step by step process as current one was outdated and not working due to Rust now needing nightly build else failing to compile (subtle v2.2.2 do not work without nightly)
> Up to date Readme.rst

- src/job.rs
- src/smtp/send.rs
It was used when timeout was set on the whole smtp.send() operation.
Now only the operations inside smtp.send() can timeout, and such timeout
errors result in SendError, so SendTimeout is unused.
> refactor(smtp): remove unused SendTimeout Error variant

- src/dc_tools.rs
This change is a part of the effort to enable `clippy::option_unwrap_used` and `clippy::result_unwrap_used`
> Remove unwrap() from time() function

- deltachat-ffi/src/lib.rs
- examples/repl/main.rs
- examples/simple.rs
- src/context.rs
- src/events.rs
- src/test_utils.rs
- tests/stress.rs
Since stock string callback has been deprecated, all event callbacks
return 0.
For compatibility, C declarations are not changed and FFI users are
expected to return 0 from their callbacks.
> Stop using Event callback return values

- src/context.rs
According to Rust documentation, usize is "The pointer-sized unsigned
integer type".
This change removes unnecessary libc dependency and makes top_evil_rs
script happier.
> Use usize to get pointer size

- src/chat.rs
- src/imex.rs
if we do not reset the device-chat on import, this may result in 
- wrong information (changelog of the wrong system)
- maybe unfunctional message (tap here to optimize battery won't work on desktop)
- important information that cannot be added again (the user may have deleted the message on the other device as it was no issue there - and labeled message are not added again)
there maybe more sophisticated approaches to solve these issues, but this one is simple :)
fixes https://github.com/deltachat/deltachat-android/issues/1187
> reset device-chat on import

- src/job.rs
The logging message printed for successful job completion said that the
job "cannot be retried" even when it does not need to be retried.
> Better logging message for job deletion

- src/chat.rs
- src/chatlist.rs
this pr updates the chat names in the database to the ones provided by the ui (localized names).
we have to do that before every search as we currently do not know when the ui changes the names, however, compared to the following search, this should be a quick sql statement.
fixes #1112
> search for special chat names

- src/chatlist.rs
in general, update-special-name-errors should not break getting chatlists.
> do not abort search completely when updating a special name fails

- src/configure/mod.rs
- src/error.rs
- src/job.rs
- src/lib.rs
- src/location.rs
This will make it possible to distinguish between successful and unsuccessful finish of job in `job_preform` and log the error there.
> Make job error handling functional

- src/contact.rs
this pr adds initializing received authnames - in the past we were leaving the field always empty and update it only in subsequent messages.
not sure if #1014 directly relates to this fix, i added a test that emulates the issue, however, i think this needs some testing with some real accounts/uis as there are more things "on the wire" that can go wrong.
> fix receiving authnames names

- src/qr.rs
this pr fixes the handling of plain OPENPGP4FRP as used eg. by openkeychain. the possible result values were defined correctly and the ui handles these cases, however, there was an early exit when the addr was not set - which is always the case for plain OPENPGP4FRP qr-codes.
fixes #1127
> handle plain OPENPGP4FRP qr-codes correctly

- src/dc_receive_imf.rs
The message says "only using first" so it should be printed right before the first address is taken with .get_index(0) operation.
> Warn about multiple From addresses only when necessary

- src/mimeparser.rs
- test-data/message/mail_with_cc.txt
Normally it happens in addr_cmp function, but update_gossip_peerstates
forms a HashSet of addresses, so they should be lowercased beforehand.
Also adjust the mail_with_cc.txt to test for non-lowercase addresses.
> Lowercase the addresses before gossip peerstate update

- src/dc_receive_imf.rs
this pr hides messages belonging to a failed/incomplete/unknown secure-join from the message list.
we do not delete them from the server, might be that other devices make some use of it or so, not sure.
should fix #1129
> hide messages with Secure-Join headers

- src/chat.rs
This is a new feature in Rust 1.40, it means users outside the crate
will not be able to create these structs, allowing us to add fields
without breaking the public API.
> Mark the ChatInfo struct non_exhaustive

- src/dc_receive_imf.rs
- src/mimeparser.rs
- src/securejoin.rs
The struct really represents a parsed MIME message and is not used as
a parser itself.  After the from_bytes() call (which should arguably
use the FromStr trait instead) the struct is fully populated.
> Rename MimeParser to MimeMessage in mimeparser.rs

- src/chat.rs
this fixes sending out DC_EVENT_CHAT_MODIFIED. it was sent out on removing members, changing name etc. - but it was missing on adding members.
add_contact_to_chat_ex() is called during a secure-join and also by the corresponding api-function, in both cases, the event should be sent.
fixes the bug described in https://github.com/deltachat/deltachat-ios/pull/473
> send DC_EVENT_CHAT_MODIFIED when adding members to a group

- python/tests/test_account.py
- src/mimeparser.rs
This is a preparation for #505 
This PR removes dependency of MDN reception on user configuration of MDNs (disabling MDNs only affects sending and *requesting* of them now, not reception) and fixes creation of multiple jobs that mark MDN message as seen and move it when it contains multiple MDNs.
> Simplify handling of MDNs

- Cargo.lock
- Cargo.toml
- src/mimeparser.rs
It does not allow parsing emails without @
> Update mailparse to 0.10.2

- src/chat.rs
- src/mimeparser.rs
The goal here is to not have a `mut chat_id` as I want to change chat
id into an opaque newtype and we can't modify it like that anymore.
> Refactor create_chat_from_msg_id

- src/mimefactory.rs
this commit sets the subject of groups to the name of the group.
if the message is a reply in the group, also the prefix `Re:` is added.
the Chat: prefix is removed for groups, also the Fwd: prefix, as it this would be expected to be set to the group name of the forwarded message, which is not really compatible with the rule "group-name = subject" (forwarded messages are detected by the body, not by the subject)
this achieves better compatibility with normal email clients as there is an option to set the subject now. also, as replies go to the same group, related mails are shown together and grouped togehter, in both, delta and the conventional client (this won't be easily the case if we would allow to set the subject completely freely)
targets issues as …
> in groups, set subject-header to group-name

- LICENSE
"libs" directory has been removed during transition to Rust
> Remove NOTE about third-party libraries

- src/chat.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/securejoin.rs
I want to avoid having to be able to represent a chat_id of 0 in order
to more nicely turn chat_id into a ChatId newtype.
> Resultify get_chat_id_by_grpid

- Cargo.lock
- Cargo.toml
TIFF file format and parallel processing of JPEGs are not necessary to
recode avatars.
> Disable unnecessary image crate features

- python/tests/test_account.py
- src/headerdef.rs
- src/job.rs
- src/message.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/param.rs
Major changes:
- MDNs may now contain an `X-Additional-Message-IDs` field, which complements `Original-Message-ID` and lists IDs of other messages that were read.
- There is a new SMTP-thread job `SendMdn`, which is different from previous one. It does not have a pre-built MDN message in a blob, but constructs it from scratch on each retry. This way it has an opportunity to consume other `SendMdn` jobs, even if they are added between retries of `SendMdn` job.
- `SendMdn` stores database message id in its parameters and contact id in its `foreign_id` field. Contact ID can be extracted from the `from_id` field of the message record, so this information is redundard. However, it is easy to filter by `foreign_id` in SQL, to find jobs that can be aggregated.
- If `SendMdn` succeeds, it removes …
> Combine multiple MDNs in a single mail

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/repl/main.rs
- src/chat.rs
- src/chatlist.rs
- src/constants.rs
- src/contact.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/events.rs
- src/job.rs
- src/location.rs
- src/message.rs
- src/mimefactory.rs
- src/securejoin.rs
- src/token.rs
This doesn't try and change the way ChatId is used.  It still allows
creating them with 0 and lets some function use a ChatId(0) as error
return.
The main change and starting point to review is probably chat.rs::ChatId and its various impls.
You might want to look at the changes to ResultExt in deltachat_ffi, they're not just adding ChatId.
Otherwise there should be no real logic refactors happening.
> Introduce a ChatId newtype

- src/job.rs
"Cannot be retried" does not make it clear if the job succeeded or failed.
> Fix the message printed on job success

- src/imap/mod.rs
before a message is actually deleted, we verify that server_folder+server_uid matches the Message-ID, so that we do not delete the wrong message by accident.  
the reason for that is that, to my knowledge, server_folder+server_uid are not necessarily stable but Message-ID is.
anyway, this check was broken and set the server_uid to 0 in all cases - where it should be set to 0 _only_ on mismatches.
a test for that would be nice, however, this would require a way to actually check what is going on on the server with an independent imap-toolchain. afaik, this is planned, but just not there :)
closes #1192
closes https://github.com/deltachat/deltachat-desktop/issues/1362
> fix message deletion on server

- src/mimeparser.rs
i don't think this fuzzy test is very useful -- the mime-parser will end very early on random-input and DC's parsing machinery probably almost never runs.
If we want to fuzzy our code and parsing handly we have to fill a kind of template structure with random data, so that DC's code paths for looking and parsing at various stuff is even triggered.
> remove hardly useful fuzzy test

- deltachat_derive/Cargo.toml
Having a number that resembles the core version number is confusing.
This doesn't matter at all, it just needs to be a version number.
fixes #1203
> Change to normal sematic version number for this sub-crate

- Cargo.lock
This should have been updated when the version of deltachat_derive was
changed.  Oops.
> Fix out of sync cargo.lock

- src/blob.rs
- src/dc_tools.rs
`.truncate()` is not safe as it may panic: https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.truncate
This resulted in DC crashing when files with cyrillic filenames are received.
> Fix panic in BlobObject::sanitise_name()

- src/securejoin.rs
this is a follow up on https://github.com/deltachat/deltachat-core-rust/pull/1209 and targets my last comment there.
in general, we should not delete handshake messages possibly belonging to secure-joins on other devices - a `HandshakeMessage::Done` deletes the message and will make fail other devices in a multi-device-setup to succeed. therefore, `HandshakeMessage::Done` should be returned only if the message was consumed successfully. 
in case of join_vg, however, we return `HandshakeMessage::Propagage` instead of Done/Ignore as the message is a normal group-added messages that should be handled - esp. if the group is not a verified group. (verified-groups and multi-device seems to be out of scope of this pr)
> do not delete handshake messages possibly belonging to secure-joins on other devices

- src/oauth2.rs
oauth2 crashes in beta23
because we did not let Serde remove the quotes from a parsed JSON email-address.
for autoconfig, we try to get a well-known URL
containing the domain of the used address - with the quote that is
https://autoconfig.gmail.com"/mail/config-v1.1.xml?...
unfortunately, instead of just returning an error,
(the url does not exist anyway)
reqwest crashes on the attempt to get this URL.
the Serde-thing is not obvious to me:
while serde_json::Value.as_str() removes the quotes,
serde_json::Value.to_string() does not.
fixes #1211, fixes https://github.com/deltachat/deltachat-android/issues/1222
> fix oauth2 login by fixing a Serde call

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
i did a `git tag 1.0.0-beta.24` and a `git push --tags` on the branch, not sure if this is sufficient.
EDIT: they go directly to master, so, if this is merged, things should be fine. for the future,  `git push --tags` should be done after merging. maybe we should add a hint to set_core_version.py's output, i am always again unsure about that.
> prepare 1.0.0-beta24

- deltachat-ffi/deltachat.h
- src/securejoin.rs
this pr changes the behavior when scanning a setup-contact qr-code.
instead of waiting, until the whole protocol is finished,
which may take something between 10 seconds and several minutes,
the dc_join_secure_join() returns instantly;
the uis typically show the created chat then.
the returned chat-id is the same than if we wait for the protocol to finish,
it is the opportunistic one-to-one chat-id, so no changes there.
all this works even when both devices are offline.
after dc_join_secure_join() returns, however,
the usual setup-contact continues. ux-wise, once the protocol finishes,
a system-info-messages is added to the chat (also unchanged),
this is directly visible, in the chat as well as in the chatlist.
while the prococol runs, the user can alredy send message to the chat,
or do …
> instant success on simple qr-setup-contact

- src/config.rs
- src/mimefactory.rs
Previously error message and condition used different values.
C core used `DC_MSGSIZE_MAX_RECOMMENDED` constant.
> Move message size limits to constants

- deltachat-ffi/src/lib.rs
error!() will show the error directly to the user,
this is not useful in this case,
and also the message with the function-name is not for the end-user.
instead, the ui shall (and already does)
show some explaining text if dc_has_import() returns false;
the error!() is disturbing here as this results in two hints shown to the user.
closes https://github.com/deltachat/deltachat-android/issues/1232
> do not bubble up errors on dc_has_import()

- python/tests/conftest.py
- python/tests/test_account.py
- python/tox.ini
Configuring an online account generates a key, we would like this
code-path tested too.  So add some functionality to the AccountManager
to not use the pre-generated keys.
Because this slows down interactively running the tests by hand add an
ignored marker which only runs if --ignored is used.  This name was
chosen because this matches the naming used by rust/cargo #[ignored].
The difference however is that --ignored on cargo *only* runs ignored
tests while here it runs *all* tests.
To ensure the ignored/slow tests are run on CI we add it as an
argument to the tox configuration, which is used by the CI to run the
tests.
> Add an integration tests which generates a key

- deltachat-ffi/src/lib.rs
- deltachat-ffi/src/tools.rs
- src/chat.rs
This clarifies some behaviour with negative times and propagates
errors a bit better around places.
> Use SystemTime instead of i64

- src/imap/mod.rs
This capability is not used by Delta Chat. Moreover, XLIST is deprecated
in favor of https://tools.ietf.org/html/rfc6154, which should be
supported instead. Delta Chat already looks for \Sent attribute in
get_folder_meaning().
> Do not check for XLIST capability

- Cargo.lock
- src/dc_receive_imf.rs
- src/imap/mod.rs
- src/job_thread.rs
> Avoid downloading messages that Delta Chat does not display

- python/tests/conftest.py
- python/tests/test_account.py
Fixes #1252 
Using peek_online_config() results in a message being sent to some
other account, used by previous test. If tests are run in parallel,
for example with pytest-xdist, we could be sending a message to a still
online DC client.
> Fix test_one_account_send_bcc_setting

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- deltachat-ffi/src/tools.rs
- python/src/deltachat/chat.py
- python/tests/test_account.py
- src/chat.rs
- src/sql.rs
To Do:
- setMuteDuration(mute duration in seconds | -1 for forever | 0 for unmute)
- getRemainingMuteDuration() -> mute duration in seconds (positive integer) | -1 for forever | 0 for not muted
-> so the client doesn't need to deal with the unix timestamp too
After thoughts:
- ~~cleanup function that removes expired mute duration from the db once in a while~~
- Android backwards compatibility
- implement in cli/repl? does it have notifications at all?, otherwise it would make no sense.
Note to UI developers:
Basically on message before sending the notification, check `is chat muted`
Also setting and getting mute duration is in relative seconds until the mute is lifted again.
> feat: mute chat

- .github/workflows/code-quality.yml
This is to catch bugs similar to the one introduced in #1254: https://github.com/deltachat/deltachat-core-rust/pull/1254#issuecomment-584398352
> GitHub actions: check all packages, examples, tests and features

- python/README.rst
- python/tests/conftest.py
For creating temp accounts the Circle CI env variable "DCC_NEW_TMP_EMAIL" is set to a url with which we do a POST request to create a new temporary one-day account for testing.
> use new URL format and service provided by mailadm

- deltachat-ffi/src/lib.rs
A couple of straight forward cleanups that should make future life that little bit easier.
Most importantly remove the option to display errors to the user, this is none of the ffi's business.
See commits for step-wise justifications.
> clean up and simplify the ffi code a little bit

- src/chatlist.rs
we forgot to respect the new pinned-state for the list of shared chats
as it is shown eg. in the profile of a contact.
> fix order of shared chats, move pinned up

- src/mimeparser.rs
[RFC 2183](https://tools.ietf.org/html/rfc2183) specifically allows filenames to be specified for MIME parts with "inline" Content-Disposition.
Previously we treated such attachments as an error, causing the whole message parsing to fail. Now it is only an error if Content-Disposition cannot be parsed.
MIME parts with filename are now considered to be attachments regardless of their Content-Disposition type. However, "attachment" Content-Disposition is still processed differently: we generate a filename for it even if it is not specified.
Fixes #1269
> Allow inline attachments

- src/chat.rs
the current tests are unreliable as several chats created in the same second have an unpredictable order (by the ID as the secondary sort criterion, the order is stable, however, we cannot really guarantee some IDs).
this pr fixes this issue by waiting a seconds before the next chat is crated. compared to how long the tests run at all, this is probably okay.
> fix pinning test by forcing a reliable order

- src/contact.rs
- src/dc_receive_imf.rs
- src/mimeparser.rs
Where needed, Option<AvatarAction> can be used to extend it.
> Remove AvatarAction::None

- deltachat-ffi/src/lib.rs
- examples/repl/main.rs
- examples/simple.rs
- src/configure/mod.rs
- src/imex.rs
- src/lib.rs
Now configure module is no longer public. Users should call
Context.configure() and Context.is_configured() methods.
Configure module is completely hidden from documentation unless
--document-private-items option is specified.
> Turn deltachat::configure functions into Context methods

- deltachat-ffi/src/lib.rs
- deltachat-ffi/src/string.rs
I know this really doesn't matter, but I couldn't help myself wanting to figure this out.  This is the most elegant way I could achieve this, but please correct me if I am wrong about the need to create a new trait.
We already have a .strdup() method on AsRef<str>, this adds this
method also to an option of this.  In case the option is None a NULL
pointer is returned.
This is done by using a new trait, as the type system otherwise
considers such an implementation conflicting with the existing one.
> Add .strdup() method to Option<AsRef<str>>

- deltachat-ffi/deltachat.h
- python/src/deltachat/const.py
- python/tests/conftest.py
- python/tests/test_account.py
- src/config.rs
- src/constants.rs
- src/e2ee.rs
- src/pgp.rs
rPGP generates EdDSA and and ECDH keys using Ed25519 only, so there is
no need to specify it explicitly anywhere.
Fixes #818
> Change generated key type to Ed25519

- spec.md
- src/chat.rs
- src/dc_receive_imf.rs
up to now, `Chat-Group-Member-Added` and `Chat-Group-Member-Removed` commands result in a complete recreation of the memberlist by collecting all addresses from the From: and To: headers.
this easily results in missed and accidentally removed members, esp. when several people at the same time scan a qr code to join a group.
this pr changes the behavior of adding members by _not removing_ members on the `Chat-Group-Member-Added` command. instead the existing memberlist is conjuncted with the memberlist seen in the message.
_only_ adding the member from the `Chat-Group-Member-Added`-header seems not to be sufficient - imaging a group of Alice and Bob:
- Alice adds Claire
- Bob adds Dave _before_ seeing that Alice added Claire
- Dave would never get the information that Claire is in the …
> alter the memberlist more carefully

- src/job.rs
- src/smtp/mod.rs
- src/smtp/send.rs
This likely fixes #1214  also refactors performing the job-action into an own function removes the slightly complicated map().find() iterative 2-tries loop. 
The PR will immediately attempt to reconnect in case of an smtp-send error, if the last success connect or send is more than 60 seconds ago.  Previously the send-job was scheduled to retrying later which can be some 10-60 seconds (or more if the smtp-job is already retried!) delay before a message goes out.  Note that if the connect-attempt fails (because we are really offline) the send-job will be retried later (with expontential back-off delays). 
Note that without the "<60 secs" check, we might enter a busy loop producing network traffic, i.e. if we successfully connect but then somehow (SSL error or whatever) fail to send the …
> directly attempt to re-connect if the smtp connection is maybe stale

- src/contact.rs
this pr add some failing tests (first commit) that is then fixed by the second commit by:
- if a manual name was never given, always update names from incoming mails
- if a manual name is cleared, fall back to names from incoming mails
i think, this has never worked, neither in core-c nor in core-rust, but now it should :)
also, some comments from core-c are re-added.
fixes #1014
> fix updating names from incoming mails

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
- set_core_version.py
we're leaving the beta track with this release \o/
the initial idea was just to use `core.25` as the version name, however, this is not easily possible, rust/cargo/whatever complains about "Error parsing major identifier for key 'package.version'" , so i've choosen the simple way :)
> prepare 1.25.0

- src/dc_receive_imf.rs
- src/imap/mod.rs
- src/mimeparser.rs
Message-IDs are not addresses, and should be parsed differently.
> Use new mailparse API to parse Message-IDs

- Cargo.lock
This version fixes incorrect serialization of ECC session keys with
leading zeros.
Fixes #1313
> Update rPGP to 0.4.1

- src/pgp.rs
the currently released versions fail sometimes in encrypting to ecc keys,
see #1313, the issue is about to be fixed,
however, we should not generate ecc keys until the
fix is rolled out - otherwise new users will get encryption errors every some
messages if their counterpart is not yet using the most recent version.
we can start generating ecc keys a few weeks after the fix is rolled out.
> revert generating ecc keys for now

- src/chatlist.rs
- src/dc_tools.rs
- src/message.rs
this pr removes linebreaks from the summaries so that they appear nicely in the chatlist and no unexpected additional text appears when a message is viewed in detail. the ellipsis is now only shown when the summary is really too long.
there was a flag "unwrap" in the called dc_truncate() function, but it did not work this way (it was okay in core-c, probably lost by some refactoring). in fact, the flag was used to choose between different ellipsis, however, this is not needed as all uis will truncate the text pixel-accurate anyway.
so, this pr also removes this unused flag.
> remove linebreaks from summary

- src/imap/mod.rs
This way we avoid trying to delete already deleted messages in the future.
> Reset server_folder and server_uid in Imap.empty_folder()

- deltachat-ffi/deltachat.h
- src/chatlist.rs
- src/constants.rs
this pr adds the flag `DC_GCL_FOR_FORWARDING` to `dc_get_chatlist()` that will sort the "self-talk" aka "saved-messages" to the top of the chatlist.
this is useful for the UI displaying a "forward" dialog, allowing the user to select the "saved messages" chat fast, without searching or scrolling.
> optionally sort 'saved messages' atop of the chatlist

- src/dc_receive_imf.rs
at least the last release does not show replies from non-dc-clients.
reason is that the Message-ID is stored without angle brackets in the database, but the mimeparser returns list that include them. the checks `is_known_rfc724_mid()` and `is_msgrmsg_rfc724_mid()` fails then (not sure if we really need both functions, but that is out of scope of this fix)
this pr adds a failing tests and makes `is_known_rfc724_mid()` and `is_msgrmsg_rfc724_mid()` more resilient, accepting both the square-angle-format and the raw-format, it seems to be hard and errorprone to force the one or the other, there are various deeply nested paths where the IDs come from, the used libs may change etc.
btw, i think, this fix justifies new releases, as the communication with non-dc-clients is a core feature and does …
> fix showing non-dc replies

- python/tests/test_account.py
- src/mimefactory.rs
this pr corrects the To:-list for groups with only SELF as member.
before, the list was empty and trying to send to groups that only contain SELF lead to a crash.
in theory, this happens for both, bcc_self enabled or not, however, if bcc_self was disabled (default setting), things worked as the whole mimerendering was skipped on a higher level. also, the saved-messages-chat was not affected as this was checked explicitly.
this pr changes the mimerendering so that From: is used as To: for all groups that contain only SELF.
successor of #1346, fixes #1320
> fix crash in self-only-groups with bcc_self enabled

- src/dc_receive_imf.rs
in the first commit, this pr adds a lot of tests wrt show_emails option, including an initially failing test, where an non-delta-group-messages shows up in the one-to-one-chat of the sender instead of creating an adhoc group. this happens only when show_emails was set to "accepted contacts", see #1349 for more details.
the second commit fixes the issue by allow group-creation if there is already a one-to-one-chat - if not, the value stays unchanged.
fixes #1349
> fix classic-email interactions

- src/configure/mod.rs
- src/constants.rs
- src/imap/mod.rs
this pr actually uses the folder-delimiter provided by the imap-server in the LIST-command.
moreover, this pr really does a folder-reconfigure on dc_configure() - this is needed as configure may change the whole server; this folder-reconfigure on dc_configure() was also done in core-c and somehow lost.
closes #1360
> fix imap delimiter

- src/pgp.rs
after fixing some issues wrt ecc keys, see #1319,
and waiting some time (three core releases, two ios/android/desktop releases),
it is now the time to switch again to ecc keys again,
after the first attempt was stopped in #1319
> switch to ecc keys

- src/dc_receive_imf.rs
- src/securejoin.rs
up to now, we've ignored our own securejoin we're observing on other devices completely.
this is fixed by this pr, the messages from a secure-join on DeviceA will no longer show up on DeviceB, closes #1300 
moreover, i did a larger comment about what seems to be needed if we want to verify contacts across devices, when reviewing this pr, please also have a look at the comment above observe_securejoin_on_other_device()
> ignore handshake messages seen from another device

- src/chat.rs
- src/config.rs
- src/sql.rs
This is a follow-up for PR #1310 to delete old messages locally.
Messages should be deleted at least when chat messages are requested by the application, and maybe also during housekeeping or even from a separate thread to clean up chats that user does not open frequently.
> Local message deletion

- deltachat-ffi/src/lib.rs
- deltachat-ffi/src/string.rs
- tests/stress.rs
CString::yolo was still used in the ffi, this was an unsafe
transitional thing.  To remove it there were two choices: 1. make
errors in creating CStrings hard errors or 2. try and be as lenient as
possible.  Given the to_string_lossy() convention adopted in the ffi
this choose the lenient option and simply skips over embedded null
bytes, leaving the rest of the strings intact.
Thus now CString::new_lossy().  It's only used for .strdup() however
so no longer a public trait.
This also cleans up the public visibility of things in the strings.rs
file:
- Rename StrExt/OptStrExt traits to what they actually do: provide
.strdup() -> Strdup/OptStrdup.
- dc_strdup() should be an implementation detail, replace all usages
with Strdup.strdup() method.
- Only allow visibility inside the crate for all …
> Remove unsafe CString::yolo from ffi

- src/chat.rs
I have a verified chat where one user can't be removed for whatever reason. The problem is that even though error is displayed and user is not removed, the message "user ... removed by me" is added to the chat each time. With this fix error is displayed, but the system message is not added.
> Add system message only if contact was removed successfully

- src/e2ee.rs
- src/pgp.rs
due to the ecc-move, they are no longer expensive.
> do not ignore keypair generation test

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/repl/main.rs
- src/chat.rs
- src/chatlist.rs
- src/config.rs
- src/dc_receive_imf.rs
- src/imap/mod.rs
- src/job.rs
- src/message.rs
- src/mimeparser.rs
- src/param.rs
- src/sql.rs
Update: now this PR includes local message deletion as well.
----
Summary of this PR:
- New setting `delete_server_after` is added, specifying the number of seconds after which the message should be deleted on the server. It is 0 (off) by default, 1 for "at once" option, > 1 is the number of seconds after which the message should be deleted. "1 second" is not an option.
- `delete_device_after` is planned for local deletion, but is not implemented in this PR
- A hidden entry is added to the chat for MDN messages, just like we did for `location.kml` messages before. It is needed to track MDN `server_uid`, so we can delete it on the server when it expires.
- `MarkseenMdnOnImap` job type is removed. Its name is misleading, it also moved MDNs to DeltaChat folder. Now that MDNs are treated as …
> Delete messages from IMAP server and device after user-configurable time

- src/smtp/mod.rs
This only makes SMTP behave the same as IMAP (see https://github.com/deltachat/deltachat-core-rust/blob/master/src/imap/mod.rs#L294 called at https://github.com/deltachat/deltachat-core-rust/blob/master/src/imap/mod.rs#L407) but it fixes #1377.
> Emit an event when SMTP fails (the same is already done for IMAP), fix #1377

- src/chat.rs
- src/sql.rs
This is a better tested version of #1380 
There is only a basic test, because rust has no API to inject encrypted/unencrypted messages into chat. Instead `INSERT INTO msgs` queries are used everywhere. But even this basic test revealed a bug in #1380:  `parent_is_encrypted` returned an error when there were no messages in the chat.
I have factored out SQL logic to handle "no rows" and `NULL`s into `Sql.query_get_row_option()` and used it here to fix the bug.
> Filter parent messages by state instead of UID 

- src/dehtml.rs
In both failing emails (https://github.com/deltachat/deltachat-android/files/4175240/Efemerides.del.dia.5.de.febrero.eml.txt, https://github.com/deltachat/deltachat-desktop/files/4213375/owa_normal.txt) there was an unclosed `<meta>` tag. I copied one of the emails into a test.
fix #1373
> Fix #1373, ignore incorrect html close tags

- src/job.rs
Maybe a better approach than #1371, also fixing #1341. Someone (or I) might look through https://tools.ietf.org/html/rfc3463 and decide what error codes might be a temporary error even though they started with 5.x.x. Actually, I think that it is better to wait and see what happens in practice.
@r10s how do I get the ChatID for chat::add_info_msg? I tried `foreign_id` but it didn't work.
fix #1341, fix #1371
> For permanent smtp error 5.5.0, try again. For others, send info message.

- src/mimeparser.rs
- src/securejoin.rs
this pr implements secure-join multi-device as described at https://github.com/deltachat/deltachat-core-rust/pull/1314/files#diff-8dd1fb9fed67be11d40e43966774d5d0R773
this adds some complexity, not sure if it is the right way to go.
maybe some simple self-sent-sync message is easier and solves more problems.
otoh, this one is done, needs some testing, however :)
> multi-device secure join

- src/simplify.rs
Just stumbled about this while working on mailing lists: If a message starts with "---" or similar it is completely ellipsized and only `[...]` is shown. In this case, instead show the complete message.
> Do not ellipsize everything in a message, do not ellipsize non-standard footers in chat messages

- python/examples/group_tracking.py
- python/examples/test_examples.py
- python/src/deltachat/account.py
- python/src/deltachat/chat.py
- python/src/deltachat/hookspec.py
- python/src/deltachat/message.py
- python/src/deltachat/testplugin.py
- python/tests/test_account.py
- src/chat.rs
Python: 
- ignores DC_EVENT_MEMBER_REMOVED/ADDED events and rather looks at system messages to determine to generate python-level ac_member_added and ac_member_removed events 
- add ac_chat_modified hook event
- add account.get_contact_by_addr (thanks @r10s)
rust: avoid duplicate DC_EVENT_MSGS_CHANGED for removed contacts
> refine generation of member-added and member-removed python-level events

- src/chat.rs
- src/chatlist.rs
For hidden messages, blobs are not deleted during housekeeping. To
actually free the space used by media files, messages should be moved to
trash instead of being hidden.
> Delete expired messages instead of hiding them

- src/test_utils.rs
Think that it would be useful to see all  output in all tests for debugging. I mean, this output is needed to find out why the test is failing.
If there is a reason no to accept this PR, it doesn't matter, I'll just locally keep these changes for test debugging.
> Log to the stdout and stderr in tests

- src/dc_receive_imf.rs
- src/imap/mod.rs
- src/message.rs
If `precheck_imf` fails to check if message with the same rfc724_mid
already exists, the same message may be downloaded twice. Instead,
abort the whole operation and retry later.
An attempt to address #1404
> Do not ignore database read errors in precheck_imf

- deltachat-ffi/deltachat.h
"The image will immediately be copied to the `blobdir`; the original image will not be needed anymore."
For whoever wrote the concerning of the Android client, this obviously wasn't clear (I fixed the Android problem in https://github.com/deltachat/deltachat-android/pull/1304)
> Improve descriptions for the profile image files

- src/contact.rs
- src/context.rs
- src/dc_tools.rs
- src/e2ee.rs
- src/imex.rs
- src/key.rs
- src/pgp.rs
- src/securejoin.rs
**tl;dr**
- Do not leave internal API in half-finished state, new API adopted in #1237
- New API has stricter correctness guarantees
- Avoid the need everywhere to explicitly check key was generated correctly
- This isn't the last PR in this series, this API is still in transition but doing this in smaller chunks for reviewability.
This moves the loading of the keys from the database to the trait and
thus with types differing between public and secret keys.  This
fetches the Config::ConfiguredAddr (configured_addr) directly from the
database in the SQL to simplify the API and consistency instead of
making this the responsiblity of all callers to get this right.
Since anyone invoking these methods also wants to be sure the keys
exist, move key generation here as well.  This already …
> Move key loading from deprecated Key struct to DcKey trait

- src/context.rs
this pr adds the context-uptime in the format `1h 2m 3s` (for 1 hour, 2 minutes, 3 seconds) to the string returned by `dc_get_info()`.
as the `dc_get_info()` output is shown on all os, one can now get an idea, how long the app is actually running - this is useful for debugging, so you can easily check if an app was killed in between on android.
it is no perfect tracking, of course, but it can give some basic information about what is going on - with very little effort.
maybe lib-update may be even more useful, however, this would require some struggling with rust-static-globals-lazy-whatever, therefore, i've chosen the simple way and added context-uptime just to the Context object.
the idea was brought up by some recent android-background discussions.
> add context-uptime to dc_get_info()

- README.md
Also set the database path to ~/deltachat-db so that nothing has to be changed in the command (it can just be copy-pasted).
> Update Readme.md: Explain database path, fix #1431

- src/mimefactory.rs
- src/simplify.rs
the footer mark normally used in email-conversations is `-- `, note the trailing space, see RFC 3676, §4.3
unfortunately, the final space is removed by some providers, which lead to footers showing up on delta-to-delta-conversations (on nondc-to-delta, this is not an issue as we cannot be sure anyway
and show a [...] therefore)
this pr accepts lines with only `--` as a footer separator if there is no other footer separator and if the line before is empty and the line after is not.
as there is still some chance to remove text accidentally, the second commit adds protection against that by completely avoiding the string `--` at the beginning of a line of a normal text message.
fixes #1429, fixes https://github.com/deltachat/deltachat-android/issues/1082, fixes …
> regard line with ony '--' as footer mark partly

- src/context.rs
- src/dc_tools.rs
use std::time::SystemTime for uptime calculation, std::time::Instant does not count eg. doze-time on android.
moreover, this pr moves duration-formatting to a separate function and test it (first i suspected the duration-formatting to do weird things :)
> fix uptime debug output

- deltachat-ffi/src/lib.rs
- src/context.rs
BTreeMap is sorted by keys when iterated, making it easier to find the
required line.
Replaces PR #1428
> Return BTreeMap instead of HashMap from get_info()

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
before doing a release, ~~i'd like to get #1422 #1426 #1428 in.~~ EDIT: done :)
~~moreover, i'd like to double-check https://github.com/deltachat/deltachat-core-rust/pull/1393/#issuecomment-613435630 (that time i could not build because of another bug ;)~~ this should not block a release
finally: what is about the missed messages?
> prepare release 1.29

- src/dc_receive_imf.rs
these events take the message-id as parameter and might be used to update an existing list (although to recommended)
if the event is issued for hidden messages, this might led to "empty" messages flashing up -
the ui tries to get the message from the event, after a moment, on the next update, the message disappears again as hidden messages are of course not returned eg. by dc_get_chat_msgs().
the effect was probably always visible for secure-join-messages on ios, however, become much more visible recently when read-receipts are added as hidden messages as well (to make them auto-deletable).
fixes https://github.com/deltachat/deltachat-ios/issues/659 as ios adds the message from DC_EVENT_INCOMING_MSG unconditionally to the chat, @Jikstra @Simon-Laux doesn't desktop do something similar? at …
> do not send DC_EVENT_MSGS_CHANGED or DC_EVENT_INCOMING_MSG for hidden messages

- src/imap/idle.rs
- src/imap/mod.rs
- src/imap/select_folder.rs
- src/job_thread.rs
Previously it was needed to pass `None` to trigger expunge when folder is already selected, and it did not deselect folder.
First commit makes `CLOSE` the first command to execute if expunge is needed. If `None` is passed, the folder is deselected.
Second commit removes the possibility to pass `None` to `select_folder`: it is never actually needed and we can make new method `close_folder` public if someone later needs to do it.
Closes #1382
> Always expunge on select_folder() if needed.

- deltachat-ffi/deltachat.h
- src/config.rs
- src/constants.rs
this pr adds the option "media_quality" to the core that can be get/set by the UIs - but also by the maybe upcoming provider-defaults from #1441 
with this pr, the provider-db will support sth. as
```
config_defaults:
media_quality: 1
```
currently, it is up to the UIs to respect the option and it is currently only implemented on android, however, this can change in the future, at least for images (we already have image-recoding for avatars, so that part is pretty simple and would streamline things between android/ios/desktop)
> support dc_get|set_config("media_quality")

- src/dc_receive_imf.rs
- src/imap/mod.rs
If error is ignored, the message will never be fetched again, even if
there was a database write error.
Addresses https://support.delta.chat/t/reload-partially-recieved-messages/954 and, maybe, #1412
May cause endless loops and not downloading any more messages if there is an error in some IMAP or parsing code, so extensive testing is needed before releasing.
> fetch_single_msg: do not ignore dc_receive_imf errors

- src/mimeparser.rs
Outlook specifies filename there and omits Content-Disposition.
Fixes #1122
> Parse attachment filenames from Content-Type "name" attribute

- src/dc_receive_imf.rs
- src/e2ee.rs
- src/headerdef.rs
- src/imap/mod.rs
- src/mimeparser.rs
Fix #1120 and (I think) fix #1421.
I repaced all `addrparse`s with `addrparse_header` and added some tests. In some cases I have `addrparse_header` has to be invoked and the result has to be stored as the original mail will not be stored and it would be too hard to store it (borrowing problems...). @link2xt explained this nicely in the issues I liked above.
I didn't use `MailAddrLists`s because they can contain `Groups`s of email addresses, which makes iterating over them harder. Instead, I used `Vec<SingleInfo>`.
Two times, (14c19d5a7c107ff82c5e6c80f57f6f2275f45de6 and 6f009b71ef90ec9f48dcfa847dc7d1f6ea474cf8) I tried functional style but failed to get it to compile because of borrowing problems. Maybe someone wants to have a look at it, but maybe it is not possible using functional …
> Fix #1120 Contact requests are not shown when name of sender includes a comma character

- src/chat.rs
Especially with read receipts, it is wrong, because they are never
encrypted and their Message-IDs are not known to other users in a group.
> Do not reply to hidden messages

- src/dc_receive_imf.rs
- src/mimeparser.rs
with 0.12.0, Message-Id parsing easily results in errors ... see https://github.com/deltachat/deltachat-core-rust/issues/1461#issuecomment-626320783
closes #1461 
~~TODO, maybe in another pr: avoid other usages of mailparse::msgidparse(), more concrete in is_known_rfc724_mid_in_list() and is_msgrmsg_rfc724_mid_in_list()~~ EDIT: done
> be more tolerant on parsing Message-Id

- src/sql.rs
These errors are usually just "database busy" errors, it is enough to
write them to the log instead of displaying to the user.
> sql: do not send DC_EVENT_ERROR on database errors

- src/imap/mod.rs
- src/smtp/mod.rs
It uses stock string, just as for IMAP errors, and is distinguishable
from IMAP errors: protocol is specified in the error message now.
Follow-up for #1378, maybe addresses https://github.com/deltachat/deltachat-ios/issues/669
> Better SMTP ErrorNetwork message

- src/message.rs
This function should only return temporary errors, e.g. database errors,
as precheck_imf() and dc_receive_imf::add_parts() treat them as such,
retrying the fetch on failure. When permanent errors, like missing
Message-ID, are bubbled up, they cause infinite fetch loop.
Fixes #1461
> Do not return "empty rfc724_mid" errors from rfc724_mid_cnt

- src/imap/idle.rs
- src/imap/mod.rs
- src/imap/select_folder.rs
- src/job_thread.rs
This reverts commit b614de2f8062772bd9b042550b5d24a91aa5c8ad.
There is also a corrupted comment in this commit. Let's just revert it to fix #1443
> Revert "imap: simplify select_folder() interface"

- src/configure/mod.rs
- src/provider/data.rs
- src/provider/mod.rs
- src/provider/update.py
this pr adds the possibility to use provider-specific-defaults for typically user-changeable options.
the options for which you can define provider-specific-defaults are eg.  `bcc_self`, `e2ee_enabled`, `sentbox_watch` and so on, in theory, every option that can be changed by [`dc_set_config()`](https://c.delta.chat/classdc__context__t.html#aff3b894f6cfca46cab5248fdffdf083d)
to get the provider-specific-defaults,  add a section as the following to the [provider-db](https://github.com/deltachat/provider-db/tree/master/_providers):
```
config_defaults:
bcc_self: 0
e2ee_enabled: 0
sentbox_watch: 0
mvbox_watch: 0
mvbox_move: 0
media_quality: 1
```
the provider-specific-defaults are applied once after the first successful configuration, they are not applied later on re-configures or on updates …
> optionally get default-options from provider-db

- src/chat.rs
The condition remains from the time when expired messages were hidden
instead of being moved into trash chat. As a result, old hidden
messages, such as location messages, were not deleted.
> Delete hidden expired messages

- deltachat-ffi/deltachat.h
Make clear that dc_set_chat_mute_duration() and dc_chat_is_muted() belong together.
> Make clear that dc_set_chat_mute_duration() and dc_chat_is_muted() belong together.

- src/imap/mod.rs
this pr adds `sentmail` to the list of known sent-folder-names, the name is actually used for chello.at
moreover, the searching for well-known names is done in a second pass and only when there is not sent-attribute found for any folder, see commit message for some more details.
closes #1486
> improve finding out the sent-folder

- src/context.rs
- src/sql.rs
this pr enables WAL unconditionally and also adds the current state to dc_get_info() which is useful for debugging.
see https://sqlite.org/wal.html and recent discussion on irc and on github eg. on #991 #1489 
@link2xt @dignifiedquire @hpk42 @Hocuri @flub @others anything speaking against enabling that?
> enable sqlite's WAL mode

- standards.md
the document standards.md exist since a long time
to get an overview but also a nice reference to get some links.
however, its placement in the android-repo is a bit unlogical,
probably comes from a time where there was only one implementation :)
as ios and desktop use the same standards and as
all acutal implementations are in the core,
we move it to the core repo.
android can have a link to the new place.
> move standards.md here

- README.md
Per this comment on the forum by @r10s: https://support.delta.chat/t/native-client-for-linux-based-mobile-os/912/12?u=lupine
telepathy-padfoot is still in progress, but already allows desktop and mobile linux text communication, using deltachat-core-rust and telepathy to get the Empathy GTK client to send and receive messages.
> Add telepathy-padfoot to the README

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- python/src/deltachat/events.py
this pr does a rough documentation of the new functions and adds it to doxygen.
moreover, this pr reverts the change from data2_str tp data3_str, i agree that it would produce too much unneeded noise currently :)  
there was one line in the python-bindings that use data3_str, i've changed that.
> ffi doc for async-jobs, keep name for data2_str

- deltachat-ffi/deltachat.h
- src/context.rs
this pr removes the condition to check is_io_running() before start_io() can be called; same for stop_io(), successor of https://github.com/deltachat/deltachat-core-rust/pull/1529#pullrequestreview-417998214
i am not yet deep into async, so not sure, if the calling is correct - or maybe i've overseen sth. :)
also, if this does not fit well into some internal concepts or thinkings, i would also be fine with this being closed again, it is only a tiny detail that can also be handled by the ui - otoh, of course, it is great if there is one thing less the ui has to take care about :)
> forgiving start_io() and stop_io()

- src/e2ee.rs
- src/imex.rs
- src/key.rs
- src/pgp.rs
Migrates .verify() and .split_key() to DcKey.  Removes all remaining
uses of Key.
Final followup of #1497 #1494 #1365 and #1237
> Finish Key->DcKey refactoring

- src/e2ee.rs
- src/imex.rs
- src/key.rs
- src/pgp.rs
This means all key conversions/serialisation/deserialisation can be
done with DcKey rather than Key.  Also migrate all key conversion
tests to DcKey rather than Key.
This is a followup to #1494 getting closer to the completion of this transition.
> Move ascii-armored stuff from Key to DcKey

- src/contact.rs
- src/context.rs
- src/e2ee.rs
- src/imex.rs
- src/key.rs
- src/keyring.rs
- src/peerstate.rs
- src/pgp.rs
- src/securejoin.rs
This moves both the Keyring and the fingerprints to the DcKey trait,
unfortunately I was not able to disentangle these two changes.  The
Keyring now ensures only the right kind of key is added to it.
The keyring now uses the DcKey::load_self method rather than
re-implement the SQL to load keys from the database.  This vastly
simpliefies the use and fixes an error where a failed key load or
unconfigured would result in the message being treated as plain text
and benefits from the in-line key generation path.
For the fingerprint a new type representing it is introduced.  The aim
is to replace more fingerpring uses with this type as now there are
various string representations being passed around and converted
between.  The Display trait is used for the space-separated and
multiline format, …
> Move Keyring and fingerprint to DcKey trait

- Cargo.toml
- src/contact.rs
- src/dc_tools.rs
Fix #1474 "Sending message to contact with < or > in Recipient gets treated as "Sent" but is not received".
As I was at it, I also extracted the correct name and address from addresses like `Mueller, Dave <dave@domain.com>`.
> Fix #1474 "Sending message to contact with < or > in Recipient gets treated as "Sent" but is not received"

- src/dc_receive_imf.rs
- src/mimefactory.rs
- src/param.rs
- src/stock.rs
The last subject is now set as a param to the chat. It turned out that the subjects are not saved anywhere, only together with the body in txt_raw. 
I could have extracted it from there but this would have felt very hacky. 
I thought about splitting up txt_raw into subject and body but I would have had to change the database structure and I am pretty sure that this is not a good idea because the databases would have to be migrated when updating DC.
Now we have a bit of redundance in the database, but I think that this is the best way.
> Set subject to Re: <last subject> for better compability with normal MUAs

- python/tests/test_account.py
- src/chat.rs
- src/dc_receive_imf.rs
- src/mimeparser.rs
Trying to reproduce #1565 
`ac1` establishes keys with `ac2` and `ac3`. Then `ac2` is cloned into `ac4` with a new key to simulate reinstallation. `ac1` creates a group with `ac2` and `ac3` and sends two messages there.
Received messages have IDs like `Gr.YhIUVTlAq0F.…`, but `ac4` assigns them to a different group ID:
```
7.47 [events-ac4] DC_EVENT_WARNING data1=0 data2=src/mimeparser.rs:162: decryption failed: missing key
...
7.50 [events-ac4] DC_EVENT_INFO data1=0 data2=src/dc_receive_imf.rs:1348: Created group '...' grpid=96e01a197ee944d4 as Chat#11
```
> Do not create ad-hoc groups when message cannot be decrypted

- python/examples/test_examples.py
- python/src/deltachat/__init__.py
- python/src/deltachat/account.py
- python/src/deltachat/chat.py
- python/src/deltachat/contact.py
- python/src/deltachat/direct_imap.py
- python/src/deltachat/events.py
- python/src/deltachat/message.py
- python/src/deltachat/testplugin.py
- python/tests/test_account.py
- python/tests/test_increation.py
- python/tests/test_lowlevel.py
- make `account.create_chat(obj)` work with Account, Contact or e-mail address objects 
- remove some now unneeded helper functions 
- introduce `account.as_contact(obj) ` to create a contact from an account, contact or e-mail address
- refactor more complex setups into common helpers 
- simplify several tests, reducing LOCs
> simplify deltachat python API and testing machinery

- python/src/deltachat/__init__.py
- python/src/deltachat/account.py
- python/src/deltachat/testplugin.py
- python/src/deltachat/tracker.py
- python/tests/test_account.py
it caused problems when using it from the command line. 
also, it reduces LOCs.
> simplify configure(), avoid special attribute in non-test mode

- Cargo.lock
- Cargo.toml
- src/dc_receive_imf.rs
- src/mimefactory.rs
- src/test_utils.rs
Fix #1575 Messages sent by DeltaChat trigger spam filters due to incorrect/non-compliant formatting options
> Fix #1575 Messages sent by DeltaChat trigger spam filters due to incorrect/non-compliant formatting options

- src/imap/mod.rs
- src/imap/select_folder.rs
CLOSE, which was used previously, only expunges messages and deselects
folder, and it should only be called if some folder is selected. For that,
Imap.close_folder() method is used.
> IMAP: logout from the server with a LOGOUT command

- src/scheduler.rs
if we trigger a reconnect we don't need to "error!" out to the user. 
the next reconnect will report anyway if it can't connect.
fixes #1598
> attempt to fix #1598 -- less chatty on errors

- Cargo.lock
- Cargo.toml
- src/blob.rs
this pr reads the orientation-tag from the exif information and applies that to the recoded pixels.
closes #1586 
nb: [The most evil feature ever conceived: the Exif Orientation Tag](http://keyj.emphy.de/exif-orientation-rant/) - i mostly agree here. things would be much easier if that tag just won't have been invented.
> respect image orientation from exif on recoding

- Cargo.lock
- Cargo.toml
- src/oauth2.rs
Do a lookup based on domain's MX servers. G Suite domains are expected
to have at least 'aspmx.l.google.com' listed in MXs.
See https://support.google.com/a/answer/140034
fixes #1425
> Add support for G Suite domains

- src/mimeparser.rs
In heuristically_parse_ndn() we also checked whether the subject contains "fail". Which is not the case for all test emails. Those who do not contain it use the "message/delivery-status" standard by sheer luck so that all tests pass.
Proposed by @r10s in https://github.com/deltachat/deltachat-core-rust/pull/1625#discussion_r440971312 (just that it was not in sync before my tiscali PR)
> Sync heuristically_parse_ndn() and maybe_ndn in prefetch_should_download()

- src/imap/mod.rs
- src/smtp/mod.rs
Also replace assert! with debug_assert!
An attempt to address https://github.com/deltachat/deltachat-android/issues/1428
I think we should eliminate all indexing and slicing eventually, they have resulted in similar crashes previously which are very hard to debug.
I'm sure this commit doesn't fix the bug, but makes searching for the source of panic a bit easier.
> Refactor imap/mod.rs to avoid indexing

- src/configure/mod.rs
- src/contact.rs
- src/dc_receive_imf.rs
- src/scheduler.rs
This PR also changes name normalization to reduce surprises when comma means something other than first name and last name separator.
Follow-up to #1636
> Forbid more indexing

- src/chatlist.rs
the last message shown in a chatlist
is the one with the largets timestamp that is not hidden.
in the past, we calcualted the last timestamp using a subquery
and uses that timestamp to finally get the message.
this may fail when there are two messages with the same max. timestamp.
with this fix, we return the id from the subquery and use that
(the subquery already filters by hidden etc.)
in practise, by time-smearing,
usually delta-chat avoids messages from the same device
having the same timestamp - however, this may not be true for multi-device
and/or read-receipts.
i have not seen this error all the years, however, it happens with
the async move several times - maybe because things are just sent faster
and things become more probabe.
wrt sql-statement: not sure, if that is …
> fix getting last message for chatlist, avoid empty summaries

- src/oauth2.rs
- src/provider/data.rs
- src/provider/mod.rs
- src/provider/update.py
this pr makes use of the new oauth2-authorizer information we added in https://github.com/deltachat/provider-db/pull/124 to the provider-db
for review, mainly the third (the last) commit is interesting:
- the whitelist is removed, instead we query the provider-db and get the information from there
- mx-lookup is done only when there is no entry at all (otherwise, we know, the provider does not support oauth2)
we got reports that an mx-lookup is not always fast, in general, this is fixed by movign lookup to an async task in https://github.com/deltachat/deltachat-android/issues/1426
however, additionally, with this pr, an mx-lookup is avoided in many situations, esp. when we know it is useless and the network can cause all kind of troubles (nauta ...)
> get Oauth2-information from provider-db

- examples/repl/cmdline.rs
the chatlist is the most complicated list to get from sql
and is also the most used list,
so it makes sense to keep an eye on the timing of that.
background:
i stopped some times while creating #1635 that uses `ORDER BY .. LIMIT` instead of `MAX` on a subselect that is executed for every chat in scope.
in fact, it does not change that much, on my pc and a >250 chats, chatlist creation takes now 43ms-64ms instead of 40ms-56ms (executing 10 times) - so, it is measurable, but still okay - and having a correctly ordered list is totally worth it :)
> print time needed to build chatlist in repl tool

- src/blob.rs
- src/chat.rs
- src/chatlist.rs
- src/config.rs
- src/configure/mod.rs
- src/contact.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/e2ee.rs
- src/imex.rs
- src/job.rs
- src/key.rs
- src/keyring.rs
- src/location.rs
- src/message.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/oauth2.rs
- src/param.rs
- src/peerstate.rs
- src/qr.rs
- src/stock.rs
- src/test_utils.rs
This tidies up our testing tools a little bit.  We had several
functions which through various changes ended up doing the same and
some more which did very similar stuff, so I merged them to have
things simpler.  Also moved towards methods on the TestContext struct
while cleaning this up anyway, seems like this structure is going to
stay around for a bit anyway.
The intersting change is in `test_utils.rs`, everything else is just
updating callers.  A few tests used example.org which I moved to
example.com to be able to re-use more configuration of the test
context.
> Unify some testing interfaces

- src/dc_receive_imf.rs
for "fresh" messages, calc_sort_timestamp() makes sure,
the sorting timestamp is not less than the last-non-fresh message.
this commit fixes the "fresh" state we give to calc_sort_timestamp(),
it just uses the message-state we've already calculated.
the old assumption, that unseen messages are always fresh
is wrong as this "seen" flag just comes from an imap-flag
that is not set for self-sent messages.
therefore, in a multi-device-setup, the message-order was totally messed up.
(the bug was probably in there since a long time,
however did not came to light until the async-move)
> give correct "fresh" flag to calc_sort_timestamp()

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
this fixes a very visible error in a multi-device-setup that came to light with async, #1645, i think, this is worth another release.
i will do a new android release probably later today night or tomorrow, so, if there are more fixes, they an also come in :)
> prepare 1.38

- src/sql.rs
When maybe_add_file was called with "$BLOBDIR" it tried to remove 9
bytes from the string, while it only contains 8.
> sql: fix potential panic in maybe_add_file

- deltachat-ffi/deltachat.h
- src/config.rs
- src/scheduler.rs
interrupts on changing `mvbox_watch` etc. are no longer needed; to take effect, `dc_stop_io()` followed by `dc_start_io()` is needed.
follow up of #1654
> remove config changes interrupt

- src/config.rs
- src/configure/mod.rs
instead of applying all config_defaults unconditionally
after the first configure, a config_defaults for a given key
is now applied when this key has never been set before.
this way, you can set some keys before calling configure()
and also, later versions can add new defaults for new keys
(that would require another call to configure() then, however)
> apply config_defaults only for unset values

- Cargo.lock
- Cargo.toml
- src/blob.rs
One advantage is that it does not depend on any crates, so there is a
higher chance of dropping regex crate eventually.
> Switch to sanitize-filename-reader-friendly

- Cargo.lock
- Cargo.toml
- src/blob.rs
Reverts deltachat/deltachat-core-rust#1664
reason is that the sanitize-filename-reader-friendly handles extensions only partly, eg. `foo=.bar` is converted to `foo_bar` - although the extension does not contain a bad character. `foo=x.bar` otoh preserves the extension.
see also recent discussion on irc.
> Revert "Switch to sanitize-filename-reader-friendly"

- deltachat-ffi/src/dc_array.rs
- src/chat.rs
- src/dc_receive_imf.rs
- src/message.rs
ChatItem can represent markers as enum variants instead of special MsgIds.
> Add ChatItem type

- deltachat-ffi/src/dc_array.rs
- deltachat-ffi/src/lib.rs
- src/chat.rs
With this change, API user does not need to look at the timestamp of
the next message to display the day marker, but can get the timestamp
directly from the marker. This way there is no database query and no
risk of error as a result of database being busy or message being deleted.
> Add timestamp to DayMarker

- deltachat-ffi/deltachat.h
- src/dc_receive_imf.rs
- src/ephemeral.rs
- src/stock.rs
The message talks about "message deletion timer" instead of "ephemeral message timer".
Closes #1678
> Add stock strings for ephemeral timer changes

- src/dc_receive_imf.rs
Instead, replace them with localized stock strings using set_better_msg.
> Do not duplicate system messages about timer changes

- src/scheduler.rs
It is annoying as it happens every time the server is rebooted.
> Do not show an error on IMAP connection failure

- python/tests/test_account.py
- src/imap/select_folder.rs
- src/scheduler.rs
This ensures Inbox is expunged timely in setups that don't watch
DeltaChat folder.
Fixes #1614
> imap: expunge folder before IDLE if needed

- src/key.rs
- src/smtp/mod.rs
- src/smtp/send.rs
time::Instant may use libc::clock_gettime(CLOCK_MONOTONIC) eg. on android and does not advance while being in deep sleep mode. therefore, time::Instant is not a reliable way for timeouts or stoping times.
we experienced that issue the first time when showing the "uptime" in info-dialog. see #1437 and https://users.rust-lang.org/t/std-now-with-android/41774 for some backgrounds.
closes #1437
> use time::SystemTime instead of time::Instant

- src/e2ee.rs
- src/mimeparser.rs
- src/securejoin.rs
`Mimeparser.was_encrypted()` checks if the message is an Autocrypt encrypted
message. It already means the message has a valid signature.
This commit documents a few functions to make it clear that signatures
stored in `Mimeparser` must be valid and must always come from encrypted
messages.
Also one `unwrap()` is eliminated in `encrypted_and_signed()`. It is possible
to further simplify `encrypted_and_signed()` by skipping the `was_encrypted()`
check, because the function only returns true if there is a matching
signature, but it is helpful for debugging to distinguish between
non-Autocrypt messages and messages whose fingerprint does not match.
Fixes #1226 
Related recent PR that ensures Mimeparser signatures are always valid: #1616
> securejoin: do not check the signatures existance twice

- src/chat.rs
- src/config.rs
- src/configure/mod.rs
- src/context.rs
- src/imap/mod.rs
- src/scheduler.rs
- src/smtp/mod.rs
- src/stock.rs
Fix #1605, fix #1687
It is not perfect because it only notifies when the user opens DC or re-connects to the network.
I changed the Event::ErrorNetwork message because this message is shown to the user.
We will have to adapt the UIs to generally send notifications for the device chat. The core now takes care about when a notification should be sent by "only" sending MsgsChanged event when no notification shall be shown. 
How expensive are mutexes (RAM and initialisation)? I added a mutex to Context to prevent a race condition when a "your pw is wrong" warning is sent, resulting in multiple messages being sent.
> Show a better toast and a notification when the password is wrong (because it was changed on the server)

- src/blob.rs
- src/contact.rs
when seeing our own profile image send from other devices,
we use this as Selfavatar on the current device as well.
as there is no special message sent on avatar changes,
this is a simple approach to sync the avatar across devices.
in some future, there may be more sophisticated sync-options, of course :)
closes #1064
> Multi device avatar sync

- src/contact.rs
- src/dc_receive_imf.rs
this pr ignores selfavatar-syncing when it comes in an unencrypted message.
this way, syncing may take a bit longer (until an avatar is sent in an encrypted message), however, it is not possible to trick the user by passing a random avatar - that may happen also for other avatars, however, the other avatars are not re-sent on behalf of the user.
as said, at some point, we need a sync-message (that is always forced encrypted :)
successor of #1716
> sync encrypted avatars only

- python/src/deltachat/account.py
- python/src/deltachat/direct_imap.py
- python/src/deltachat/events.py
- python/src/deltachat/testplugin.py
- python/tests/test_account.py
- src/imap/idle.rs
- src/job.rs
fix #1720 -- don't wait for the daemon eventhread to terminate but count on it to eventually die
maybe help with #1639 -- we should now not get stuck in INBOX while a new message in fact arrived already.
> Fix hanging tests (stuck idle + details) and make python shutdown more robust

- python/examples/group_tracking.py
- python/examples/test_examples.py
- python/src/deltachat/hookspec.py
- python/src/deltachat/message.py
- python/tests/test_account.py
make ac_member_removed and ac_member_added be called if the action was triggered remotely.
also pass in the "actor" contact so one can know who caused an addition/removal.
fixes #1480
> Fix ac_member_removed/added events 

- python/CHANGELOG
plan is to follow core-versions but inc/deviate in the micro version part (third part of version).
So the py version number is not semantic versioning for now.
> prepare 1.40.0 python deltachat release

- deltachat-ffi/deltachat.h
- src/config.rs
for the upcoming webrtc call feature in desktop.
We are currently implementing video hangouts into the desktop client and need this config property to store the server address that should be used for signaling to establish the p2p connections between the connected users of a video hangout room.
https://github.com/deltachat/deltachat-desktop/pull/1789
> add config value BasicWebRTCInstance

- deltachat-ffi/deltachat.h
- src/events.rs
- src/log.rs
- src/scheduler.rs
the error "IMAP Connect without configured params" was emited as DC_EVENT_ERROR, these kind of errors are typically always show to the user eg. as a toast on android.
however, there is also the DC_EVENT_ERROR_NETWORK event, that is typically not reported in sequence to the user (following the docs ;) and also, when there is no network available, eg. android only shows a toast saying "Not network" instead of a random, unrelated error.
this pr changes the described error to DC_EVENT_ERROR_NETWORK and also updates the documentation (in fact, core does not handle tracking of subsequent errors as documented)
see also https://github.com/deltachat/deltachat-android/issues/1489 and https://github.com/deltachat/deltachat-android/issues/1490
> avoid popping up "IMAP Connect without configured params"

- .github/workflows/ci.yml
See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-new-combinations
Adding this because of the current nightly regression: https://github.com/rust-lang/rust/issues/74614
> ci: allow nightly runs to fail

- src/job.rs
Permanent error 550 5.1.1 is no longer considered temporary.
Enhanced status code is checked now, so only 550 5.5.0 is an exception
for misconfigured Postfix servers.
Yandex error 554 5.7.1 was handled correctly, but only because it had
response code 554, while the comment talks about enhanced status code
5.7.1. The comments are corrected.
Failed messages are now marked as such with message::set_msg_failed.
Previously they were left in a pending state.
If info message cannot be added to the chat, the error is displayed with
error! instead of being logged with warn!.
> Refine SMTP error handling

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/repl/main.rs
- src/chat.rs
- src/config.rs
- src/constants.rs
- src/headerdef.rs
- src/message.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/param.rs
- src/stock.rs
- test-data/message/videochat_invitation.eml
i first thought, that the invite-function should returns some more information about the url or so, however, as also the recipient will need these information, it seemed easier to attach them to the message object - as we've done also in some other case (eg. setup message, disappearing message info)
the invite-function is blocking, so it has to be called from within a thread - even if it will return fast in most cases.
for now i decided against special events or message-types - this seems not to be needed for now :)
next step would be to add some very basic implementation, so that the UIs are satisfied - wrt TOKEN etc. that can be refined in core, the UIs need not to take care about that. at least, this is the rough idea, of course, we can add additional apis as needed ;)
> add APIs for videochats

- src/qr.rs
It presents no security issue, because properly configured servers will
only serve passwords on HTTPS and distribute only HTTPS QR codes, but
makes testing easier when HTTPS is not easy to deploy.
If attacker can control the URL used, they can change the URL to another
HTTPS URL controlled by them and act as a proxy between the client and
original server anyway.
> Allow http scheme for DCACCOUNT URLs

- python/src/deltachat/testplugin.py
- python/tox.ini
Since introduction of provider database, these certificate checks are
enabled for test servers anyway, but this setting prevents usage of
local servers with self-signed certificates.
> Do not enable strict certificate checks in tests by default

- src/qr.rs
since #1770, http: is a correct scheme.
> fix test_decode_account_bad_scheme

- src/configure/mod.rs
> configure: compare mail_port to 143

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/chatlist.rs
needed for how node/js handles the chatlist currently
(it convertes the ffi-object to an js-object and throws ffi-object away directly,
this makes it hard to access dc_chatlist_get_summary() later.
cc  @Jikstra, @Simon-Laux
> add dc_chatlist_get_summary2() api

- set_core_version.py
thanks to @dignifiedquire, we've found a smarter solution that sets lto=true on the destination platforms, see https://github.com/deltachat/deltachat-android/pull/1512 and https://github.com/deltachat/deltachat-ios/pull/885
> do not set lto=true in release-script

- ci_scripts/run_all.sh
- python/install_python_bindings.py
and the default "python install_python_bindings.py" without it.
> try to do the python release packaging with lto

- Cargo.lock
- Cargo.toml
- src/smtp/send.rs
Fix #1383, depends on https://github.com/async-email/async-smtp/pull/26.
The timeout is 60s + 180 extra seconds per MB now. This is about twice the amounts @hpk42 reported in the original issue.
> [WIP] Flexible timeouts for larger emails

- deltachat-ffi/deltachat.h
- src/lot.rs
- src/qr.rs
introduce the qr-code-type `DCWEBRTC:[webrtc_instance]`.
dc_check_qr() returns this as the type DC_QR_WEBRTC
and these qr-codes can be passed to dc_set_config_from_qr() then;
this finally sets `webrtc_instance` using dc_set_config().
> share webrtc-instance via qr-code

- src/imap/mod.rs
Before, if the user had blocked their mailer daemon (like me), ndns were
not parsed.
> Download possible ndns also if the mailer daemon is blocked

- src/e2ee.rs
- src/mimeparser.rs
I would have liked to add some tests as this is quite a critical part but did not have any plan how.
> Fix #1753 In opportunistic chats, a wrongly signed message should be readable eventually

- src/mimeparser.rs
Signatures are checked for unprotected From, so it should not be modified
afterwards.
A follow-up for #1789
> Do not accept protected From headers

- deltachat-ffi/deltachat.h
- src/constants.rs
- src/message.rs
this pr allows prefixing custom jitsi urls with `jitsi:`
so that clients have a chance to detect these custom instances
and may start the corresponding app.
> add videochat-type "jitsi"

- src/contact.rs
- src/dc_receive_imf.rs
- src/e2ee.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/peerstate.rs
- src/qr.rs
- src/securejoin.rs
- src/sql.rs
Normally NULL is used when there is no fingerprint, but default value
for fingerprint columns is an empty string.
In this case, loading should not fail with an "invalid length" error,
but treat the fingerprint as missing.
Strict check was introduced in commit ca95f25639e90dfa7d028b6ce89e3a81a0bf09dd
Fixes #1596
> peerstate: ignore invalid fingerprints in SQL

- deltachat-ffi/src/lib.rs
A bug reported at https://support.delta.chat/t/app-crashes-suddenly/1031/26
Likely caused by this migration: https://github.com/deltachat/deltachat-android/blob/bdaf4df76455818c8a26e5a059f60df9291a62f7/src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java#L88
> dc_set_chat_mute_duration: avoid panic on overflow

- .github/workflows/ci.yml
- examples/repl/cmdline.rs
the peerstate api was slightly changed in #1800, this pr adapts the repl-tool to the new api (without, repl does not even build)
> adapt repl-tool to new peerstate api 

- python/tests/test_account.py
- src/imap/mod.rs
If some IMAP command responses are left unread, they, along with the `OK` or any other result, will be left in the socket, and reappear later as responses to the next command. async-imap library expects that user exhausts the stream before sending additional commands. 
Fixes #1796, fixes #1788
> imap: always read all the responses

- python/tests/test_account.py
The server sometimes reorders the messages even if they were accepted
strictly in sequence.
Follow-up for #1795
> Second attempt to fix flaky test

- python/src/deltachat/direct_imap.py
- python/tests/test_account.py
This change fixes `test_immediate_autodelete` and maybe other tests using
`DirectImap.get_all_messages()`.
> python: fix more flaky tests

- src/mimefactory.rs
Just stumbled about this code. Was there any reason it was there?
Or should we maybe set this header to something "unsuspicious" like "Firefox"? OTOH Thunderbird seems not to set this header, either, so probably not.
> Remove debug X-Mailer header

- src/message.rs
this pr only adds a test.
test that, in general, msg.get_width() and msg.get_height()
return reasonable values.
> add a higher-level test for dc_get_filemeta()

- src/configure/mod.rs
- src/login_param.rs
For IMAP, example.org, imap.example.org and mail.example.org are tried.
For SMTP, example.org, smtp.example.org and mail.example.org are tried.
> configure: refactor to try various server domains

- src/mimeparser.rs
(using a rather minimal approach)
> Fix #1790 Unprotected subjects in encrypted messages are shown as encrypted

- deltachat-ffi/deltachat.h
this is meant to be merged to #1835
> Tweak nicer configure

- src/sql.rs
example for an alternative to the discussion at https://github.com/deltachat/deltachat-core-rust/pull/1835 - might be merged to #1835 or just be closed :)
> trick rustfmt to make things not less readable

- src/configure/mod.rs
- src/login_param.rs
When certificate checks setting is Automatic, strict_tls setting
from provider database is applied dynamically in Imap.connect() and
Smtp.connect().
> Automatic certificate checks for providers from DB

- src/message.rs
.tgs files are Telegram stickers. Internally they are gzipped JSON files,
containing a single Lottie animation.
MIME type application/x-tgsticker is commonly used for telegram documents
containing such stickers.
> Recognize .tgs files as stickers

- src/chat.rs
- src/message.rs
this pr adds more tolerance to webrtc-servers as specified via set_config("webrtc_instance") - which is settable directly from the uis.
- if reasonable, missing slashes are added to the specified servers
- the protocol may be left out, in this case, https:// is added
so, you can use jitsi by just typing `meet.jit.si` instead of `https://meet.jit.si/`
fixes #1830
> be more tolerant on webrtc-servers set by the user

- .github/workflows/ci.yml
this pr comments-out the always-failing test with rust-nightly (see https://github.com/deltachat/deltachat-core-rust/pull/1835#issuecomment-674202818), building on rust.1.45 stays in place.
once, the nightlies work again on github-actions, we can revert this pr.
> greenify ci 💚💚

- .circleci/config.yml
- ci_scripts/remote_tests_python.sh
- ci_scripts/remote_tests_rust.sh
re-enable remote_tests_rust -- running on the dedicated "b1" build machine is a good fallback and runs outside github actions  VM
Enable SCCACHE which should help with cross-PR build speeds.  SCCACHE can be disabled by reverting https://github.com/deltachat/deltachat-core-rust/pull/1850/commits/63d637978f8c2c95a375429b24f2366fdde3dcaf
> try to reinstate remote_tests_rust

- src/dc_receive_imf.rs
- src/dehtml.rs
- test-data/message/wrong-html.eml
This fixes #1804 in two ways: First, it removes a <!doctype html> from
the start of the mail, if there is any.
Then, it parses the html itself it quick-xml fails, just stripping
everything between < and >.
Both of these would have fixed this specific issue, but they are probably both useful for similar issues.
Also, add tests for both fixes.
> Fix #1804: remove <!doctype html> and accept invalid HTML

- src/message.rs
in general, Viewtypes other than File should be used only
when the added file type is tested on all platforms -
including Android4 currently.
as this is easily overseen,
i've added a comment.
this partly reverts Viewtype changes done by
https://github.com/deltachat/deltachat-core-rust/pull/1818
> use Viewtype::File for types that may be unsupported on some systems.

- src/configure/auto_mozilla.rs
- test-data/autoconfig/lakenet.ch.xml
- test-data/autoconfig/outlook.com.xml
Only one server is used, because at the end `LoginParam` is returned, but there is a test for parser checking that multiple `IncomingServer` sections are parsed.
> Parse multiple servers in Mozilla autoconfig

- src/location.rs
Using only two digits results in visible difference between original
location and location received by other users.
Fixes #1870
> Do not restrict message.kml coordinates precision

- deltachat-ffi/src/lib.rs
- src/dc_tools.rs
- src/imex.rs
Fix https://github.com/deltachat/deltachat-android/issues/1579
Also: Make sure that if an error happens, the UI can show the error to the user
I mainly tested with the new export/import logic because we will not use the old one for long anymore anyway.
I might not be able to react to the review anymore, so just push to this pr if you would like changes. I will still be reachable for private messages over Delta Chat.
> Fix cancelling imex

- src/configure/auto_mozilla.rs
- src/configure/auto_outlook.rs
- src/configure/mod.rs
- src/configure/server_params.rs
- src/dc_tools.rs
- src/login_param.rs
- src/provider/mod.rs
`LoginParamNew` structure, which contained possible IMAP and SMTP
configurations to try is replaced with uniform vectors of `ServerParams`
structures. These vectors are initialized from provider database, online
Mozilla or Outlook XML configuration or user entered parameters.
During configuration, vectors of `ServerParams` are expanded to replace
unknown values with all possible variants, which are tried one by one
until configuration succeeds or all variants for a particular protocol
(IMAP or SMTP) are exhausted.
`ServerParams` structure is moved into `configure` submodule, and all
dependencies on it outside of this submodule are removed.
Closes #1863
> configure: try multiple servers for each protocol

- src/constants.rs
- src/param.rs
- src/securejoin.rs
This turns the Bob::expects field into an enum, removing the old
constants.  It also makes the field private, nothing outside the
securejoin module uses it.
Finally it documents stuff, including a seemingly-unrelated Param.
But that param is used by the securejoin module... It's nice to have
doc tooltips be helpful.
> Turn Bob::expects into an enum and add docs

- src/chat.rs
- src/sql.rs
thanks a lot to @csb0730 for endless trying to figure out a database bottleneck - where i was not even totally convinced that it even exist!
i tested the change on my 2yo motog and iphone7 with a database of 50k messages - and even here, saving was significant, see comments in the sourcecode. i added the comment also to ensure, we do not run into this issue again on changes.
fixes #1879
> add an index to significantly speed up get_fresh_msg_cnt()

- python/tests/test_account.py
- src/imap/idle.rs
- src/imap/mod.rs
- src/smtp/mod.rs
Previously `DC_EVENT_ERROR_NETWORK` events were emitted for each failed
attempt during autoconfiguration, even if eventually configuration
succeeded. Such error reports are not useful and often confusing,
especially if they report failures to connect to domains that don't
exist, such as imap.example.org when mail.example.org should be used.
Now `DC_EVENT_ERROR_NETWORK` is only emitted when attempting to connect
with existing IMAP and SMTP configuration already stored in the
database.
Configuration failure is still indicated by `DC_EVENT_CONFIGURE_PROGRESS`
with `data1` set to 0. Python tests from `TestOnlineConfigurationFails`
group are changed to only wait for this event.
Fixes #1849
> Do not show errors during configuration

- src/key.rs
- src/securejoin.rs
- src/test_utils.rs
This currently tests the setup-contact full flow and the shortcut
flow.  More securejoin tests are needed but this puts some
infrastructure in place to start writing these.
> Add some initial tests for securejoin

- src/chat.rs
- src/e2ee.rs
- src/imex.rs
- src/mimefactory.rs
- src/param.rs
- src/securejoin.rs
If message does not contain Autocrypt header, but is encrypted, do not
change the peerstate.
Closes #1874
> Do not reset peerstate on encrypted messages

- deltachat-ffi/src/lib.rs
- examples/repl/main.rs
- src/chat.rs
- src/securejoin.rs
This gets rid of ChatId::new(0) usage and is generally a nice first
refactoing step.  The complexity of cleanup() unravels nicely.
----
This includes the changes of #1896, filter by commits to omit them.
> Resultify join_securejoin

- deltachat-ffi/src/lib.rs
- examples/repl/main.rs
- src/chat.rs
- src/dc_receive_imf.rs
- src/securejoin.rs
This field is entirely unused.
----
This is on top of flub/resultify-join-securejoin branch, needs to be
retargetted to master once that is merged.
> Remove the Bob::status field and BobStatus enum

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/main.rs
- examples/simple.rs
- python/src/deltachat/cutil.py
- src/configure/mod.rs
- src/events.rs
- src/stock.rs
For now it is only set on error, but could contain user-readable log
messages in the future.
Closes: #1866
> Set data2 in ConfigureProgress event

- Cargo.lock
- Cargo.toml
It is one commit ahead 0.3.4, replacing EHLO localhost with EHLO [127.0.0.1].
Fixes #1847
> Update to non-release version of async-smtp

- src/sql.rs
On Android, there is to /tmp directory, so SQLite may throw
SQLITE_IOERR_GETTEMPPATH when trying to find a place for temporary
files. Storing temporary files in memory is a workaround that always
works (until out of memory).
See https://github.com/mozilla/mentat/issues/505 for discussion of a
similar issue.
> sql: set PRAGMA temp_store=memory

- deltachat-ffi/deltachat.h
- src/chat.rs
- src/constants.rs
- src/dc_tools.rs
- src/provider/data.rs
- src/provider/mod.rs
- src/provider/update.py
- src/scheduler.rs
- src/stock.rs
as discussed several times offline and on other channels ([eg.](https://support.delta.chat/t/automatically-update-check/488)), this pr attempts to detect bad system dates and outdated apps and adds a device message in this case.
the bad system date is currently only detected when `time()` reports a date that is _older_ than some known date. however, this simple approach already handles a lot of typical errors we've seen several times in the past, eg.
- devices may fall back to "system compile time" easily - in theory, there is a timeserver and so on, however, this does not always sync or work - o/ @hpk42 :)
- the user may be wrong when setting the time by a whole year or month
to have a reference date, that is not too old - and to keep the option for reproducible builds and to not mess …
> add device-message on bad system clock or on outdated app

- deltachat-ffi/deltachat.h
add some crosslinks, clarify when the timer is started,
and avoid mixing "ephemeral" with "delete old messages".
> tweak ephemeral ffi documentation

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/config.rs
- src/configure/mod.rs
- src/constants.rs
- src/dc_receive_imf.rs
- src/events.rs
- src/imap/idle.rs
- src/imap/mod.rs
- src/job.rs
Fix https://github.com/deltachat/deltachat-android/issues/1516, During onboarding and after we scanned the history, we might ask the user something along the lines of
"oh, it appears you are using this e-mail account also with another email program. Do you want to a) see all your e-mails in Delta Chat or b) only see chat conversations from other Delta Chat users?"
The plan is to also fetch the last 100 messages from each folder and just show them. This will make it clearei to the user what they just decided and that they can really write EMAILS with DC.
> [WIP] Fetch old messages, ask the user about the "Show all emails" on start

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- python/tests/test_account.py
- src/chat.rs
- src/contact.rs
- src/events.rs
- src/message.rs
the new event can be used for updating the badge counter.
to get the old behavior, implementations can just do the same on both events.
this event is needed to make markseen-handling easier on ios (@cyBerta and me are doing currently a partly rewrite of the chatview), but will also mitigate flickering and needless redraws on android and possibly on desktop.
~~in a further improvement, we can set the correct chat_id in dc_markseen_msgs(), however, this won't affect implementation as a "broadcast" event is still needed for other functions. also, chat_id=0 is also needed for DC_EVENT_MSGS_CHANGED, so this new event does not add additional complexity here.~~ EDIT: done by recent commits, chat_id is now always set.
> split DC_EVENT_MSGS_NOTICED off DC_EVENT_MSGS_CHANGED, remove dc_marknoticed_all_chats()

- deltachat-ffi/deltachat.h
`dc_str_unref()` currently just calles `libc::free()` - and `man free` reads "If ptr is a NULL pointer, no operation is performed".
there were ancient implementations 20y ago or so where free(NULL) was invalid, but afaik, these times have passed.
> clarify dc_str_unref()

- deltachat-ffi/src/lib.rs
- src/accounts.rs
- src/events.rs
> fix: avoid manual poll impl for accounts events

- Cargo.lock
fix #1953 by `cargo update` (esp. update async-io to 1.1.6)
See https://github.com/async-email/async-native-tls/issues/23#issuecomment-702336439
> fix #1953 by `cargo update` (esp. update async-io to 1.1.6)

- src/sql.rs
This variable is not used afterwards, and it is already not set in migrations added after version 54.
> sql: do not set dbversion after each migration

- src/chat.rs
- src/message.rs
Address is used to generate `Message-Id`.
Previously error toast was shown, but `MsgId` was returned from `chat::prepare_msg` anyway. Now `chat::prepare_msg` returns an error.
`error!()` is removed, because FFI library shows errors via `.unwrap_or_log_default()`.
> prepare_msg: return Err if no address is configured

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/chat.rs
- src/constants.rs
- src/message.rs
- src/sql.rs
- src/stock.rs
both are not used in productive:
- chat-id "in-creation" was dropped completely already in core-c
as it does not allow assigning messages to chats in time.
- message flag "starred" was added at some point and never used.
ux-wise, "disappearing messages" promises to clean up a chat -
this does not fit well with "starring" messages.
"saved messages" chat seems to be superior in that regard.
but anyway, it is not used but comes at maintainance costs
(and is not well-maintained, eg. searching over that chat is not implemented)
so it is better to delete its functionality for now.
(the db entries, however, are left for now,
that might be more tricky to remove)
> remove unused types "starred" and "in-creation"

- python/src/deltachat/account.py
- python/src/deltachat/direct_imap.py
- python/src/deltachat/events.py
- python/src/deltachat/testplugin.py
- python/tests/test_account.py
- src/config.rs
- src/configure/mod.rs
- src/constants.rs
- src/dc_receive_imf.rs
- src/imap/idle.rs
- src/imap/mod.rs
- src/job.rs
- src/message.rs
- src/mimeparser.rs
Read all of an e-mail accounts messages and extract all To/CC addresses if the From was from our own account.
Then, fetch existing messages from the server and show them.
Also, I fixed two other things:
- just by chance my test failed because of an completely unrelated bug. The bug: bcc_self messages were not marked as read if mvbox_move was set to true.
- add some color to the test output (minor change)
> Peek recipients, fetch old messages

- src/imap/idle.rs
- src/scheduler.rs
If a configured account is disconnected/offline, and there is no "interrupt_idle" coming, fake_idle would wait indefinitely. 
The problem and fix can be reproduced/tested on linux using eg `sudo iptables -A OUTPUT -d imap.deltachat.de -j DROP` if using a deltachat.de account and then starting a desktop (or CLI) using the master core before this PR.  You can then wait some time and will see that fake-idle enters indefinite wait on interrupt_idle but there is no interrupt. When you remove the iptables-block with `sudo iptables -D OUTPUT -d imap.deltachat.de -j DROP` fake_idle will never recover. 
With this PR, we wake up every minute to retry connecting or if we get an interrupt-idle event.  This makes the above scenario work and message receiving recover. I think we can not solely rely on …
> fix recovering offline/lost connection situations (fixes background receive bug)

- src/configure/mod.rs
- src/configure/read_url.rs
Examining https://github.com/deltachat/deltachat-android/issues/1631 I realized that the current warnings are not very helpful.
> Show more errors

- python/tests/test_account.py
- src/message.rs
For text messages, summary joins all lines into one, so multi-line quotes
look bad in Thunderbird.
> Only use summary for quote if text is empty

- src/mimefactory.rs
This makes quotes easier to read in previous DC versions and plaintext
MUAs.
> Separate quote from reply with an empty line

- deltachat-ffi/deltachat.h
- src/chat.rs
- src/dc_receive_imf.rs
- src/sql.rs
emit DC_EVENT_MSGS_NOTICED if new answers from other devices are seen and the chat was not yet noticed.
if UI use this event to update badge counters and notifications, this is now also updated when a chat is answered on another device. #1974 is about "best effort using current data", at some point, we can refine that, if needed and the effort is reasonable.
depending on how the events are currently used in the UIs, this pr might result in double-redrawing as DC_EVENT_MSGS_CHANGED with a concrete message-id is emitted anyway. however, as this affects only messages sent by the user one other devices and as DC_EVENT_MSGS_NOTICED is only emitted when _really_ things are changed, this is probably no big deal.
successor of #1942
closed #1974
> basic DC_EVENT_MSGS_NOTICED multi-device-support

- src/simplify.rs
Top quotes are displayed as quotes for non-chat mails, so [...] used to
indicate there was a quote is not needed.
> Do not display [...] after non-chat quotes

- deltachat-ffi/deltachat.h
the constant comes from c-core
and was used to define the size of the string-array that time.
this is no longer needed in core
and also the UIs seems not to use it
(they will treat DC_STR* like an id,
there should be no need to know the max. DC_STR* value)
however, maintaining the value is annoying and error-prone, so i suggest to remove it :)
cc @Jikstra @Simon-Laux - can you please check if removal is fine for you? i did a grep, and at a first glance, desktop seems not to use it.
> remove DC_STR_COUNT

- deltachat-ffi/deltachat.h
- src/message.rs
- src/stock.rs
a draft may contain only a quote,
without any text set yet.
these drafts cannot be sent, however, appear in the summary -
currently with the summary-text "", which results to sth.
as "Draft: " - which looks like an error or at least a bit weird.
this pr sets the summary text to "Reply" - similar to "Image", "Video" etc. -
the UI just expects some text here, not an empty string.
the result are summaries as "Draft: Reply" on all UIs -
which, btw. is also roughly the same what Signal does in this case.
> name quote-only drafts as such in the summary

- src/e2ee.rs
should_encrypt() shall return Ok(false)
on peerstate=EncryptPreference::Reset
only for opportunistic groups.
for verified/protected groups (e2ee_guaranteed set),
Ok(true) or Error() should be returned.
this bug was introduced by #1946 (Require quorum to enable encryption).
> priorize e2ee_guaranteed over Reset

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- python/src/deltachat/__init__.py
- python/src/deltachat/account.py
- python/src/deltachat/testplugin.py
- src/chat.rs
- src/config.rs
- src/configure/mod.rs
- src/stock.rs
update_device_chats() takes about 2 seconds on a modern device (Android) because the
welcome image file has to be written to the disk as a blob. The problem
was that this was done after the progress bar had vanished and before
anything else happened so that I thought that something had gone wrong
multiple times.
The UIs have to remove update_device_chats(), too..
> Call update_device_chats automatically during configure

- src/message.rs
To make sure the UI recognizes the message as the correct type if suffix is missing/unknown (had this problem with the swipe-to-reply pr)
> Add new filemime-guessing suffix

- src/chat.rs
- src/dc_receive_imf.rs
- src/test_utils.rs
groups are created by any message. if this random group message has a `Chat-Verified` header, the group is created as a protected group. in this case, we do not really know who has actually enabled the protection.
eg. saying "Chat-protection enabled by Alice" only because Alice has sent the message used by Bob to create the group is wrong. the group protection may have been enabled by Claire.
therefore, we just leave the "by ..." suffix out if we do not know. i came over that when playing around with the new protected-chats :)
otoh, if a dedicated protection enabled/disabled is received, we still add these information.
moreover, this pr clarifies the function signature of `add_protection_msg()` and makes sure, also unpromoted info-message return the correct type when using …
> do not say, a concrete user has enabled protection if we do not really know

- src/dehtml.rs
- src/mimeparser.rs
Fixes probably https://github.com/deltachat/deltachat-core-rust/issues/1982 (I could not test it with the original emails because they were too big to fit in by inbox but the new rust test passes; I'll add `needs-retry`)
> Don't show HTML if there is no content and there is a file attached

- src/message.rs
- src/mimeparser.rs
There may be multiple messages with the same `Message-Id`-header alias
rfc724_mid because an email with multiple attachments was split up.
> Mark all failed messages as failed when receiving an NDN

- python/src/deltachat/account.py
- python/src/deltachat/contact.py
- python/tests/test_account.py
also introduce Contact.block() and Contact.unblock() methods
and deprecate the c-ish "Contact.set_blocked()" api.
fixes #2011
> introduce Account.get_blocked_contacts

- src/blob.rs
this works around the executer-blocking-handling bug as described at https://github.com/async-rs/async-std/issues/900
to make the android4.4 work again, only the flush() at create() is needed - however, create_and_copy() looks very similar to me, so i also added the flush() there. not sure if that is needed at other places as well.
closes #2021 
closes https://github.com/deltachat/deltachat-android/issues/1682
> workaround executer-blocking-handling bug

- src/dc_receive_imf.rs
It has just happened again that a message was put into trash and the log did not say why, this change will help to skip the first debugging step in "message not shown" bugs
> Always show the cause for which a msg landed in trash

- src/mimeparser.rs
- src/simplify.rs
Previously quote at the end was always displayed as [...].
> Display a quote if top posting is detected

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- python/src/deltachat/events.py
- python/src/deltachat/testplugin.py
- python/tests/test_account.py
- src/accounts.rs
- src/imex.rs
add some more precise logging and testing and a fix for the export/import self-key roundtrip.  Also simplify imex functions to directly take path instead of an option and erroring out.
> Fix secret key export/import roundtrip

- deltachat-ffi/deltachat.h
- src/context.rs
ephemeral_task holds a reference to Context, preventing event emitter
from returning NULL and terminating event loop. Prior to this change,
there was no way to quickly terminate pending ephemeral_task.
> Cancel ephemeral task in Context.stop_io()

- src/dc_receive_imf.rs
there was a test, however, that was not working due to a typo :)
with that test fixed, the wrong unarchive-on-read-receipt is easily reproducible - it just does not check any state. i've moved the unarchive() call down a few line, where also secure-join-protocol-messages and kml are detected as hidden-messages, so that for none of these _hidden_ messages, chats get unarchived.
for normal messages, things should stay unchanged.
closes https://github.com/deltachat/deltachat-android/issues/1695
closes https://github.com/deltachat/deltachat-core-rust/issues/2054
> fix mistakenly unarchive

- deltachat-ffi/deltachat.h
- src/chat.rs
- src/stock.rs
the saved-messages can be deleted as any other chat;
if the feature is unneeded, this probably also makes some sense.
however, if saved-messages was deleted accidentally,
it is not intuitive to see how the saved-messages feature can be restored.
this pr just drops a note about how-to-restore to the device chat.
i've seen this issue in reality - and also, by recent android/ios cleanup of the saved-messages and device-chat profiles (removing unavailable things), the "delete" is even more outstanding ;)
we may think about not allowing deletion of saved-messages at all, however, even then, this not is useful, due to different uis.
> add hint about how to restore saved-messages chat

- src/accounts.rs
the field was never set or read.
to get the name for an account,
use `dc_get_config(account, "displayname")`.
closes #2053
> remove unused AccountConfig::name

- src/smtp/mod.rs
Also do not allow downgrade if STARTTLS is not available
> smtp: do not use STARTTLS when PLAIN connection is requested

- src/scheduler.rs
Before, if there were more than 20 jobs at once, we unconditionally
fetched from inbox
This small bug was probably the reason why all of Rene's emails were deleted.
> [CRITICAL] Don't fetch from INBOX if it is disabled

- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
- set_core_version.py
1.50.0-alpha.0 sits between 1.49.X and 1.50.0
This way we can better distinguish tagged from untagged core releases, also in logs etc.
We might, from time to time, increase the alpha.N "N" number if we are entering testing etc.
> let core carry a 1.50.0-alpha.0 version 

- src/config.rs
- src/imap/mod.rs
That's another narrow-stitching patch for a scenario where many emails could be deleted all at once and surprisingly:
user disables inbox-watch, enables delete-from-server, after a moth enables inbox-watch again -> currently all emails that arrived in the meantime will be deleted
(if emails are not fetched, they won't be deleted)
> Don't fetch messages that arrived in the meantime if InboxWatch is disabled and re-enabled

- src/imap/mod.rs
fix #2031
@link2xt do you think any of these optimisations are worth implementing?
- do not fetch emails in chunks of 100 but, like, 5000; only if this fails go back to chunks of 100, we could also remember this
- try to find consecutive ranges (`29:31` instead of `29,30,31`);
- Use sequence numbers instead of uids as there will be more consecutive ranges
- Usually UIDs won't be 9-or 10-digit, so we currently are staying way below the 1000 chars limit
I tend not to think it's worth it because this will only be a real advantage if we download more than 100 messages at once, which is not very often.
> Don't download ranges of messages (i.e. first:last)

- src/mimeparser.rs
- standards.md
- test-data/message/attach_filename_apostrophed.eml
- test-data/message/attach_filename_apostrophed_cont.eml
- test-data/message/attach_filename_apostrophed_cp1252.eml
- test-data/message/attach_filename_apostrophed_windows1251.eml
- test-data/message/attach_filename_encoded_words_bad_delimiter.eml
- test-data/message/attach_filename_encoded_words_binary.eml
- test-data/message/attach_filename_encoded_words_windows1251.eml
this pr handles filenames for the follwing formats and/or adds tests for that:
- encoded-words filenames ([rfc2047](https://tools.ietf.org/html/rfc2047)) as of `filename="==?utf-8?Q?foo?=`
- encoded-words filenames with non-utf-8 character sets (cyrillic)
- apostroped-filenames ([rfc2231](https://tools.ietf.org/html/rfc2231)) as of `filename*=utf-8'en'foo`
- apostroped-filenames with non-utf-8 character sets (cyrillic, ansi)
- this pr does **not** handle encoded word filenames that do not use spaces for separation, not sure that is really needed, it is beyond spec, might be fixed by tweaking the precedence, see https://github.com/deltachat/deltachat-core-rust/issues/1510#issuecomment-737524828 for some more details.
successor of https://github.com/deltachat/deltachat-core-rust/pull/2080 …
> test and fix non-utf8 filenames

- deltachat-ffi/src/lib.rs
- src/dc_receive_imf.rs
- src/ephemeral.rs
- src/imap/mod.rs
- src/message.rs
- src/securejoin.rs
- src/test_utils.rs
If user sends a message before receiving an ephemeral timer change, they will accidentally revert the timer setting.
To prevent this, compare the timer setting to the parent message and ignore the change if parent message had the same timer setting.
> Compare ephemeral timer to parent message to deal with reordering better

- deltachat-ffi/deltachat.h
just came over that when commenting on https://github.com/deltachat/deltachat-core-rust/issues/2096
> correct and refine docs for DC_MSG_IMAGE

- src/mimeparser.rs
Otherwise users with uppercase letters in their addresses never receive read receipts.
> Compare Chat-Disposition-Notification-To: address case-insensitively

- python/tests/test_account.py
- src/config.rs
- src/job.rs
fix #2097: After fetch-existing-msgs completed, go through all group contact requests. If there is an unblocked chat with the sender, also unblock the group chat
> Next try to re-enable fetch-existing-msgs, fixing #2097

- python/src/deltachat/_build.py
- python/src/deltachat/direct_imap.py
Previously only TLS on port 993 was allowed.
> python: use configured_mail_{port,security} when creating IMAPClient

- src/blob.rs
- src/chat.rs
- src/chatlist.rs
- src/config.rs
- src/configure/mod.rs
- src/contact.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/e2ee.rs
- src/ephemeral.rs
- src/imex.rs
- src/job.rs
- src/key.rs
- src/keyring.rs
- src/message.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/param.rs
- src/stock.rs
- src/test_utils.rs
- Create and use some test helper functions
- make TestContext deref to Context so that we don't have to write `.ctx` all the time
- Replace all t.ctx with t (bulk rename)
Not sure if that's the way to go because, you know, merge conflicts (at least it's in the tests, which don't change as often as the rest of the code base) (the rename is all in one commit so no problem to revert this), but we could do this now.
> Nicer rust tests

- python/tests/test_account.py
- src/dc_receive_imf.rs
- src/imap/mod.rs
If mvbox_move was on and an mdn was received, it was not marked as read.
Also remove a confusing log that said that we are adding a markseen job, even if we weren't. As job::save() logs itself, there is no need to log this again.
> Fix marking read receipts as seen

- src/oauth2.rs
Currently we have only one provider in the list, so there is no
difference, but more providers (e.g. Yandex.Connect) may be added later.
> Resolve MX domain only once per OAuth2 provider

- src/provider/data.rs
- src/provider/update.py
Now strict TLS should be explicitly turned off.
By default it is only turned off for nauta provider.
> Enable strict TLS by default

- standards.md
RFC 3676 is understood for incoming messages
and used for outgoing messages.
just found out that that bit is missing in standards.md when dealing with fixed/flowed in #2125
> add reference to RFC 3676 to standards.md

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/config.rs
- src/configure/mod.rs
- src/imap/mod.rs
- src/login_param.rs
- src/oauth2.rs
- src/provider/data.rs
- src/provider/mod.rs
- src/provider/update.py
- src/smtp/mod.rs
- src/smtp/send.rs
- src/sql.rs
Previously MX records were queried only for OAuth 2 configuration and did not affect the list of servers tried. User was required to manually configure the servers for Google Workspace (former GSuite) domains.
Now MX records are queried during configuration. If provider is found in offline database, its ID, corresponding to the filename, is saved as `configured_provider`.
`configured_provider` is also set during database migration if email address uses the domain from the provider database, but no MX querying is done.
Fixes #1759
> Configure provider based on MX record

- src/sql.rs
in addition to merged pr #2123,
dbversion=70 was also used by pr #2125.
pr #2125 is not yet merged, however beta-versions were shipped with
that pr, so, dbversion=70 is already in use on some systems and on these
systems ConfiguredProvider won't be set.
the other way round, that ConfiguredProvider is set twice on some systems
affects only dev-installations and should not harm.
once this pr is merged, #2125 needs a rebase and will use dbversion=72 for
its changes to add the new column also n the dev-installations :)
(we need to check that the column to add does not exist, however)
> use dbversion=71 for updating ConfiguredProvider

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- python/src/deltachat/account.py
- python/src/deltachat/testplugin.py
- python/tests/test_account.py
- src/chat.rs
- src/context.rs
It is misleading and should never be checked.
dc_stop_io() also stops pending ephemeral message deletion tasks, so it
should be called in any case before releasing context.
Closes #2052
> ffi: remove dc_is_io_running()

- src/dc_receive_imf.rs
- src/mimefactory.rs
for easier handling, this pr also adds a helper function `maybe_encode_words()` and uses that for the filename.
fixes #2124
nb: for the `needs_encoding()` check - i am pretty sure that this check is too restrictive and encodes more than needed, eg. spaces, that already prevented usage at https://github.com/deltachat/deltachat-core-rust/pull/1702. but that can be changed later, there is not much waste currently :)
> word-encode Chat-Group-Name-Changed

- src/imap/idle.rs
- src/scheduler.rs
Reverts deltachat/deltachat-core-rust#2076
Unfortunately the verbose logs didn't do the job and @gerryfrancis said it's unlikely they will, as the logs get bloated by the verbose log and he therefore has only half an hour of past logs.
> Revert "Add verbose logging for #2065"

- deltachat-ffi/deltachat.h
- python/src/deltachat/_build.py
- python/tests/test_account.py
- src/chat.rs
- src/constants.rs
useful for creating an "audit log" view of a chat that helps to find
actions like who added/removed who quickly and without endless scrolling.
> add flag to get only info/system messages of chat

- src/context.rs
- src/events.rs
- src/securejoin.rs
- src/test_utils.rs
This also checks that some of the correct user interactions happen,
checking we get a joiner event and the verified chat messages.
It also extends the test utils with the ability to distinguish the
different context logs by having them named.
I'm mostly trying to reduce the diff of an upcoming securejoin PR...
> Add more detail to securejoin tests

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/contact.rs
- src/message.rs
instead, dc_contact_get_display_name() should be used.
dc_contact_get_first_name() was created to save some space on the screen,
esp. on mobile devices,
however, this does not always work and has issues on its own
with some names ("Dr. Strangelove", ":) Name" and so on).
as with mailing lists, more apis with first_name() would be needed,
we decided to drop that instead of following that way.
it is also less an issue as some years ago as screens have become larger,
if really, needed, the ui can handle that more gracefully,
however, just using dc_contact_get_display_name() should be fine as well.
closes #2162 
help on #1964
> remove dc_contact_get_first_name() api

- examples/repl/cmdline.rs
- src/accounts.rs
- src/blob.rs
- src/chat.rs
- src/chatlist.rs
- src/contact.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/e2ee.rs
- src/ephemeral.rs
- src/error.rs
- src/html.rs
- src/imap/idle.rs
- src/imap/mod.rs
- src/imap/scan_folders.rs
- src/imex.rs
- src/job.rs
- src/location.rs
- src/message.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/param.rs
- src/peerstate.rs
- src/pgp.rs
- src/qr.rs
- src/sql.rs
- src/stock.rs
This removes the proxy via crate::error to depend on anyhow directly.
There is no benefit to this indirection and this makes it simpler to
see which error types are used.
> Depend on anyhow directly

- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/imap/mod.rs
This should help if parent message can't be found because messages were
reordered or deleted.
This does not prevent group IDs from being removed from Message-IDs in
the future, in which case it will become dead code.
> Try to extract group ID from In-Reply-To and References as a last resort

- deltachat-ffi/deltachat.h
#define removed ffi-funcion dc_contact_get_first_name as dc_contact_get_display_name to make updating easier
that may help on building desktop while node is not yet updated; so https://github.com/deltachat/deltachat-desktop/issues/2071 can be postponed.
> add define for removed dc_contact_get_first_name()

- python/tests/test_account.py
- src/peerstate.rs
Encryption preference was already applied since commit 78d855c,
but only for already existing peerstates.
As a result, new users ignored gossiped encryption preference in the
"member added" message and had to wait until someone gossiped encryption
preferences for inactive users the second time.
This is a follow-up to #1167
> Apply gossiped encryption preference to new peerstates

- python/README.rst
~~there must not be a space between link text and the link in angle brackets:
https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html~~
~~did not try that out, not sure if i understand that correctly, however.~~ 
EDIT: this is about sphinx (that also defines :ref:  and so on), so, just adding the `#` should do the trick, i could test that at least locally with the rst-plugin of CLion.
closes https://github.com/deltachat/deltachat-core-rust/issues/2145
> fix internal link in README.rst

- python/README.rst
the virtualenv.pypa.io-link without .html extension shows a 404
came over that when fixing #2146
> fix link to virtualenv in python readme

- deltachat-ffi/src/lib.rs
- src/contact.rs
- src/dc_receive_imf.rs
- src/message.rs
- src/securejoin.rs
- src/stock.rs
Using a Contact ID as an error type is risky and a C leftover.
> Resultify Contact::lookup_id_by_addr

- src/location.rs
`is_marker()` should check for length in characters, not bytes.
This was broken during the Rust translation in changeset a5553f98af5df262abd54f3171f53360258655dd
> fix: allow emojis for location markers

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/message.rs
(this pr merges to #1964, not to master!)
this allows to check if a contact request belongs to a mailing list
and to show name/avatar/whatever of the mailinglist.
another approach was to duplicate some chat-apis for messages
(eg. dc_msg_is_mailing_list()) however that would require far more new apis.
the idea to change the behavior of dc_msg_get_chat_id() would be
more clean, however, that easily breaks existing implementations
and can led to hard to find bugs.
> add dc_msg_get_real_chat_id()

- src/chat.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/events.rs
- src/html.rs
- src/message.rs
- src/securejoin.rs
- src/securejoin/bobstate.rs
- src/securejoin/mod.rs
- src/securejoin/qrinvite.rs
- src/test_utils.rs
This PR is still my attempt at working towards addressing #1177 by attempting to split off concerns and make things easier to modify without breaking things.  The tests have been updated in #2154 to cover all code that gets modified here, so there is pretty good confidence this doesn't break things.
There are three main things attempted here, which I failed to separate out further, I apologise for the size:
- QR handling has a specific struct and does not require brittle macros, instead there is type-safety on things being correctly accessed.
- The InnerContext::bob field has been changed to use inner-mutability, this hides the weird typing hoops from parts that don't have to care.  This type also handles other global state management on the context, like the ongoing process interactions. …
> Refactor securejoin QR-code and bob state handling

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/chatlist.rs
- src/dc_receive_imf.rs
- src/message.rs
- options are `StartChat`, `Block` and `NotNow` (instead of Yes/Never/NotNow)- esp. the wording "block" seems to be better as that wording is also used in the ui and also there are unblock functions to revert the option. also for mailinglists, we should keep that wording
- add DC_DECIDE* constants to deltachat.h
- move decide_on_contact_request() to context-object, see commit message for reasoning
> refine decide api

- src/param.rs
- src/qr.rs
Param should only be used to parse dictionaries stored in SQL database, not external data.
Since Param parser has been extended to escape newlines with newlines, QR-codes parser started to treat && as escaped &, which is wrong.
This change also uses String keys like "n" for "name" instead of completely unrelated constants like Param::SetLongitude.
> Parse QR codes without using Param

- python/tests/test_account.py
- src/config.rs
- src/context.rs
- src/message.rs
fix https://github.com/deltachat/deltachat-core-rust/issues/2176
we can re-enable it when DC determines automatically which folders to watch and
this is deployed for at least 1 release.
This PR adds a config "senbox_move" that is currently only needed for the tests; we can decide what we want to do with it later.
> Disable moving to Sentbox for now

- src/chat.rs
- src/chatlist.rs
- src/constants.rs
- src/dc_receive_imf.rs
- src/job.rs
- src/message.rs
- src/param.rs
this pr merges to mailinglists2, not to master.
we can now pretty freely decide, how to handle chattype in ffi.
> re-introduce Chattype::Mailinglist

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- python/src/deltachat/chat.py
- python/tests/test_account.py
- src/chat.rs
- src/contact.rs
- src/stock.rs
This PR will add a function `dc_get_chat_encrinfo` similar to `dc_get_contact_encrinfo` to make it easier to debug why the group does not encrypt. Currently the process involves sending a message and then searching the log for `peerstate`, or worse, asking someone else to do the same, often multiple times.
On Android, related "Encryption" menu item can be added to the chat profile screen to avoid cluttering the menu in the chat screen. For 1:1 chats we can either use `dc_get_contact_encrinfo` or deprecate `dc_get_contact_encrinfo` and always use `dc_get_chat_encrinfo`.
Recent related PR: #2174
> dc_get_chat_encrinfo

- src/message.rs
some videochat-services do not support adding random rooms to the url,
users let people in manually, so they can always use the same url.
as hacks as hiding the genrated random room behind `#$ROOM` or `?foo=$ROOM`
do not always work, this pr introduces the parameter `$NOROOM` that is
just replaced by the empty string.
see https://support.delta.chat/t/videochat-with-webex/1412
for further details.
> support videochat-services not suppporting rooms

- src/job.rs
.get(0) gets the whole first line
> Use .first_word() to get enhanced status code

- src/imap/mod.rs
The get_chat_id_by_grpid() call is already resultified.  The database
can only contain consistent data since on creation it inserts rows for
the special chats which do not have a grpid set so can never match.
Thus we can safely remove another use of the ChatId::is_unset call
which should be removed to clean up the type.
> Remove obsolete ChatId::is_unset check

- deltachat-ffi/src/lib.rs
- examples/repl/main.rs
- src/securejoin/mod.rs
- src/token.rs
The ChatId::is_unset method is something we need to get rid of to
clean up the type.  This removes one use-case in generating QR codes
for securejoin.
> Remove use of ChatId::is_unset

- Cargo.toml
This does not affect the release profile and it significantly speeds
up compilation.  In the rare cases where panics are not sufficient to
debug something you can manually enable this again.
> Disable debug info in the dev profile by default

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/context.rs
Using a ChatId value of 0 to indicate global search is a left over
from C-land.  Refactor this to be an option instead.
> Avoid ChatId::is_unset for searching messages

- python/tests/test_account.py
- src/contact.rs
- src/dc_receive_imf.rs
- src/qr.rs
- src/sql.rs
The following rules apply now:
1. "name" column is only updated manually and never over the network
2. "authname" column is only updated over the network and never manually
3. Displayname is a "name" if it is non-empty, otherwise it is "authname".
This fixes a known (pytest.xfail) problem of "name" being changed over
the network when user has set it to non-empty string manually.
This also fixes the problem when "name" and "authname"
became unsynchronized accidentally, when they were equal and then
Origin::IncomingUnknownTo update arrived, setting "name" but not
"authname". Rust regression test is added for this case.
> Fix contact name update rules

- deltachat-ffi/deltachat.h
- src/contact.rs
strike the part "as defined by the contact himself".
> update docs for dc_contact_get_name()

- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
1.51.0-alpha.0 is somewhere between 1.50 and 1.51,
as various beta-versions come or already came out with the new core,
this is helps in logs/debugging.
i think, the version will stay untagged, it is mainly for logs
cmp. https://github.com/deltachat/deltachat-core-rust/pull/2084
> bump version to 1.51.0-alpha.0

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
in rare cases, you need the "original name" in the ui, eg. to make a placeholder as suggested at https://github.com/deltachat/deltachat-desktop/issues/2109 work properly and it is also needed for https://github.com/deltachat/deltachat-ios/pull/1051
successor of #2206
> add dc_contact_get_auth_name()

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/location.rs
- src/mimefactory.rs
Special chats can never send locations, so no need to hit the
database.  This also means there's no need to use ChatId::is_unset.
> Avoid ChatId::is_unset when querying location sending

- Cargo.lock
- Cargo.toml
- src/chat.rs
- src/color.rs
- src/contact.rs
- src/dc_tools.rs
- src/lib.rs
This should make colors used by Delta Chat for emails similar to colors
used by XMPP clients implementing the same specification[1], such as
Conversations and Snikket.
Previously Delta Chat used only hardcoded 16 colors, so this change
should also increase the number of colors and make it easier to
distinguish different contacts.
[1] https://xmpp.org/extensions/xep-0392.html
> Implement Consistent Color Generation (XEP-0392)

- src/contact.rs
- src/e2ee.rs
- src/job.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/peerstate.rs
- src/securejoin/mod.rs
Reduce the number of lifetimes and move message building to the end of MimeFactory.render()
This is the first part of #2232
> Refactor MimeFactory

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/dc_receive_imf.rs
- src/headerdef.rs
- src/message.rs
- src/mimefactory.rs
- src/param.rs
this pr introduces `dc_msg_set_override_sender_name()` that allows to set a sender name that is valid only for a single message. this is useful for impersonation, for bots and bridges. the pr is build on things that were already introduced by the mailinglists in #1964, so, a UI that implements receiving mailing lists also supports these manually set per-message-names.
once a recipient receives a message with override-sender-name set, it does _not_ update the name in the contact database (as done usually), so the rename does not affect past and future messages.
**on protocol-level,** the question discussed recently on irc was, how the per-message-name can be identified, one option would be a separate header, however, quite a few ppl are sceptical in introducing more headers. an alternative …
> impersonate: allow to override sender name

- python/tests/test_account.py
- src/imap/scan_folders.rs
- src/scheduler.rs
- Remove confusing log
- Only scan_folders() on the Inbox folder to prevent race conditions when multiple threads scan at once. But make sure that the inbox folder always scans. I missed this when implementing scan_folders().
> Scan folders adjustments

- CHANGELOG.md
- src/dc_receive_imf.rs
- src/message.rs
- src/mimeparser.rs
closes #2235 
moreover, this pr ensures, all detected mailinglists are also handled somehow; before, not all lists detected by is_mailing_list_message() were treated as mailinglists.
if we encounter in the future, that the `Precedence` + `Sender` check misses too many mailing lists, `get_mailinglist_type()` should be pretty easy to adapt. however, i think, the vast majority of mailing lists have a `ListId` anyway.
> support mailinglists without ListId-header

- src/securejoin/bobstate.rs
- src/securejoin/mod.rs
This fixes #2246.
It's probably best to look at the two commits separately:
1. The first commit fixes the bug.
2. The second commit is actually a new feature, I noticed we can do
better than just sleep while waiting for the ongoing process.
> Fix ongoing management in securejoin

- src/headerdef.rs
- src/imap/mod.rs
- src/mimefactory.rs
- src/mimeparser.rs
outlooks SMTP-server change the Message-ID of messages
and put the original Message-ID to X-Microsoft-Original-Message-ID.
the changed Message-ID has some issues:
- outgoing messages with bcc_self enabled are shown twice
as the self-copy got the changed Message-ID while the database uses
the original one
- read receipts do not work as they refer to the changed message id
- in general, sender and recipient see different Message-IDs
the issues can be fixed by
1. **let all receivers use the original Message-ID**
this is what this pr is doing
and this should fix all issues with delta-to-delta communication,
including groups, group-images etc.
there may be issues left in communication
with other MUAs as they are using another Message-ID.
2. ftr, this is not what this pr is doing:
**updating …
> improve outlook compatibility

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/repl/main.rs
- src/contact.rs
this pr adds some missing functionality to the repl tool to make testing easier.
moreover, this pr deprecates `dc_get_blocked_cnt()` - as far as i see, this was not really used anywhere, just for a test in node (therefore, it is still there, not yet removed ;)
getting rid of this functions makes upcoming changes wrt blocking easier as there is only one function left to deal with blocked contacts.
> add decision- and blocking-functions to repl, cleanup

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/contact.rs
- src/dc_receive_imf.rs
for review: **only the last commit contains the logic** (only one file affected), the other commits are cleanup, a fix and a test. some in advance:
to get #1964 in, we postponed the question about unblocking mailing lists - on current master, they can be blocked but there is no method to unblock them.
this pr picks up the original idea and keeps the existing api (therefore, no adaption is needed in ui, see comment 3. at https://github.com/deltachat/deltachat-core-rust/pull/1964/commits/3c0d1a591bd4e893b1c4def01ac460958e246dd6).
however, instead of introducing a "pseudo contact" that is always added to the mailing list, we add such a contact only if the mailing list is actually blocked and if the blocked-list is requested. `Origin::MailinglistAddress` makes sure, the contact is not created …
> allow unblocking mailinglists using the existing api

- src/dc_receive_imf.rs
- test-data/message/mailinglist_dhl.eml
- test-data/message/mailinglist_dpd.eml
if mailinglists are sent from an address that appears to be a "noreply" address AND we do not have found out a name yet, the name in `From:`-header is probably better than the (often partly random/numeric) List-id which we would use as a last resort otherwise.
i've seen this pattern today for two bit german parcel services (which i wrote the tests for), but i assume, this pr will also catch other similar mailinglists and get them a nicer name :)
> tweak mailinglist names

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/context.rs
~~this still needs a test.~~ EDIT: test added.
closes #2268, closes https://github.com/deltachat/deltachat-desktop/issues/2147
nb: for whatsapp, a similar fix made it to theverge: https://www.theverge.com/2019/10/29/20937835/whatsapp-muted-chats-notification-badges-ios-update
> exclude muted chats from notified-list

- examples/repl/cmdline.rs
- examples/repl/main.rs
- src/context.rs
this is a successor or #2269 that excludes muted chats from `get_fresh_msgs()`. unfortunately, the used condition was just wrong.
moreover, this pr adds a test and the "mute functionality" to the repl tool.
closes #2276
> fix muted-check in get_fresh_msgs()

- src/dc_receive_imf.rs
- src/html.rs
- test-data/message/mailinglist_with_mimepart_footer_signed.eml
usually, there is at most one text/html and one text/plain part.
multiple text/plain parts, however,
are known to be generated by mailinglist software that want to add a footer
but cannot alter the original content part -
maybe because it is html and things are hard to stitch
or maybe because the content part is cryptographically signed
and cannot be altered therefore.
related #2270 
closes #2278
> let get_html() return first instead of last text

- src/constants.rs
- src/dc_tools.rs
- src/mimeparser.rs
see #2213 for reasoning.
the pr just truncates text after ~~20000~~ 29000 characters unconditionally, the limit is a bit lower that the old, hard cut, as we not only truncate the text but also offer a "Show full message" button. to keep things simple, the pr does not handle long links or so (see issue), if really needed, we can do that at some later point, but i would suggest to see how this simple approach works out first.
closes #2213
> Deal with long incoming messages

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- python/tests/test_account.py
- src/dc_receive_imf.rs
- src/ephemeral.rs
- src/message.rs
- src/mimefactory.rs
- src/param.rs
- src/sql.rs
- src/test_utils.rs
fix  #2138
new api `dc_msg_get_subject()`,
when quoting, use the subject of the quoted message as the new subject, instead of the
last subject in the chat
> save subject for messages

- src/chat.rs
>  When forwarding a message that is an impersonating message, the forwarder should not be impersonating

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/imex.rs
- src/job.rs
- src/log.rs
I started to implement this as I wanted to use `log_m()` in https://github.com/deltachat/deltachat-core-rust/pull/2283 but then decided to make an extra PR.
> Even nicer logging: Add log_m()

- src/chat.rs
this adds some resilience against smtp-server changing Message-ID header, before, these headers were unset.
`In-Reply-To:`-header is still unset, so, MUA should still be able to detecht things accordingly; `References` is usually only used as a "further hint", iirc. the related RFC is https://tools.ietf.org/html/rfc5322#page-25 - seems as if we are not even breaking that :)
on incoming messages, no changes seems to be needed as we already try to extract the grpid from `References:`-header before.
i tested that with an outlook-com-delta-chat client communicating with thunderbird-non-outlook 🗡️ 
closes #2252
> set References header to Message-ID on top-level messages

- src/lot.rs
- src/qr.rs
Previously QrFprWithoutAddr was returned incorrectly.
Also fix spelling error ("Missmatch").
> qr: return QrFprMismatch on fingerprint mismatch

- python/CHANGELOG
this is to see if CI is happy with 1.51 and the current state of python bindings.
> prepare 1.51.0 release

- deltachat-ffi/src/lib.rs
dc_get_config() must never return NULL, instead return ""
> fix test_fetch_existing

- src/contact.rs
sqlx does not bind the first `?` implicitly to `?1`,
therefore the sql-statement fails 
(returns count==0 and the ChatModified-event is not sent).
we could use `?1` several times, however,
i did not find good documentation about that,
and even if that works now, that could fail with other db
or even with sqlite in newer versions.
therefore, we just bind every parameter explicitly.
~~not sure yet, if that alone fixes the issue, though.~~
EDIT: seems so, only 5 failing python tests left, test_contact_rename passes with this pr.  
i also checked similar occurances, however, did not find more issues of the same type.
> sqlx-port: do not re-use bind parameters

- deltachat-ffi/src/lib.rs
- src/dc_receive_imf.rs
this pr adds a rust-test to check the save_mime_headers flag; the rust-test test even more circumstances than the python test.
the second and third commit fix the issue.
in fact, the issue was already there on master [[1]](https://app.circleci.com/pipelines/github/deltachat/deltachat-core-rust/8107/workflows/6419f0b1-ee27-4657-8c14-66dfd1e0873c/jobs/31047), however, for whatever reason, was not fixed there. the issue was that, by html-mails, if introduce a "raw-decrypted" field which, for preformance reasons, is set only when needed by html-view. `save_mime_headers` flag tries to save it unconditionally for encrypted messages (the second mail in the test is encrypted).  
(wondering, if this `save_mime_headers` is acutally in use somewhere, however, now it is fixed, so we can postpone this …
> sqlx: fix failing TestOnlineAccount::test_saved_mime_on_received_message

- src/context.rs
- src/sql/mod.rs
setting the number of connections
to the number of cpus seems to be to low in general:
- on a mac i5 from 2017, that would result in 4 connections
- on an iphone7, that would result in only 2 connections
the sqlx-default is 10 connections,
so, this pr uses that default (plus 1 connection for the writer tag).
on the iphone7, that change was directly noticable -
sqlx with 2 connections feelt not much faster that rusqlite with 10 connections,
however, using sqlx with the 10+1 connection was a real boost,
at least at a first glance :)
might be, fewer connections would be sufficient as well,
however, i do not see much reasons not to go with the default here.
> set max_connections=10 (default), show num_cpus in get_info()

- src/sql/mod.rs
A follow-up to 720135a915759d8014a27b7944ae2975bae32a4d
> sql: enable virtual statement cache on the reader pool

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- src/dc_receive_imf.rs
fix  #2073
fix #2292 (I think)
- Messages can be assigned to any chat by the References and In-Reply-To, also to 1:1 chats; this has higher priority than the group id because with ad-hoc groups, it can happen that two devices have different group ids for the same conversation thread.
- If `From` is not in the chat (we call this "shadow sender"), `OverrideSenderDisplayname` is set. This communicates to the UI that:
- A `~`should be added in front of the sender's displayname.
- Also in 1:1 chats, the sender's displayname and avatar is shown, as if this was a group.
The "Unknown sender for this chat" messages are completely removed for unprotected groups.
For protected chats, everything stays as it was before.
POSTPONED:
- Maybe (if it turns out to be still necessary):
- The ad-hoc group id …
> Add alias support 2

- Cargo.lock
- Cargo.toml
- examples/repl/cmdline.rs
- src/chat.rs
- src/chatlist.rs
- src/config.rs
- src/context.rs
- src/imex.rs
- src/key.rs
- src/location.rs
- src/message.rs
- src/peerstate.rs
- src/sql/migrations.rs
- src/sql/mod.rs
&str queries are not persistent by default.  To make queries persistent,
they have to be constructed with sqlx::query.
Upstream sqlx does not contain the change that make all queries
persistent, but it is not needed anymore. but
> sql: make all queries persistent and update to upstream sqlx

- src/e2ee.rs
- standards.md
- test-data/message/protonmail-mixed-up.eml
- test-data/message/protonmail-repaired.eml
This is an PGP/MIME format produced by Microsoft Exchange and ProtonMail IMAP/SMTP Bridge, described in detail in https://tools.ietf.org/id/draft-dkg-openpgp-pgpmime-message-mangling-00.html
This patch adds seamless support for "Mixed Up" Encryption, repairing mangled Autocrypt messages without notifying the user.
Fixes #2320
> Add support for "Mixed Up" MIME format

- python/src/deltachat/chat.py
- python/src/deltachat/message.py
`Chat.send_msg()` is updating `Message._dc_msg` but `Message.id` is not a dynamic property so message id was still `0` in the message object, not synchronized with the real id from the database.
> make Message.id a dynamic property

- src/chatlist.rs
- src/contact.rs
the user-given contact name may be set to an empty string;
in this case the authname or the email is used for the contact
and also for the name of possibly existing chats.
this works well for `dc_chat_get_name()` as that just uses
`dc_contact_get_display_name()` for single-chats.
it did not work for `dc_get_chatlist(query)` as that
uses the database for performance reasons -
however, in the database, the empty string is written
instead of the display name is written for a chat.
this is fixed by this pr by also using
`dc_contact_get_display_name()` when updating the chats-table
(similar to `dc_create_chat_by_contact_id()`)
closes #2343 
i came over that when tweaking the global search on ios in https://github.com/deltachat/deltachat-ios/pull/1140 :)
i also checked the official android 1.14 …
> fix single chat search

- .circleci/config.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
core52 to have an official version with sqlx merged in, even if there are some known issues, see below.
as sqlx is quite a huge change, beta-releases based on core52 should also be bumped, so eg. android/ios 1.19 then, not 1.17.x.
what's left for a final, stable core53+:
- finish the avatar-pr #2232 
- not sure about the blocker #2335 in the [email-compat](https://github.com/orgs/deltachat/projects/31) project - is that really a blocker?
> prepare 1.52

- Cargo.lock
- Cargo.toml
- src/sql/mod.rs
This is based on #2355, which should be merged in first.
Fixes #2353
I am not sure about safety of `PRAGMA read_uncommitted=1;`, but it is suggested by https://sqlite.org/sharedcache.html and I get "table locked" errors otherwise. I think it should not cause significant issues because we usually don't commit many rows in a single transaction and don't rely on them being either written or not at the same time during reading.
> sql: enable shared cache

- python/src/deltachat/account.py
- python/src/deltachat/direct_imap.py
- python/src/deltachat/testplugin.py
- python/tests/test_account.py
This PR originally contained a fix for sqlx which turned out not not to be necessary. But on the way, I made some general improvements:
- Under some circumstances, a "normal" test failure led to a timeout, without printing a decent error message. See e.g. https://app.circleci.com/pipelines/github/deltachat/deltachat-core-rust/8069/workflows/ba2a9949-b4ad-4ceb-a930-073bba05e2db/jobs/30965.
(The problem was: if there is an exception in dc_account_extra_configure(), when trying to handle the exception the line account.log("===================", e, "===================") was called, which can't work as log() only expects one parameter)
- When a test fails: Call `dump_account_info()` even if there is no direct_imap
- In test_import_export_online_all(), add another 100KB file to the backup. …
> Some general Python test improvements

- src/dc_receive_imf.rs
This check dates back to C core, where it checked for NULL, not empty string.
> dc_receive_imf: remove unnecessary check for empty folder name

- src/context.rs
It reduces the time by ~20% according to `search_msgs` benchmark.
Sorting by IDs is sufficient for global search as IDs increase in the
order of message reception.
> Sort global message search result only by ID

- deltachat-ffi/deltachat.h
- src/context.rs
see code documentation for details.
EDIT: i also just tested on android, _without_ this pr: depending on typing speed, search_msgs() is called for lots result, easily resulting in execution times of >10s on a bigger database; avoiding exactly these long runs is what this pr is about.
EDIT: yip, i can confirm, the max search time is reliably limited to <1s on the testphone, making the overall ux of incremental search much smooth :)
> LIMIT global search

- src/ephemeral.rs
- src/job.rs
Fix #2335
- You are offline, and an ephemeral message is due to delete.
- load_imap_deletion_job() is called and returns a deletion job for it.
- The job fails because, well, we are offline.
- The job is saved into the database.
- load_imap_deletion_job() is called again, and so on.
Now, this doesn't check if there is already a postponed message deletion job for this message before saving a new one to the database because I was unsure how to do it: The nicest way to do it seems to be to let SQL make sure that there aren't two jobs with the same thread, action, foreign_id and param. Is this maybe possible?
Otherwise, should we just check in job::save() whether there is an existing job? As above, it would probably make sense to not only do this for DeleteMsgOnImap, but also …
> Fix #2335 (delete job flooding)

- src/sql.rs
It was set in `sqlx` code, but not in `rusqlite` mode.
synchronous=FULL makes benchmark that write to the database a lot slower.
> sql: set PRAGMA synchronous=normal

- deltachat-ffi/deltachat.h
- examples/repl/cmdline.rs
- src/chat.rs
- src/message.rs
UIs call `dc_marknoticed_chat()` when the  deaddrop is opened as well as `dc_markseen_msgs()` for messages scrolled over. 
up to now, messages in the deaddrop are marked as _noticed_ in `dc_markseen_msgs()`, this has the following disadvantages:
1. depending on the scrolling through the deaddrop, by debouncing, _some_ messages may be marked as noticed (see #2371) - which results in a bit random contact requests appearing in the chatlist (which show unnoticed, _fresh_ messages)
2. the UIs do not have control about _when_ things are marked as noticed (`dc_markseen_msgs()` does some more things and needs to be called unconditionally, see comment in .h)
this pr moves the mark-as-noticed action to `dc_marknoticed_chat()`, fixing 1. by that and allowing an explicit "Not now for all" button for …
> mark deaddrop as 'noticed' in dc_marknoticed_chat() instead of dc_markseen_msgs()

- python/src/deltachat/_build.py
I'm packaging libdeltachat for NixOS and also want to package the Python bindings: https://github.com/NixOS/nixpkgs/pull/121151.
> python: fix build against system library

- src/mimefactory.rs
- src/mimeparser.rs
Current plan is to place the image directly into Chat-User-Avatar header. As the header can be large, it should be placed into the root of encrypted MIME message, like Autocrypt-Gossip. If the message is not encrypted, single-part `multipart/mixed` message should be created and `protected_headers` placed into its root.
> Place user avatar directly into Chat-User-Avatar header

- CHANGELOG.md
- src/contact.rs
- src/dc_receive_imf.rs
This feature is similar to existing avatar synchronization.
Whenever encrypted BCC-to-self copy of chat message is received, status
setting is updated with the signature of the message.
Closes #2219
> contact: synchronize status between devices

- .github/dependabot.yml
Configuration file is documented at https://docs.github.com/en/code-security/supply-chain-security/enabling-and-disabling-version-updates
> github: add Dependabot configuration

- Cargo.toml
It is enabled from deltachat-ffi/Cargo.toml by default.
Fix for abac35c872adb55ff9b1ef8ffe134ffe61d5e445
> Cargo.toml: move "rusqlite/bundled" to "vendored" feature

- .github/workflows/remote_tests.yml
- scripts/manual_remote_tests.sh
- scripts/remote_tests_python.sh
- scripts/remote_tests_rust.sh
Instead, allow specifying free-form BUILD_ID from the command line.
scripts/remote_python_packaging.sh still uses CIRCLE_ variables to avoid
changing working CircleCI config.
> ci: remove CIRCLE_* environment variables from scripts

- deltachat-ffi/src/lib.rs
- src/blob.rs
- src/chat.rs
- src/config.rs
- src/dc_tools.rs
- src/sql.rs
- src/sql/migrations.rs
- Currently, group images are compressed as well because it was easier to implement that way.
- Currently, in the unlikely case that the avatar is compressed down to 20x20 pixels but still bigger than 20KB, the user doesn't get any indication of this, the avatar simply isn't changed (at least on Android).
If we want to change this, the easiest way is probably to let `dc_set_config()` in the ffi call `error!()` if `Selfavatar` can't be set. The same might make sense for some or all other configs. BUUUUUT: At least Android doesn't show error!() toasts anymore, probably because they were used too often and too spammy.
- The factor by which we scale down if the file is too big is 1.5.
I hope everything is clear :joy: there were surprisingly many small problems.
> Compress avatar to below 20k

- CHANGELOG.md
- python/setup.py
It is used in `testplugin.py`.
Fixes #2330
> python: list `requests` as a requirement

- scripts/set_core_version.py
According to `git help tag`, annotated tags are meant for releases.
If tags are not annotated, `git describe` ignores them.
> scripts/set_core_version.py: suggest using annotated tags

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/simple.rs
- src/chat.rs
- src/chatlist.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/ephemeral.rs
- src/events.rs
- src/imex.rs
- src/job.rs
- src/log.rs
- src/message.rs
- src/mimefactory.rs
- src/peerstate.rs
- src/qr.rs
- src/securejoin.rs
- src/securejoin/bobstate.rs
- src/stock_str.rs
- src/test_utils.rs
This introduces the explicit ChatIdBlocked struct to more explicitly
create a chat with a blocked status.  It also adds a common shortcut
to ChatId itself which is more natural to use in many cases.
In the second commit this moves some constructors to associated methods on the type, which makes the creation of `ChatId`s more coherent.
I admit some of this is rather subjective, I think the `ChatId::get_for_contact()` shortcut is probably the most significant addition.  As are some small fixes on callers that `_or_default()` and documenting the SQL a bit better.
Additionally however my main driving factor is the further pursuit of removing the usage of `ChatId(0)` occurrences.  While this is not yet achieved, this fixes up some usages and isolates the remaining usages of `<ChatId as …
> Explicit API for creating chats with blocked status

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- src/blob.rs
- src/chat.rs
- src/color.rs
- src/config.rs
- src/configure.rs
- src/configure/auto_mozilla.rs
- src/contact.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/imap.rs
- src/imap/client.rs
- src/imap/idle.rs
- src/imap/select_folder.rs
- src/imex.rs
- src/job.rs
- src/message.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/oauth2.rs
- src/param.rs
- src/provider.rs
- src/qr.rs
- src/securejoin.rs
- src/sql.rs
- src/stock_str.rs
- src/test_utils.rs
Using `impl AsRef<str>` as the argument instead of `&str` makes it
possible to call the function with `&str`, `String` and other types
that implement `AsRef` trait.
The cost of it is that compiled binary contains mulitple versions of
the same function, one for each variant of types. If function contains
multiple generic `impl AsRef` arguments, the number of versions possibly
compiled into binary grows exponentially with the number of arguments.
Simple way to avoid it is to call `.as_ref()` on the caller side to
convert the argument to `&str`. In most cases even adding a `&` and
relying on `Deref` coercion is sufficient.
This patch changes many functions that accepted `impl AsRef<str>` and
`impl AsRef<Path>` to accept `&str` and `&Path` instead.
In some places `.clone()` calls are removed. …
> Debloat the binary by using less `AsRef` arguments

- python/tests/test_account.py
- src/imap/scan_folders.rs
Issue Reported by @webratte
When watch_inbox was off, scan_folders failed and a toast "IMAP operation attempted while it is torn down" was shown.
--
When inbox_watch is off, scan_folders() is called at https://github.com/deltachat/deltachat-core-rust/blob/244260a9789a34c8cdd50c73b96557a8ced40345/src/scheduler.rs#L107 but connect_configured() is not called before.
> Make scan_folders work when inbox is not watched

- python/tests/test_account.py
This test checks that MDN is marked as seen on ac1.  Because ac1 also
receives BCC-self, it is possible that event of marking this message
as seen is confused with marking MDN as seen, and the test passes even
if MDN is not marked as seen.  Explicitly disabling BCC-self for ac1
ensures it receives only one message (MDN).
Also start direct_imap as early as possible, before sending the
message. It is possible now, because BCC-self is not sent.
> python: disable BCC-self in `test_markseen_message_and_mdn`

- src/dc_receive_imf.rs
- src/mimeparser.rs
Fix https://github.com/deltachat/deltachat-android/issues/1940, fix https://github.com/deltachat/deltachat-core-rust/issues/2220 (I assume these are the same bug)
- Gmail adds a header `Bcc: <self-address>` to our bcc-self message
- `to_id` was just set to the first recipient, in this case _self_
- it was seen that `to_id` is _self_, so it's a self-sent message
> Fix all outgoing messages popping up in selfchat

- src/configure.rs
- src/context.rs
- src/imap.rs
- src/imap/idle.rs
- src/imap/scan_folders.rs
- src/job.rs
- src/scheduler.rs
`Imap` structure is always created in a configured state now. There is
no default value for `ImapConfig` anymore.
Also resultify Scheduler::start() to fail on database errors, for
example if IMAP configuration cannot be read from the database during
`start_io()`. Previosuly errors during reading keys such as
`mvbox_watch` were simply ignored and folders were not watched until
the application is completely restarted, now start_io() will fail and
scheduler will only be started at the next start_io() call which
usually happens when app is brought to the foreground.
> imap: refactor to always create Imap configured

- src/blob.rs
Fix #2468
If `max_bytes` is `None`, `encoded_img_exceeds_bytes` does nothing, esp. it doesn't encode the image into `encoded`.
Then,
https://github.com/deltachat/deltachat-core-rust/blob/c183203577d8c0b397a3c6216d80c1f2d3112d06/src/blob.rs#L537-L539
encoded the image into `encoded`, but without scaling it down.
(these three lines are needed in case the image does not need to be scaled at all but just rotated)
I wrote a test, but it doesn't include the case that an image has to be rotated; I'm wondering whether this would be worth the effort as we would probably need to put an image with the rotation-exif-flag into the `test-data` folder, sending it out to get the "actual" image, manually rotating it inside the test to get the "expected" image, and then somehow comparing …
> Fix downscaling images

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deltachat-ffi/Cargo.toml
the new core includes some bugfixes that may be considered as being a bit critical, esp. the images that are sent in too high resolutions and the outgoing messages popping up in selfchat for some providers.
~~the changelog already mentions #2471 , so that should be reviewed/approved/merged first.~~ EDIT: done
~~@link2xt @flub shall we also merge in https://github.com/deltachat/deltachat-core-rust/pull/2182 ? - this still lgtm :)~~ EDIT: i merged #2182 in an rebased this pr
git tag -a 1.56.0
git push origin 1.56.0
> prepare 1.56

- python/tests/test_account.py
- src/chat.rs
Also do not count hidden messages in get_msg_cnt().
> chat: make get_msg_cnt() and get_fresh_msg_cnt() work for deaddrop

- src/dc_receive_imf.rs
- src/headerdef.rs
systemli.org seems not to include Received: header in messages sent to
self, including BCC-self and messages sent to Saved message chat. This
results in all these messages not being displayed on other devices in
multi-device setting. To work around this problem we restrict draft
detection based on Received: header to classical mails.
Delta Chat already implements proper draft detection based on the
\Draft message flag and \Drafts folder flag (#2454). However, Thunderbird does
not set \Draft flag when message is stored as "Template". To make
draft detection for Thunderbird more robust, in case Received: header
check is removed altogether later, we check for X-Mozilla-Draft-Info
header which Thunderbird sets both for "Drafts" and "Templates".
> Improve drafts detection

- src/blob.rs
- src/color.rs
- src/configure.rs
- src/configure/auto_mozilla.rs
- src/configure/auto_outlook.rs
- src/dc_receive_imf.rs
- src/dc_tools.rs
- src/imap.rs
- src/imap/select_folder.rs
- src/imex.rs
- src/job.rs
- src/log.rs
- src/message.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/oauth2.rs
- src/pgp.rs
- src/simplify.rs
- src/sql.rs
fix rustdoc errors as 
```
Error:   --> src/log.rs:79:13
|
79 |     /// See https://github.com/rust-lang/rust/issues/78840 for progress on this.
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://github.com/rust-lang/rust/issues/78840>`
|
= note: `-D rustdoc::bare-urls` implied by `-D warnings`
= note: bare URLs are not automatically turned into clickable links
error: this URL is not a hyperlink
```
the errors are probably related to new rust 1.53.
for consistency, i also formatted most links in non-rustdoc comments the same way.
> move links to angle brackets to avoid rustdoc errors

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/accounts.rs
the default account created by `dc_accounts_new()`
is annoying when doing a migrate/import account;
in this case, you must not forget to remove the default account.
in between you have two account,
and accounts are swiched.
it seems to be better
to just call add_account() on a new account object as needed.
> avoid creating a default account, adapt tests

- src/chat.rs
set_draft message changed event returns now draft msg id instead of 0.
We found this out while investigating ways to solve https://github.com/deltachat/deltachat-desktop/issues/2131#issuecomment-801181618, but unfortunately that bug was not fixed by this yet.
> set_draft message changed event returns now draft's msg id

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- python/src/deltachat/message.py
- python/tests/test_account.py
- src/message.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/param.rs
New `dc_msg_is_bot()` C API and corresponding `Message.is_bot()` Python
API can be used to check if incoming message is sent by a bot, e.g. to
avoid two echo bots replying indefinitely to each other.
"Bot" flag is not set for outgoing messages, but may be set for
BCC-self messages. For now documentation says that `dc_msg_is_bot()`
return value is unspecified for outgoing messages. It can be better
specified later if needed for specific applications, e.g. sharing an
account with a helper bot.
Fixes #1301
> Use `Auto-Submitted: auto-generated` header to identify bots

- src/chat.rs
- src/dc_receive_imf.rs
Fixes mainly #2499 and related bugs.
See commit messages for details.
Generally the idea is to ensure that messages stored in the database are displayed at least somewhere. Info messages that go into contact requests are still not shown anywhere, but this will probably be solved by replacing contact request chat with a contact request chatlist later, so info messages will be shown in relevant chats.
> Avoid hiding outgoing classic emails

- deltachat-ffi/src/string.rs
- src/dc_receive_imf.rs
- src/html.rs
- src/message.rs
- src/sql/tables.sql
- test-data/message/cp1252-html.eml
Raw MIME messages may contain non-ASCII characters. Attempting to
store them as TEXT by using String::from_utf8_lossy results in
non-ASCII characters being replaced with Unicode U+FFFD "REPLACEMENT
CHARACTER" which is later incorrectly decoded when attempting to parse
`mime_headers` content into HTML.
Fixes #2455
> Store mime_headers as BLOBs

- deltachat-ffi/deltachat.h
- src/lot.rs
- src/qr.rs
- src/token.rs
closes #2511 
this pr adds options to withdraw/revive own qr-codes by simply scanning them.
- `dc_check_qr()` may return one of DC_QR_{WITHDRAW|REVIVE}_VERIFY{CONTACT|GROUP}
- the UI should ask the user, sth. as "This QR code was generated by your for ... do you want to withdraw it?"
- if wanted, one can change the configuration using `dc_set_config_from_qr()` with just the qr-code as paramters.
internally, on withdrawing, the corresponding tokens are deleted or re-inserted.
re-insertion may result in N tokens for a given chat - however, that should not be an issue as the token is verified by exists(token) and not by lookup(chat_id). lookup(), however, makes sure to return only one token and using the newest one.
> withdraw/revive own qr-codes

- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/simple.rs
- src/chatlist.rs
- src/dc_receive_imf.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/test_utils.rs
Avoid using MsgId::new(0) in place of `None` in the Rust part.
Zero ID is only used in FFI part now.
> chatlist: resultify `get_msg_id`, `get_summary` and `get_summary2`

- src/chat.rs
- src/dc_receive_imf.rs
Ensure messages without `Date:` header bump the chat to the top of chatlist.
> Fixes for message timestamps

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/accounts.rs
in most (all?) UIs, import/export works on an already created account,
so, dc_accounts_import_account() does not really help here -
but adds some noise and confusion
eg. as for the other dc_accounts_t functions,
the corrsponding dc_context_t functions must not be called.
if really a new account is required for import,
it seems to be easier to call add_account() before import.
> remove dc_accounts_import_account() api

- CHANGELOG.md
I tried improving the format, here are the "rules" I followed
- The change-log should contain all changes that are user-facing
- user-facing change of behavior, like the account manager doesn't create a default account anymore
- and of course api changes
-  internal changes and changes of rust-bindings are not too important for the change-log right now, because the rust bindings are not considered stable/user-facing
-  but if there is a change that improves performance as not processing duplicated messages, that change might be interesting for users again
- The changelog can contain the following sections:
- Api Changes: *changes to the api that need to or can be adopted by users*
- Added: *new stuff*
- Changes: *changes to existing stuff*
- Removed: *old stuff that is now removed*
- …
> changelog: update to include previous changes

- Cargo.lock
- Cargo.toml
- src/mimeparser.rs
mailparse supports RFC 2231 since version 0.13.5, so there is no need
for our own code to support it.
> mimeparser: use mailparse to parse RFC 2231 filenames

- CHANGELOG.md
- src/contact.rs
- src/dc_tools.rs
They prevent "user@localhost" addresses from being parsed, which are
useful for running online tests against local server.
> Remove strict domain checks for EmailAddress::from_str

- examples/repl/cmdline.rs
- examples/repl/main.rs
- src/scheduler/connectivity.rs
closes #2545 
closes #2538
before/after on ios (the different sized come the initially missing viewport:
before/after on android7:
> tweak connectivity html

- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- src/accounts.rs
- src/scheduler.rs
closes #2547, however, it should be tested explicitly if calling `dc_accounts_maybe_network_lost()` solves the problem.
> add dc_accounts_maybe_network_lost()

- CHANGELOG.md
- deltachat-ffi/deltachat.h
- deltachat-ffi/src/lib.rs
- examples/repl/cmdline.rs
- examples/repl/main.rs
- python/src/deltachat/account.py
- python/src/deltachat/chat.py
- python/src/deltachat/hookspec.py
- python/src/deltachat/message.py
- python/tests/test_account.py
- src/chat.rs
- src/chatlist.rs
- src/constants.rs
- src/contact.rs
- src/context.rs
- src/dc_receive_imf.rs
- src/job.rs
- src/message.rs
- src/mimefactory.rs
- src/mimeparser.rs
- src/peerstate.rs
- src/qr.rs
- src/securejoin.rs
- src/stock_str.rs
Contact request chats are not merged into a single virtual "deaddrop"
chat anymore. Instead, they are shown in the chatlist the same way as
other chats, but sending of messages to them is not allowed and MDNs
are not sent automatically until the chat is "accepted" by the user.
New API:
- dc_chat_is_contact_request(): returns true if chat is a contact
request.  In this case an option to accept the chat via
dc_accept_chat() should be shown in the UI.
- dc_accept_chat(): unblock the chat or accept contact request
- dc_block_chat(): block the chat, currently works only for mailing
lists.
Removed API:
- dc_create_chat_by_msg_id(): deprecated 2021-02-07 in favor of
dc_decide_on_contact_request()
- dc_marknoticed_contact(): deprecated 2021-02-07 in favor of
dc_decide_on_contact_request()
- …
> Remove deaddrop chat

- CMakeLists.txt
- deltachat-ffi/build.rs
- deltachat-ffi/deltachat.pc.in
See https://github.com/jtojnar/cmake-snips#assuming-cmake_install_dir-is-relative-path.
~Since `CMAKE_INSTALL_PREFIX` [defaults to `/usr/local`](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html), there is no need for `unwrap_or_else()`.~
> allow installing lib and include under different prefixes

- src/chat.rs
"Archived Chats" also contain old contact requests now
(an maybe new one if the user archives them),
so, there may be easily some thousands chats in "Archived Chats" -
and the count has no real meaning to the user,
esp. as we not even display the number of "Real Chats".
also, this counter may be confused with "New" or so.
it was never very useful, however, by the added contact requests,
it is even more unuseful :)
Might be that this "Link" will go away anyway sooner or later,
however, for now, it is just fine to remove the badge counter.
example of a useless counter:
finally, by #2563, we want to have the archive also accessible from eg. the menu -
and there one definitely does not want that info.
> remove archived count suffix

- src/accounts.rs
- src/context.rs
the WAL files come from sqlite WAL mode,
they have the same name as the database file with an extra `-wal` suffix.
according to https://sqlite.org/wal.html#the_wal_file ,
the WAL file is part of the persistent state of the database
and should be kept with the database if the database is copied or moved.
without moving WAL files,
the database may lose the last records on migrate,
as just experienced in the testing group.
nb: there are much more temporary files in sqlite,
https://sqlite.org/tempfiles.html
> also move WAL file when moving database

- src/imap/scan_folders.rs
Gmail labels are not folders and should be skipped. For example, emails
appear in the inbox and under "All Mail" as soon as it is received. The
code used to wrongly conclude that the email had already been moved and
left it in the inbox.
Fixes issue #2586.
> Skip Gmail labels

- src/accounts.rs
I don't think this needs a change log entry as this is about a small addition in the rust API which is not much used directly yet.
I missed that function and want to use it.
Yes there are other ways to get to this information, but this way is cleaner.
> add `Accounts::get_selected_account_id` function

- src/chat.rs
- src/contact.rs
- src/dc_receive_imf.rs
- src/imap.rs
- src/qr.rs
- src/securejoin.rs
- src/securejoin/bobstate.rs
Use `Option` instead of `Error` to indicate that no chat ID is found.
> Resultify `get_chat_id_by_grpid` and `create_or_lookup_mailinglist`

- src/chat.rs
- src/dc_receive_imf.rs
- src/e2ee.rs
- src/location.rs
- src/message.rs
- src/mimeparser.rs
- src/peerstate.rs
- src/qr.rs
- src/securejoin.rs
Previously system messages were always added to the end of the chat,
even if the message triggering them was sent earlier.  This is
especially important for messages about disappearing timer reset
triggered by classic email messages, as they should be placed right
after the message resetting the timer.
Fixes #2263
> Set timestamps for system messages

- src/job.rs
- src/scheduler.rs
- src/smtp.rs
fix #2539
In case you're wondering: It's always a bit ambiguous which function should do `set_err` or set `last_send_error`, I used this rule here:
If some code returns `Status::RetryLater`, then it sets `last_send_error`, because `Status::RetryLater` means that the user won't see the error directly on the message (if we returned `Status::Failed(Err(_))`, then the message would be shown as failed to the user, and it wouldn't be as important that we also show the error message in the connectivity view) Also, `smtp_send` always sets `last_send_error` because, well, sending just failed or succeeded.
Also, remove unused field `pending_error`.
> Connectivity view: Only set smtp to "connected" if the last message was actually sent

- src/scheduler.rs
- src/scheduler/connectivity.rs
@r10s reported that without doing this, the connectivity would stay at
"Connected" for 16 more seconds after network is gone and
dc_maybe_network_lost() was called.
Not tested as I don't have iOS.
> In dc_maybe_network_lost() directly set the connectivity "Not connected"

- src/dc_receive_imf.rs
- test-data/message/gmx-forward.eml
Recognizing these emails as forwarded would probably be too complicated and require too much special-casing, but now the user can access the email text via "Show full message".
fix #2599
> Fix: Make emails forwarded by GMX readable

- src/provider/update.py
needed for tor,  https://github.com/deltachat/provider-db/pull/195
> add support for socket PLAIN coming from provider-db

- Cargo.lock
- Cargo.toml
- src/context.rs
- src/imap.rs
- src/imap/scan_folders.rs
- src/job.rs
- src/lib.rs
- src/quota.rs
- src/scheduler/connectivity.rs
- standards.md
this pr is based on the work of @Simon-Laux in https://github.com/deltachat/deltachat-core-rust/pull/2462 and https://github.com/async-email/async-imap/pull/47 and adds quota information to the existing connectivity view, more precise to `dc_get_connectivity_html()`.
this is how it looks like on ios using gmai.com and testrun.org:
the connectivity view adds one line per resource and resources are grouped in "quota roots", whatever that is in detail - for gmail, the "quota root name" is just empty - and i did not found another provider providing quota information. the color of the icon beside each quota line changes to yellow/red when things become full.
`dc_get_connectivity_html()` just prints the recently fetched quota and, if recently fetched is older than one minute, starts a job to …
> Add Quota to Connectivity View

- src/provider/data.rs
- src/provider/update.py
ran `./src/provider/update.py ../provider-db/_providers/ > src/provider/data.rs`
to pull in recent changes from https://github.com/deltachat/provider-db
moreover, the pr tweaks `update.py` to accept dotless domains.
~~maybe we should merge https://github.com/deltachat/provider-db/pull/199 and run the script again before merging.~~ EDIT: done.
> update provider database, add yggmail and mail2tor

- src/contact.rs
- src/stock_str.rs
the 'device chat about' was shown as a single message
as at that time, there was just no 'status'.
meanwhile, we have the status option,
and it feels much more natural to get the information there,
esp. as the subtitle on all UIs already read
'Messages in this chat are generated locally' -
and a tap on that will show the hint, without scrolling or so.
this also teaches the user where to find such information -
and the "welcome" chat is less spammy and really starts with the text
"Welcome to Delta Chat!"
> add 'device chat about' to now existing status
